// Code generated by BarefootJS. DO NOT EDIT.

//go:build !production

package main

// Assets maps a logical asset name (this map's key) to its resolved URL.
// Two build-tagged files declare this SAME symbol so exactly one
// compiles: bf_assets.go (tag !production, the untagged default) holds
// Vite dev-server-origin URLs and is committed since they're stable
// across rebuilds; bf_assets_prod.go (tag production, gitignored) holds
// content-hashed build URLs that change every `vite build`. Compile
// against the production build with `-tags production`. Regenerated
// by @barefootjs/go-template/vite's afterEmit hook every time templates
// are (re)emitted.
var Assets = map[string]string{
	"RouterEntry": "http://localhost:5173/integrations/nethttp/static/client/router-entry.ts",
}
