// Code generated by BarefootJS. DO NOT EDIT.
package main

// Assets maps a logical asset name (this map's key) to its resolved URL
// for the current build: a Vite dev-server origin URL in dev, a
// content-hashed manifest path in production. Regenerated by
// @barefootjs/go-template/vite's afterEmit hook every time templates are
// (re)emitted.
var Assets = map[string]string{
	"RouterEntry": "/integrations/nethttp/static/assets/router-entry-DDIPLN_z.js",
}
