// Code generated by BarefootJS. DO NOT EDIT.
package main

import (
	"fmt"
	"math/rand"

	bf "github.com/barefootjs/runtime/bf"
)

// randomID generates a random string of length n for ScopeID.
func randomID(n int) string {
	const chars = "abcdefghijklmnopqrstuvwxyz0123456789"
	b := make([]byte, n)
	for i := range b {
		b[i] = chars[rand.Intn(len(chars))]
	}
	return string(b)
}

// Message represents a message.
type Message struct {
	ID int `json:"id"`
	Role interface{} `json:"role"`
	Content string `json:"content"`
}

// AIChatInteractiveInput is the user-facing input type.
type AIChatInteractiveInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
}

// AIChatInteractiveProps is the props type for the AIChatInteractive component.
type AIChatInteractiveProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Messages []Message `json:"messages"`
	Input string `json:"input"`
	StreamingText string `json:"streamingText"`
	IsStreaming bool `json:"isStreaming"`
}

// ConditionalReturnInput is the user-facing input type.
type ConditionalReturnInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	Variant string
}

// ConditionalReturnProps is the props type for the ConditionalReturn component.
type ConditionalReturnProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Variant string `json:"variant"`
	Count int `json:"count"`
}

// CounterInput is the user-facing input type.
type CounterInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	Initial int
}

// CounterProps is the props type for the Counter component.
type CounterProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Initial int `json:"initial"`
	Count int `json:"count"`
	Doubled int `json:"doubled"`
}

// FormInput is the user-facing input type.
type FormInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
}

// FormProps is the props type for the Form component.
type FormProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Accepted bool `json:"accepted"`
}

// PortalExampleInput is the user-facing input type.
type PortalExampleInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
}

// PortalExampleProps is the props type for the PortalExample component.
type PortalExampleProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Open bool `json:"open"`
}

// ReactiveChildInput is the user-facing input type.
type ReactiveChildInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	Value int
	Label string
	OnIncrement interface{}
}

// ReactiveChildProps is the props type for the ReactiveChild component.
type ReactiveChildProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Value int `json:"value"`
	Label string `json:"label"`
	OnIncrement interface{} `json:"onIncrement"`
}

// ReactivePropsInput is the user-facing input type.
type ReactivePropsInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
}

// ReactivePropsProps is the props type for the ReactiveProps component.
type ReactivePropsProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Count int `json:"count"`
	Doubled int `json:"doubled"`
	ReactiveChildSlot5 ReactiveChildProps `json:"-"`
	ReactiveChildSlot6 ReactiveChildProps `json:"-"`
}

// PropsStyleChildInput is the user-facing input type.
type PropsStyleChildInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	Value int
	Label string
}

// PropsStyleChildProps is the props type for the PropsStyleChild component.
type PropsStyleChildProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Value int `json:"value"`
	Label string `json:"label"`
	DisplayValue interface{} `json:"displayValue"`
}

// DestructuredStyleChildInput is the user-facing input type.
type DestructuredStyleChildInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	Value interface{}
	Label interface{}
}

// DestructuredStyleChildProps is the props type for the DestructuredStyleChild component.
type DestructuredStyleChildProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Value interface{} `json:"value"`
	Label interface{} `json:"label"`
	DisplayValue interface{} `json:"displayValue"`
}

// PropsReactivityComparisonInput is the user-facing input type.
type PropsReactivityComparisonInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
}

// PropsReactivityComparisonProps is the props type for the PropsReactivityComparison component.
type PropsReactivityComparisonProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Count int `json:"count"`
	PropsStyleChildSlot3 PropsStyleChildProps `json:"-"`
	DestructuredStyleChildSlot4 DestructuredStyleChildProps `json:"-"`
}

// TextEscapeInput is the user-facing input type.
type TextEscapeInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	Label string
}

// TextEscapeProps is the props type for the TextEscape component.
type TextEscapeProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Label string `json:"label"`
	Count int `json:"count"`
}

// Todo represents a todo.
type Todo struct {
	ID int `json:"id"`
	Text string `json:"text"`
	Done bool `json:"done"`
	Editing bool `json:"editing"`
}

// Filter is a string type.
type Filter = string

// TodoAppInput is the user-facing input type.
type TodoAppInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	InitialTodos []Todo
}

// TodoAppProps is the props type for the TodoApp component.
type TodoAppProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	InitialTodos []Todo `json:"initialTodos"`
	Todos []Todo `json:"todos"`
	NewText string `json:"newText"`
	Filter Filter `json:"filter"`
	TodoItems []TodoItemProps `json:"-"`
}

// TodoAppSSRInput is the user-facing input type.
type TodoAppSSRInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	InitialTodos []Todo
}

// TodoAppSSRProps is the props type for the TodoAppSSR component.
type TodoAppSSRProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	InitialTodos []Todo `json:"initialTodos"`
	Todos []Todo `json:"todos"`
	NewText string `json:"newText"`
	Filter Filter `json:"filter"`
	TodoItems []TodoItemProps `json:"-"`
}

// TodoItemInput is the user-facing input type.
type TodoItemInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	Todo Todo
	OnToggle interface{}
	OnDelete interface{}
	OnStartEdit interface{}
	OnFinishEdit interface{}
}

// TodoItemProps is the props type for the TodoItem component.
type TodoItemProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Todo Todo `json:"todo"`
	OnToggle interface{} `json:"onToggle"`
	OnDelete interface{} `json:"onDelete"`
	OnStartEdit interface{} `json:"onStartEdit"`
	OnFinishEdit interface{} `json:"onFinishEdit"`
}

// ToggleItemInput is the user-facing input type.
type ToggleItemInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	Label string
	DefaultOn bool
}

// ToggleItemProps is the props type for the ToggleItem component.
type ToggleItemProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Label string `json:"label"`
	DefaultOn bool `json:"defaultOn"`
	On bool `json:"on"`
}

// ToggleInput is the user-facing input type.
type ToggleInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	ToggleItems []ToggleItemInput
}

// ToggleProps is the props type for the Toggle component.
type ToggleProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	ToggleItems []ToggleItemProps `json:"toggleItems"`
}

// NewAIChatInteractiveProps creates AIChatInteractiveProps from AIChatInteractiveInput.
func NewAIChatInteractiveProps(in AIChatInteractiveInput) AIChatInteractiveProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "AIChatInteractive_" + randomID(6)
	}

	return AIChatInteractiveProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Messages: nil,
		Input: "",
		StreamingText: "",
		IsStreaming: false,
	}
}

// NewConditionalReturnProps creates ConditionalReturnProps from ConditionalReturnInput.
func NewConditionalReturnProps(in ConditionalReturnInput) ConditionalReturnProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "ConditionalReturn_" + randomID(6)
	}

	return ConditionalReturnProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Variant: in.Variant,
		Count: 0,
	}
}

// NewCounterProps creates CounterProps from CounterInput.
func NewCounterProps(in CounterInput) CounterProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "Counter_" + randomID(6)
	}

	return CounterProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Initial: in.Initial,
		Count: in.Initial,
		Doubled: in.Initial * 2,
	}
}

// NewFormProps creates FormProps from FormInput.
func NewFormProps(in FormInput) FormProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "Form_" + randomID(6)
	}

	return FormProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Accepted: false,
	}
}

// NewPortalExampleProps creates PortalExampleProps from PortalExampleInput.
func NewPortalExampleProps(in PortalExampleInput) PortalExampleProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "PortalExample_" + randomID(6)
	}

	return PortalExampleProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Open: false,
	}
}

// NewReactiveChildProps creates ReactiveChildProps from ReactiveChildInput.
func NewReactiveChildProps(in ReactiveChildInput) ReactiveChildProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "ReactiveChild_" + randomID(6)
	}

	return ReactiveChildProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Value: in.Value,
		Label: in.Label,
		OnIncrement: in.OnIncrement,
	}
}

// NewReactivePropsProps creates ReactivePropsProps from ReactivePropsInput.
func NewReactivePropsProps(in ReactivePropsInput) ReactivePropsProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "ReactiveProps_" + randomID(6)
	}

	return ReactivePropsProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Count: 0,
		Doubled: 0 * 2,
		ReactiveChildSlot5: NewReactiveChildProps(ReactiveChildInput{
			ScopeID: scopeID + "_s5",
			BfParent: scopeID,
			BfMount: "s5",
			Value: 0,
			Label: "Child A",
		}),
		ReactiveChildSlot6: NewReactiveChildProps(ReactiveChildInput{
			ScopeID: scopeID + "_s6",
			BfParent: scopeID,
			BfMount: "s6",
			Value: 0 * 2,
			Label: "Child B (doubled)",
		}),
	}
}

// NewPropsStyleChildProps creates PropsStyleChildProps from PropsStyleChildInput.
func NewPropsStyleChildProps(in PropsStyleChildInput) PropsStyleChildProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "PropsStyleChild_" + randomID(6)
	}

	return PropsStyleChildProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Value: in.Value,
		Label: in.Label,
		DisplayValue: in.Value * 10,
	}
}

// NewDestructuredStyleChildProps creates DestructuredStyleChildProps from DestructuredStyleChildInput.
func NewDestructuredStyleChildProps(in DestructuredStyleChildInput) DestructuredStyleChildProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "DestructuredStyleChild_" + randomID(6)
	}

	return DestructuredStyleChildProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Value: in.Value,
		Label: in.Label,
		DisplayValue: in.Value.(int) * 10,
	}
}

// NewPropsReactivityComparisonProps creates PropsReactivityComparisonProps from PropsReactivityComparisonInput.
func NewPropsReactivityComparisonProps(in PropsReactivityComparisonInput) PropsReactivityComparisonProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "PropsReactivityComparison_" + randomID(6)
	}

	return PropsReactivityComparisonProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Count: 1,
		PropsStyleChildSlot3: NewPropsStyleChildProps(PropsStyleChildInput{
			ScopeID: scopeID + "_s3",
			BfParent: scopeID,
			BfMount: "s3",
			Value: 1,
			Label: "Props Style",
		}),
		DestructuredStyleChildSlot4: NewDestructuredStyleChildProps(DestructuredStyleChildInput{
			ScopeID: scopeID + "_s4",
			BfParent: scopeID,
			BfMount: "s4",
			Value: 1,
			Label: "Destructured",
		}),
	}
}

// NewTextEscapeProps creates TextEscapeProps from TextEscapeInput.
func NewTextEscapeProps(in TextEscapeInput) TextEscapeProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "TextEscape_" + randomID(6)
	}

	return TextEscapeProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Label: in.Label,
		Count: 0,
	}
}

// NewTodoAppProps creates TodoAppProps from TodoAppInput.
//
// NOTE: `TodoItems` is populated by the route handler, not by
// NewTodoAppProps — the SSR template iterates over it
// dynamically (`.TodoItems`). Build the slice from your source data and
// assign it before passing the props to your renderer. Example:
//
//   props := NewTodoAppProps(TodoAppInput{ /* ... */ })
//   props.TodoItems = make([]TodoItemProps, len(items))
//   for i, item := range items {
//     props.TodoItems[i] = NewTodoItemProps(TodoItemInput{ /* fields */ })
//     props.TodoItems[i].BfParent = props.ScopeID
//     props.TodoItems[i].BfMount = "s3"
//   }
func NewTodoAppProps(in TodoAppInput) TodoAppProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "TodoApp_" + randomID(6)
	}

	return TodoAppProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		InitialTodos: in.InitialTodos,
		Todos: in.InitialTodos,
		NewText: "",
		Filter: "all",
	}
}

// NewTodoAppSSRProps creates TodoAppSSRProps from TodoAppSSRInput.
//
// NOTE: `TodoItems` is populated by the route handler, not by
// NewTodoAppSSRProps — the SSR template iterates over it
// dynamically (`.TodoItems`). Build the slice from your source data and
// assign it before passing the props to your renderer. Example:
//
//   props := NewTodoAppSSRProps(TodoAppSSRInput{ /* ... */ })
//   props.TodoItems = make([]TodoItemProps, len(items))
//   for i, item := range items {
//     props.TodoItems[i] = NewTodoItemProps(TodoItemInput{ /* fields */ })
//     props.TodoItems[i].BfParent = props.ScopeID
//     props.TodoItems[i].BfMount = "s3"
//   }
func NewTodoAppSSRProps(in TodoAppSSRInput) TodoAppSSRProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "TodoAppSSR_" + randomID(6)
	}

	return TodoAppSSRProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		InitialTodos: in.InitialTodos,
		Todos: in.InitialTodos,
		NewText: "",
		Filter: "all",
	}
}

// NewTodoItemProps creates TodoItemProps from TodoItemInput.
func NewTodoItemProps(in TodoItemInput) TodoItemProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "TodoItem_" + randomID(6)
	}

	return TodoItemProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Todo: in.Todo,
		OnToggle: in.OnToggle,
		OnDelete: in.OnDelete,
		OnStartEdit: in.OnStartEdit,
		OnFinishEdit: in.OnFinishEdit,
	}
}

// NewToggleItemProps creates ToggleItemProps from ToggleItemInput.
func NewToggleItemProps(in ToggleItemInput) ToggleItemProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "ToggleItem_" + randomID(6)
	}

	return ToggleItemProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Label: in.Label,
		DefaultOn: in.DefaultOn,
		On: in.DefaultOn,
	}
}

// NewToggleProps creates ToggleProps from ToggleInput.
func NewToggleProps(in ToggleInput) ToggleProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "Toggle_" + randomID(6)
	}

	toggleItems := make([]ToggleItemProps, len(in.ToggleItems))
	for i, item := range in.ToggleItems {
		toggleItems[i] = NewToggleItemProps(item)
		toggleItems[i].BfParent = scopeID
		toggleItems[i].BfMount = "s0"
		toggleItems[i].BfDataKey = fmt.Sprint(item.Label)
	}

	return ToggleProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		ToggleItems: toggleItems,
	}
}
