// Code generated by BarefootJS. DO NOT EDIT.
package main

import (
	"fmt"
	"math/rand"
	"strings"

	bf "github.com/barefootjs/runtime/bf"
)

// randomID generates a random string of length n for ScopeID.
func randomID(n int) string {
	const chars = "abcdefghijklmnopqrstuvwxyz0123456789"
	b := make([]byte, n)
	for i := range b {
		b[i] = chars[rand.Intn(len(chars))]
	}
	return string(b)
}

// Message represents a message.
type Message struct {
	ID int `json:"id"`
	Role interface{} `json:"role"`
	Content string `json:"content"`
}

// AIChatInteractiveInput is the user-facing input type.
type AIChatInteractiveInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
}

// AIChatInteractiveProps is the props type for the AIChatInteractive component.
type AIChatInteractiveProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Messages []Message `json:"messages"`
	Input string `json:"input"`
	StreamingText string `json:"streamingText"`
	IsStreaming bool `json:"isStreaming"`
}

// ConditionalReturnInput is the user-facing input type.
type ConditionalReturnInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	Variant string
}

// ConditionalReturnProps is the props type for the ConditionalReturn component.
type ConditionalReturnProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Variant string `json:"variant"`
	Count int `json:"count"`
}

// CounterInput is the user-facing input type.
type CounterInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	Initial int
}

// CounterProps is the props type for the Counter component.
type CounterProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Initial int `json:"initial"`
	Count int `json:"count"`
	Doubled int `json:"doubled"`
}

// FormInput is the user-facing input type.
type FormInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
}

// FormProps is the props type for the Form component.
type FormProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Accepted bool `json:"accepted"`
}

// PortalExampleInput is the user-facing input type.
type PortalExampleInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
}

// PortalExampleProps is the props type for the PortalExample component.
type PortalExampleProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Open bool `json:"open"`
}

// ReactiveChildInput is the user-facing input type.
type ReactiveChildInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	Value int
	Label string
	OnIncrement interface{}
}

// ReactiveChildProps is the props type for the ReactiveChild component.
type ReactiveChildProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Value int `json:"value"`
	Label string `json:"label"`
	OnIncrement interface{} `json:"onIncrement"`
}

// ReactivePropsInput is the user-facing input type.
type ReactivePropsInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
}

// ReactivePropsProps is the props type for the ReactiveProps component.
type ReactivePropsProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Count int `json:"count"`
	Doubled int `json:"doubled"`
	ReactiveChildSlot5 ReactiveChildProps `json:"-"`
	ReactiveChildSlot6 ReactiveChildProps `json:"-"`
}

// PropsStyleChildInput is the user-facing input type.
type PropsStyleChildInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	Value int
	Label string
}

// PropsStyleChildProps is the props type for the PropsStyleChild component.
type PropsStyleChildProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Value int `json:"value"`
	Label string `json:"label"`
	DisplayValue int `json:"displayValue"`
}

// DestructuredStyleChildInput is the user-facing input type.
type DestructuredStyleChildInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	Value int
	Label string
}

// DestructuredStyleChildProps is the props type for the DestructuredStyleChild component.
type DestructuredStyleChildProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Value int `json:"value"`
	Label string `json:"label"`
	DisplayValue int `json:"displayValue"`
}

// PropsReactivityComparisonInput is the user-facing input type.
type PropsReactivityComparisonInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
}

// PropsReactivityComparisonProps is the props type for the PropsReactivityComparison component.
type PropsReactivityComparisonProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Count int `json:"count"`
	PropsStyleChildSlot3 PropsStyleChildProps `json:"-"`
	DestructuredStyleChildSlot4 DestructuredStyleChildProps `json:"-"`
}

// TextEscapeInput is the user-facing input type.
type TextEscapeInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	Label string
}

// TextEscapeProps is the props type for the TextEscape component.
type TextEscapeProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Label string `json:"label"`
	Count int `json:"count"`
}

// Todo represents a todo.
type Todo struct {
	ID int `json:"id"`
	Text string `json:"text"`
	Done bool `json:"done"`
	Editing bool `json:"editing"`
}

// Filter is a string type.
type Filter = string

// TodoAppInput is the user-facing input type.
type TodoAppInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	InitialTodos []Todo
}

// TodoAppProps is the props type for the TodoApp component.
type TodoAppProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	InitialTodos []Todo `json:"initialTodos"`
	Todos []Todo `json:"todos"`
	NewText string `json:"newText"`
	Filter Filter `json:"filter"`
	TodoItems []TodoItemProps `json:"-"`
}

// TodoAppSSRInput is the user-facing input type.
type TodoAppSSRInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	InitialTodos []Todo
}

// TodoAppSSRProps is the props type for the TodoAppSSR component.
type TodoAppSSRProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	InitialTodos []Todo `json:"initialTodos"`
	Todos []Todo `json:"todos"`
	NewText string `json:"newText"`
	Filter Filter `json:"filter"`
	TodoItems []TodoItemProps `json:"-"`
}

// TodoItemInput is the user-facing input type.
type TodoItemInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	Todo Todo
	OnToggle interface{}
	OnDelete interface{}
	OnStartEdit interface{}
	OnFinishEdit interface{}
}

// TodoItemProps is the props type for the TodoItem component.
type TodoItemProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Todo Todo `json:"todo"`
	OnToggle interface{} `json:"onToggle"`
	OnDelete interface{} `json:"onDelete"`
	OnStartEdit interface{} `json:"onStartEdit"`
	OnFinishEdit interface{} `json:"onFinishEdit"`
}

// ToggleItemInput is the user-facing input type.
type ToggleItemInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	Label string
	DefaultOn bool
}

// ToggleItemProps is the props type for the ToggleItem component.
type ToggleItemProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Label string `json:"label"`
	DefaultOn bool `json:"defaultOn"`
	On bool `json:"on"`
}

// ToggleInput is the user-facing input type.
type ToggleInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	ToggleItems []ToggleItemInput
}

// ToggleProps is the props type for the Toggle component.
type ToggleProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	ToggleItems []ToggleItemProps `json:"toggleItems"`
}

// LikeButtonInput is the user-facing input type.
type LikeButtonInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
}

// LikeButtonProps is the props type for the LikeButton component.
type LikeButtonProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Likes int `json:"likes"`
}

// NowPlayingInput is the user-facing input type.
type NowPlayingInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
}

// NowPlayingProps is the props type for the NowPlaying component.
type NowPlayingProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Playing bool `json:"playing"`
	Elapsed int `json:"elapsed"`
}

// PageShellInput is the user-facing input type.
type PageShellInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	Children interface{}
}

// PageShellProps is the props type for the PageShell component.
type PageShellProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Children interface{} `json:"-"`
	ReaderToolbarSlot0 ReaderToolbarProps `json:"-"`
}

// PostArticleInput is the user-facing input type.
type PostArticleInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	Slug string
	Title string
	Date string
	Tags []string
	Body []string
	Position int
	Total int
	Base string
	PrevSlug string
	PrevTitle interface{}
	NextSlug string
	NextTitle interface{}
}

// PostArticleProps is the props type for the PostArticle component.
type PostArticleProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Slug string `json:"slug"`
	Title string `json:"title"`
	Date string `json:"date"`
	Tags []string `json:"tags"`
	Body []string `json:"body"`
	Position int `json:"position"`
	Total int `json:"total"`
	Base string `json:"base"`
	PrevSlug string `json:"prevSlug"`
	PrevTitle interface{} `json:"prevTitle"`
	NextSlug string `json:"nextSlug"`
	NextTitle interface{} `json:"nextTitle"`
	LikeButtonSlot9 LikeButtonProps `json:"-"`
	ReadingTimerSlot10 ReadingTimerProps `json:"-"`
	NowPlayingSlot11 NowPlayingProps `json:"-"`
}

// Item represents a item.
type Item struct {
	Slug string `json:"slug"`
	Title string `json:"title"`
	Date string `json:"date"`
	Tags []string `json:"tags"`
	Meta string `json:"meta"`
}

// SortKey is a string type.
type SortKey = string

// PostListInput is the user-facing input type.
type PostListInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	SearchParams bf.SearchParams // Optional: request query for searchParams()
	Items []Item
	Tags []string
	Base string
}

// PostListProps is the props type for the PostList component.
type PostListProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	SearchParams bf.SearchParams `json:"-"`
	Items []Item `json:"items"`
	Tags []string `json:"tags"`
	Base string `json:"base"`
	Params map[string]interface{} `json:"params"`
	Visible []Item `json:"visible"`
	Root string `json:"-"`
	PostListItems []PostListItemProps `json:"-"`
}

// PostListItemInput is the user-facing input type.
type PostListItemInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
	Href string
	Title string
	Date string
	Meta string
}

// PostListItemProps is the props type for the PostListItem component.
type PostListItemProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Href string `json:"href"`
	Title string `json:"title"`
	Date string `json:"date"`
	Meta string `json:"meta"`
	Pinned bool `json:"pinned"`
}

// ReaderToolbarInput is the user-facing input type.
type ReaderToolbarInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
}

// ReaderToolbarProps is the props type for the ReaderToolbar component.
type ReaderToolbarProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Level int `json:"level"`
}

// ReadingTimerInput is the user-facing input type.
type ReadingTimerInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
}

// ReadingTimerProps is the props type for the ReadingTimer component.
type ReadingTimerProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Secs int `json:"secs"`
}

// SidebarInput is the user-facing input type.
type SidebarInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
}

// SidebarProps is the props type for the Sidebar component.
type SidebarProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Pins int `json:"pins"`
}

// ThemeToggleInput is the user-facing input type.
type ThemeToggleInput struct {
	ScopeID string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount string // Optional: slot id in parent
}

// ThemeToggleProps is the props type for the ThemeToggle component.
type ThemeToggleProps struct {
	ScopeID string `json:"scopeID"`
	BfIsRoot bool `json:"-"`
	BfIsChild bool `json:"-"`
	BfParent string `json:"-"`
	BfMount string `json:"-"`
	BfDataKey string `json:"-"`
	Scripts *bf.ScriptCollector `json:"-"`
	Light bool `json:"light"`
}

// NewAIChatInteractiveProps creates AIChatInteractiveProps from AIChatInteractiveInput.
func NewAIChatInteractiveProps(in AIChatInteractiveInput) AIChatInteractiveProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "AIChatInteractive_" + randomID(6)
	}

	return AIChatInteractiveProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Messages: nil,
		Input: "",
		StreamingText: "",
		IsStreaming: false,
	}
}

// NewConditionalReturnProps creates ConditionalReturnProps from ConditionalReturnInput.
func NewConditionalReturnProps(in ConditionalReturnInput) ConditionalReturnProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "ConditionalReturn_" + randomID(6)
	}

	return ConditionalReturnProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Variant: in.Variant,
		Count: 0,
	}
}

// NewCounterProps creates CounterProps from CounterInput.
func NewCounterProps(in CounterInput) CounterProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "Counter_" + randomID(6)
	}

	return CounterProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Initial: in.Initial,
		Count: in.Initial,
		Doubled: in.Initial * 2,
	}
}

// NewFormProps creates FormProps from FormInput.
func NewFormProps(in FormInput) FormProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "Form_" + randomID(6)
	}

	return FormProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Accepted: false,
	}
}

// NewPortalExampleProps creates PortalExampleProps from PortalExampleInput.
func NewPortalExampleProps(in PortalExampleInput) PortalExampleProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "PortalExample_" + randomID(6)
	}

	return PortalExampleProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Open: false,
	}
}

// NewReactiveChildProps creates ReactiveChildProps from ReactiveChildInput.
func NewReactiveChildProps(in ReactiveChildInput) ReactiveChildProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "ReactiveChild_" + randomID(6)
	}

	return ReactiveChildProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Value: in.Value,
		Label: in.Label,
		OnIncrement: in.OnIncrement,
	}
}

// NewReactivePropsProps creates ReactivePropsProps from ReactivePropsInput.
func NewReactivePropsProps(in ReactivePropsInput) ReactivePropsProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "ReactiveProps_" + randomID(6)
	}

	return ReactivePropsProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Count: 0,
		Doubled: 0 * 2,
		ReactiveChildSlot5: NewReactiveChildProps(ReactiveChildInput{
			ScopeID: scopeID + "_s5",
			BfParent: scopeID,
			BfMount: "s5",
			Value: 0,
			Label: "Child A",
		}),
		ReactiveChildSlot6: NewReactiveChildProps(ReactiveChildInput{
			ScopeID: scopeID + "_s6",
			BfParent: scopeID,
			BfMount: "s6",
			Value: 0 * 2,
			Label: "Child B (doubled)",
		}),
	}
}

// NewPropsStyleChildProps creates PropsStyleChildProps from PropsStyleChildInput.
func NewPropsStyleChildProps(in PropsStyleChildInput) PropsStyleChildProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "PropsStyleChild_" + randomID(6)
	}

	return PropsStyleChildProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Value: in.Value,
		Label: in.Label,
		DisplayValue: in.Value * 10,
	}
}

// NewDestructuredStyleChildProps creates DestructuredStyleChildProps from DestructuredStyleChildInput.
func NewDestructuredStyleChildProps(in DestructuredStyleChildInput) DestructuredStyleChildProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "DestructuredStyleChild_" + randomID(6)
	}

	return DestructuredStyleChildProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Value: in.Value,
		Label: in.Label,
		DisplayValue: in.Value * 10,
	}
}

// NewPropsReactivityComparisonProps creates PropsReactivityComparisonProps from PropsReactivityComparisonInput.
func NewPropsReactivityComparisonProps(in PropsReactivityComparisonInput) PropsReactivityComparisonProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "PropsReactivityComparison_" + randomID(6)
	}

	return PropsReactivityComparisonProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Count: 1,
		PropsStyleChildSlot3: NewPropsStyleChildProps(PropsStyleChildInput{
			ScopeID: scopeID + "_s3",
			BfParent: scopeID,
			BfMount: "s3",
			Value: 1,
			Label: "Props Style",
		}),
		DestructuredStyleChildSlot4: NewDestructuredStyleChildProps(DestructuredStyleChildInput{
			ScopeID: scopeID + "_s4",
			BfParent: scopeID,
			BfMount: "s4",
			Value: 1,
			Label: "Destructured",
		}),
	}
}

// NewTextEscapeProps creates TextEscapeProps from TextEscapeInput.
func NewTextEscapeProps(in TextEscapeInput) TextEscapeProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "TextEscape_" + randomID(6)
	}

	return TextEscapeProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Label: in.Label,
		Count: 0,
	}
}

// NewTodoAppProps creates TodoAppProps from TodoAppInput.
//
// NOTE: `TodoItems` is populated by the route handler, not by
// NewTodoAppProps — the SSR template iterates over it
// dynamically (`.TodoItems`). Build the slice from your source data and
// assign it before passing the props to your renderer. Example:
//
//   props := NewTodoAppProps(TodoAppInput{ /* ... */ })
//   props.TodoItems = make([]TodoItemProps, len(items))
//   for i, item := range items {
//     props.TodoItems[i] = NewTodoItemProps(TodoItemInput{ /* fields */ })
//     props.TodoItems[i].BfParent = props.ScopeID
//     props.TodoItems[i].BfMount = "s3"
//   }
func NewTodoAppProps(in TodoAppInput) TodoAppProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "TodoApp_" + randomID(6)
	}

	return TodoAppProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		InitialTodos: in.InitialTodos,
		Todos: in.InitialTodos,
		NewText: "",
		Filter: "all",
	}
}

// NewTodoAppSSRProps creates TodoAppSSRProps from TodoAppSSRInput.
//
// NOTE: `TodoItems` is populated by the route handler, not by
// NewTodoAppSSRProps — the SSR template iterates over it
// dynamically (`.TodoItems`). Build the slice from your source data and
// assign it before passing the props to your renderer. Example:
//
//   props := NewTodoAppSSRProps(TodoAppSSRInput{ /* ... */ })
//   props.TodoItems = make([]TodoItemProps, len(items))
//   for i, item := range items {
//     props.TodoItems[i] = NewTodoItemProps(TodoItemInput{ /* fields */ })
//     props.TodoItems[i].BfParent = props.ScopeID
//     props.TodoItems[i].BfMount = "s3"
//   }
func NewTodoAppSSRProps(in TodoAppSSRInput) TodoAppSSRProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "TodoAppSSR_" + randomID(6)
	}

	return TodoAppSSRProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		InitialTodos: in.InitialTodos,
		Todos: in.InitialTodos,
		NewText: "",
		Filter: "all",
	}
}

// NewTodoItemProps creates TodoItemProps from TodoItemInput.
func NewTodoItemProps(in TodoItemInput) TodoItemProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "TodoItem_" + randomID(6)
	}

	return TodoItemProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Todo: in.Todo,
		OnToggle: in.OnToggle,
		OnDelete: in.OnDelete,
		OnStartEdit: in.OnStartEdit,
		OnFinishEdit: in.OnFinishEdit,
	}
}

// NewToggleItemProps creates ToggleItemProps from ToggleItemInput.
func NewToggleItemProps(in ToggleItemInput) ToggleItemProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "ToggleItem_" + randomID(6)
	}

	return ToggleItemProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Label: in.Label,
		DefaultOn: in.DefaultOn,
		On: in.DefaultOn,
	}
}

// NewToggleProps creates ToggleProps from ToggleInput.
func NewToggleProps(in ToggleInput) ToggleProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "Toggle_" + randomID(6)
	}

	toggleItems := make([]ToggleItemProps, len(in.ToggleItems))
	for i, item := range in.ToggleItems {
		toggleItems[i] = NewToggleItemProps(item)
		toggleItems[i].BfParent = scopeID
		toggleItems[i].BfMount = "s0"
		toggleItems[i].BfDataKey = fmt.Sprint(item.Label)
	}

	return ToggleProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		ToggleItems: toggleItems,
	}
}

// NewLikeButtonProps creates LikeButtonProps from LikeButtonInput.
func NewLikeButtonProps(in LikeButtonInput) LikeButtonProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "LikeButton_" + randomID(6)
	}

	return LikeButtonProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Likes: 0,
	}
}

// NewNowPlayingProps creates NowPlayingProps from NowPlayingInput.
func NewNowPlayingProps(in NowPlayingInput) NowPlayingProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "NowPlaying_" + randomID(6)
	}

	return NowPlayingProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Playing: false,
		Elapsed: 0,
	}
}

// NewPageShellProps creates PageShellProps from PageShellInput.
func NewPageShellProps(in PageShellInput) PageShellProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "PageShell_" + randomID(6)
	}

	return PageShellProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Children: in.Children,
		ReaderToolbarSlot0: NewReaderToolbarProps(ReaderToolbarInput{
			ScopeID: scopeID + "_s0",
			BfParent: scopeID,
			BfMount: "s0",
		}),
	}
}

// NewPostArticleProps creates PostArticleProps from PostArticleInput.
func NewPostArticleProps(in PostArticleInput) PostArticleProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "PostArticle_" + randomID(6)
	}

	return PostArticleProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Slug: in.Slug,
		Title: in.Title,
		Date: in.Date,
		Tags: in.Tags,
		Body: in.Body,
		Position: in.Position,
		Total: in.Total,
		Base: in.Base,
		PrevSlug: in.PrevSlug,
		PrevTitle: in.PrevTitle,
		NextSlug: in.NextSlug,
		NextTitle: in.NextTitle,
		LikeButtonSlot9: NewLikeButtonProps(LikeButtonInput{
			ScopeID: scopeID + "_s9",
			BfParent: scopeID,
			BfMount: "s9",
		}),
		ReadingTimerSlot10: NewReadingTimerProps(ReadingTimerInput{
			ScopeID: scopeID + "_s10",
			BfParent: scopeID,
			BfMount: "s10",
		}),
		NowPlayingSlot11: NewNowPlayingProps(NowPlayingInput{
			ScopeID: scopeID + "_s11",
			BfParent: scopeID,
			BfMount: "s11",
		}),
	}
}

// NewPostListProps creates PostListProps from PostListInput.
//
// NOTE: `PostListItems` is populated by the route handler, not by
// NewPostListProps — the SSR template iterates over it
// dynamically (`.PostListItems`). Build the slice from your source data and
// assign it before passing the props to your renderer. Example:
//
//   props := NewPostListProps(PostListInput{ /* ... */ })
//   props.PostListItems = make([]PostListItemProps, len(items))
//   for i, item := range items {
//     props.PostListItems[i] = NewPostListItemProps(PostListItemInput{ /* fields */ })
//     props.PostListItems[i].BfParent = props.ScopeID
//     props.PostListItems[i].BfMount = "s13"
//   }
func NewPostListProps(in PostListInput) PostListProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "PostList_" + randomID(6)
	}

	return PostListProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		SearchParams: in.SearchParams,
		Items: in.Items,
		Tags: in.Tags,
		Base: in.Base,
		Params: map[string]interface{}{
		"Sort": func() string { if bf.Includes([]string{"date", "title", "tag"}, in.SearchParams.Get("sort")) { return in.SearchParams.Get("sort") }; return "date" }(),
		"Tag": in.SearchParams.Get("tag"),
	},
		Visible: nil,
		Root: func() string { v := strings.TrimRight(in.Base, "/"); if v != "" { return v }; return "/" }(),
	}
}

// NewPostListItemProps creates PostListItemProps from PostListItemInput.
func NewPostListItemProps(in PostListItemInput) PostListItemProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "PostListItem_" + randomID(6)
	}

	return PostListItemProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Href: in.Href,
		Title: in.Title,
		Date: in.Date,
		Meta: in.Meta,
		Pinned: false,
	}
}

// NewReaderToolbarProps creates ReaderToolbarProps from ReaderToolbarInput.
func NewReaderToolbarProps(in ReaderToolbarInput) ReaderToolbarProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "ReaderToolbar_" + randomID(6)
	}

	return ReaderToolbarProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Level: 1,
	}
}

// NewReadingTimerProps creates ReadingTimerProps from ReadingTimerInput.
func NewReadingTimerProps(in ReadingTimerInput) ReadingTimerProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "ReadingTimer_" + randomID(6)
	}

	return ReadingTimerProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Secs: 0,
	}
}

// NewSidebarProps creates SidebarProps from SidebarInput.
func NewSidebarProps(in SidebarInput) SidebarProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "Sidebar_" + randomID(6)
	}

	return SidebarProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Pins: 0,
	}
}

// NewThemeToggleProps creates ThemeToggleProps from ThemeToggleInput.
func NewThemeToggleProps(in ThemeToggleInput) ThemeToggleProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "ThemeToggle_" + randomID(6)
	}

	return ThemeToggleProps{
		ScopeID: scopeID,
		BfParent: in.BfParent,
		BfMount: in.BfMount,
		Light: false,
	}
}
