// Plan → implement → polish one or more GitHub issues into stacked PR(s) for this repo.
//
// Usage: Workflow({ name: 'implement-issues', args: { issues: [123, 456], repo: 'piconic-ai/barefootjs', coauthor: 'Name <email>' } })
//   args.issues — required, array of issue numbers (numbers, "#123", or full issue URLs all work)
//   args.repo   — optional, "owner/repo", defaults to piconic-ai/barefootjs
//   args.coauthor — required, "Name <email>" of the human every commit is co-authored with (the caller resolves it per CLAUDE.md's "Git Commit" section before invoking)
//   args.base   — optional, the branch every group starts from and the first PR of each stack
//                 targets, defaults to the repository's default branch. Pass an open PR's branch
//                 to stack new work on top of it (e.g. a feature whose runtime is still in review).
//
// No reviewer-assignment step: this session's GitHub credentials author every PR it opens
// (as "kfly8" in this repo), and GitHub refuses to let a PR's own author be requested as
// its reviewer — there is no reviewer to assign that isn't already the author. Instead, the
// human gets a real GitHub @-mention notification once the PR is GENUINELY done — see below.
//
// IMPORTANT — notifying @kfly8 is entirely the CALLER's job, not this script's. This
// script's Polish phase marks each PR ready for review (undraft) and returns a ready-to-post
// `reviewRequestDraft` per PR, but does NOT post the @-mention itself. Why: undrafting a PR
// is what TRIGGERS Pullfrog's own review (an async, event-driven job this script cannot
// wait on without polling indefinitely — see below), so posting the mention in the same
// script turn as the undraft pings the human BEFORE Pullfrog's first review has even run,
// let alone before its findings are addressed. (Measured on a real run: undraft → Pullfrog
// "leaping into action" 2-4s later → mention posted 8-20s later → Pullfrog's actual
// first-pass review, with a real finding, landed 7 MINUTES after the mention. Resolving
// that finding, plus two more rounds of human-caught issues, took another ~3 hours before
// the PR was actually merged — all after the human had already been told "ready".)
//
// The CALLER must only post the @-mention once ALL of the following hold, and then only
// ONCE, per PR:
//   1. Pullfrog has reviewed the PR's CURRENT head (not a stale one) with no unresolved
//      blocking findings.
//   2. CI is green on that same head, with no merge conflict.
//   3. The caller has itself re-read the FINAL cumulative diff — Polish's own "clean,
//      nothing to fix" verdict is advisory only and must NOT be treated as evidence; on the
//      real run above, Polish reported both PRs clean and Pullfrog still found a real issue,
//      and the human still found two more issues neither Polish nor Pullfrog caught
//      (changeset hygiene; a regression test that approximated the real pipeline instead of
//      exercising it — see the Implement-phase note below). Re-review against: does every
//      new test exercise the REAL production entry point, or a hand-built approximation of
//      it? Are changesets/known-limitation pointers/fixture-drift checks (CLAUDE.md) in order?
//   4. No push has landed since the last Pullfrog approval (a fixup after approval
//      invalidates it — re-check, don't assume it still holds).
// Use the PR's OWN `reviewRequestDraft` as the comment body, but amend it if the diff
// changed since Polish produced it — a draft describing tests that no longer exist misleads
// the reviewer. For a stack, remember a fixup pushed to a LOWER PR (and the rebase it forces
// on everything above it) invalidates any approval already given to the PRs above it —
// re-verify the whole stack's current heads, not just the PR you just fixed.
//
// Footer hygiene (verified empirically against a real create/update pair on #3013, the PR
// that introduced this note — not just reasoned about): the GitHub MCP tools that CREATE
// something (`create_pull_request`, `add_issue_comment`, a review reply) auto-append their
// own canonical "_Generated by [Claude Code](...)_" footer whenever the submitted body
// doesn't already end with that EXACT string — but the dedup is a plain string match, so it
// does NOT recognize this session's differently-worded PR-description-style footer
// ("🤖 Generated with [Claude Code](...)") as an equivalent duplicate. Include that PR-
// description footer yourself in a body passed to `create_pull_request` and you get BOTH,
// stacked (measured: PR #3011's body, and #3013's own body on its first create_pull_request
// call). So: when CREATING a PR or POSTING a comment/reply/review — including the CALLER
// posting `reviewRequestDrafts[prNumber]` as a fresh comment via `add_issue_comment`, which
// Polish step 6 composes footer-less for exactly this reason — do not type any attribution
// footer yourself; leave it to the tool, and post the draft as-is.
//
// `update_pull_request` is the one exception: unlike the tools above, it does NOT auto-append
// anything (measured: an update with a footer-less body came back with zero footers). So if
// the CALLER directly edits an existing PR's body via `update_pull_request` (not the same
// thing as posting a new comment), add exactly one footer by hand — nothing else will.
//
// What this workflow does NOT do: it does not wait for Pullfrog's review or CI to turn
// green after opening the PR(s) — that is an ongoing, event-driven job (Pullfrog fires on
// its own trigger, CI takes minutes). Once this workflow returns, the caller must
// subscribe_pr_activity on each returned PR and drive it to green using this repo's
// standing "PR you opened" rules (CLAUDE.md's Git Commit section, the pullfrog review
// rubric in .github/pullfrog/review.md, and the harness's own PR-babysitting rules) —
// AND only post the @-mention once the bar above is met, per PR.

export const meta = {
  name: 'implement-issues',
  description: 'Plan, implement, review/simplify, and open stacked PR(s) for one or more GitHub issues',
  phases: [
    { title: 'Fetch', detail: 'read each issue and skim the codebase for likely touch points' },
    { title: 'Plan', detail: 'assess conflict risk and group issues into parallel/serial (stacked) batches', model: 'claude-opus-5' },
    { title: 'Implement', detail: 'implement, test, commit, and open draft PR(s) per group, stacking within a group' },
    { title: 'Polish', detail: 'per group, run code-review + simplify down the PR stack in order, push fixes, mark each ready for review, and draft (not post) a review-request comment for the caller' },
  ],
}

// Design/planning uses a stronger model per the requester's instruction; implementation
// and polish use Sonnet. Swap DESIGN_MODEL to 'claude-fable-5-1' if Fable is preferred.
const DESIGN_MODEL = 'claude-opus-5'
const IMPLEMENT_MODEL = 'claude-sonnet-5'

function parseIssueNumber(x) {
  if (typeof x === 'number') return x
  const s = String(x)
  // Prefer the /issues/<n> path segment so a comment-anchored issue URL
  // (".../issues/123#issuecomment-456") resolves to 123, not the trailing 456.
  const issuePath = s.match(/\/issues\/(\d+)(?:[/?#]|$)/)
  if (issuePath) return Number(issuePath[1])
  const m = s.match(/(\d+)\s*$/)
  return m ? Number(m[1]) : NaN
}

const repo = (args && args.repo) || 'piconic-ai/barefootjs'

// Where every group starts and what the first PR of each stack targets. The default branch
// unless the caller stacks this run on an existing branch (an open PR's head). A git ref name
// only: no whitespace, no leading '-', so it cannot smuggle an option into a git command.
const BASE_BRANCH = args && typeof args.base === 'string' ? args.base.trim() : ''
if (BASE_BRANCH && !/^[A-Za-z0-9._\/-]+$/.test(BASE_BRANCH)) {
  throw new Error(`args.base must be a plain branch name, got ${JSON.stringify(args.base)}`)
}
if (BASE_BRANCH.startsWith('-')) {
  throw new Error(`args.base must not start with '-', got ${JSON.stringify(args.base)}`)
}
const BASE_DESC = BASE_BRANCH ? `the branch \`${BASE_BRANCH}\` (fetch it from origin first)` : "the repository's default branch"

// The human collaborator every commit is co-authored with. CLAUDE.md's "Git Commit" section
// says a remote session (git author `Claude`) must pick the human identity via
// AskUserQuestion before the first commit. A workflow agent has no user to ask, so the
// CALLER resolves the identity (it has the user in front of it) and passes it in; nothing is
// hard-coded here. Measured on the first real run: without an explicit identity the
// Implement and Polish agents produced four commits with only the model trailer, and the
// human had to ask for a history rewrite afterwards.
const HUMAN_COAUTHOR = args && typeof args.coauthor === 'string' ? args.coauthor.trim() : ''
if (!/^[^<>]+ <[^<>@\s]+@[^<>\s]+>$/.test(HUMAN_COAUTHOR)) {
  throw new Error(
    'args.coauthor is required: the "Name <email>" of the human every commit is co-authored with. ' +
      "Resolve it the way CLAUDE.md's \"Git Commit\" section says (git log for the human identity, AskUserQuestion if ambiguous) before invoking this workflow.",
  )
}

// Interpolated verbatim into the Implement and Polish prompts. It does not restate the
// trailer format — CLAUDE.md's "Git Commit" section is the one rule — it only supplies the
// piece an agent cannot obtain itself: the human identity the caller already chose.
const COMMIT_TRAILER_RULE = `Commit exactly as CLAUDE.md's "Git Commit" section says (your own implementer trailer first, then the other collaborators, as the final lines of the message). You cannot run its AskUserQuestion step, so the human collaborator has already been chosen by the caller of this workflow — add \`Co-authored-by: ${HUMAN_COAUTHOR}\` to every commit, and commit as the default remote author (\`git -c user.name=Claude -c user.email=noreply@anthropic.com\`).`
const rawIssues = (args && args.issues) || []
const issues = rawIssues.map(parseIssueNumber).filter((n) => !Number.isNaN(n))

if (issues.length === 0) {
  throw new Error('args.issues must be a non-empty array of issue numbers (or "#123" / issue URLs)')
}

const ISSUE_SCHEMA = {
  type: 'object',
  properties: {
    number: { type: 'number' },
    title: { type: 'string' },
    body: { type: 'string' },
    labels: { type: 'array', items: { type: 'string' } },
    likelyFiles: {
      type: 'array',
      items: { type: 'string' },
      description: 'Files/subsystems this issue will likely touch, based on the issue text and a codebase skim. Do not implement anything yet.',
    },
  },
  required: ['number', 'title', 'body'],
}

phase('Fetch')
const fetched = await parallel(
  issues.map((num) => () =>
    agent(
      `In the GitHub repo ${repo}, fetch issue #${num} (title, full body, labels) using the GitHub MCP tools. ` +
        `Then skim the codebase to guess which files or subsystems this issue will likely touch — do NOT implement anything yet, this is reconnaissance only. ` +
        `Return the issue's number, title, body, labels, and your likelyFiles guess as structured data.`,
      { schema: ISSUE_SCHEMA, phase: 'Fetch', label: `fetch #${num}` },
    ),
  ),
)

const validIssues = fetched.filter(Boolean)
if (validIssues.length === 0) {
  throw new Error(`Could not fetch any of the requested issues from ${repo}: ${issues.join(', ')}`)
}
if (validIssues.length < issues.length) {
  const found = new Set(validIssues.map((i) => i.number))
  const missing = issues.filter((n) => !found.has(n))
  log(`Warning: could not fetch issue(s) ${missing.join(', ')} — continuing with the rest.`)
}

function issueByNumber(n) {
  return validIssues.find((i) => i.number === n)
}

phase('Plan')

let plan
if (validIssues.length === 1) {
  plan = {
    groups: [{ issues: [validIssues[0].number], reason: 'Only one issue was given.' }],
    conflictAnalysis: 'Single issue — no cross-issue conflict analysis needed.',
  }
  log(`Single issue #${validIssues[0].number} — skipping conflict analysis, one group.`)
} else {
  const PLAN_SCHEMA = {
    type: 'object',
    properties: {
      groups: {
        type: 'array',
        description:
          `Ordered list of groups. Groups run in PARALLEL with each other (each starting from ${BASE_DESC}, in its own worktree). Issues within a group run STRICTLY SERIALLY, each PR stacked on the previous one's branch.`,
        items: {
          type: 'object',
          properties: {
            issues: { type: 'array', items: { type: 'number' } },
            reason: { type: 'string' },
          },
          required: ['issues', 'reason'],
        },
      },
      conflictAnalysis: { type: 'string' },
    },
    required: ['groups', 'conflictAnalysis'],
  }

  const planPrompt = `
You are planning how to implement the following GitHub issues from ${repo} as pull requests.

Issues (number, title, body, labels, likely files):
${JSON.stringify(validIssues, null, 2)}

Decide:
1. For every pair of issues, whether implementing them risks touching the same files or subsystems (a real conflict risk) — based on likelyFiles, title, and body, and your own knowledge of the codebase's structure.
2. Group the issues into an ORDERED LIST OF GROUPS. Issues in the SAME group are implemented strictly serially, each PR stacked on top of the previous one's branch (later PR's base = earlier PR's branch). Issues in DIFFERENT groups are implemented in parallel, each starting from ${BASE_DESC} in a separate git worktree.
3. Only place issues in different (parallel) groups when you are CONFIDENT they touch disjoint files/areas. If you are unsure, or the risk is ambiguous, keep them in the SAME group (serial) — when in doubt, serial.
4. Every issue must appear in exactly one group.

Return the groups (each with its issue numbers and a one-line reason) plus a short conflictAnalysis paragraph explaining your reasoning across all issues.
`.trim()

  plan = await agent(planPrompt, { schema: PLAN_SCHEMA, phase: 'Plan', model: DESIGN_MODEL, label: 'conflict + grouping plan' })
  log(`Plan: ${plan.groups.length} group(s) — ${plan.conflictAnalysis}`)
}

// The planner is asked to place every issue in exactly one group (PLAN_SCHEMA's own
// invariant), but nothing enforces that a model actually honored it — verify it here the
// same way Fetch verifies its own completeness, rather than trusting the plan blindly.
{
  const counts = new Map()
  for (const group of plan.groups) {
    for (const n of group.issues) counts.set(n, (counts.get(n) || 0) + 1)
  }
  const allNumbers = validIssues.map((i) => i.number)
  const duplicated = [...new Set(allNumbers.filter((n) => (counts.get(n) || 0) > 1))]
  if (duplicated.length > 0) {
    throw new Error(
      `Plan placed issue(s) ${duplicated.join(', ')} in more than one group — refusing to risk duplicate/conflicting PRs.`,
    )
  }
  const missing = allNumbers.filter((n) => !counts.has(n))
  if (missing.length > 0) {
    log(`Warning: plan omitted issue(s) ${missing.join(', ')} — appending them as a trailing serial group.`)
    plan.groups.push({ issues: missing, reason: "Added by validation: the planner's grouping omitted these issues." })
  }
}

phase('Implement')

const GROUP_RESULT_SCHEMA = {
  type: 'object',
  properties: {
    prs: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          issueNumbers: { type: 'array', items: { type: 'number' } },
          branch: { type: 'string' },
          baseBranch: { type: 'string' },
          prNumber: { type: 'number' },
          prUrl: { type: 'string' },
          title: { type: 'string' },
          pipelineAssumptions: {
            type: 'array',
            items: { type: 'string' },
            description:
              'Every assumption this fix\'s correctness makes about state controlled by the REAL production entry point it runs in (iteration/call/compile order, timing, caching, cross-file or cross-request state) — empty array if genuinely none. Each entry must say how it was verified (a citation into the real pipeline code) or that it is instead tracked as a known-limitation (issue URL).',
          },
          pipelineVerifiedAgainst: {
            type: 'string',
            description:
              'The real production entry point this fix was traced through (file:line or command), or "N/A — no order/timing/state-dependent assumptions" if pipelineAssumptions is empty. Must NOT just name the unit test you wrote if that test only exercises the fix directly rather than the real pipeline.',
          },
        },
        required: ['branch', 'baseBranch', 'prNumber', 'prUrl', 'pipelineAssumptions', 'pipelineVerifiedAgainst'],
      },
    },
    notes: { type: 'string' },
  },
  required: ['prs'],
}

function buildImplementPrompt(groupIssues) {
  const issuesText = groupIssues
    .map((i) => `### Issue #${i.number}: ${i.title}\n\n${i.body}`)
    .join('\n\n---\n\n')
  return `
You are implementing the following GitHub issue(s) from ${repo}, in this exact order, as one stack of PRs. This repo's CLAUDE.md is already loaded for you — follow it, especially the "Git Commit" trailer rules and the testing table, and (for compiler/adapter changes) the "Never ..." code conventions and the subset-conformance fixture-coupling rule.

${issuesText}

For each issue above, in order:
1. Create a branch off the current HEAD: the FIRST issue's branch is created off ${BASE_DESC}; each SUBSEQUENT issue's branch is created off the PREVIOUS issue's branch, so the PRs stack.
2. Implement it. If an issue naturally splits into more than one semantic unit of work, split it into multiple sequential commits and multiple stacked PRs instead of one large PR — use judgement, most issues are a single PR. Do not bundle unrelated cleanup into the same commit.
3. Before writing tests, name the REAL entry point that will execute this change in production (e.g. \`bf build\` / the \`@barefootjs/vite\` plugin's real component-discovery and compile pipeline, not just the adapter/compiler API you're unit-testing directly). List every assumption the fix's correctness makes about state that entry point controls — iteration/call/compile order, timing, caching, cross-file or cross-request state. For each assumption, either (a) verify it against that REAL entry point's actual code (cite file:line for the guarantee — a hand-built unit test that happens to call things in a convenient order is NOT verification, since it can pass by accident even when the real pipeline's order differs), (b) change the fix so it no longer depends on that assumption, or (c) if fixing it in general is out of scope, file a \`known-limitation\` issue and scope this PR's body honestly to what it actually fixes, per CLAUDE.md's known-limitation policy — do not claim "Closes #N" for a case the fix doesn't actually cover.
4. Run the relevant tests/typecheck for what you touched and confirm they pass before committing. Follow the CLAUDE.md testing decision guide to pick the right test layer. Prefer a test that exercises the real entry point from step 3 over one that calls the unit in isolation, whenever the fix's correctness depends on any assumption you listed in step 3. If the change touches a file shared by many components rather than one component's own source (\`packages/client/src/runtime/\`, \`packages/jsx/src/\`, or an adapter's shared render path) — "relevant" is not determinable by reading the diff, since any component on that shared path can be affected; run the FULL suite at that layer (e.g. the whole \`site/ui/e2e\` sweep, not a hand-picked subset) rather than guessing which specs are relevant. When the change touches component identity/context resolution specifically, also check the component instantiated once per \`.map()\` row, not just once at top level — a fix verified only against a single, non-looped instance can silently fail for every row after the first, or leak state across rows, with no error and no failing assertion in a narrower test (measured: #3099/#3115 — an SSR-portal fix that was fully green against every non-looped e2e spec still broke a looped, multi-level-forwarded \`<Select>\` in a way none of those specs could have caught).
5. ${COMMIT_TRAILER_RULE}
6. Push the branch with \`git push -u origin <branch>\` and open the PR as a DRAFT via the GitHub MCP tools, with base = the branch from the previous step (or, for the first PR in the stack, ${BASE_BRANCH ? `\`${BASE_BRANCH}\`` : 'the default branch'}). Check the repo for a PR template first (there is none at the time of writing, but re-check). Put "Closes #<issue>" in the body for whichever issue(s) that PR resolves — only for the case(s) it genuinely covers, per step 3(c). Do NOT type any "Generated by/with Claude Code" attribution footer into the body you pass to the PR-creation tool — it auto-appends its own, and a footer you add yourself (in ANY wording) stacks with it instead of being deduplicated, producing two visible "Generated by Claude Code" blocks (measured on #3011 and #3013 — see the header comment above for the full mechanism).

Return the full list of PRs you opened, in the order you opened them: for each, the issue number(s) it addresses, its branch, its base branch, PR number, PR URL, title, the pipelineAssumptions list from step 3, and pipelineVerifiedAgainst.
`.trim()
}

const groupImplementResults = await parallel(
  plan.groups.map((group, gi) => () => {
    const groupIssues = group.issues.map(issueByNumber).filter(Boolean)
    return agent(buildImplementPrompt(groupIssues), {
      schema: GROUP_RESULT_SCHEMA,
      phase: 'Implement',
      label: `group ${gi + 1} (issues ${group.issues.join(', ')})`,
      model: IMPLEMENT_MODEL,
      isolation: plan.groups.length > 1 ? 'worktree' : undefined,
    })
  }),
)

const allPRs = groupImplementResults.filter(Boolean).flatMap((r) => r.prs || [])
if (allPRs.length === 0) {
  log('No PRs were opened by the implement phase — stopping before polish/land.')
  return { repo, plan, prs: [] }
}
log(`Implement phase opened ${allPRs.length} PR(s): ${allPRs.map((p) => `#${p.prNumber}`).join(', ')}`)

phase('Polish')

const POLISH_ITEM_SCHEMA = {
  type: 'object',
  properties: {
    prNumber: { type: 'number' },
    polishSelfAssessment: {
      type: 'string',
      description:
        'ADVISORY ONLY — what this pass found and fixed, or "clean — nothing to fix" if nothing. Do NOT treat "clean" as proof the PR is done: Pullfrog and the human maintainer have both independently found real issues on PRs this pass called clean. This is one input among several the caller weighs before notifying anyone, never sufficient by itself.',
    },
    pushedFixes: { type: 'boolean' },
    markedReadyForReview: { type: 'boolean' },
    reviewRequestDraft: {
      type: 'string',
      description:
        'A ready-to-post PR comment body (starting with "@kfly8", including What / How to verify / Expected result) that the CALLER may post later — once it has confirmed Pullfrog approved the PR\'s current head with no unresolved findings, CI is green, there is no merge conflict, and the caller has itself re-reviewed the final diff. Do NOT post this comment yourself; return it as text only. If the diff changes after this pass (a Pullfrog fixup, a caller-driven follow-up), the caller is responsible for amending this draft before posting it, not this pass.',
    },
  },
  required: ['prNumber', 'polishSelfAssessment', 'pushedFixes', 'markedReadyForReview', 'reviewRequestDraft'],
}

const POLISH_GROUP_SCHEMA = {
  type: 'object',
  properties: { results: { type: 'array', items: POLISH_ITEM_SCHEMA } },
  required: ['results'],
}

// PRs within a group stack (each based on the previous one's branch). Polishing them with
// one independent agent per PR, all in parallel, would let a lower PR's fixup commit miss
// the higher PRs that already forked from its pre-fix tip and are being polished at the
// same time — the stack would come out needing a manual rebase. So one agent processes an
// entire group's stack itself, in order, in a single worktree, rebasing each PR onto the
// previous one's (possibly just-fixed) tip before reviewing it.
function buildGroupPolishPrompt(groupPRs) {
  const stackList = groupPRs.map((pr, i) => `${i + 1}. PR #${pr.prNumber} — branch "${pr.branch}" (base "${pr.baseBranch}")`).join('\n')
  return `
The following PR(s) in ${repo} form one stack, in this order (each based on the previous):

${stackList}

Process them ONE AT A TIME, IN THIS ORDER, in the same working tree so any fixup commits propagate down the stack:

For each PR, in order:
1. Check out its branch. If it stacks on a PR you already polished earlier in this same task and that PR's branch received fixup commits, rebase (or merge) this branch onto that updated base branch FIRST, resolving any conflicts, before reviewing — do not move on to review until this PR's branch includes the previous PR's fixes.
2. Run the equivalent of the /code-review skill (medium-high effort) against this branch's diff versus its base branch: look for correctness bugs and reuse/simplification/efficiency issues. If the Skill tool is available to you, invoke it with skill "code-review"; otherwise perform the same review inline, using this repo's CLAUDE.md conventions and .github/pullfrog/review.md's rubric as your criteria.
3. Run the equivalent of the /simplify skill on the same diff: apply reuse, simplification, efficiency, and "altitude" cleanups to the changed code ONLY. This step is quality-only — do not go hunting for new bugs, that was the previous step.
4. Apply any fixes directly on the branch, re-run the relevant tests, commit them, and push — the NEXT PR in the stack depends on this being pushed before you move on. If a test fails and you're tempted to call it "pre-existing" or "unrelated to this change," verify that claim before writing it down anywhere (a PR comment, this step's own reasoning) — check out the PR's base branch (or \`git bisect\`) and run that SAME test against it; only a failure you've reproduced there is actually pre-existing. Asserting it from reading the diff alone is not verification, and reporting an unverified guess as fact is worse than saying you're not sure. ${COMMIT_TRAILER_RULE}
5. Once you're satisfied this PR is genuinely ready for a human, use the GitHub MCP tools to mark it "ready for review" (undraft it). Undrafting triggers Pullfrog's own automated review asynchronously — do NOT wait for it, and do NOT post any comment or @-mention on the PR yourself. That is the CALLER's job, done later, only after Pullfrog has actually reviewed this PR's head with no unresolved findings and CI is green — not right now, and not by you.
6. Instead, COMPOSE (but do not post) a review-request comment as text, starting with "@kfly8", that the caller can post later. Make it a self-contained review request, not just a ping — include all of:
   - **What**: one or two sentences on what changed and why.
   - **How to verify**: concrete, runnable steps a reviewer would follow to check the change themselves (exact commands — tests, typecheck, a manual repro — not "review the diff"). If code-review/simplify already ran clean, say so; if they fixed something, name what.
   - **Expected result**: what those steps should show when the change is correct (test output, behavior, absence of a prior symptom) — specific enough that a reviewer knows whether what they see matches, not just "it works".
   Do NOT append any "Generated by/with Claude Code" attribution footer to this draft — the caller posts it as a plain new comment via the GitHub MCP tools, which auto-appends the correct footer on its own; a footer baked in here would stack with that instead of being deduplicated (see the header comment above for the measured mechanism).

Return one entry per PR above, in the same order, each with: prNumber, polishSelfAssessment (what you found/fixed, or "clean — nothing to fix" — but see the schema note: this is advisory only, not proof of done-ness), whether you pushed any fix commits, whether you marked it ready for review, and the reviewRequestDraft text from step 6 (composed, NOT posted).
`.trim()
}

const polishGroupResults = await parallel(
  groupImplementResults.map((groupResult, gi) => () => {
    const groupPRs = groupResult && groupResult.prs ? groupResult.prs : []
    if (groupPRs.length === 0) return null
    return agent(buildGroupPolishPrompt(groupPRs), {
      schema: POLISH_GROUP_SCHEMA,
      phase: 'Polish',
      label: `polish group ${gi + 1} (${groupPRs.length}-PR stack)`,
      model: IMPLEMENT_MODEL,
      isolation: 'worktree',
    })
  }),
)

const polishResults = polishGroupResults.filter(Boolean).flatMap((r) => r.results || [])

// The Polish prompt asks each PR to report markedReadyForReview precisely because it can
// fail — trust the flag instead of assuming every PR succeeded, so a PR that's actually
// still in draft gets called out instead of silently reported as done. Note this is
// "undrafted", NOT "done" — @-mentioning the human is deliberately NOT part of this
// script (see the header comment); reviewRequestDraft below is a draft for the CALLER to
// post later, once it has independently confirmed the PR is actually ready.
const polishedByNumber = new Map(polishResults.map((r) => [r.prNumber, r]))
const readyForReview = []
const needsFollowUp = []
for (const pr of allPRs) {
  const r = polishedByNumber.get(pr.prNumber)
  if (r && r.markedReadyForReview) {
    readyForReview.push(pr)
  } else {
    needsFollowUp.push({ pr, result: r })
  }
}

if (needsFollowUp.length > 0) {
  log(
    `Warning: ${needsFollowUp.length} PR(s) still need manual follow-up (not marked ready for review): ` +
      needsFollowUp
        .map(({ pr, result }) =>
          result
            ? `#${pr.prNumber} (${pr.prUrl}) — markedReadyForReview=${result.markedReadyForReview}`
            : `#${pr.prNumber} (${pr.prUrl}) — its group's polish agent produced no result for it`,
        )
        .join('; '),
  )
}

// Filtered to readyForReview only — a PR whose polish agent reported
// markedReadyForReview: false (still draft) must never surface a draft the
// caller could mistake for postable, however unlikely given the caller's
// own Pullfrog/CI gate (pullfrog[bot] review, PR #2993).
const readyForReviewNumbers = new Set(readyForReview.map((pr) => pr.prNumber))
const reviewRequestDrafts = Object.fromEntries(
  polishResults.filter((r) => readyForReviewNumbers.has(r.prNumber)).map((r) => [r.prNumber, r.reviewRequestDraft]),
)

log(
  `Done. ${readyForReview.length}/${allPRs.length} PR(s) marked ready for review: ${readyForReview.map((p) => p.prUrl).join(', ') || 'none'}. ` +
    `NOT @-mentioned — that is the caller's job. Caller: subscribe_pr_activity on each, drive CI/Pullfrog feedback to green ` +
    `per this repo's standing PR rules, and ONLY THEN — after Pullfrog approves the current head with no unresolved findings, ` +
    `CI is green, no conflicts, and you've re-reviewed the final diff yourself (Polish's own "clean" verdict is advisory, not proof) — ` +
    `post the matching reviewRequestDraft (amended if the diff changed since) as a PR comment, exactly once per PR. ` +
    `Also proactively notify the user now that this workflow finished — this script cannot do that part itself.`,
)

return {
  repo,
  plan,
  prs: allPRs,
  polish: polishResults,
  readyForReview,
  needsFollowUp: needsFollowUp.map(({ pr }) => pr),
  handoff: {
    notifyHuman: 'caller',
    note:
      'Post reviewRequestDrafts[prNumber] as a PR comment only after: Pullfrog approved the PR\'s CURRENT head with no unresolved findings, CI is green, no merge conflict, and you have re-reviewed the final diff yourself. Exactly once per PR. For a stack, a fixup on a lower PR invalidates approvals already given to the PRs above it — re-verify the whole stack\'s current heads before posting any mention.',
    reviewRequestDrafts,
  },
}
