/**
 * Generates the landing-page demo panels from REAL compiler output.
 *
 * The LP promises "what your server renders" — so the right-hand panels
 * must be the actual `compileJSX` (bf build) output for the source shown
 * in the left-hand panel, never hand-written approximations
 * (see design/LP-RENEWAL.md, 決定事項 6).
 *
 * Run from site/core:
 *   bun run landing/generate-demo-outputs.ts
 *
 * Writes landing/components/shared/demo-outputs.ts (committed) so the
 * Worker bundle stays static and reviewers can diff exactly what the LP
 * claims the compiler produces.
 */

import { compileJSX } from '@barefootjs/jsx'
import type { TemplateAdapter } from '@barefootjs/jsx'
import { GoTemplateAdapter } from '@barefootjs/go-template/adapter'
import { ErbAdapter } from '@barefootjs/erb/adapter'
import { JinjaAdapter } from '@barefootjs/jinja/adapter'
import { MojoAdapter } from '@barefootjs/mojolicious/adapter'
import { resolve, dirname } from 'node:path'

const OUT_FILE = resolve(dirname(import.meta.path), 'components/shared/demo-outputs.ts')

/** The exact source shown in the left panel. Compiled as Counter.tsx. */
const SOURCE = `"use client"

import { createSignal } from '@barefootjs/client'

export function Counter() {
  const [count, setCount] = createSignal(0)
  return (
    <button onClick={() => setCount(c => c + 1)}>
      Count: {count()}
    </button>
  )
}
`

interface DemoTarget {
  /** Tab id used in the LP markup. */
  id: string
  /** Tab label (the backend the visitor recognizes, per the mock). */
  label: string
  /** Filename comment shown above the output. */
  file: string
  /** Shiki language for highlighting. */
  lang: string
  adapter: () => TemplateAdapter
}

const TARGETS: DemoTarget[] = [
  { id: 'go', label: 'go', file: 'counter.tmpl', lang: 'go-html-template', adapter: () => new GoTemplateAdapter() },
  { id: 'erb', label: 'rails', file: 'counter.html.erb', lang: 'erb', adapter: () => new ErbAdapter() },
  { id: 'jinja', label: 'django', file: 'counter.html.j2', lang: 'jinja', adapter: () => new JinjaAdapter() },
  { id: 'ep', label: 'perl', file: 'counter.html.ep', lang: 'perl', adapter: () => new MojoAdapter() },
]

interface DemoOutput {
  id: string
  label: string
  file: string
  lang: string
  code: string
}

const outputs: DemoOutput[] = []
let clientJs = ''

for (const target of TARGETS) {
  const adapter = target.adapter()
  const result = compileJSX(SOURCE, 'Counter.tsx', { adapter })

  const errors = result.errors.filter((e) => e.severity === 'error')
  if (errors.length > 0) {
    console.error(`Errors compiling for ${target.id}:`)
    for (const e of errors) console.error(`  ${e.code}: ${e.message}`)
    process.exit(1)
  }

  const template = result.files.find((f) => f.type === 'markedTemplate')
  if (!template) {
    console.error(`No markedTemplate produced for ${target.id}`)
    process.exit(1)
  }

  outputs.push({
    id: target.id,
    label: target.label,
    file: target.file,
    lang: target.lang,
    code: template.content.trimEnd(),
  })

  const client = result.files.find((f) => f.type === 'clientJs')
  if (client) clientJs = client.content.trimEnd()
}

const banner = `/**
 * AUTO-GENERATED — Do not edit manually.
 *
 * Real \`compileJSX\` output for the landing-page demo, generated by
 * landing/generate-demo-outputs.ts. Regenerate with:
 *
 *   bun run landing/generate-demo-outputs.ts   (from site/core)
 *
 * The LP's honesty guarantee: these panels are the compiler's actual
 * output for DEMO_SOURCE, not hand-written approximations.
 */
`

const module_ = `${banner}
/** The exact Counter.tsx source the panels were compiled from. */
export const DEMO_SOURCE = ${JSON.stringify(SOURCE.trimEnd())}

export interface DemoOutput {
  id: string
  label: string
  file: string
  lang: string
  code: string
}

export const DEMO_OUTPUTS: DemoOutput[] = ${JSON.stringify(outputs, null, 2)}

/** The client JS the compiler emits alongside the templates (same for every adapter). */
export const DEMO_CLIENT_JS = ${JSON.stringify(clientJs)}
`

await Bun.write(OUT_FILE, module_)
console.log(`Wrote ${OUT_FILE}`)
for (const o of outputs) {
  console.log(`--- ${o.id} (${o.code.split('\n').length} lines) ---`)
  console.log(o.code)
}
console.log(`--- client JS (${clientJs.split('\n').length} lines) ---`)
console.log(clientJs)
