// Maintains a Cloudflare Workers `.assetsignore` in the build `outDir` so
// `wrangler deploy` doesn't upload barefoot's server/build-only outputs as
// publicly fetchable assets. See piconic-ai/barefootjs#1651.
//
// `bf build` writes both browser-served files (`barefoot.js`, `*.client.js`,
// vendor chunks) and server/build-only files (SSR `.tsx` templates,
// `manifest.json`, `barefoot-externals.json`, `.bfemit.json`,
// `.buildcache.json`, `.dev/`) into the same `outDir`. When that dir is a
// Workers `assets.directory`, the server-only files ship as downloadable
// assets — leaking SSR template source and wasting uploads.
//
// `.assetsignore` is a wrangler-specific convention (gitignore-style), so the
// file is only touched when the project targets Workers. barefoot owns a
// single marked block inside the file; any user-authored lines outside the
// markers are preserved across rebuilds.

import { resolve } from 'node:path'
import { fileExists, readText } from './runtime'
import { writeIfChanged } from './fs-utils'
import { CACHE_FILENAME } from './build-cache'
import { EMIT_LEDGER_FILENAME } from './emit-ledger'

export const ASSETS_IGNORE_FILENAME = '.assetsignore'

const BLOCK_BEGIN = '# >>> barefoot managed block (generated by `bf build`) >>>'
const BLOCK_END = '# <<< barefoot managed block <<<'

// `.assetsignore` is read by wrangler, so its presence is the signal that the
// project deploys to Cloudflare Workers. A wrangler config sitting next to
// `barefoot.config.ts` is the cheapest, runtime-agnostic detection (the Hono
// adapter targets both Node and Workers, so the adapter name can't tell us).
const WRANGLER_CONFIG_NAMES = ['wrangler.toml', 'wrangler.json', 'wrangler.jsonc'] as const

/**
 * True when `projectDir` looks like a Cloudflare Workers project — i.e. it
 * holds a wrangler config alongside `barefoot.config.ts`.
 */
export async function isCloudflareWorkersProject(projectDir: string): Promise<boolean> {
  for (const name of WRANGLER_CONFIG_NAMES) {
    if (await fileExists(resolve(projectDir, name))) return true
  }
  return false
}

export interface ServerOnlyAssetsInput {
  /** Subdir holding `.dev/build-id` (build.ts `DEV_SENTINEL_SUBDIR`). */
  devSentinelSubdir: string
  /** Subdir holding `manifest.json` and the SSR templates. */
  templatesSubdir: string
  /** Build manifest: `componentId → { markedTemplate, clientJs }`. */
  manifest: Record<string, { markedTemplate?: string }>
  /** Whether `config.externals` is non-empty (gates `barefoot-externals.json`). */
  hasExternals: boolean
  /** Whether the build skipped templates + manifest (`clientOnly`). */
  clientOnly: boolean
}

/**
 * The set of `outDir`-relative paths that `bf build` emits but the browser
 * never fetches: build cache / dev sentinel, the externals map, the manifest,
 * and every SSR template. Sorted so the emitted block is stable across builds.
 */
export function collectServerOnlyAssets(input: ServerOnlyAssetsInput): string[] {
  const entries = new Set<string>()
  // Build cache + dev live-reload marker (always written).
  entries.add(`${input.devSentinelSubdir}/`)
  entries.add(EMIT_LEDGER_FILENAME)
  entries.add(CACHE_FILENAME)
  // Importmap/externals map is only written when externals are configured.
  if (input.hasExternals) entries.add('barefoot-externals.json')
  // Templates + manifest only exist outside clientOnly mode.
  if (!input.clientOnly) {
    entries.add(`${input.templatesSubdir}/manifest.json`)
    for (const row of Object.values(input.manifest)) {
      // The `__barefoot__` runtime sentinel has an empty markedTemplate; real
      // components carry their SSR template path (e.g. `components/button.tsx`).
      if (row.markedTemplate) entries.add(row.markedTemplate)
    }
  }
  return [...entries].sort()
}

/**
 * Remove barefoot's previously-generated block (markers included) and return
 * the remaining user content, trimmed. Collapses the blank-line gap the
 * removal leaves behind so repeated rewrites don't accrete whitespace.
 */
function stripManagedBlock(content: string): string {
  const lines = content.split('\n')
  const begin = lines.indexOf(BLOCK_BEGIN)
  const end = lines.indexOf(BLOCK_END)
  if (begin !== -1 && end !== -1 && end > begin) {
    const kept = [...lines.slice(0, begin), ...lines.slice(end + 1)]
    return kept.join('\n').replace(/\n{3,}/g, '\n\n').trim()
  }
  return content.trim()
}

function buildManagedBlock(entries: string[]): string {
  return [
    BLOCK_BEGIN,
    '# Server/build-only barefoot outputs — not browser-served. Regenerated on',
    '# every `bf build`; add your own entries outside this block.',
    ...entries,
    BLOCK_END,
  ].join('\n')
}

/**
 * Merge `entries` into `<outDir>/.assetsignore` as a single managed block,
 * preserving any user-authored lines outside the markers. Returns true when
 * the file changed on disk.
 */
export async function writeAssetsIgnore(outDir: string, entries: string[]): Promise<boolean> {
  const path = resolve(outDir, ASSETS_IGNORE_FILENAME)
  const existing = (await fileExists(path)) ? await readText(path) : ''
  const userContent = stripManagedBlock(existing)
  const block = buildManagedBlock(entries)
  const merged = userContent.length > 0 ? `${userContent}\n\n${block}\n` : `${block}\n`
  return writeIfChanged(path, merged)
}
