// CSS-library scaffold transforms.
//
// `bf init` offers a `--css` choice (lib/templates.ts `CSS_LIBRARIES`).
// Today the two options are `unocss` (the default — wires UnoCSS + the
// barefootjs UI registry) and `none` (bring your own CSS: no UnoCSS, no
// registry components, no stylesheets). The adapter templates are written
// for the UnoCSS path; the helpers here rewrite that output for `none` so
// a single set of templates serves both without every adapter branching
// internally.
//
// All three transforms are pure string→string so they stay trivially
// unit-testable against the real adapter script/markup shapes
// (see __tests__/css.test.ts).

import { CSS_LINKS_BEGIN, CSS_LINKS_END } from './adapters/shared'

// Rewrite the stylesheet `<link>` region every adapter's <head> wraps in
// CSS_LINKS_BEGIN/END marker lines.
//   - `unocss`: drop the two marker lines, keep the links + comment.
//   - `none`:   drop the markers AND everything between them, leaving a
//               <head> with no stylesheet references.
// Files without the markers (most scaffold files) pass through untouched.
export function processCssHead(content: string, usesUno: boolean): string {
  if (!content.includes(CSS_LINKS_BEGIN)) return content
  const out: string[] = []
  let inRegion = false
  for (const line of content.split('\n')) {
    const trimmed = line.trim()
    if (trimmed === CSS_LINKS_BEGIN) {
      inRegion = true
      continue
    }
    if (trimmed === CSS_LINKS_END) {
      inRegion = false
      continue
    }
    // Inside the region, keep the body only for the UnoCSS path.
    if (inRegion && !usesUno) continue
    out.push(line)
  }
  return out.join('\n')
}

// Strip every UnoCSS touch-point out of a package.json script command.
// Handles the concrete shapes the adapters emit:
//   - the `"unocss --watch"` pane inside a `concurrently` invocation
//     (and the matching `uno`/`magenta` entries in its -n/-c lists)
//   - `unocss` links in `&&` chains (`vite build && unocss`,
//     `vite build && unocss && <next>`, `go mod tidy && vite build && unocss`)
// Commands with no UnoCSS reference are returned unchanged.
export function stripUnocssFromScript(cmd: string): string {
  let out = cmd
  // 1. Remove the dedicated unocss concurrently pane. The leading space
  //    is part of the match so the surrounding panes stay correctly
  //    single-spaced whether the pane sat in the middle or at the end.
  out = out.split(' "unocss --watch"').join('')
  // 2. Re-balance the concurrently name/color lists now that the `uno`
  //    pane is gone. Positional, NOT a match on known pane names: the
  //    adapters name their other panes differently (`vite,uno,wrangler`,
  //    `dev,uno,server`, `build,uno,server`, `build,uno`), and a rewrite
  //    keyed on any one of those spellings silently no-ops on the rest —
  //    leaving three names for two commands, so `concurrently` labels the
  //    server pane `uno` and colors it magenta. `uno` is the only entry
  //    whose position is fixed by construction (it is the pane this
  //    function just removed); everything else is read off the string.
  out = out.replace(/-n (\S+) -c (\S+)/, (whole, names: string, colors: string) => {
    const nameList = names.split(',')
    const unoIndex = nameList.indexOf('uno')
    if (unoIndex === -1) return whole
    const colorList = colors.split(',')
    nameList.splice(unoIndex, 1)
    if (unoIndex < colorList.length) colorList.splice(unoIndex, 1)
    return `-n ${nameList.join(',')} -c ${colorList.join(',')}`
  })
  // 3. Drop `unocss` from `&&` chains: middle occurrence first, then a
  //    trailing one.
  out = out.split(' && unocss && ').join(' && ')
  out = out.replace(/ && unocss$/, '')
  return out
}

// Remove the `# UnoCSS output` block from a generated `.gitignore`.
// buildGitignore (lib/adapters/shared.ts) always seeds this paragraph;
// the bare scaffold never produces `uno.css`, so the ignore entry would
// be dead. Targeted on the exact shared block so it's a no-op for any
// adapter that doesn't carry it.
export function stripUnoGitignore(content: string): string {
  return content.replace(
    '# UnoCSS output (regenerated by `unocss --watch` / `unocss`)\npublic/uno.css\n\n',
    '',
  )
}
