/**
 * The source-level directives the compiler recognizes. This module is the
 * single definition of their spelling: every detection site in the
 * analyzer, the IR builder, and the preprocessors reads the constants
 * below rather than repeating the literal, and the API reference
 * (`docs/core/advanced/api-reference.md`, generated by
 * `scripts/generate-api-reference.ts`) reads their JSDoc tags.
 *
 * The docstrings below write the client directive with a zero-width space
 * (U+200B) before the `/` that would close this comment, and before the `c`
 * of a space-preceded at-sign that TypeScript's JSDoc scanner would
 * otherwise read as a new tag. The generator strips every U+200B, so the
 * published reference shows — and a reader can copy — the real syntax.
 */

/**
 * Module-level `"use client"` directive. A component file that opens with
 * it ships client JS and hydrates; without it the file's components render
 * to static HTML only, and importing a browser-only API from it is a
 * compile error.
 *
 * @example
 * ```tsx
 * "use client"
 * import { createSignal } from '@barefootjs/client'
 *
 * export function Counter() {
 *   const [count, setCount] = createSignal(0)
 *   return <button onClick={() => setCount(count() + 1)}>{count()}</button>
 * }
 * ```
 *
 * @since 0.1.0
 * @stability beta
 */
export const USE_CLIENT_DIRECTIVE = 'use client'

/**
 * Expression-level `/* @​client *​/` directive, placed as a block comment
 * directly before a JSX expression, an attribute initializer or a component
 * prop initializer. It tells the compiler to skip server evaluation of that
 * expression and evaluate it on the client only — the escape for expressions
 * no template adapter can lower.
 *
 * @example
 * ```tsx
 * // No template adapter can lower `toLocaleString()`, so evaluate it on the
 * // client only. The server renders nothing there; hydration fills it in.
 * <span>{/* @​client *​/ total().toLocaleString()}</span>
 * ```
 *
 * @since 0.1.0
 * @stability beta
 */
export const CLIENT_EXPRESSION_DIRECTIVE = '@client'

/**
 * True when a string-literal expression statement's text is the
 * `"use client"` directive. Accepts the doubly-quoted spelling
 * (`"'use client'"`) some detection sites have always tolerated.
 *
 * @internal
 */
export function isUseClientDirectiveText(text: string): boolean {
  return text === USE_CLIENT_DIRECTIVE || text === `'${USE_CLIENT_DIRECTIVE}'`
}

/**
 * Matches the interior of a block comment that is exactly the client
 * expression directive (whitespace-padded), so the directive word as a
 * substring of some other comment never matches.
 *
 * @internal
 */
export const CLIENT_DIRECTIVE_INTERIOR_RE = new RegExp(`^\\s*${CLIENT_EXPRESSION_DIRECTIVE}\\s*$`)
