/**
 * The source-level directives the compiler recognizes. This module is the
 * single definition of their spelling: every detection site in the
 * analyzer, the IR builder, and the preprocessors reads the constants
 * below rather than repeating the literal, and the API reference
 * (`docs/core/advanced/api-reference.md`, generated by
 * `scripts/generate-api-reference.ts`) reads their JSDoc tags.
 */

/**
 * Module-level `"use client"` directive. A component file that opens with
 * it ships client JS and hydrates; without it the file's components render
 * to static HTML only, and importing a browser-only API from it is a
 * compile error.
 *
 * @since 0.1.0
 * @stability beta
 */
export const USE_CLIENT_DIRECTIVE = 'use client'

/**
 * Expression-level client-only directive: a block comment whose interior is
 * exactly the word `client` prefixed with an at-sign, placed directly before
 * a JSX expression, attribute initializer, or component prop initializer.
 * It tells the compiler to skip server evaluation of that expression and
 * evaluate it on the client only — the escape for expressions no template
 * adapter can lower. (Spelled out rather than written literally here because
 * the at-sign would start a new JSDoc tag.)
 *
 * @since 0.1.0
 * @stability beta
 */
export const CLIENT_EXPRESSION_DIRECTIVE = '@client'

/**
 * True when a string-literal expression statement's text is the
 * `"use client"` directive. Accepts the doubly-quoted spelling
 * (`"'use client'"`) some detection sites have always tolerated.
 *
 * @internal
 */
export function isUseClientDirectiveText(text: string): boolean {
  return text === USE_CLIENT_DIRECTIVE || text === `'${USE_CLIENT_DIRECTIVE}'`
}

/**
 * Matches the interior of a block comment that is exactly the client
 * expression directive (whitespace-padded), so the directive word as a
 * substring of some other comment never matches.
 *
 * @internal
 */
export const CLIENT_DIRECTIVE_INTERIOR_RE = new RegExp(`^\\s*${CLIENT_EXPRESSION_DIRECTIVE}\\s*$`)
