// Client-side rendering (CSR) adapter starter.
//
// Ships a static HTML page with an empty mount point, built by Vite,
// and a tiny `node:http` server that serves the page + the compiled
// client bundles Vite produces. `CSRAdapter` from `@barefootjs/client/
// build` switches the compiler into CSR mode — no SSR — everything
// renders in the browser via @barefootjs/client/runtime.
//
// The server is plain Node (run via `tsx`, same as the hono-node
// starter) so a user on npm / pnpm / yarn isn't forced to install Bun.
// It still runs unchanged under Bun or Deno — `node:http` + `node:fs`
// are supported everywhere.

import type { AdapterTemplate } from '../templates'
import {
  buildGitignore,
  CSS_LINKS_BEGIN,
  CSS_LINKS_END,
  FAVICON_SVG,
  faviconLinkTag,
  SHARED_COUNTER_BARE_TSX,
  SHARED_COUNTER_BARE_TEST_TSX,
  STYLES_CSS,
  TOKENS_CSS,
  UNOCSS_DEV_DEPENDENCIES,
  UNO_CSS_PLACEHOLDER,
  unoConfigTs,
} from './shared'

// CSR scaffold: `dist/` is the whole vite build target. The dev
// server is stateless (no scratch directory), so the build output
// is the only generated tree to ignore — the lockfile is left for
// the user's package manager to manage.
const CSR_GITIGNORE = buildGitignore([
  {
    heading: 'vite build outputs (regenerated by `vite build`)',
    entries: ['dist/'],
  },
])

// CSRAdapter's `generate()` always returns empty output — CSR has no
// template-language backend, no SSR shell, nothing for a `templates`
// dir to hold. `templates` stays unset; `@barefootjs/vite` verifies
// that claim itself (see its `assertNoRealTemplateOutput`).
const CSR_VITE_CONFIG_TS = `import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vite'
import { barefoot } from '@barefootjs/vite'
import { CSRAdapter } from '@barefootjs/client/build'

const HERE = dirname(fileURLToPath(import.meta.url))

// \`pages/index.html\` is a genuine Vite entry (not a static passthrough
// asset): its inline \`<script type="module">\` imports \`Counter.tsx\`
// directly and \`@barefootjs/client/runtime\`. Both need real module
// resolution/bundling, which is what routes it through Vite's own
// multi-page build instead of a hand-written import map.
export default defineConfig({
  base: '/static/',
  resolve: {
    // Mirrors tsconfig.json's \`@/components/*\` path mapping (unused by
    // the starter Counter, which is self-contained and registry-free —
    // see \`bundledRegistryComponents: []\` below — but a future \`bf add\`
    // fetching a registry component that imports via
    // \`@/components/...\` would need it). Vite's dev-server dependency
    // pre-scan parses raw source directly (before this plugin's own
    // \`transform\` hook runs) and has no notion of tsconfig \`paths\`
    // without this.
    alias: {
      '@/components': resolve(HERE, 'components'),
    },
  },
  // \`./public\` is served directly by server.ts (as a fallback under
  // \`/static/\` behind vite's own bundled output — see server.ts), not
  // copied by Vite itself: Vite's own default \`publicDir\` behavior
  // would otherwise write a second, build-order-dependent copy into
  // \`dist/\` that goes stale the moment \`unocss\` (which regenerates
  // \`public/uno.css\`) runs AFTER this build in \`package.json\`'s
  // \`build\` script — and server.ts's dist-first fallback chain would
  // then serve that STALE copy instead of the fresh \`public/uno.css\`.
  publicDir: false,
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    // The starter Counter has no top-level await, but this matches
    // every other JS adapter scaffold's Vite config (and the CSR
    // integration's own reasoning: several apps that grow beyond the
    // starter use top-level \`await import(...)\`, which needs a modern
    // target).
    target: 'esnext',
    rollupOptions: {
      input: { 'pages/index': resolve(HERE, 'pages/index.html') },
    },
  },
  plugins: [
    barefoot({
      adapter: new CSRAdapter(),
      components: ['components'],
    }),
  ],
})
`

const CSR_SERVER_TS = `// Tiny \`node:http\` server for the CSR starter:
//   - HTML pages from \`./dist/pages/<name>.html\` (\`/\` → index.html) —
//     vite's own build output, NOT the \`pages/\` source dir: the source
//     page's inline \`<script type="module">\` imports \`Counter.tsx\`
//     directly and \`@barefootjs/client/runtime\` by bare specifier —
//     both need \`vite build\`'s own HTML processing to become real,
//     resolvable, hashed asset references (see vite.config.ts).
//   - Everything else under \`/static/\` — vite's own hashed JS bundles
//     (\`dist/assets/*\`) AND the handwritten stylesheets (\`public/*\`),
//     tried in that order so the two never collide by filename.
//
// Plain \`node:http\` + \`node:fs\` so the starter runs on any JS runtime
// (Node via \`tsx\`, Bun, Deno) — no runtime is forced on you. No backend
// logic, no API. Replace with Hono / Express / Fastify / etc. when the
// app outgrows static-pages-plus-API.

import { createServer, type ServerResponse } from 'node:http'
import { readFile } from 'node:fs/promises'
import { dirname, resolve, relative, isAbsolute, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(fileURLToPath(import.meta.url))
const DIST_DIR = resolve(ROOT, 'dist')
const PAGES_DIR = resolve(DIST_DIR, 'pages')
const PUBLIC_DIR = resolve(ROOT, 'public')

const port = Number(process.env.PORT ?? 3003)

const server = createServer(async (req, res) => {
  let path: string
  try {
    path = decodeURIComponent((req.url ?? '/').split('?')[0])
  } catch {
    // Malformed percent-encoding (e.g. \`/%%\`) — answer 400 instead of
    // letting the decode throw take down the dev server.
    res.writeHead(400).end('Bad Request')
    return
  }

  if (path.startsWith('/static/')) {
    const rel = path.slice('/static/'.length)
    if (isTraversal(rel)) {
      res.writeHead(403).end('Forbidden')
      return
    }
    // vite's hashed bundle output first (dist/assets/*.js, matching
    // vite.config.ts's \`base: '/static/'\`), then the handwritten
    // stylesheets in public/ — the two never share a filename, so this
    // fallback chain never masks one with the other.
    if (await serveFromDir(res, DIST_DIR, rel, { onMiss: 'fallthrough' })) return
    await serveFromDir(res, PUBLIC_DIR, rel, { onMiss: 'notFound' })
    return
  }

  const pageName = path === '/' ? 'index' : path.slice(1).replace(/\\/$/, '')
  const rel = \`\${pageName}.html\`
  if (isTraversal(rel)) {
    res.writeHead(403).end('Forbidden')
    return
  }
  await serveFromDir(res, PAGES_DIR, rel, { onMiss: 'notFound' })
})

// Defense-in-depth path traversal guard. Compare via relative() so it
// holds on Windows (\`\\\` separators) too — a literal \`dir + '/'\` prefix
// check would 403 every request there. Checked once against \`rel\`
// itself (not per candidate dir): the traversal outcome depends only
// on \`rel\`'s own \`..\` segments, not on which directory it's resolved
// against.
function isTraversal(rel: string): boolean {
  const target = resolve(DIST_DIR, rel)
  const rel2 = relative(DIST_DIR, target)
  return rel2 === '..' || rel2.startsWith('..' + sep) || isAbsolute(rel2)
}

async function serveFromDir(
  res: ServerResponse,
  dir: string,
  rel: string,
  opts: { onMiss: 'notFound' | 'fallthrough' },
): Promise<boolean> {
  const target = resolve(dir, rel)
  try {
    const body = await readFile(target)
    res.writeHead(200, { 'Content-Type': contentTypeFor(target) }).end(body)
    return true
  } catch (err) {
    // Missing path → 404 (unless a fallback dir still gets a turn);
    // anything else (permissions, IO) → 500, so real problems surface
    // in development instead of masquerading as 404s.
    const code = (err as { code?: string }).code
    if (code === 'ENOENT' || code === 'ENOTDIR' || code === 'EISDIR') {
      if (opts.onMiss === 'notFound') res.writeHead(404).end('Not Found')
      return false
    }
    res.writeHead(500).end('Internal Server Error')
    return true
  }
}

function contentTypeFor(path: string): string {
  const ext = path.split('.').pop() ?? ''
  switch (ext) {
    case 'html': return 'text/html; charset=utf-8'
    case 'js':   return 'application/javascript; charset=utf-8'
    case 'css':  return 'text/css; charset=utf-8'
    case 'json': return 'application/json; charset=utf-8'
    case 'svg':  return 'image/svg+xml'
    case 'png':  return 'image/png'
    case 'jpg':
    case 'jpeg': return 'image/jpeg'
    default:     return 'application/octet-stream'
  }
}

server.listen(port, () => {
  console.log(\`  ➜ http://localhost:\${port}\`)
})
`

const CSR_INDEX_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>BarefootJS app</title>
  ${faviconLinkTag('/static/favicon.svg')}
  ${CSS_LINKS_BEGIN}
  <!-- Link all three sheets so the browser fetches them in parallel —
       chaining via styles.css @import would defer tokens/uno to a
       second round-trip and flash unstyled DOM. tokens first so its
       CSS variables are defined before any rule references them. -->
  <link rel="stylesheet" href="/static/tokens.css">
  <link rel="stylesheet" href="/static/styles.css">
  <link rel="stylesheet" href="/static/uno.css">
  ${CSS_LINKS_END}
</head>
<body>
  <main>
    <div id="app"></div>
  </main>
  <script type="module">
    import { render } from '@barefootjs/client/runtime'
    await import('../components/Counter.tsx')
    render(document.getElementById('app'), 'Counter', { initial: 0 })
  </script>
</body>
</html>
`

const CSR_TSCONFIG = `{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "jsx": "react-jsx",
    "jsxImportSource": "@barefootjs/jsx",
    "types": ["node"],
    "strict": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "noEmit": true,
    "baseUrl": ".",
    "paths": {
      "@/components/*": ["./components/*"]
    }
  },
  "include": ["**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules", "dist"]
}
`

export const CSR_ADAPTER: AdapterTemplate = {
  label: 'CSR (client-side rendering only)',
  port: 3003,
  files: {
    'server.ts': CSR_SERVER_TS,
    'pages/index.html': CSR_INDEX_HTML,
    'vite.config.ts': CSR_VITE_CONFIG_TS,
    'tsconfig.json': CSR_TSCONFIG,
    // No compiled `.tsx` output dir to also scan — CSRAdapter emits no
    // templates (see vite.config.ts's docstring).
    'uno.config.ts': unoConfigTs([
      'components/**/*.tsx',
      'pages/**/*.html',
    ]),
    // Bare starter Counter (native <button>, no registry <Button>) — see
    // `bundledRegistryComponents: []` below for why.
    'components/Counter.tsx': SHARED_COUNTER_BARE_TSX,
    'components/Counter.test.tsx': SHARED_COUNTER_BARE_TEST_TSX,
    'public/styles.css': STYLES_CSS,
    'public/tokens.css': TOKENS_CSS,
    'public/uno.css': UNO_CSS_PLACEHOLDER,
    'public/favicon.svg': FAVICON_SVG,
    '.gitignore': CSR_GITIGNORE,
  },
  scripts: {
    // `vite build --watch` (NOT `vite dev`): CSR's pages are the shell,
    // served verbatim by server.ts from `dist/pages/` — there is no
    // backend to bake a dev-origin URL INTO (unlike the SSR adapters).
    // `vite build --watch` rebuilds `dist/` on save and server.ts's
    // static files pick it up on the next request; no server restart
    // needed. See the CSR integration's own vite.config.ts docstring.
    dev: 'vite build && unocss && concurrently -k -n build,uno,server -c blue,magenta,green "vite build --watch" "unocss --watch" "tsx watch server.ts"',
    build: 'vite build && unocss',
    start: 'tsx server.ts',
  },
  dependencies: {
    '@barefootjs/client': 'latest',
    '@barefootjs/jsx': 'latest',
    '@barefootjs/shared': 'latest',
  },
  devDependencies: {
    ...UNOCSS_DEV_DEPENDENCIES,
    '@barefootjs/cli': 'latest',
    '@barefootjs/test': 'latest',
    // vite.config.ts imports `barefoot` from `@barefootjs/vite` directly
    // (CSR has no composed adapter-specific `/vite` wrapper package).
    '@barefootjs/vite': 'latest',
    vite: '^6.0.0',
    '@types/node': '^22.0.0',
    concurrently: '^9.0.0',
    tsx: '^4.19.0',
    typescript: '^5.6.0',
  },
  // The registry <Button>/<Slot> pair each re-export named types
  // (`export type { ButtonVariant, ... }`), and the compiler always
  // emits that re-export line into the component's `markedTemplate`
  // output regardless of adapter — CSRAdapter's own `generate()`
  // returns empty sections, but the type re-export line still lands in
  // the combined per-file template text `@barefootjs/vite`'s
  // `assertNoRealTemplateOutput` inspects. With no `templates` dir
  // configured (CSR's whole point — see vite.config.ts), that guard
  // correctly refuses to silently drop non-empty output rather than
  // risk swallowing a real one, so a CSR project using the registry
  // Button fails `vite build` outright. The bare, dependency-free
  // native-<button> Counter above sidesteps the whole class (no
  // registry component compiled at all) — same fix already applied to
  // the Xslate scaffold above (see XSLATE_COUNTER_TSX) for its own,
  // different compiler gap. Omit the explicit empty array so a future
  // fix to the guard (or CSRAdapter) just needs this line deleted.
  bundledRegistryComponents: [],
  // Runs on plain Node via `tsx` (same as the hono-node starter), so
  // there's no Bun-on-PATH prerequisite to warn about.
  prereqWarnings: () => [],
}
