// Client-side rendering (CSR) adapter starter.
//
// Ships a static HTML page with an empty mount point and a tiny
// `node:http` server that serves the page + the compiled client
// bundles produced by `bf build`. The `createConfig` from
// `@barefootjs/client/build` switches the compiler into CSR mode — no
// SSR — everything renders in the browser via @barefootjs/client/runtime.
//
// The server is plain Node (run via `tsx`, same as the hono-node
// starter) so a user on npm / pnpm / yarn isn't forced to install Bun.
// It still runs unchanged under Bun or Deno — `node:http` + `node:fs`
// are supported everywhere.

import type { AdapterTemplate } from '../templates'
import {
  buildGitignore,
  CSS_LINKS_BEGIN,
  CSS_LINKS_END,
  SHARED_COUNTER_TSX,
  SHARED_COUNTER_TEST_TSX,
  STYLES_CSS,
  TOKENS_CSS,
  UNOCSS_DEV_DEPENDENCIES,
  UNO_CSS_PLACEHOLDER,
  unoConfigTs,
} from './shared'

// CSR scaffold: `dist/` is the whole bf build target. The dev
// server is stateless (no scratch directory), so the build output
// is the only generated tree to ignore — the lockfile is left for
// the user's package manager to manage.
const CSR_GITIGNORE = buildGitignore([
  {
    heading: 'bf build outputs (regenerated by `bf build` / `bf build --watch`)',
    entries: ['dist/'],
  },
])

const CSR_BAREFOOT_CONFIG_TS = `import { createConfig } from '@barefootjs/client/build'

export default createConfig({
  paths: {
    components: 'components/ui',
    tokens: 'tokens',
    meta: 'meta',
  },
  components: ['components'],
  outDir: 'dist',
})
`

const CSR_SERVER_TS = `// Tiny \`node:http\` server for the CSR starter:
//   - HTML pages from \`./pages/<name>.html\` (\`/\` → index.html)
//   - Compiled component bundles from \`./dist/components/\` at /static/components/
//   - Other static assets from \`./public/\` at /static/
//
// Plain \`node:http\` + \`node:fs\` so the starter runs on any JS runtime
// (Node via \`tsx\`, Bun, Deno) — no runtime is forced on you. No backend
// logic, no API. Replace with Hono / Express / Fastify / etc. when the
// app outgrows static-pages-plus-API.

import { createServer, type ServerResponse } from 'node:http'
import { readFile } from 'node:fs/promises'
import { dirname, resolve, relative, isAbsolute, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(fileURLToPath(import.meta.url))
const PAGES_DIR = resolve(ROOT, 'pages')
const DIST_DIR = resolve(ROOT, 'dist')
const PUBLIC_DIR = resolve(ROOT, 'public')

const port = Number(process.env.PORT ?? 3003)

const server = createServer(async (req, res) => {
  let path: string
  try {
    path = decodeURIComponent((req.url ?? '/').split('?')[0])
  } catch {
    // Malformed percent-encoding (e.g. \`/%%\`) — answer 400 instead of
    // letting the decode throw take down the dev server.
    res.writeHead(400).end('Bad Request')
    return
  }

  if (path.startsWith('/static/components/')) {
    return serveFromDir(res, resolve(DIST_DIR, 'components'), path.slice('/static/components/'.length))
  }
  if (path.startsWith('/static/')) {
    return serveFromDir(res, PUBLIC_DIR, path.slice('/static/'.length))
  }

  const pageName = path === '/' ? 'index' : path.slice(1).replace(/\\/$/, '')
  return serveFromDir(res, PAGES_DIR, \`\${pageName}.html\`)
})

async function serveFromDir(res: ServerResponse, dir: string, rel: string): Promise<void> {
  const target = resolve(dir, rel)
  // Defense-in-depth path traversal guard. Compare via relative() so it
  // holds on Windows (\`\\\` separators) too — a literal \`dir + '/'\` prefix
  // check would 403 every request there.
  const rel2 = relative(dir, target)
  if (rel2 === '..' || rel2.startsWith('..' + sep) || isAbsolute(rel2)) {
    res.writeHead(403).end('Forbidden')
    return
  }
  try {
    const body = await readFile(target)
    res.writeHead(200, { 'Content-Type': contentTypeFor(target) }).end(body)
  } catch (err) {
    // Missing path → 404; anything else (permissions, IO) → 500, so real
    // problems surface in development instead of masquerading as 404s.
    const code = (err as { code?: string }).code
    if (code === 'ENOENT' || code === 'ENOTDIR' || code === 'EISDIR') {
      res.writeHead(404).end('Not Found')
    } else {
      res.writeHead(500).end('Internal Server Error')
    }
  }
}

function contentTypeFor(path: string): string {
  const ext = path.split('.').pop() ?? ''
  switch (ext) {
    case 'html': return 'text/html; charset=utf-8'
    case 'js':   return 'application/javascript; charset=utf-8'
    case 'css':  return 'text/css; charset=utf-8'
    case 'json': return 'application/json; charset=utf-8'
    case 'svg':  return 'image/svg+xml'
    case 'png':  return 'image/png'
    case 'jpg':
    case 'jpeg': return 'image/jpeg'
    default:     return 'application/octet-stream'
  }
}

server.listen(port, () => {
  console.log(\`  ➜ http://localhost:\${port}\`)
})
`

const CSR_INDEX_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>BarefootJS app</title>
  <script type="importmap">
    { "imports": { "@barefootjs/client/runtime": "/static/components/barefoot.js" } }
  </script>
  ${CSS_LINKS_BEGIN}
  <!-- Link all three sheets so the browser fetches them in parallel —
       chaining via styles.css @import would defer tokens/uno to a
       second round-trip and flash unstyled DOM. tokens first so its
       CSS variables are defined before any rule references them. -->
  <link rel="stylesheet" href="/static/tokens.css">
  <link rel="stylesheet" href="/static/styles.css">
  <link rel="stylesheet" href="/static/uno.css">
  ${CSS_LINKS_END}
</head>
<body>
  <main>
    <div id="app"></div>
  </main>
  <script type="module">
    import { render } from '@barefootjs/client/runtime'
    await import('/static/components/Counter.client.js')
    render(document.getElementById('app'), 'Counter', { initial: 0 })
  </script>
</body>
</html>
`

const CSR_TSCONFIG = `{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "jsx": "react-jsx",
    "jsxImportSource": "@barefootjs/jsx",
    "types": ["node"],
    "strict": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "noEmit": true,
    "baseUrl": ".",
    "paths": {
      "@/components/*": ["./components/*"]
    }
  },
  "include": ["**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules", "dist"]
}
`

export const CSR_ADAPTER: AdapterTemplate = {
  label: 'CSR (client-side rendering only)',
  port: 3003,
  files: {
    'server.ts': CSR_SERVER_TS,
    'pages/index.html': CSR_INDEX_HTML,
    'barefoot.config.ts': CSR_BAREFOOT_CONFIG_TS,
    'tsconfig.json': CSR_TSCONFIG,
    'uno.config.ts': unoConfigTs([
      'components/**/*.tsx',
      'dist/components/**/*.tsx',
      'pages/**/*.html',
    ]),
    'components/Counter.tsx': SHARED_COUNTER_TSX,
    'components/Counter.test.tsx': SHARED_COUNTER_TEST_TSX,
    'public/styles.css': STYLES_CSS,
    'public/tokens.css': TOKENS_CSS,
    'public/uno.css': UNO_CSS_PLACEHOLDER,
    '.gitignore': CSR_GITIGNORE,
  },
  scripts: {
    dev: 'bf build && unocss && concurrently -k -n build,uno,server -c blue,magenta,green "bf build --watch" "unocss --watch" "tsx watch server.ts"',
    build: 'bf build && unocss',
    start: 'tsx server.ts',
  },
  dependencies: {
    '@barefootjs/client': 'latest',
    '@barefootjs/jsx': 'latest',
    '@barefootjs/shared': 'latest',
  },
  devDependencies: {
    ...UNOCSS_DEV_DEPENDENCIES,
    '@barefootjs/cli': 'latest',
    '@barefootjs/test': 'latest',
    '@types/node': '^22.0.0',
    concurrently: '^9.0.0',
    tsx: '^4.19.0',
    typescript: '^5.6.0',
  },
  // Runs on plain Node via `tsx` (same as the hono-node starter), so
  // there's no Bun-on-PATH prerequisite to warn about.
  prereqWarnings: () => [],
}
