// Echo (Go) adapter starter.
//
// Scaffolds a runnable Echo + Go html/template app with the BarefootJS
// runtime vendored under `./bf-runtime` (a `replace` directive in
// `go.mod` keeps imports stable). The runtime sources are inlined into
// the CLI bundle by `scripts/embed-runtimes.mjs` so the scaffold is
// self-contained — no network fetch, no monorepo path leaks.

import { execSync } from 'node:child_process'
import type { AdapterTemplate } from '../templates'
import {
  NATIVE_BUTTON_COUNTER_TSX,
  STYLES_CSS,
  TOKENS_CSS,
  UNOCSS_DEV_DEPENDENCIES,
  UNO_CSS_PLACEHOLDER,
  unoConfigTs,
} from './shared'
import {
  bfGoSource,
  streamingGoSource,
} from './runtimes.generated'

// We don't ship the upstream `bf-runtime/go.mod` as-is — it pins the
// Go version to whatever the monorepo developer happens to be on
// (currently 1.25). Override with a permissive `go 1.22` floor so the
// scaffold runs on any reasonably current Go install.
const ECHO_BF_RUNTIME_GO_MOD = `module github.com/barefootjs/runtime/bf

go 1.22
`

const ECHO_BAREFOOT_CONFIG_TS = `import { createConfig } from '@barefootjs/go-template/build'

export default createConfig({
  paths: {
    components: 'components/ui',
    tokens: 'tokens',
    meta: 'meta',
  },
  components: ['components'],
  outDir: 'dist',
  adapterOptions: {
    packageName: 'main',
    clientJsBasePath: '/static/components/',
    barefootJsPath: '/static/components/barefoot.js',
  },
  // Generated Go struct types for every component, written next to main.go.
  // Overwritten on every \`barefoot build\` run.
  typesOutputFile: 'components.go',
})
`

// Lean Go entry. We use an anonymous prop struct in the route handler
// so main.go compiles even before the first \`barefoot build\` writes
// \`components.go\` — which would supply the typed \`CounterProps\`.
const ECHO_MAIN_GO = `package main

import (
\t"fmt"
\t"html/template"
\t"io"
\t"io/fs"
\t"net/http"
\t"os"
\t"path/filepath"

\tbf "github.com/barefootjs/runtime/bf"
\t"github.com/labstack/echo/v4"
\t"github.com/labstack/echo/v4/middleware"
)

// loadTemplates walks dist/templates/ recursively and parses every
// \`.tmpl\` file. Plain \`ParseGlob("dist/templates/*.tmpl")\` only catches
// the top-level directory, missing the per-component subdirectories
// (e.g. dist/templates/ui/button/index.tmpl) that Counter.tmpl invokes
// via \`{{template "Button" ...}}\`.
//
// We also stub a no-op "Tag" template. The compiled Slot template
// references \`{{template "Tag" ...}}\` for the AsChild=true branch that
// the go-template adapter doesn't currently emit. html/template's
// escape pass validates references in unreachable branches too, so
// without a stub the very first call to any template that transitively
// includes Slot fails with "no such template Tag".
func loadTemplates() (*template.Template, error) {
\troot := template.New("").Funcs(bf.FuncMap())
\tif _, err := root.New("Tag").Parse(""); err != nil {
\t\treturn nil, err
\t}
\terr := filepath.WalkDir("dist/templates", func(path string, d fs.DirEntry, err error) error {
\t\tif err != nil {
\t\t\treturn err
\t\t}
\t\tif d.IsDir() || filepath.Ext(path) != ".tmpl" {
\t\t\treturn nil
\t\t}
\t\t_, parseErr := root.ParseFiles(path)
\t\treturn parseErr
\t})
\treturn root, err
}

type echoRenderer struct {
\tbf *bf.Renderer
}

func (r *echoRenderer) Render(w io.Writer, name string, data interface{}, c echo.Context) error {
\topts := data.(bf.RenderOptions)
\topts.ComponentName = name
\t_, err := w.Write([]byte(r.bf.Render(opts)))
\treturn err
}

func defaultLayout(ctx *bf.RenderContext) string {
\treturn fmt.Sprintf(\`<!DOCTYPE html>
<html lang="en">
<head>
\t<meta charset="utf-8" />
\t<meta name="viewport" content="width=device-width, initial-scale=1.0" />
\t<title>%s</title>
\t<link rel="stylesheet" href="/static/styles.css" />
</head>
<body>
\t<main>%s</main>
\t%s
\t%s
</body>
</html>\`,
\t\tctx.Title,
\t\tctx.ComponentHTML,
\t\tctx.Portals,
\t\tctx.Scripts,
\t)
}

func main() {
\te := echo.New()
\te.Use(middleware.Logger())
\te.Use(middleware.Recover())

\ttmpl, err := loadTemplates()
\tif err != nil {
\t\te.Logger.Fatal(err)
\t}
\te.Renderer = &echoRenderer{bf: bf.NewRenderer(tmpl, defaultLayout)}

\t// The go-template adapter emits client bundles under dist/client/ but
\t// templates reference them at /static/components/ (matching
\t// barefoot.config.ts \`clientJsBasePath\`). Bridge the URL → disk path.
\te.Static("/static/components", "dist/client")
\te.Static("/static", "public")

\te.GET("/", func(c echo.Context) error {
\t\t// \`NewCounterProps\` and \`CounterInput\` are auto-generated by
\t\t// \`barefoot build\` into components.go. They handle ScopeID
\t\t// allocation, child-component slot wiring (the buttons inside
\t\t// Counter), and initial signal values — the template references
\t\t// these fields by name, so a hand-rolled props struct would
\t\t// render an empty page.
\t\tprops := NewCounterProps(CounterInput{Initial: 0})
\t\treturn c.Render(http.StatusOK, "Counter", bf.RenderOptions{
\t\t\tTitle: "BarefootJS app",
\t\t\tProps: &props,
\t\t})
\t})

\tport := os.Getenv("PORT")
\tif port == "" {
\t\tport = "3001"
\t}
\tfmt.Printf("  ➜ http://localhost:%s\\n", port)
\te.Logger.Fatal(e.Start(":" + port))
}
`

const ECHO_GO_MOD = `module barefoot-app

go 1.22

require (
\tgithub.com/barefootjs/runtime/bf v0.0.0
\tgithub.com/labstack/echo/v4 v4.12.0
)

// The BarefootJS Go runtime ships vendored under ./bf-runtime so this
// scaffold runs without depending on a published Go module.
replace github.com/barefootjs/runtime/bf => ./bf-runtime
`

const ECHO_TSCONFIG = `{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "jsx": "react-jsx",
    "jsxImportSource": "@barefootjs/jsx",
    "strict": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "noEmit": true,
    "baseUrl": ".",
    "paths": {
      "@/components/*": ["./components/*"]
    }
  },
  "include": ["**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules", "dist", "bf-runtime"]
}
`

export const ECHO_ADAPTER: AdapterTemplate = {
  label: 'Echo (Go, html/template SSR)',
  port: 3001,
  files: {
    'main.go': ECHO_MAIN_GO,
    'go.mod': ECHO_GO_MOD,
    'bf-runtime/bf.go': bfGoSource,
    'bf-runtime/streaming.go': streamingGoSource,
    'bf-runtime/go.mod': ECHO_BF_RUNTIME_GO_MOD,
    'barefoot.config.ts': ECHO_BAREFOOT_CONFIG_TS,
    'tsconfig.json': ECHO_TSCONFIG,
    'uno.config.ts': unoConfigTs([
      'components/**/*.tsx',
      'dist/components/**/*.tsx',
    ]),
    'components/Counter.tsx': NATIVE_BUTTON_COUNTER_TSX,
    'public/styles.css': STYLES_CSS,
    'public/tokens.css': TOKENS_CSS,
    'public/uno.css': UNO_CSS_PLACEHOLDER,
  },
  scripts: {
    // `go mod tidy` resolves Echo's deps into go.sum on first run —
    // subsequent runs are a fast no-op against the module cache. After
    // that, build everything once (barefoot generates components.go +
    // dist/templates/*.tmpl, unocss generates uno.css), then run the
    // watchers and the Go server side-by-side. `concurrently -k` makes
    // Ctrl-C kill all three. Go has no built-in hot reload — restart
    // manually after main.go edits, or swap in `air` later.
    dev: 'go mod tidy && barefoot build && unocss && concurrently -k -n build,uno,server -c blue,magenta,green "barefoot build --watch" "unocss --watch" "go run ."',
    build: 'go mod tidy && barefoot build && unocss',
    start: 'go run .',
  },
  dependencies: {
    '@barefootjs/cli': 'latest',
    '@barefootjs/client': 'latest',
    '@barefootjs/go-template': 'latest',
    '@barefootjs/jsx': 'latest',
    '@barefootjs/shared': 'latest',
  },
  devDependencies: {
    ...UNOCSS_DEV_DEPENDENCIES,
    concurrently: '^9.0.0',
    typescript: '^5.6.0',
  },
  prereqWarnings: () => goPrereqs(),
}

function goPrereqs(): string[] {
  try {
    execSync('go version', { stdio: 'ignore' })
    return []
  } catch {
    return [
      'Go toolchain not found on PATH. Install Go 1.22+ (https://go.dev/dl/) before `bun run dev`.',
    ]
  }
}
