// Gin (Go) adapter starter.
//
// Scaffolds a runnable Gin + Go html/template app. Shares all
// non-router scaffold pieces (layout, env flag, vendored runtime,
// config, components) with the Chi and net/http adapters via
// `./go-shared`; only `main.go`, `bf_render.go`, and the `go.mod`
// require block are Gin-specific.

import { makeGoAdapter, GO_RENDER_SHARED_FNS } from './go-shared'
import type { AdapterTemplate } from '../templates'

// Application entry: just routes and the server. The render plumbing
// (template loading, render bridge, dev reload) lives in bf_render.go;
// the layout HTML lives in renderer.go.
const GIN_MAIN_GO = `package main

import (
	"fmt"
	"net/http"
	"os"

	bf "github.com/barefootjs/runtime/bf"
	"github.com/gin-gonic/gin"
)

func main() {
	// Load + cache templates once (re-parsed per request in dev so a
	// \`bf build --watch\` rebuild shows up on refresh). See bf_render.go.
	renderer := mustNewRenderer()

	r := gin.Default()

	// Dev auto-reload SSE — mounts /_bf/reload only when APP_ENV is not
	// "production"; a no-op otherwise. Pairs with the snippet
	// bf_render.go injects into <body>.
	MountDevReload(r)

	// The go-template adapter emits client bundles under dist/client/
	// and templates reference them at /client/ (per barefoot.config.ts).
	// Public assets (CSS) live under public/ and are served at /static/.
	// The two prefixes are kept disjoint so Gin's router tree doesn't
	// panic on nested catch-alls.
	r.Static("/client", "dist/client")
	r.Static("/static", "public")

	r.GET("/", func(c *gin.Context) {
		// \`NewCounterProps\` / \`CounterInput\` are generated into
		// components.go by \`bf build\` — they wire up scope IDs,
		// child-slot props, and signal initial values. Use them instead
		// of constructing props by hand.
		props := NewCounterProps(CounterInput{Initial: 0})
		render(c, renderer, http.StatusOK, "Counter", bf.RenderOptions{
			Title: "BarefootJS app",
			Props: &props,
		})
	})

	port := os.Getenv("PORT")
	if port == "" {
		port = "3001"
	}
	fmt.Printf("  ➜ http://localhost:%s\\n", port)
	if err := r.Run(":" + port); err != nil {
		fmt.Fprintf(os.Stderr, "barefoot: server error: %v\\n", err)
		os.Exit(1)
	}
}
`

// Auto-generated render glue. Tied closely to BarefootJS internals;
// seeded by \`bf init\` and intentionally not refreshed on re-runs.
const GIN_BF_RENDER_GO = `package main

// Code generated by BarefootJS for the Gin adapter. DO NOT EDIT.
// To refresh, delete this file and re-run \`bf init\` from a fresh
// directory — \`bf init\` skips existing files, so it won't clobber your
// edits in place.

import (
	"fmt"
	"html/template"
	"io/fs"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	bf "github.com/barefootjs/runtime/bf"
	"github.com/barefootjs/runtime/bf/bfdev"
	"github.com/gin-gonic/gin"
)

${GO_RENDER_SHARED_FNS}
// render writes a fully laid-out HTML page for the named component.
func render(c *gin.Context, renderer *bf.Renderer, status int, name string, opts bf.RenderOptions) {
	html, err := renderToString(renderer, name, opts)
	if err != nil {
		c.String(http.StatusInternalServerError, "template error: %v", err)
		return
	}
	c.Data(status, "text/html; charset=utf-8", []byte(html))
}

// MountDevReload registers the SSE auto-reload endpoint in dev mode.
// In production it is a no-op.
func MountDevReload(r *gin.Engine) {
	if !IsDev() {
		return
	}
	r.GET("/_bf/reload", gin.WrapH(bfdev.NewReloadHandler(bfdev.Config{DistDir: "./dist"})))
}
`

const GIN_GO_MOD = `module barefoot-app

go 1.22

require (
	github.com/barefootjs/runtime/bf v0.0.0
	github.com/gin-gonic/gin v1.10.0
)

// The BarefootJS Go runtime ships vendored under ./bf-runtime so this
// scaffold runs without depending on a published Go module.
replace github.com/barefootjs/runtime/bf => ./bf-runtime
`

export const GIN_ADAPTER: AdapterTemplate = makeGoAdapter({
  label: 'Gin (Go, html/template SSR)',
  mainGo: GIN_MAIN_GO,
  bfRenderGo: GIN_BF_RENDER_GO,
  goMod: GIN_GO_MOD,
})
