// Hono adapter starter (Node, JSX SSR + hydration).
//
// The Node target runs the Hono app via `@hono/node-server`'s
// `serve()`. Auto-reload is wired through `barefootDevReload`
// middleware from `@barefootjs/hono/app`, which mounts the SSE
// endpoint and publishes its URL on the request context so
// `<BfDevReload />` in renderer.tsx renders the matching browser-
// side subscriber. The two pieces share a single endpoint string
// owned by factory.ts, so re-routing is a 1-line edit.

import type { AdapterTemplate } from '../templates'
import {
  buildGitignore,
  CSS_LINKS_BEGIN,
  CSS_LINKS_END,
  FAVICON_SVG,
  faviconLinkTag,
  SHARED_COUNTER_TSX,
  SHARED_COUNTER_TEST_TSX,
  STYLES_CSS,
  TOKENS_CSS,
  UNOCSS_DEV_DEPENDENCIES,
  UNO_CSS_PLACEHOLDER,
  unoConfigTs,
} from './shared'

// Hono on Node: `dist/components` carries the compiled SSR templates
// (imported directly by server.tsx/factory.ts via `tsx`, never served
// over HTTP); `public/components` carries the vite-bundled, hashed
// client JS `serveStatic` serves. `.env` lands here too — `factory.ts`
// reads `process.env`, and a default `.env` is a likely follow-up the
// user shouldn't be expected to write a gitignore line for.
const HONO_NODE_GITIGNORE = buildGitignore([
  {
    heading: 'vite build outputs (regenerated by `vite build` / `vite dev`)',
    entries: ['dist/', 'public/components/'],
  },
  {
    heading: 'Local environment',
    entries: ['.env', '.env.local', '.env.*.local'],
  },
])

const HONO_NODE_SERVER_TSX = `import { serve } from '@hono/node-server'
import { createApp } from './factory'
import { Counter } from '@/components/Counter'

const app = createApp()

app.get('/', (c) =>
  c.render(
    <main>
      <Counter />
    </main>,
    { title: 'BarefootJS app' },
  ),
)

serve({ fetch: app.fetch, port: Number(process.env.PORT ?? 3000) }, (info) => {
  console.log(\`  ➜ http://localhost:\${info.port}\`)
})

export default app
`

const HONO_NODE_FACTORY_TS = `import { Hono } from 'hono'
import { serveStatic } from '@hono/node-server/serve-static'
import { barefootDevReload } from '@barefootjs/hono/app'
import { createRenderer } from './renderer'
import { isProd } from './env'

// Single source of truth for the SSE endpoint. \`barefootDevReload\`
// mounts the route here and publishes the URL on the request context;
// \`<BfDevReload />\` in renderer.tsx reads it back. Change the path
// in one place and both pieces stay in sync.
const DEV_RELOAD_ENDPOINT = '/_bf/reload'

export function createApp(): Hono {
  // Compiled component bundles: served from \`componentsBase\` URL,
  // sourced from \`componentsDistDir\` on disk (vite's \`build.outDir\`
  // — see vite.config.ts).
  const componentsBase = '/static/components'
  const componentsDistDir = './public/components'

  // Everything else under public/: served from \`publicBase\` URL,
  // sourced from \`publicDir\` on disk.
  const publicBase = '/static'
  const publicDir = './public'

  const renderer = createRenderer()

  const app = new Hono()

  app.use('*', renderer)

  app.use(
    \`\${componentsBase}/*\`,
    serveStatic({
      root: componentsDistDir,
      rewriteRequestPath: (path) => path.replace(componentsBase, ''),
    }),
  )

  app.use(
    \`\${publicBase}/*\`,
    serveStatic({
      root: publicDir,
      rewriteRequestPath: (path) => path.replace(publicBase, ''),
    }),
  )

  // Dev-reload SSE + browser snippet. The middleware uses a
  // per-process boot id and the standard SSE \`Last-Event-ID\`
  // reconnection protocol, so the browser only fires a refresh
  // once the new server process is actually accepting connections
  // — no \"reload into the dying old server\" race.
  app.use('*', barefootDevReload({ endpoint: DEV_RELOAD_ENDPOINT, enabled: !isProd }))

  return app
}
`

// No import map: under the Vite build, \`@barefootjs/client\` is an
// ordinary bundled ESM specifier every island's compiled entry imports —
// esbuild/tsx follow that import on their own with no specifier
// redirection needed. \`<BfScripts />\` needs no \`manifest\`/\`base\`
// props either — \`HonoAdapter.generate()\` bakes each component's
// Vite-resolved script URL(s) in at codegen time (see
// \`registerComponentScripts\` in \`@barefootjs/hono/scripts\`).
const HONO_NODE_RENDERER_TSX = `import { jsxRenderer } from 'hono/jsx-renderer'
import { BfDevReload } from '@barefootjs/hono/app'
import { BfScripts } from '@barefootjs/hono/scripts'

declare module 'hono' {
  interface ContextRenderer {
    (children: unknown, props?: { title?: string }): Response
  }
}

export function createRenderer() {
  return jsxRenderer(({ children, title }) => {
    return (
      <html lang="en">
        <head>
          <meta charset="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <title>{title ?? 'BarefootJS app'}</title>
          ${faviconLinkTag('/static/favicon.svg')}
          ${CSS_LINKS_BEGIN}
          {/* Link all three sheets so the browser fetches them in
              parallel — chaining via styles.css @import would defer
              tokens/uno to a second round-trip and flash unstyled
              DOM. tokens.css first so CSS variables are defined
              before any rule references them. */}
          <link rel="stylesheet" href="/static/tokens.css" />
          <link rel="stylesheet" href="/static/styles.css" />
          <link rel="stylesheet" href="/static/uno.css" />
          ${CSS_LINKS_END}
        </head>
        <body>
          {children}
          <BfScripts />
          <BfDevReload />
        </body>
      </html>
    )
  })
}
`

// Centralised dev/prod flag. Read once at module load — changing
// NODE_ENV mid-process is unusual and would require an explicit
// restart anyway. Keeping these in one file means future "dev gate"
// logic (debug headers, verbose error pages, etc.) doesn't grow a
// second `process.env.NODE_ENV` reference somewhere else.
const HONO_NODE_ENV_TS = `export const isProd = process.env.NODE_ENV === 'production'
export const isDev = !isProd
`

// \`templates: 'dist/components'\` is a SEPARATE, non-web-exposed
// directory: the compiled SSR \`.tsx\` files \`tsx\` (the Node runtime)
// imports directly via factory.ts's/server.tsx's \`@/components/*\`
// path mapping, never served over HTTP. \`build.outDir\` is the CLIENT
// asset half — hashed JS bundles \`factory.ts\`'s \`serveStatic\` serves
// from \`./public/components\` at \`/static/components/\`.
const HONO_NODE_VITE_CONFIG_TS = `import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vite'
import { barefoot } from '@barefootjs/hono/vite'

const HERE = dirname(fileURLToPath(import.meta.url))

export default defineConfig({
  base: '/static/components/',
  resolve: {
    // Mirrors tsconfig.json's \`@/components/*\` path mapping — see the
    // Cloudflare Workers Hono adapter's \`vite.config.ts\` docstring for
    // why Vite's dev-server dependency pre-scan needs this even though
    // \`tsc\`/\`tsx\` already resolve it from tsconfig alone.
    alias: {
      '@/components': resolve(HERE, 'components'),
    },
  },
  // \`build.outDir\` (\`public/components\`) is itself a subdirectory of
  // \`public/\` — Vite's own default \`publicDir\` behavior would copy
  // \`public/\`'s OTHER contents (styles.css, tokens.css, favicon.svg,
  // uno.css) into \`public/components\` too, which factory.ts's
  // \`serveStatic\` mounts never read (they're already served straight
  // from \`public/\` itself) and which \`emptyOutDir\` would immediately
  // churn on the next build.
  publicDir: false,
  build: {
    outDir: 'public/components',
    emptyOutDir: true,
  },
  plugins: barefoot({
    components: ['components'],
    templates: 'dist/components',
  }),
})
`

const HONO_NODE_TSCONFIG = `{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "jsx": "react-jsx",
    "jsxImportSource": "@barefootjs/hono/jsx",
    "types": ["node"],
    "strict": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "noEmit": true,
    "baseUrl": ".",
    "paths": {
      // Build output first so the server resolves the compiled SSR
      // template (with hydration markers + script collection).
      // Source is the fallback for files not yet built.
      "@/components/*": ["./dist/components/*", "./components/*"]
    }
  },
  "include": ["**/*.ts", "**/*.tsx"],
  // Do NOT exclude dist/components here. The server imports the compiled
  // SSR templates from there (see the @/components/* paths above), and
  // tsx applies the JSX transform per-file honouring this include/
  // exclude — an excluded .tsx loses jsxImportSource and falls back to
  // the classic React runtime, so SSR throws "ReferenceError: React is
  // not defined" at the first render. They must stay in scope.
  "exclude": ["node_modules"]
}
`

export const HONO_NODE_ADAPTER: AdapterTemplate = {
  label: 'Hono (Node, JSX SSR + hydration)',
  shortLabel: 'Hono / Node',
  port: 3000,
  files: {
    'server.tsx': HONO_NODE_SERVER_TSX,
    'factory.ts': HONO_NODE_FACTORY_TS,
    'renderer.tsx': HONO_NODE_RENDERER_TSX,
    'env.ts': HONO_NODE_ENV_TS,
    'vite.config.ts': HONO_NODE_VITE_CONFIG_TS,
    'tsconfig.json': HONO_NODE_TSCONFIG,
    'uno.config.ts': unoConfigTs([
      'components/**/*.tsx',
      'dist/components/**/*.tsx',
      'server.tsx',
      'renderer.tsx',
    ]),
    'components/Counter.tsx': SHARED_COUNTER_TSX,
    'components/Counter.test.tsx': SHARED_COUNTER_TEST_TSX,
    'public/styles.css': STYLES_CSS,
    'public/tokens.css': TOKENS_CSS,
    'public/uno.css': UNO_CSS_PLACEHOLDER,
    'public/favicon.svg': FAVICON_SVG,
    '.gitignore': HONO_NODE_GITIGNORE,
  },
  scripts: {
    // `vite build` runs once up front so `dist/components` +
    // `public/components` exist before `tsx watch server.tsx` starts;
    // `vite dev` then takes over the watch loop, re-emitting SSR
    // templates with dev-origin script URLs on every component edit.
    dev: 'vite build && unocss && concurrently -k -n dev,uno,server -c blue,magenta,green "vite dev" "unocss --watch" "tsx watch server.tsx"',
    build: 'vite build && unocss',
    start: 'tsx server.tsx',
  },
  dependencies: {
    '@barefootjs/client': 'latest',
    '@barefootjs/hono': 'latest',
    '@barefootjs/jsx': 'latest',
    '@barefootjs/shared': 'latest',
    '@hono/node-server': '^1.13.0',
    hono: '^4.6.0',
  },
  devDependencies: {
    ...UNOCSS_DEV_DEPENDENCIES,
    '@barefootjs/cli': 'latest',
    '@barefootjs/test': 'latest',
    '@barefootjs/vite': 'latest',
    vite: '^6.0.0',
    '@types/node': '^22.0.0',
    concurrently: '^9.0.0',
    tsx: '^4.19.0',
    typescript: '^5.6.0',
  },
  prereqWarnings: () => [],
}
