// net/http (Go standard library) adapter starter.
//
// Scaffolds a runnable app using only the Go standard library — no web
// framework dependency. Shares all non-router scaffold pieces with the
// Gin and Chi adapters via `./go-shared`; only `main.go`,
// `bf_render.go`, and the `go.mod` (which has no external web
// framework) are net/http-specific. Uses the Go 1.22+ `http.ServeMux`
// method+pattern routing.

import { makeGoAdapter, GO_RENDER_SHARED_FNS } from './go-shared'
import type { AdapterTemplate } from '../templates'

const NETHTTP_MAIN_GO = `package main

import (
	"fmt"
	"net/http"
	"os"

	bf "github.com/barefootjs/runtime/bf"
)

func main() {
	// Load + cache templates once (re-parsed per request in dev so a
	// \`bf build --watch\` rebuild shows up on refresh). See bf_render.go.
	renderer := mustNewRenderer()

	mux := http.NewServeMux()

	// Dev auto-reload SSE — registers /_bf/reload only when APP_ENV is
	// not "production"; a no-op otherwise. Pairs with the snippet
	// bf_render.go injects into <body>.
	MountDevReload(mux)

	// The go-template adapter emits client bundles under dist/client/
	// and templates reference them at /client/ (per barefoot.config.ts).
	// Public assets (CSS) live under public/ and are served at /static/.
	mux.Handle("/client/", http.StripPrefix("/client/", http.FileServer(http.Dir("dist/client"))))
	mux.Handle("/static/", http.StripPrefix("/static/", http.FileServer(http.Dir("public"))))

	// Go 1.22+ ServeMux matches "GET /{$}" only for the exact root path,
	// so static-asset requests don't fall through to the home handler.
	mux.HandleFunc("GET /{$}", func(w http.ResponseWriter, req *http.Request) {
		// \`NewCounterProps\` / \`CounterInput\` are generated into
		// components.go by \`bf build\` — they wire up scope IDs,
		// child-slot props, and signal initial values. Use them instead
		// of constructing props by hand.
		props := NewCounterProps(CounterInput{Initial: 0})
		render(w, renderer, http.StatusOK, "Counter", bf.RenderOptions{
			Title: "BarefootJS app",
			Props: &props,
		})
	})

	port := os.Getenv("PORT")
	if port == "" {
		port = "3001"
	}
	fmt.Printf("  ➜ http://localhost:%s\\n", port)
	if err := http.ListenAndServe(":"+port, mux); err != nil {
		fmt.Fprintf(os.Stderr, "barefoot: server error: %v\\n", err)
		os.Exit(1)
	}
}
`

const NETHTTP_BF_RENDER_GO = `package main

// Code generated by BarefootJS for the net/http adapter. DO NOT EDIT.
// To refresh, delete this file and re-run \`bf init\` from a fresh
// directory — \`bf init\` skips existing files, so it won't clobber your
// edits in place.

import (
	"fmt"
	"html/template"
	"io/fs"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	bf "github.com/barefootjs/runtime/bf"
	"github.com/barefootjs/runtime/bf/bfdev"
)

${GO_RENDER_SHARED_FNS}
// render writes a fully laid-out HTML page for the named component.
func render(w http.ResponseWriter, renderer *bf.Renderer, status int, name string, opts bf.RenderOptions) {
	html, err := renderToString(renderer, name, opts)
	if err != nil {
		http.Error(w, fmt.Sprintf("template error: %v", err), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(status)
	_, _ = w.Write([]byte(html))
}

// MountDevReload registers the SSE auto-reload endpoint in dev mode.
// In production it is a no-op.
func MountDevReload(mux *http.ServeMux) {
	if !IsDev() {
		return
	}
	mux.Handle("/_bf/reload", bfdev.NewReloadHandler(bfdev.Config{DistDir: "./dist"}))
}
`

const NETHTTP_GO_MOD = `module barefoot-app

go 1.22

require github.com/barefootjs/runtime/bf v0.0.0

// The BarefootJS Go runtime ships vendored under ./bf-runtime so this
// scaffold runs without depending on a published Go module.
replace github.com/barefootjs/runtime/bf => ./bf-runtime
`

export const NETHTTP_ADAPTER: AdapterTemplate = makeGoAdapter({
  label: 'net/http (Go standard library, html/template SSR)',
  mainGo: NETHTTP_MAIN_GO,
  bfRenderGo: NETHTTP_BF_RENDER_GO,
  goMod: NETHTTP_GO_MOD,
})
