/**
 * Mutation sweep suite (#2481 step 2, "mutation sweep v1").
 *
 * `oracle.playwright.ts` runs three independent oracles against the FROZEN
 * fixture corpus. This suite runs the exact same three oracles
 * (`oracle-core.ts`) against every MUTANT `scripts/mutation-generate.ts`
 * produced — a fixture's root source put through one of
 * `mutation/mutations.ts`'s meaning-preserving structural rewrites
 * (`alias-props` / `fragment-wrap` / `block-body`) and recompiled. A real
 * component should render identically before and after any of them; an
 * oracle failure here is either a mutation exposing a compiler bug the
 * base fixture's exact shape happened not to trigger, or (less
 * interestingly) a mutation-tool artifact — see each quarantine entry's
 * `reason` for which.
 *
 * Requires `.mutants/manifest.json` (gitignored, regenerated by
 * `test:mutation`'s `bun run scripts/mutation-generate.ts` step) — when
 * absent, every test in this file is skipped with a pointer to that
 * command rather than erroring, so running `bunx playwright test` directly
 * against a checkout that never ran the sweep doesn't look like a crash.
 *
 * Noise control: a mutant inherits its base fixture's already-quarantined
 * oracle failures (`oracle-quarantine.ts`) — reproducing a known-broken
 * base-fixture oracle on a mutant is not a new finding, so
 * `mutation.playwright.ts` skips that (fixture, oracle) combination
 * entirely rather than double-booking it into `mutation-quarantine.ts`.
 */

import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { Server } from 'node:http'
import { test } from '@playwright/test'
import { createFixture, type JSXFixture } from '../src/types'
import { startFixtureServer } from './fixture-host'
import { ORACLE_QUARANTINE, type OracleKind } from './oracle-quarantine'
import { mutationQuarantineEntry } from './mutation-quarantine'
import { runIdempotenceOracle, runSnapOracle, runThreePointOracle } from './oracle-core'
import { actionStepsOf } from './interaction-runner'
import type { ManifestEntry } from '../scripts/mutation-generate'

const HERE = dirname(fileURLToPath(import.meta.url))
const MUTANTS_DIR = resolve(HERE, '../.mutants')
const MANIFEST_PATH = resolve(MUTANTS_DIR, 'manifest.json')

function loadManifest(): ManifestEntry[] | undefined {
  if (!existsSync(MANIFEST_PATH)) return undefined
  return JSON.parse(readFileSync(MANIFEST_PATH, 'utf8')) as ManifestEntry[]
}

const manifest = loadManifest()

test.describe('mutation sweep', () => {
  test.skip(
    manifest === undefined,
    `${MANIFEST_PATH} not found — run \`bun run scripts/mutation-generate.ts\` (or \`bun run test:mutation\`) first.`,
  )

  if (manifest === undefined) {
    test('mutation sweep skipped — manifest not generated', () => {})
    return
  }

  const mutants = manifest.filter((e): e is ManifestEntry & Required<Pick<ManifestEntry, 'htmlFile' | 'clientJsFile'>> => e.status === 'ok')

  function loadMutantFixture(entry: (typeof mutants)[number]): JSXFixture {
    const html = readFileSync(resolve(MUTANTS_DIR, entry.htmlFile), 'utf8')
    const clientJs = readFileSync(resolve(MUTANTS_DIR, entry.clientJsFile), 'utf8')
    return createFixture({
      // Filesystem-safe, URL-path-safe id — also `fixture-host.ts`'s route
      // key, so it must be unique across the whole manifest (it is: one
      // entry per (fixtureId, mutationId) pair).
      id: `${entry.fixtureId}__${entry.mutationId}`,
      description: `mutant: ${entry.fixtureId} × ${entry.mutationId}`,
      // No JSX source to carry — the mutant's compiled output (html/
      // clientJs below) is all `fixture-host.ts` ever reads; `source` only
      // exists on `JSXFixture` for the adapter-conformance compile path,
      // which this suite doesn't use.
      source: '',
      componentName: entry.componentName,
      props: entry.props,
      expectedHtml: html,
      expectedClientJs: clientJs,
      interactions: entry.interactions,
      externalImports: entry.externalImports,
      hostStyles: entry.hostStyles,
    })
  }

  let server: Server
  let baseUrl: string

  test.beforeAll(async () => {
    const fixtures = mutants.map(loadMutantFixture)
    ;({ server, baseUrl } = await startFixtureServer(fixtures))
  })

  test.afterAll(async () => {
    await new Promise<void>(resolveClose => server.close(() => resolveClose()))
  })

  /**
   * Mirrors `oracle.playwright.ts`'s `runQuarantined`, keyed on the
   * (fixtureId, mutationId, oracle) triple instead of (fixtureId, oracle).
   */
  async function runQuarantined(fixtureId: string, mutationId: string, oracle: OracleKind, assertion: () => Promise<void>): Promise<void> {
    const entry = mutationQuarantineEntry(fixtureId, mutationId, oracle)
    if (!entry) {
      await assertion()
      return
    }
    let failure: unknown
    try {
      await assertion()
    } catch (err) {
      failure = err
    }
    if (failure === undefined) {
      throw new Error(
        `mutation-quarantine.ts entry for [${fixtureId}/${mutationId}]/'${oracle}' is stale — the mutant now passes ` +
          `this oracle; delete the entry (and close/update its tracking issue: ${entry.issue ?? '<none filed yet>'}).`,
      )
    }
  }

  /** True when the BASE fixture already has this oracle quarantined — see this file's docstring. */
  function baseAlreadyQuarantined(fixtureId: string, oracle: OracleKind): boolean {
    const entry = ORACLE_QUARANTINE[fixtureId]
    return !!entry && entry.oracles.includes(oracle)
  }

  for (const entry of mutants) {
    const fixture = loadMutantFixture(entry)
    const label = `${entry.fixtureId} × ${entry.mutationId}`

    test(`[snap] ${label}: hydration is a no-op on SSR state`, async ({ page }) => {
      test.skip(baseAlreadyQuarantined(entry.fixtureId, 'snap'), `base fixture already quarantined for 'snap' in oracle-quarantine.ts`)
      await runQuarantined(entry.fixtureId, entry.mutationId, 'snap', () => runSnapOracle(page, fixture, baseUrl))
    })

    test(`[three-point] ${label}: SSR ≡ hydrated ≡ csr-mount`, async ({ page }) => {
      test.skip(
        baseAlreadyQuarantined(entry.fixtureId, 'three-point'),
        `base fixture already quarantined for 'three-point' in oracle-quarantine.ts`,
      )
      await runQuarantined(entry.fixtureId, entry.mutationId, 'three-point', () => runThreePointOracle(page, fixture, baseUrl))
    })

    if (actionStepsOf(fixture.interactions).length === 0) continue
    test(`[idempotence] ${label}: replayed actions agree between hydrated and csr-mount`, async ({ page }) => {
      test.skip(
        baseAlreadyQuarantined(entry.fixtureId, 'idempotence'),
        `base fixture already quarantined for 'idempotence' in oracle-quarantine.ts`,
      )
      test.setTimeout(30_000)
      await runQuarantined(entry.fixtureId, entry.mutationId, 'idempotence', () => runIdempotenceOracle(page, fixture, baseUrl))
    })
  }
})
