/**
 * Pairwise-sweep quarantine ledger (#2481 step 5, browser-oracle leg).
 *
 * `pairwise.playwright.ts` runs the same three oracles `oracle.playwright.ts`
 * and `mutation.playwright.ts` run (`oracle-core.ts`), but against every
 * `status: 'ok'` case `scripts/pairwise-generate.ts` produced from the t=2
 * covering array. Mirrors `mutation-quarantine.ts`'s shape and rot-check
 * discipline exactly (see that file's docstring for the rationale): a bare
 * skip would go silently stale the moment a fix lands, so
 * `pairwise.playwright.ts` instead asserts each quarantined
 * `[caseId, oracle]` pair is STILL failing — a pair that starts passing
 * fails its rot check with a "stale — delete the entry" message.
 *
 * ONE deliberate difference from `mutation-quarantine.ts`: mutation has
 * `baseAlreadyQuarantined`, which skips a mutant's oracle when the SAME
 * oracle is already known-broken on the unmutated base fixture — pairwise
 * has no base fixture (every case is synthesized fresh from the covering
 * array), so there is no equivalent "already known broken" set to inherit
 * from and no analogous skip. Every pairwise oracle failure is a genuine
 * new finding.
 *
 * Key STRICTLY on the exact case id (the full axis-tuple string
 * `scripts/pairwise-generate.ts`'s `idFor` produces) — never on an axis
 * pattern or wildcard. If N cases fail from one root cause, that is N
 * entries sharing one `reason`/`issue`, not one entry matching all of
 * them: a pattern entry is how a quarantine quietly becomes a blanket
 * skip, which is exactly the failure mode this ledger exists to prevent
 * (CLAUDE.md's `known-limitation` discipline, applied here).
 *
 * Populated 2026-08-28 from a full sweep at head `1d1a8e8d7` (111 failing
 * `[caseId, oracle]` pairs). Triaged into nine `known-limitation` issues
 * (#2749–#2751, #2753–#2757, plus the pre-existing #2714) by reading each
 * failure's actual `Expected`/`Received` diff (or, for the browser-console
 * cases, a targeted diagnostic script), not by assuming the issue-mapping
 * table a human handed down in advance — see each `reason` for the
 * specific evidence. `assertSnapshotsAgree` (oracle-core.ts) runs the
 * structural-HTML `toBe` check before the DOM-state `toEqual` check inside
 * ONE call, so a case failing BOTH throws on the HTML check and never
 * reaches the DOM-state one — several entries below name a second,
 * currently-masked defect for exactly this reason (search "fires first").
 * Two rows (`early-return` + `controlled-select`, `state-prop-shadowing-
 * signal`, oracles `snap`/`three-point`) measured as a genuinely distinct,
 * un-diagnosed divergence (a controlled `<select>` whose value matches no
 * `<option>` resolves `selectedIndex`/`value` differently between SSR's
 * browser-default behavior and the client's explicit property write) that
 * does not fit any of the nine issues — deliberately left OUT of this
 * ledger rather than forced into the nearest bucket; that pair is still
 * red and reported separately as unquarantined.
 */

import type { OracleKind } from './oracle-quarantine'

export interface PairwiseQuarantineEntry {
  caseId: string
  oracle: OracleKind
  /** Why — a short human summary of the observed divergence. */
  reason: string
  /** `known-limitation` issue URL, filled in after triage. */
  issue?: string
}

function key(caseId: string, oracle: OracleKind): string {
  return `${caseId}::${oracle}`
}

const ENTRIES: readonly PairwiseQuarantineEntry[] = [

  // --- #2753 ---------------------------------------------------------
  { caseId: "state-getter-elided-signal__structure-fragment-row-loop__binding-boolean-attr__event-handler-reading-outer-signal__callback-function-reference", oracle: "snap", reason: "Hydration stamps a positional-index `data-key` on every row of this unkeyed loop that SSR never emits (#2753, Shape A) — this structure's template carries no `key={}` at all, so every SSR adapter renders no `data-key`, while the client runtime stamps one anyway.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-getter-elided-signal__structure-fragment-row-loop__binding-boolean-attr__event-handler-reading-outer-signal__callback-function-reference", oracle: "three-point", reason: "Hydration stamps a positional-index `data-key` on every row of this unkeyed loop that SSR never emits (#2753, Shape A) — this structure's template carries no `key={}` at all, so every SSR adapter renders no `data-key`, while the client runtime stamps one anyway.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-getter-elided-signal__structure-fragment-row-loop__binding-controlled-input__event-handler-reading-outer-signal__callback-sort-comparator", oracle: "snap", reason: "Hydration stamps a positional-index `data-key` on every row of this unkeyed loop that SSR never emits (#2753, Shape A) — this structure's template carries no `key={}` at all, so every SSR adapter renders no `data-key`, while the client runtime stamps one anyway.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-getter-elided-signal__structure-fragment-row-loop__binding-controlled-input__event-handler-reading-outer-signal__callback-sort-comparator", oracle: "three-point", reason: "Hydration stamps a positional-index `data-key` on every row of this unkeyed loop that SSR never emits (#2753, Shape A) — this structure's template carries no `key={}` at all, so every SSR adapter renders no `data-key`, while the client runtime stamps one anyway.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-getter-elided-signal__structure-fragment-row-loop__binding-controlled-textarea__event-handler-reading-loop-param__callback-filter-predicate", oracle: "snap", reason: "Hydration stamps a positional-index `data-key` on every row of this unkeyed loop that SSR never emits (#2753, Shape A) — this structure's template carries no `key={}` at all, so every SSR adapter renders no `data-key`, while the client runtime stamps one anyway.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-getter-elided-signal__structure-fragment-row-loop__binding-controlled-textarea__event-handler-reading-loop-param__callback-filter-predicate", oracle: "three-point", reason: "Hydration stamps a positional-index `data-key` on every row of this unkeyed loop that SSR never emits (#2753, Shape A) — this structure's template carries no `key={}` at all, so every SSR adapter renders no `data-key`, while the client runtime stamps one anyway.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-getter-elided-signal__structure-nested-loop-depth-2__binding-class__event-direct-handler__callback-filter-predicate", oracle: "snap", reason: "Three independent things differ in this one structural comparison, none of them fully understood as a single fix: (1) the nested loop's inner row gains a second, plain `data-key` alongside SSR's `data-key-1` — #2753, Shape B; (2) the class binding's getter-elided `val` accessor is never called (`Boolean(val)` is unconditionally truthy), so this row's class is pinned to its truthy branch (`class=\"on\"`) regardless of the signal's actual value — #2755's class-binding facet (see the comment thread on #2755); (3) SSR omits the `class` attribute from this row ENTIRELY, which is neither of the above and is explicitly flagged on #2755 as identified but not root-caused. Filed under #2753 since the `data-key` half is its cleanest, best-understood component; the class-related halves are #2755's responsibility and its own comment says so explicitly — this entry's reason names all three so the ledger doesn't imply more understanding than actually exists.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-getter-elided-signal__structure-nested-loop-depth-2__binding-class__event-direct-handler__callback-filter-predicate", oracle: "three-point", reason: "Three independent things differ in this one structural comparison, none of them fully understood as a single fix: (1) the nested loop's inner row gains a second, plain `data-key` alongside SSR's `data-key-1` — #2753, Shape B; (2) the class binding's getter-elided `val` accessor is never called (`Boolean(val)` is unconditionally truthy), so this row's class is pinned to its truthy branch (`class=\"on\"`) regardless of the signal's actual value — #2755's class-binding facet (see the comment thread on #2755); (3) SSR omits the `class` attribute from this row ENTIRELY, which is neither of the above and is explicitly flagged on #2755 as identified but not root-caused. Filed under #2753 since the `data-key` half is its cleanest, best-understood component; the class-related halves are #2755's responsibility and its own comment says so explicitly — this entry's reason names all three so the ledger doesn't imply more understanding than actually exists.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-memo__structure-fragment-row-loop__binding-controlled-select__event-ref-callback__callback-flatmap-callback", oracle: "snap", reason: "Hydration stamps a positional-index `data-key` on every row of this unkeyed `fragment-row-loop` that SSR never emits (#2753, Shape A) AND stamps a `data-mounted` attribute from a ref-callback mount effect that never runs at SSR (#2714) — both differences land in the same single structural-HTML `toBe` comparison, so both must be fixed for this row to pass. Filed under #2753 (the larger, better-characterized group); #2714 covers the `data-mounted` half.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-memo__structure-fragment-row-loop__binding-controlled-select__event-ref-callback__callback-flatmap-callback", oracle: "three-point", reason: "Hydration stamps a positional-index `data-key` on every row of this unkeyed `fragment-row-loop` that SSR never emits (#2753, Shape A) AND stamps a `data-mounted` attribute from a ref-callback mount effect that never runs at SSR (#2714) — both differences land in the same single structural-HTML `toBe` comparison, so both must be fixed for this row to pass. Filed under #2753 (the larger, better-characterized group); #2714 covers the `data-mounted` half.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-memo__structure-nested-loop-depth-2__binding-attr__event-handler-reading-outer-signal__callback-flatmap-callback", oracle: "snap", reason: "Hydration stamps a second, plain `data-key` on the nested loop's first inner row alongside SSR's depth-suffixed `data-key-1` (#2753, Shape B) — SSR and the client runtime disagree on the inner loop's key attribute name/count.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-memo__structure-nested-loop-depth-2__binding-attr__event-handler-reading-outer-signal__callback-flatmap-callback", oracle: "three-point", reason: "Hydration stamps a second, plain `data-key` on the nested loop's first inner row alongside SSR's depth-suffixed `data-key-1` (#2753, Shape B) — SSR and the client runtime disagree on the inner loop's key attribute name/count.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-prop-shadowing-signal__structure-fragment-row-loop__binding-style__event-handler-reading-loop-param__callback-sort-comparator", oracle: "snap", reason: "Hydration stamps a positional-index `data-key` on every row of this unkeyed loop that SSR never emits (#2753, Shape A) — this structure's template carries no `key={}` at all, so every SSR adapter renders no `data-key`, while the client runtime stamps one anyway.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-prop-shadowing-signal__structure-fragment-row-loop__binding-style__event-handler-reading-loop-param__callback-sort-comparator", oracle: "three-point", reason: "Hydration stamps a positional-index `data-key` on every row of this unkeyed loop that SSR never emits (#2753, Shape A) — this structure's template carries no `key={}` at all, so every SSR adapter renders no `data-key`, while the client runtime stamps one anyway.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-prop-shadowing-signal__structure-nested-loop-depth-2__binding-controlled-textarea__event-delegated-handler-in-row__callback-filter-predicate", oracle: "snap", reason: "Hydration stamps a second, plain `data-key` on the nested loop's first inner row alongside SSR's depth-suffixed `data-key-1` (#2753, Shape B) — SSR and the client runtime disagree on the inner loop's key attribute name/count.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-prop-shadowing-signal__structure-nested-loop-depth-2__binding-controlled-textarea__event-delegated-handler-in-row__callback-filter-predicate", oracle: "three-point", reason: "Hydration stamps a second, plain `data-key` on the nested loop's first inner row alongside SSR's depth-suffixed `data-key-1` (#2753, Shape B) — SSR and the client runtime disagree on the inner loop's key attribute name/count.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-prop-shadowing-signal__structure-nested-loop-depth-2__binding-style__event-handler-reading-loop-param__callback-inline-arrow", oracle: "snap", reason: "Hydration stamps a second, plain `data-key` on the nested loop's first inner row alongside SSR's depth-suffixed `data-key-1` (#2753, Shape B) — SSR and the client runtime disagree on the inner loop's key attribute name/count.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-prop-shadowing-signal__structure-nested-loop-depth-2__binding-style__event-handler-reading-loop-param__callback-inline-arrow", oracle: "three-point", reason: "Hydration stamps a second, plain `data-key` on the nested loop's first inner row alongside SSR's depth-suffixed `data-key-1` (#2753, Shape B) — SSR and the client runtime disagree on the inner loop's key attribute name/count.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-prop__structure-fragment-row-loop__binding-attr__event-delegated-handler-in-row__callback-filter-predicate", oracle: "snap", reason: "Hydration stamps a positional-index `data-key` on every row of this unkeyed loop that SSR never emits (#2753, Shape A) — this structure's template carries no `key={}` at all, so every SSR adapter renders no `data-key`, while the client runtime stamps one anyway.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-prop__structure-fragment-row-loop__binding-attr__event-delegated-handler-in-row__callback-filter-predicate", oracle: "three-point", reason: "Hydration stamps a positional-index `data-key` on every row of this unkeyed loop that SSR never emits (#2753, Shape A) — this structure's template carries no `key={}` at all, so every SSR adapter renders no `data-key`, while the client runtime stamps one anyway.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-prop__structure-nested-loop-depth-2__binding-text__event-handler-reading-loop-param__callback-sort-comparator", oracle: "snap", reason: "Hydration stamps a second, plain `data-key` on the nested loop's first inner row alongside SSR's depth-suffixed `data-key-1` (#2753, Shape B) — SSR and the client runtime disagree on the inner loop's key attribute name/count.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-prop__structure-nested-loop-depth-2__binding-text__event-handler-reading-loop-param__callback-sort-comparator", oracle: "three-point", reason: "Hydration stamps a second, plain `data-key` on the nested loop's first inner row alongside SSR's depth-suffixed `data-key-1` (#2753, Shape B) — SSR and the client runtime disagree on the inner loop's key attribute name/count.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-signal__structure-fragment-row-loop__binding-class__event-ref-callback__callback-filter-predicate", oracle: "snap", reason: "Hydration stamps a positional-index `data-key` on every row of this unkeyed `fragment-row-loop` that SSR never emits (#2753, Shape A) AND stamps a `data-mounted` attribute from a ref-callback mount effect that never runs at SSR (#2714) — both differences land in the same single structural-HTML `toBe` comparison, so both must be fixed for this row to pass. Filed under #2753 (the larger, better-characterized group); #2714 covers the `data-mounted` half.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-signal__structure-fragment-row-loop__binding-class__event-ref-callback__callback-filter-predicate", oracle: "three-point", reason: "Hydration stamps a positional-index `data-key` on every row of this unkeyed `fragment-row-loop` that SSR never emits (#2753, Shape A) AND stamps a `data-mounted` attribute from a ref-callback mount effect that never runs at SSR (#2714) — both differences land in the same single structural-HTML `toBe` comparison, so both must be fixed for this row to pass. Filed under #2753 (the larger, better-characterized group); #2714 covers the `data-mounted` half.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-signal__structure-fragment-row-loop__binding-text__event-direct-handler__callback-inline-arrow", oracle: "snap", reason: "Hydration stamps a positional-index `data-key` on every row of this unkeyed loop that SSR never emits (#2753, Shape A) — this structure's template carries no `key={}` at all, so every SSR adapter renders no `data-key`, while the client runtime stamps one anyway.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-signal__structure-fragment-row-loop__binding-text__event-direct-handler__callback-inline-arrow", oracle: "three-point", reason: "Hydration stamps a positional-index `data-key` on every row of this unkeyed loop that SSR never emits (#2753, Shape A) — this structure's template carries no `key={}` at all, so every SSR adapter renders no `data-key`, while the client runtime stamps one anyway.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-signal__structure-nested-loop-depth-2__binding-boolean-attr__event-ref-callback__callback-function-reference", oracle: "snap", reason: "Hydration stamps a second, plain `data-key` on the nested loop's first inner row alongside SSR's depth-suffixed `data-key-1` (#2753, Shape B) — SSR and the client runtime disagree on the inner loop's key attribute name/count.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-signal__structure-nested-loop-depth-2__binding-boolean-attr__event-ref-callback__callback-function-reference", oracle: "three-point", reason: "Hydration stamps a second, plain `data-key` on the nested loop's first inner row alongside SSR's depth-suffixed `data-key-1` (#2753, Shape B) — SSR and the client runtime disagree on the inner loop's key attribute name/count.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-signal__structure-nested-loop-depth-2__binding-controlled-input__event-delegated-handler-in-row__callback-inline-arrow", oracle: "snap", reason: "Hydration stamps a second, plain `data-key` on the nested loop's first inner row alongside SSR's depth-suffixed `data-key-1` (#2753, Shape B) — SSR and the client runtime disagree on the inner loop's key attribute name/count.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-signal__structure-nested-loop-depth-2__binding-controlled-input__event-delegated-handler-in-row__callback-inline-arrow", oracle: "three-point", reason: "Hydration stamps a second, plain `data-key` on the nested loop's first inner row alongside SSR's depth-suffixed `data-key-1` (#2753, Shape B) — SSR and the client runtime disagree on the inner loop's key attribute name/count.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-signal__structure-nested-loop-depth-2__binding-controlled-select__event-direct-handler__callback-sort-comparator", oracle: "snap", reason: "Hydration stamps a second, plain `data-key` on the nested loop's first inner row alongside SSR's depth-suffixed `data-key-1` (#2753, Shape B) — SSR and the client runtime disagree on the inner loop's key attribute name/count.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },
  { caseId: "state-signal__structure-nested-loop-depth-2__binding-controlled-select__event-direct-handler__callback-sort-comparator", oracle: "three-point", reason: "Hydration stamps a second, plain `data-key` on the nested loop's first inner row alongside SSR's depth-suffixed `data-key-1` (#2753, Shape B) — SSR and the client runtime disagree on the inner loop's key attribute name/count.", issue: "https://github.com/piconic-ai/barefootjs/issues/2753" },

  // --- #2755 ---------------------------------------------------------
  { caseId: "state-getter-elided-signal__structure-child-component__binding-controlled-select__event-direct-handler__callback-inline-arrow", oracle: "snap", reason: "`assertSnapshotsAgree`'s structural-HTML check passes for the SSR-vs-hydrated comparison, but the DOM-state check fails: the getter-elided `val` accessor reaches the controlled-value `createEffect` uncalled (#2755, site 2), so the live `.value`/`.selectedIndex` becomes the stringified accessor (or a memo's source text) instead of the signal's value. This case is ALSO one of #2751's six csr-mount-crash cases (site 1, the same module-scope `template` thunk defect) — but three-point's second (hydrated-vs-csr-mount) comparison, where that crash would show, is never reached because this DOM-state assertion throws first. #2755 is therefore the issue that must be fixed for THIS row to pass; #2751's crash on the same case is recorded separately on this case's idempotence quarantine row.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },
  { caseId: "state-getter-elided-signal__structure-child-component__binding-controlled-select__event-direct-handler__callback-inline-arrow", oracle: "three-point", reason: "`assertSnapshotsAgree`'s structural-HTML check passes for the SSR-vs-hydrated comparison, but the DOM-state check fails: the getter-elided `val` accessor reaches the controlled-value `createEffect` uncalled (#2755, site 2), so the live `.value`/`.selectedIndex` becomes the stringified accessor (or a memo's source text) instead of the signal's value. This case is ALSO one of #2751's six csr-mount-crash cases (site 1, the same module-scope `template` thunk defect) — but three-point's second (hydrated-vs-csr-mount) comparison, where that crash would show, is never reached because this DOM-state assertion throws first. #2755 is therefore the issue that must be fixed for THIS row to pass; #2751's crash on the same case is recorded separately on this case's idempotence quarantine row.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },
  { caseId: "state-getter-elided-signal__structure-fragment__binding-controlled-input__event-direct-handler__callback-function-reference", oracle: "snap", reason: "`assertSnapshotsAgree`'s structural-HTML check passes for the SSR-vs-hydrated comparison, but the DOM-state check fails: the getter-elided `val` accessor reaches the controlled-value `createEffect` uncalled (#2755, site 2), so the live `.value`/`.selectedIndex` becomes the stringified accessor (or a memo's source text) instead of the signal's value. This case is ALSO one of #2751's six csr-mount-crash cases (site 1, the same module-scope `template` thunk defect) — but three-point's second (hydrated-vs-csr-mount) comparison, where that crash would show, is never reached because this DOM-state assertion throws first. #2755 is therefore the issue that must be fixed for THIS row to pass; #2751's crash on the same case is recorded separately on this case's idempotence quarantine row.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },
  { caseId: "state-getter-elided-signal__structure-fragment__binding-controlled-input__event-direct-handler__callback-function-reference", oracle: "three-point", reason: "`assertSnapshotsAgree`'s structural-HTML check passes for the SSR-vs-hydrated comparison, but the DOM-state check fails: the getter-elided `val` accessor reaches the controlled-value `createEffect` uncalled (#2755, site 2), so the live `.value`/`.selectedIndex` becomes the stringified accessor (or a memo's source text) instead of the signal's value. This case is ALSO one of #2751's six csr-mount-crash cases (site 1, the same module-scope `template` thunk defect) — but three-point's second (hydrated-vs-csr-mount) comparison, where that crash would show, is never reached because this DOM-state assertion throws first. #2755 is therefore the issue that must be fixed for THIS row to pass; #2751's crash on the same case is recorded separately on this case's idempotence quarantine row.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },
  { caseId: "state-getter-elided-signal__structure-fragment__binding-controlled-select__event-handler-reading-outer-signal__callback-function-reference", oracle: "snap", reason: "`assertSnapshotsAgree`'s structural-HTML check passes for the SSR-vs-hydrated comparison, but the DOM-state check fails: the getter-elided `val` accessor reaches the controlled-value `createEffect` uncalled (#2755, site 2), so the live `.value`/`.selectedIndex` becomes the stringified accessor (or a memo's source text) instead of the signal's value. This case is ALSO one of #2751's six csr-mount-crash cases (site 1, the same module-scope `template` thunk defect) — but three-point's second (hydrated-vs-csr-mount) comparison, where that crash would show, is never reached because this DOM-state assertion throws first. #2755 is therefore the issue that must be fixed for THIS row to pass; #2751's crash on the same case is recorded separately on this case's idempotence quarantine row.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },
  { caseId: "state-getter-elided-signal__structure-fragment__binding-controlled-select__event-handler-reading-outer-signal__callback-function-reference", oracle: "three-point", reason: "`assertSnapshotsAgree`'s structural-HTML check passes for the SSR-vs-hydrated comparison, but the DOM-state check fails: the getter-elided `val` accessor reaches the controlled-value `createEffect` uncalled (#2755, site 2), so the live `.value`/`.selectedIndex` becomes the stringified accessor (or a memo's source text) instead of the signal's value. This case is ALSO one of #2751's six csr-mount-crash cases (site 1, the same module-scope `template` thunk defect) — but three-point's second (hydrated-vs-csr-mount) comparison, where that crash would show, is never reached because this DOM-state assertion throws first. #2755 is therefore the issue that must be fixed for THIS row to pass; #2751's crash on the same case is recorded separately on this case's idempotence quarantine row.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },
  { caseId: "state-getter-elided-signal__structure-fragment__binding-controlled-textarea__event-handler-reading-outer-signal__callback-inline-arrow", oracle: "snap", reason: "`assertSnapshotsAgree`'s structural-HTML check passes for the SSR-vs-hydrated comparison, but the DOM-state check fails: the getter-elided `val` accessor reaches the controlled-value `createEffect` uncalled (#2755, site 2), so the live `.value`/`.selectedIndex` becomes the stringified accessor (or a memo's source text) instead of the signal's value. This case is ALSO one of #2751's six csr-mount-crash cases (site 1, the same module-scope `template` thunk defect) — but three-point's second (hydrated-vs-csr-mount) comparison, where that crash would show, is never reached because this DOM-state assertion throws first. #2755 is therefore the issue that must be fixed for THIS row to pass; #2751's crash on the same case is recorded separately on this case's idempotence quarantine row.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },
  { caseId: "state-getter-elided-signal__structure-fragment__binding-controlled-textarea__event-handler-reading-outer-signal__callback-inline-arrow", oracle: "three-point", reason: "`assertSnapshotsAgree`'s structural-HTML check passes for the SSR-vs-hydrated comparison, but the DOM-state check fails: the getter-elided `val` accessor reaches the controlled-value `createEffect` uncalled (#2755, site 2), so the live `.value`/`.selectedIndex` becomes the stringified accessor (or a memo's source text) instead of the signal's value. This case is ALSO one of #2751's six csr-mount-crash cases (site 1, the same module-scope `template` thunk defect) — but three-point's second (hydrated-vs-csr-mount) comparison, where that crash would show, is never reached because this DOM-state assertion throws first. #2755 is therefore the issue that must be fixed for THIS row to pass; #2751's crash on the same case is recorded separately on this case's idempotence quarantine row.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },
  { caseId: "state-getter-elided-signal__structure-keyed-loop__binding-controlled-select__event-handler-reading-loop-param__callback-filter-predicate", oracle: "snap", reason: "The getter-elided `val` accessor reaches the loop row builder/patcher uncalled (#2755, site 3) — the live `.value` becomes the stringified accessor (or its dependency-tracking `read()` function's own source text, via `Function.prototype.toString`) instead of the signal's value. Invisible to the structural-HTML comparison; caught only by the DOM-state property diff.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },
  { caseId: "state-getter-elided-signal__structure-keyed-loop__binding-controlled-select__event-handler-reading-loop-param__callback-filter-predicate", oracle: "three-point", reason: "The getter-elided `val` accessor reaches the loop row builder/patcher uncalled (#2755, site 3) — the live `.value` becomes the stringified accessor (or its dependency-tracking `read()` function's own source text, via `Function.prototype.toString`) instead of the signal's value. Invisible to the structural-HTML comparison; caught only by the DOM-state property diff.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },
  { caseId: "state-getter-elided-signal__structure-keyed-loop__binding-controlled-textarea__event-handler-reading-loop-param__callback-flatmap-callback", oracle: "snap", reason: "The getter-elided `val` accessor reaches the loop row builder/patcher uncalled (#2755, site 3) — the live `.value` becomes the stringified accessor (or its dependency-tracking `read()` function's own source text, via `Function.prototype.toString`) instead of the signal's value. Invisible to the structural-HTML comparison; caught only by the DOM-state property diff.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },
  { caseId: "state-getter-elided-signal__structure-keyed-loop__binding-controlled-textarea__event-handler-reading-loop-param__callback-flatmap-callback", oracle: "three-point", reason: "The getter-elided `val` accessor reaches the loop row builder/patcher uncalled (#2755, site 3) — the live `.value` becomes the stringified accessor (or its dependency-tracking `read()` function's own source text, via `Function.prototype.toString`) instead of the signal's value. Invisible to the structural-HTML comparison; caught only by the DOM-state property diff.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },
  { caseId: "state-getter-elided-signal__structure-preamble-builder-body__binding-controlled-input__event-handler-reading-loop-param__callback-function-reference", oracle: "snap", reason: "The getter-elided `val` accessor reaches the loop row builder/patcher uncalled (#2755, site 3) — the live `.value` becomes the stringified accessor (or its dependency-tracking `read()` function's own source text, via `Function.prototype.toString`) instead of the signal's value. Invisible to the structural-HTML comparison; caught only by the DOM-state property diff.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },
  { caseId: "state-getter-elided-signal__structure-preamble-builder-body__binding-controlled-input__event-handler-reading-loop-param__callback-function-reference", oracle: "three-point", reason: "The getter-elided `val` accessor reaches the loop row builder/patcher uncalled (#2755, site 3) — the live `.value` becomes the stringified accessor (or its dependency-tracking `read()` function's own source text, via `Function.prototype.toString`) instead of the signal's value. Invisible to the structural-HTML comparison; caught only by the DOM-state property diff.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },
  { caseId: "state-getter-elided-signal__structure-preamble-builder-body__binding-controlled-select__event-delegated-handler-in-row__callback-inline-arrow", oracle: "snap", reason: "The getter-elided `val` accessor reaches the loop row builder/patcher uncalled (#2755, site 3) — the live `.value` becomes the stringified accessor (or its dependency-tracking `read()` function's own source text, via `Function.prototype.toString`) instead of the signal's value. Invisible to the structural-HTML comparison; caught only by the DOM-state property diff.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },
  { caseId: "state-getter-elided-signal__structure-preamble-builder-body__binding-controlled-select__event-delegated-handler-in-row__callback-inline-arrow", oracle: "three-point", reason: "The getter-elided `val` accessor reaches the loop row builder/patcher uncalled (#2755, site 3) — the live `.value` becomes the stringified accessor (or its dependency-tracking `read()` function's own source text, via `Function.prototype.toString`) instead of the signal's value. Invisible to the structural-HTML comparison; caught only by the DOM-state property diff.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },
  { caseId: "state-getter-elided-signal__structure-signal-array-loop__binding-controlled-select__event-direct-handler__callback-inline-arrow", oracle: "snap", reason: "The getter-elided `val` accessor reaches the loop row builder/patcher uncalled (#2755, site 3) — the live `.value` becomes the stringified accessor (or its dependency-tracking `read()` function's own source text, via `Function.prototype.toString`) instead of the signal's value. Invisible to the structural-HTML comparison; caught only by the DOM-state property diff.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },
  { caseId: "state-getter-elided-signal__structure-signal-array-loop__binding-controlled-select__event-direct-handler__callback-inline-arrow", oracle: "three-point", reason: "The getter-elided `val` accessor reaches the loop row builder/patcher uncalled (#2755, site 3) — the live `.value` becomes the stringified accessor (or its dependency-tracking `read()` function's own source text, via `Function.prototype.toString`) instead of the signal's value. Invisible to the structural-HTML comparison; caught only by the DOM-state property diff.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },
  { caseId: "state-getter-elided-signal__structure-signal-array-loop__binding-controlled-textarea__event-direct-handler__callback-flatmap-callback", oracle: "snap", reason: "The getter-elided `val` accessor reaches the loop row builder/patcher uncalled (#2755, site 3) — the live `.value` becomes the stringified accessor (or its dependency-tracking `read()` function's own source text, via `Function.prototype.toString`) instead of the signal's value. Invisible to the structural-HTML comparison; caught only by the DOM-state property diff.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },
  { caseId: "state-getter-elided-signal__structure-signal-array-loop__binding-controlled-textarea__event-direct-handler__callback-flatmap-callback", oracle: "three-point", reason: "The getter-elided `val` accessor reaches the loop row builder/patcher uncalled (#2755, site 3) — the live `.value` becomes the stringified accessor (or its dependency-tracking `read()` function's own source text, via `Function.prototype.toString`) instead of the signal's value. Invisible to the structural-HTML comparison; caught only by the DOM-state property diff.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },
  { caseId: "state-getter-elided-signal__structure-static-array-loop__binding-controlled-input__event-delegated-handler-in-row__callback-sort-comparator", oracle: "snap", reason: "The getter-elided `val` accessor reaches the loop row builder/patcher uncalled (#2755, site 3) — the live `.value` becomes the stringified accessor (or its dependency-tracking `read()` function's own source text, via `Function.prototype.toString`) instead of the signal's value. Invisible to the structural-HTML comparison; caught only by the DOM-state property diff.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },
  { caseId: "state-getter-elided-signal__structure-static-array-loop__binding-controlled-input__event-delegated-handler-in-row__callback-sort-comparator", oracle: "three-point", reason: "The getter-elided `val` accessor reaches the loop row builder/patcher uncalled (#2755, site 3) — the live `.value` becomes the stringified accessor (or its dependency-tracking `read()` function's own source text, via `Function.prototype.toString`) instead of the signal's value. Invisible to the structural-HTML comparison; caught only by the DOM-state property diff.", issue: "https://github.com/piconic-ai/barefootjs/issues/2755" },

  // --- #2754 ---------------------------------------------------------
  { caseId: "state-getter-elided-signal__structure-component-row-root-loop__binding-controlled-select__event-handler-reading-loop-param__callback-sort-comparator", oracle: "idempotence", reason: "Idempotence replays a click against the csr-mount leg; the caller-supplied `data-pw-event` prop on this child-component/row root is silently dropped under pure `createComponent` mount (#2754) — confirmed directly (csr-mount [data-pw-event] count=0, no console error, unlike the #2751/#2750 crash cases above).", issue: "https://github.com/piconic-ai/barefootjs/issues/2754" },
  { caseId: "state-getter-elided-signal__structure-component-row-root-loop__binding-controlled-select__event-handler-reading-loop-param__callback-sort-comparator", oracle: "three-point", reason: "A caller-supplied prop on this component-row-root-loop/child-component root (`data-pw-event`) is silently dropped under pure `createComponent` mount (#2754) — SSR and hydration agree; only the hydrated-vs-csr-mount comparison diverges, with no console error (a clean drop, not a crash).", issue: "https://github.com/piconic-ai/barefootjs/issues/2754" },
  { caseId: "state-getter-elided-signal__structure-component-row-root-loop__binding-controlled-textarea__event-ref-callback__callback-inline-arrow", oracle: "idempotence", reason: "Idempotence replays a click against the csr-mount leg; the caller-supplied `data-pw-event` prop on this child-component/row root is silently dropped under pure `createComponent` mount (#2754) — confirmed directly (csr-mount [data-pw-event] count=0, no console error, unlike the #2751/#2750 crash cases above).", issue: "https://github.com/piconic-ai/barefootjs/issues/2754" },
  { caseId: "state-getter-elided-signal__structure-component-row-root-loop__binding-controlled-textarea__event-ref-callback__callback-inline-arrow", oracle: "three-point", reason: "A caller-supplied prop on this component-row-root-loop/child-component root (`data-pw-event`) is silently dropped under pure `createComponent` mount (#2754) — SSR and hydration agree; only the hydrated-vs-csr-mount comparison diverges, with no console error (a clean drop, not a crash).", issue: "https://github.com/piconic-ai/barefootjs/issues/2754" },
  { caseId: "state-memo__structure-child-component__binding-controlled-input__event-ref-callback__callback-inline-arrow", oracle: "idempotence", reason: "Idempotence replays a click against the csr-mount leg; the caller-supplied `data-pw-event` prop on this child-component/row root is silently dropped under pure `createComponent` mount (#2754) — confirmed directly (csr-mount [data-pw-event] count=0, no console error, unlike the #2751/#2750 crash cases above).", issue: "https://github.com/piconic-ai/barefootjs/issues/2754" },
  { caseId: "state-memo__structure-child-component__binding-controlled-textarea__event-direct-handler__callback-inline-arrow", oracle: "idempotence", reason: "Idempotence replays a click against the csr-mount leg; the caller-supplied `data-pw-event` prop on this child-component/row root is silently dropped under pure `createComponent` mount (#2754) — confirmed directly (csr-mount [data-pw-event] count=0, no console error, unlike the #2751/#2750 crash cases above).", issue: "https://github.com/piconic-ai/barefootjs/issues/2754" },
  { caseId: "state-memo__structure-component-row-root-loop__binding-style__event-direct-handler__callback-function-reference", oracle: "idempotence", reason: "Idempotence replays a click against the csr-mount leg; the caller-supplied `data-pw-event` prop on this child-component/row root is silently dropped under pure `createComponent` mount (#2754) — confirmed directly (csr-mount [data-pw-event] count=0, no console error, unlike the #2751/#2750 crash cases above).", issue: "https://github.com/piconic-ai/barefootjs/issues/2754" },
  { caseId: "state-memo__structure-component-row-root-loop__binding-style__event-direct-handler__callback-function-reference", oracle: "three-point", reason: "A caller-supplied prop on this component-row-root-loop/child-component root (`data-pw-event`) is silently dropped under pure `createComponent` mount (#2754) — SSR and hydration agree; only the hydrated-vs-csr-mount comparison diverges, with no console error (a clean drop, not a crash).", issue: "https://github.com/piconic-ai/barefootjs/issues/2754" },
  { caseId: "state-prop-shadowing-signal__structure-child-component__binding-text__event-ref-callback__callback-function-reference", oracle: "idempotence", reason: "Idempotence replays a click against the csr-mount leg; the caller-supplied `data-pw-event` prop on this child-component/row root is silently dropped under pure `createComponent` mount (#2754) — confirmed directly (csr-mount [data-pw-event] count=0, no console error, unlike the #2751/#2750 crash cases above).", issue: "https://github.com/piconic-ai/barefootjs/issues/2754" },
  { caseId: "state-prop-shadowing-signal__structure-component-row-root-loop__binding-text__event-delegated-handler-in-row__callback-filter-predicate", oracle: "idempotence", reason: "Idempotence replays a click against the csr-mount leg; the caller-supplied `data-pw-event` prop on this child-component/row root is silently dropped under pure `createComponent` mount (#2754) — confirmed directly (csr-mount [data-pw-event] count=0, no console error, unlike the #2751/#2750 crash cases above).", issue: "https://github.com/piconic-ai/barefootjs/issues/2754" },
  { caseId: "state-prop-shadowing-signal__structure-component-row-root-loop__binding-text__event-delegated-handler-in-row__callback-filter-predicate", oracle: "three-point", reason: "A caller-supplied prop on this component-row-root-loop/child-component root (`data-pw-event`) is silently dropped under pure `createComponent` mount (#2754) — SSR and hydration agree; only the hydrated-vs-csr-mount comparison diverges, with no console error (a clean drop, not a crash).", issue: "https://github.com/piconic-ai/barefootjs/issues/2754" },
  { caseId: "state-prop__structure-child-component__binding-attr__event-handler-reading-outer-signal__callback-inline-arrow", oracle: "idempotence", reason: "Idempotence replays a click against the csr-mount leg; the caller-supplied `data-pw-event` prop on this child-component/row root is silently dropped under pure `createComponent` mount (#2754) — confirmed directly (csr-mount [data-pw-event] count=0, no console error, unlike the #2751/#2750 crash cases above).", issue: "https://github.com/piconic-ai/barefootjs/issues/2754" },
  { caseId: "state-prop__structure-component-row-root-loop__binding-boolean-attr__event-handler-reading-loop-param__callback-inline-arrow", oracle: "idempotence", reason: "Idempotence replays a click against the csr-mount leg; the caller-supplied `data-pw-event` prop on this child-component/row root is silently dropped under pure `createComponent` mount (#2754) — confirmed directly (csr-mount [data-pw-event] count=0, no console error, unlike the #2751/#2750 crash cases above).", issue: "https://github.com/piconic-ai/barefootjs/issues/2754" },
  { caseId: "state-prop__structure-component-row-root-loop__binding-boolean-attr__event-handler-reading-loop-param__callback-inline-arrow", oracle: "three-point", reason: "A caller-supplied prop on this component-row-root-loop/child-component root (`data-pw-event`) is silently dropped under pure `createComponent` mount (#2754) — SSR and hydration agree; only the hydrated-vs-csr-mount comparison diverges, with no console error (a clean drop, not a crash).", issue: "https://github.com/piconic-ai/barefootjs/issues/2754" },
  { caseId: "state-prop__structure-component-row-root-loop__binding-class__event-handler-reading-outer-signal__callback-inline-arrow", oracle: "idempotence", reason: "Idempotence replays a click against the csr-mount leg; the caller-supplied `data-pw-event` prop on this child-component/row root is silently dropped under pure `createComponent` mount (#2754) — confirmed directly (csr-mount [data-pw-event] count=0, no console error, unlike the #2751/#2750 crash cases above).", issue: "https://github.com/piconic-ai/barefootjs/issues/2754" },
  { caseId: "state-prop__structure-component-row-root-loop__binding-class__event-handler-reading-outer-signal__callback-inline-arrow", oracle: "three-point", reason: "A caller-supplied prop on this component-row-root-loop/child-component root (`data-pw-event`) is silently dropped under pure `createComponent` mount (#2754) — SSR and hydration agree; only the hydrated-vs-csr-mount comparison diverges, with no console error (a clean drop, not a crash).", issue: "https://github.com/piconic-ai/barefootjs/issues/2754" },
  { caseId: "state-signal__structure-child-component__binding-class__event-ref-callback__callback-function-reference", oracle: "idempotence", reason: "Idempotence replays a click against the csr-mount leg; the caller-supplied `data-pw-event` prop on this child-component/row root is silently dropped under pure `createComponent` mount (#2754) — confirmed directly (csr-mount [data-pw-event] count=0, no console error, unlike the #2751/#2750 crash cases above).", issue: "https://github.com/piconic-ai/barefootjs/issues/2754" },
  { caseId: "state-signal__structure-child-component__binding-style__event-direct-handler__callback-inline-arrow", oracle: "idempotence", reason: "Idempotence replays a click against the csr-mount leg; the caller-supplied `data-pw-event` prop on this child-component/row root is silently dropped under pure `createComponent` mount (#2754) — confirmed directly (csr-mount [data-pw-event] count=0, no console error, unlike the #2751/#2750 crash cases above).", issue: "https://github.com/piconic-ai/barefootjs/issues/2754" },
  { caseId: "state-signal__structure-component-row-root-loop__binding-controlled-input__event-handler-reading-loop-param__callback-flatmap-callback", oracle: "idempotence", reason: "Idempotence replays a click against the csr-mount leg; the caller-supplied `data-pw-event` prop on this child-component/row root is silently dropped under pure `createComponent` mount (#2754) — confirmed directly (csr-mount [data-pw-event] count=0, no console error, unlike the #2751/#2750 crash cases above).", issue: "https://github.com/piconic-ai/barefootjs/issues/2754" },
  { caseId: "state-signal__structure-component-row-root-loop__binding-controlled-input__event-handler-reading-loop-param__callback-flatmap-callback", oracle: "three-point", reason: "A caller-supplied prop on this component-row-root-loop/child-component root (`data-pw-event`) is silently dropped under pure `createComponent` mount (#2754) — SSR and hydration agree; only the hydrated-vs-csr-mount comparison diverges, with no console error (a clean drop, not a crash).", issue: "https://github.com/piconic-ai/barefootjs/issues/2754" },

  // --- #2714 ---------------------------------------------------------
  { caseId: "state-getter-elided-signal__structure-keyed-loop__binding-boolean-attr__event-ref-callback__callback-filter-predicate", oracle: "snap", reason: "A `ref` callback's mount effect (`el.setAttribute('data-mounted', ...)`) never runs during SSR — same root cause as the existing accordion/radio-group/command entries in oracle-quarantine.ts (#2714): SSR bakes markup with no `data-mounted` attribute at all, and hydration's first effect pass adds it, so the SSR-vs-hydrated structural comparison sees an attribute appear that SSR never emitted.", issue: "https://github.com/piconic-ai/barefootjs/issues/2714" },
  { caseId: "state-getter-elided-signal__structure-keyed-loop__binding-boolean-attr__event-ref-callback__callback-filter-predicate", oracle: "three-point", reason: "A `ref` callback's mount effect (`el.setAttribute('data-mounted', ...)`) never runs during SSR — same root cause as the existing accordion/radio-group/command entries in oracle-quarantine.ts (#2714): SSR bakes markup with no `data-mounted` attribute at all, and hydration's first effect pass adds it, so the SSR-vs-hydrated structural comparison sees an attribute appear that SSR never emitted.", issue: "https://github.com/piconic-ai/barefootjs/issues/2714" },
  { caseId: "state-memo__structure-signal-array-loop__binding-controlled-input__event-ref-callback__callback-filter-predicate", oracle: "snap", reason: "A `ref` callback's mount effect (`el.setAttribute('data-mounted', ...)`) never runs during SSR — same root cause as the existing accordion/radio-group/command entries in oracle-quarantine.ts (#2714): SSR bakes markup with no `data-mounted` attribute at all, and hydration's first effect pass adds it, so the SSR-vs-hydrated structural comparison sees an attribute appear that SSR never emitted.", issue: "https://github.com/piconic-ai/barefootjs/issues/2714" },
  { caseId: "state-memo__structure-signal-array-loop__binding-controlled-input__event-ref-callback__callback-filter-predicate", oracle: "three-point", reason: "A `ref` callback's mount effect (`el.setAttribute('data-mounted', ...)`) never runs during SSR — same root cause as the existing accordion/radio-group/command entries in oracle-quarantine.ts (#2714): SSR bakes markup with no `data-mounted` attribute at all, and hydration's first effect pass adds it, so the SSR-vs-hydrated structural comparison sees an attribute appear that SSR never emitted.", issue: "https://github.com/piconic-ai/barefootjs/issues/2714" },
  { caseId: "state-prop-shadowing-signal__structure-fragment__binding-style__event-ref-callback__callback-inline-arrow", oracle: "snap", reason: "A `ref` callback's mount effect (`el.setAttribute('data-mounted', ...)`) never runs during SSR — same root cause as the existing accordion/radio-group/command entries in oracle-quarantine.ts (#2714): SSR bakes markup with no `data-mounted` attribute at all, and hydration's first effect pass adds it, so the SSR-vs-hydrated structural comparison sees an attribute appear that SSR never emitted.", issue: "https://github.com/piconic-ai/barefootjs/issues/2714" },
  { caseId: "state-prop-shadowing-signal__structure-fragment__binding-style__event-ref-callback__callback-inline-arrow", oracle: "three-point", reason: "A `ref` callback's mount effect (`el.setAttribute('data-mounted', ...)`) never runs during SSR — same root cause as the existing accordion/radio-group/command entries in oracle-quarantine.ts (#2714): SSR bakes markup with no `data-mounted` attribute at all, and hydration's first effect pass adds it, so the SSR-vs-hydrated structural comparison sees an attribute appear that SSR never emitted.", issue: "https://github.com/piconic-ai/barefootjs/issues/2714" },
  { caseId: "state-prop-shadowing-signal__structure-static-array-loop__binding-class__event-ref-callback__callback-flatmap-callback", oracle: "snap", reason: "A `ref` callback's mount effect (`el.setAttribute('data-mounted', ...)`) never runs during SSR — same root cause as the existing accordion/radio-group/command entries in oracle-quarantine.ts (#2714): SSR bakes markup with no `data-mounted` attribute at all, and hydration's first effect pass adds it, so the SSR-vs-hydrated structural comparison sees an attribute appear that SSR never emitted.", issue: "https://github.com/piconic-ai/barefootjs/issues/2714" },
  { caseId: "state-prop-shadowing-signal__structure-static-array-loop__binding-class__event-ref-callback__callback-flatmap-callback", oracle: "three-point", reason: "A `ref` callback's mount effect (`el.setAttribute('data-mounted', ...)`) never runs during SSR — same root cause as the existing accordion/radio-group/command entries in oracle-quarantine.ts (#2714): SSR bakes markup with no `data-mounted` attribute at all, and hydration's first effect pass adds it, so the SSR-vs-hydrated structural comparison sees an attribute appear that SSR never emitted.", issue: "https://github.com/piconic-ai/barefootjs/issues/2714" },
  { caseId: "state-prop__structure-keyed-loop__binding-attr__event-ref-callback__callback-sort-comparator", oracle: "snap", reason: "A `ref` callback's mount effect (`el.setAttribute('data-mounted', ...)`) never runs during SSR — same root cause as the existing accordion/radio-group/command entries in oracle-quarantine.ts (#2714): SSR bakes markup with no `data-mounted` attribute at all, and hydration's first effect pass adds it, so the SSR-vs-hydrated structural comparison sees an attribute appear that SSR never emitted.", issue: "https://github.com/piconic-ai/barefootjs/issues/2714" },
  { caseId: "state-prop__structure-keyed-loop__binding-attr__event-ref-callback__callback-sort-comparator", oracle: "three-point", reason: "A `ref` callback's mount effect (`el.setAttribute('data-mounted', ...)`) never runs during SSR — same root cause as the existing accordion/radio-group/command entries in oracle-quarantine.ts (#2714): SSR bakes markup with no `data-mounted` attribute at all, and hydration's first effect pass adds it, so the SSR-vs-hydrated structural comparison sees an attribute appear that SSR never emitted.", issue: "https://github.com/piconic-ai/barefootjs/issues/2714" },
  { caseId: "state-prop__structure-preamble-builder-body__binding-text__event-ref-callback__callback-flatmap-callback", oracle: "snap", reason: "A `ref` callback's mount effect (`el.setAttribute('data-mounted', ...)`) never runs during SSR — same root cause as the existing accordion/radio-group/command entries in oracle-quarantine.ts (#2714): SSR bakes markup with no `data-mounted` attribute at all, and hydration's first effect pass adds it, so the SSR-vs-hydrated structural comparison sees an attribute appear that SSR never emitted.", issue: "https://github.com/piconic-ai/barefootjs/issues/2714" },
  { caseId: "state-prop__structure-preamble-builder-body__binding-text__event-ref-callback__callback-flatmap-callback", oracle: "three-point", reason: "A `ref` callback's mount effect (`el.setAttribute('data-mounted', ...)`) never runs during SSR — same root cause as the existing accordion/radio-group/command entries in oracle-quarantine.ts (#2714): SSR bakes markup with no `data-mounted` attribute at all, and hydration's first effect pass adds it, so the SSR-vs-hydrated structural comparison sees an attribute appear that SSR never emitted.", issue: "https://github.com/piconic-ai/barefootjs/issues/2714" },

  // --- #2751 ---------------------------------------------------------
  { caseId: "state-getter-elided-signal__structure-child-component__binding-boolean-attr__event-direct-handler__callback-function-reference", oracle: "idempotence", reason: "Idempotence replays a click against the csr-mount leg; this case's pure CSR mount throws `ReferenceError: val is not defined` (the getter-elided-signal module-scope `template` thunk references a component-scope signal binding, #2751), so `createComponent` mounts an empty body and the click target ([data-pw-event]) never exists there — confirmed directly (page console: 'ReferenceError: val is not defined'; csr-mount [data-pw-event] count=0). The hydrate leg is unaffected.", issue: "https://github.com/piconic-ai/barefootjs/issues/2751" },
  { caseId: "state-getter-elided-signal__structure-child-component__binding-boolean-attr__event-direct-handler__callback-function-reference", oracle: "three-point", reason: "Pure CSR mount throws `ReferenceError: val is not defined` (the getter-elided-signal module-scope `template` thunk references a component-scope signal binding it never calls, #2751) — `createComponent` mounts an empty body, so the hydrated-vs-csr-mount comparison sees the entire subtree vanish (confirmed: csr-mount page console shows the same ReferenceError). SSR and hydration agree; only csr-mount diverges.", issue: "https://github.com/piconic-ai/barefootjs/issues/2751" },
  { caseId: "state-getter-elided-signal__structure-child-component__binding-controlled-select__event-direct-handler__callback-inline-arrow", oracle: "idempotence", reason: "Idempotence replays a click against the csr-mount leg; this case's pure CSR mount throws `ReferenceError: val is not defined` (the getter-elided-signal module-scope `template` thunk references a component-scope signal binding, #2751), so `createComponent` mounts an empty body and the click target ([data-pw-event]) never exists there — confirmed directly (page console: 'ReferenceError: val is not defined'; csr-mount [data-pw-event] count=0). The hydrate leg is unaffected.", issue: "https://github.com/piconic-ai/barefootjs/issues/2751" },
  { caseId: "state-getter-elided-signal__structure-fragment__binding-class__event-direct-handler__callback-function-reference", oracle: "idempotence", reason: "Idempotence replays a click against the csr-mount leg; this case's pure CSR mount throws `ReferenceError: val is not defined` (the getter-elided-signal module-scope `template` thunk references a component-scope signal binding, #2751), so `createComponent` mounts an empty body and the click target ([data-pw-event]) never exists there — confirmed directly (page console: 'ReferenceError: val is not defined'; csr-mount [data-pw-event] count=0). The hydrate leg is unaffected.", issue: "https://github.com/piconic-ai/barefootjs/issues/2751" },
  { caseId: "state-getter-elided-signal__structure-fragment__binding-class__event-direct-handler__callback-function-reference", oracle: "three-point", reason: "Pure CSR mount throws `ReferenceError: val is not defined` (the getter-elided-signal module-scope `template` thunk references a component-scope signal binding it never calls, #2751) — `createComponent` mounts an empty body, so the hydrated-vs-csr-mount comparison sees the entire subtree vanish (confirmed: csr-mount page console shows the same ReferenceError). SSR and hydration agree; only csr-mount diverges.", issue: "https://github.com/piconic-ai/barefootjs/issues/2751" },
  { caseId: "state-getter-elided-signal__structure-fragment__binding-controlled-input__event-direct-handler__callback-function-reference", oracle: "idempotence", reason: "Idempotence replays a click against the csr-mount leg; this case's pure CSR mount throws `ReferenceError: val is not defined` (the getter-elided-signal module-scope `template` thunk references a component-scope signal binding, #2751), so `createComponent` mounts an empty body and the click target ([data-pw-event]) never exists there — confirmed directly (page console: 'ReferenceError: val is not defined'; csr-mount [data-pw-event] count=0). The hydrate leg is unaffected.", issue: "https://github.com/piconic-ai/barefootjs/issues/2751" },
  { caseId: "state-getter-elided-signal__structure-fragment__binding-controlled-select__event-handler-reading-outer-signal__callback-function-reference", oracle: "idempotence", reason: "Idempotence replays a click against the csr-mount leg; this case's pure CSR mount throws `ReferenceError: val is not defined` (the getter-elided-signal module-scope `template` thunk references a component-scope signal binding, #2751), so `createComponent` mounts an empty body and the click target ([data-pw-event]) never exists there — confirmed directly (page console: 'ReferenceError: val is not defined'; csr-mount [data-pw-event] count=0). The hydrate leg is unaffected.", issue: "https://github.com/piconic-ai/barefootjs/issues/2751" },
  { caseId: "state-getter-elided-signal__structure-fragment__binding-controlled-textarea__event-handler-reading-outer-signal__callback-inline-arrow", oracle: "idempotence", reason: "Idempotence replays a click against the csr-mount leg; this case's pure CSR mount throws `ReferenceError: val is not defined` (the getter-elided-signal module-scope `template` thunk references a component-scope signal binding, #2751), so `createComponent` mounts an empty body and the click target ([data-pw-event]) never exists there — confirmed directly (page console: 'ReferenceError: val is not defined'; csr-mount [data-pw-event] count=0). The hydrate leg is unaffected.", issue: "https://github.com/piconic-ai/barefootjs/issues/2751" },

  // --- #2756 ---------------------------------------------------------
  { caseId: "state-memo__structure-fragment-row-loop__binding-controlled-select__event-ref-callback__callback-flatmap-callback", oracle: "idempotence", reason: "After the filter action shrinks the row count, a csr-mount-rebuilt `<select>` row's row builder bakes a literal `value=\"...\"` attribute a hydration-reused row's SSR markup never had (#2756, select sub-mechanism, same shape as the textarea case) — the hydrated-actions and csr-mount-actions legs disagree on which rows carry it.", issue: "https://github.com/piconic-ai/barefootjs/issues/2756" },
  { caseId: "state-memo__structure-signal-array-loop__binding-controlled-input__event-ref-callback__callback-filter-predicate", oracle: "idempotence", reason: "After the filter action shrinks the row count, a hydration-reused `<input>` row and a csr-mount-rebuilt row disagree on whether the controlled `value` attribute survives as a literal DOM attribute (#2756, input sub-mechanism) — measured directly: the csr-mount-actions leg carries `value=\"0\"`, the hydrated-actions leg does not.", issue: "https://github.com/piconic-ai/barefootjs/issues/2756" },
  { caseId: "state-prop-shadowing-signal__structure-nested-loop-depth-2__binding-controlled-textarea__event-delegated-handler-in-row__callback-filter-predicate", oracle: "idempotence", reason: "After the filter action shrinks the row count, the keyed-loop reconciler rebuilds some surviving `<textarea>` rows and reuses others in the same list; a rebuilt row's row builder bakes a literal `value=\"...\"` attribute that a reused (hydration-origin) row's SSR markup never had (#2756, textarea sub-mechanism) — the hydrated-actions and csr-mount-actions legs disagree on which rows carry it.", issue: "https://github.com/piconic-ai/barefootjs/issues/2756" },
  { caseId: "state-signal__structure-preamble-builder-body__binding-controlled-textarea__event-handler-reading-outer-signal__callback-filter-predicate", oracle: "idempotence", reason: "Same #2756 textarea sub-mechanism as this case's three-point row, now observed after replaying the filter action: the rebuilt/reused `value` attribute split between the hydrated-actions and csr-mount-actions legs.", issue: "https://github.com/piconic-ai/barefootjs/issues/2756" },
  { caseId: "state-signal__structure-preamble-builder-body__binding-controlled-textarea__event-handler-reading-outer-signal__callback-filter-predicate", oracle: "three-point", reason: "A csr-mount-freshly-built `<textarea>` row's row builder embeds the value into its HTML template string (a literal `value=\"...\"` attribute); a hydration-reused row keeps SSR's attribute-free markup (#2756, textarea sub-mechanism) — diverges on the hydrated-vs-csr-mount comparison even before any interaction.", issue: "https://github.com/piconic-ai/barefootjs/issues/2756" },

  // --- #2749 ---------------------------------------------------------
  { caseId: "state-memo__structure-child-component__binding-controlled-input__event-ref-callback__callback-inline-arrow", oracle: "snap", reason: "Hydration stringifies this child-component call-site `ref` callback's source text into a literal `ref=\"...\"` DOM attribute instead of invoking it (#2749) — function source leaks into the markup and the callback never runs. This already fails the structural-HTML SSR-vs-hydrated comparison, so three-point's second (hydrated-vs-csr-mount) comparison is never reached. The SAME case also drops the caller-supplied `data-pw-event` prop under csr-mount (#2754 — confirmed directly: this case's idempotence click-timeout is a clean, error-free prop drop), but that divergence is invisible here because #2749 fires first. #2749 is therefore the issue that must be fixed for THIS row to pass.", issue: "https://github.com/piconic-ai/barefootjs/issues/2749" },
  { caseId: "state-memo__structure-child-component__binding-controlled-input__event-ref-callback__callback-inline-arrow", oracle: "three-point", reason: "Hydration stringifies this child-component call-site `ref` callback's source text into a literal `ref=\"...\"` DOM attribute instead of invoking it (#2749) — function source leaks into the markup and the callback never runs. This already fails the structural-HTML SSR-vs-hydrated comparison, so three-point's second (hydrated-vs-csr-mount) comparison is never reached. The SAME case also drops the caller-supplied `data-pw-event` prop under csr-mount (#2754 — confirmed directly: this case's idempotence click-timeout is a clean, error-free prop drop), but that divergence is invisible here because #2749 fires first. #2749 is therefore the issue that must be fixed for THIS row to pass.", issue: "https://github.com/piconic-ai/barefootjs/issues/2749" },
  { caseId: "state-prop-shadowing-signal__structure-child-component__binding-text__event-ref-callback__callback-function-reference", oracle: "snap", reason: "Hydration stringifies this child-component call-site `ref` callback's source text into a literal `ref=\"...\"` DOM attribute instead of invoking it (#2749) — function source leaks into the markup and the callback never runs. This already fails the structural-HTML SSR-vs-hydrated comparison, so three-point's second (hydrated-vs-csr-mount) comparison is never reached. The SAME case also drops the caller-supplied `data-pw-event` prop under csr-mount (#2754 — confirmed directly: this case's idempotence click-timeout is a clean, error-free prop drop), but that divergence is invisible here because #2749 fires first. #2749 is therefore the issue that must be fixed for THIS row to pass.", issue: "https://github.com/piconic-ai/barefootjs/issues/2749" },
  { caseId: "state-prop-shadowing-signal__structure-child-component__binding-text__event-ref-callback__callback-function-reference", oracle: "three-point", reason: "Hydration stringifies this child-component call-site `ref` callback's source text into a literal `ref=\"...\"` DOM attribute instead of invoking it (#2749) — function source leaks into the markup and the callback never runs. This already fails the structural-HTML SSR-vs-hydrated comparison, so three-point's second (hydrated-vs-csr-mount) comparison is never reached. The SAME case also drops the caller-supplied `data-pw-event` prop under csr-mount (#2754 — confirmed directly: this case's idempotence click-timeout is a clean, error-free prop drop), but that divergence is invisible here because #2749 fires first. #2749 is therefore the issue that must be fixed for THIS row to pass.", issue: "https://github.com/piconic-ai/barefootjs/issues/2749" },
  { caseId: "state-signal__structure-child-component__binding-class__event-ref-callback__callback-function-reference", oracle: "snap", reason: "Hydration stringifies this child-component call-site `ref` callback's source text into a literal `ref=\"...\"` DOM attribute instead of invoking it (#2749) — function source leaks into the markup and the callback never runs. This already fails the structural-HTML SSR-vs-hydrated comparison, so three-point's second (hydrated-vs-csr-mount) comparison is never reached. The SAME case also drops the caller-supplied `data-pw-event` prop under csr-mount (#2754 — confirmed directly: this case's idempotence click-timeout is a clean, error-free prop drop), but that divergence is invisible here because #2749 fires first. #2749 is therefore the issue that must be fixed for THIS row to pass.", issue: "https://github.com/piconic-ai/barefootjs/issues/2749" },
  { caseId: "state-signal__structure-child-component__binding-class__event-ref-callback__callback-function-reference", oracle: "three-point", reason: "Hydration stringifies this child-component call-site `ref` callback's source text into a literal `ref=\"...\"` DOM attribute instead of invoking it (#2749) — function source leaks into the markup and the callback never runs. This already fails the structural-HTML SSR-vs-hydrated comparison, so three-point's second (hydrated-vs-csr-mount) comparison is never reached. The SAME case also drops the caller-supplied `data-pw-event` prop under csr-mount (#2754 — confirmed directly: this case's idempotence click-timeout is a clean, error-free prop drop), but that divergence is invisible here because #2749 fires first. #2749 is therefore the issue that must be fixed for THIS row to pass.", issue: "https://github.com/piconic-ai/barefootjs/issues/2749" },

  // --- #2757 ---------------------------------------------------------
  { caseId: "state-memo__structure-child-component__binding-controlled-textarea__event-direct-handler__callback-inline-arrow", oracle: "three-point", reason: "This top-level `structure: child-component` case never threads `_parentScopeId` into its nested `renderChild` under pure CSR mount, so the child invents its own `bf-s` prefix from its own display name (`PairwiseRow_...`) instead of the caller-derived prefix SSR and hydration both use (#2757) — SSR and hydration agree; only csr-mount's scope-id prefix diverges. The same row also drops the caller-supplied `data-pw-event` prop under csr-mount (#2754) — separable, and not the subject of this entry.", issue: "https://github.com/piconic-ai/barefootjs/issues/2757" },
  { caseId: "state-prop__structure-child-component__binding-attr__event-handler-reading-outer-signal__callback-inline-arrow", oracle: "three-point", reason: "This top-level `structure: child-component` case never threads `_parentScopeId` into its nested `renderChild` under pure CSR mount, so the child invents its own `bf-s` prefix from its own display name (`PairwiseRow_...`) instead of the caller-derived prefix SSR and hydration both use (#2757) — SSR and hydration agree; only csr-mount's scope-id prefix diverges. The same row also drops the caller-supplied `data-pw-event` prop under csr-mount (#2754) — separable, and not the subject of this entry.", issue: "https://github.com/piconic-ai/barefootjs/issues/2757" },
  { caseId: "state-signal__structure-child-component__binding-style__event-direct-handler__callback-inline-arrow", oracle: "three-point", reason: "This top-level `structure: child-component` case never threads `_parentScopeId` into its nested `renderChild` under pure CSR mount, so the child invents its own `bf-s` prefix from its own display name (`PairwiseRow_...`) instead of the caller-derived prefix SSR and hydration both use (#2757) — SSR and hydration agree; only csr-mount's scope-id prefix diverges. The same row also drops the caller-supplied `data-pw-event` prop under csr-mount (#2754) — separable, and not the subject of this entry.", issue: "https://github.com/piconic-ai/barefootjs/issues/2757" },

  // --- #2750 ---------------------------------------------------------
  { caseId: "state-signal__structure-nested-loop-depth-2__binding-boolean-attr__event-ref-callback__callback-function-reference", oracle: "idempotence", reason: "Idempotence replays a click against the csr-mount leg; this case's nested-loop `ref` const (`handleMount`) has its call site emitted but its declaration dropped from the module (#2750), so both hydrate and csr-mount throw `ReferenceError: handleMount is not defined` — confirmed directly (page console on both legs). Only csr-mount actually loses its click target though (count=0): the hydrate leg's rows are still built by the template pass before the ref effect throws, so [data-pw-event] survives there and the click succeeds.", issue: "https://github.com/piconic-ai/barefootjs/issues/2750" },

  // --- #2758 ---------------------------------------------------------
  { caseId: "state-prop-shadowing-signal__structure-early-return__binding-controlled-select__event-direct-handler__callback-function-reference", oracle: "snap", reason: "SSR emits the select with no `selected` attribute because the bound value (prop `val: 7`) matches no option, so the browser defaults to the first option; hydration then assigns `.value` explicitly, which for an out-of-range value yields selectedIndex -1 and an empty value. Measured pre = selectedIndex 0 / value 0, post = selectedIndex -1 / value empty. Independent of the harness `_p` handling: `bf-p` IS present in the served DOM, and `String(String(7))` and `String(String(undefined))` both match no option, so the divergence is identical either way (#2758).", issue: "https://github.com/piconic-ai/barefootjs/issues/2758" },
  { caseId: "state-prop-shadowing-signal__structure-early-return__binding-controlled-select__event-direct-handler__callback-function-reference", oracle: "three-point", reason: "SSR emits the select with no `selected` attribute because the bound value (prop `val: 7`) matches no option, so the browser defaults to the first option; hydration then assigns `.value` explicitly, which for an out-of-range value yields selectedIndex -1 and an empty value. Measured pre = selectedIndex 0 / value 0, post = selectedIndex -1 / value empty. Independent of the harness `_p` handling: `bf-p` IS present in the served DOM, and `String(String(7))` and `String(String(undefined))` both match no option, so the divergence is identical either way (#2758).", issue: "https://github.com/piconic-ai/barefootjs/issues/2758" },
]

export const PAIRWISE_QUARANTINE: ReadonlyMap<string, PairwiseQuarantineEntry> = new Map(
  ENTRIES.map(e => [key(e.caseId, e.oracle), e]),
)

export function pairwiseQuarantineEntry(caseId: string, oracle: OracleKind): PairwiseQuarantineEntry | undefined {
  return PAIRWISE_QUARANTINE.get(key(caseId, oracle))
}
