/**
 * Pairwise sweep suite (#2481 step 5, browser-oracle leg).
 *
 * `oracle.playwright.ts` runs three independent oracles (`oracle-core.ts`)
 * against the FROZEN fixture corpus; `mutation.playwright.ts` runs them
 * against single meaning-preserving mutations of that corpus. This suite
 * runs the same three oracles against every `status: 'ok'` case
 * `scripts/pairwise-generate.ts` produced from the t=2 (plus fragile-axis
 * t=3) covering array over #2481's feature grammar — combinations no
 * single-feature fixture and no one-mutation-at-a-time sweep reaches.
 *
 * Requires `.pairwise/manifest.json` (gitignored, regenerated by
 * `test:pairwise`'s `bun run scripts/pairwise-generate.ts` step) — when
 * absent, every test in this file is skipped with a pointer to that
 * command rather than erroring, so running `bunx playwright test` directly
 * against a checkout that never ran the sweep doesn't look like a crash.
 *
 * ONE deliberate difference from `mutation.playwright.ts`: that suite has
 * `baseAlreadyQuarantined`, which skips a mutant's oracle when the SAME
 * oracle is already known-broken on the unmutated BASE fixture the mutant
 * derives from. A pairwise case has no base fixture to inherit a known
 * failure from — every case is synthesized directly from the axis tuple —
 * so there is no analogous skip here. Every failure this suite finds is a
 * genuine new one; `pairwise-quarantine.ts` is the only noise control.
 */

import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { Server } from 'node:http'
import { test } from '@playwright/test'
import { createFixture, type JSXFixture } from '../src/types'
import { startFixtureServer } from './fixture-host'
import type { OracleKind } from './oracle-quarantine'
import { pairwiseQuarantineEntry } from './pairwise-quarantine'
import { runIdempotenceOracle, runSnapOracle, runThreePointOracle } from './oracle-core'
import { actionStepsOf } from './interaction-runner'
import type { PairwiseManifestEntry } from '../scripts/pairwise-generate'

const HERE = dirname(fileURLToPath(import.meta.url))
const PAIRWISE_DIR = resolve(HERE, '../.pairwise')
const MANIFEST_PATH = resolve(PAIRWISE_DIR, 'manifest.json')

function loadManifest(): PairwiseManifestEntry[] | undefined {
  if (!existsSync(MANIFEST_PATH)) return undefined
  return JSON.parse(readFileSync(MANIFEST_PATH, 'utf8')) as PairwiseManifestEntry[]
}

const manifest = loadManifest()

test.describe('pairwise sweep', () => {
  test.skip(
    manifest === undefined,
    `${MANIFEST_PATH} not found — run \`bun run scripts/pairwise-generate.ts\` (or \`bun run test:pairwise\`) first.`,
  )

  if (manifest === undefined) {
    test('pairwise sweep skipped — manifest not generated', () => {})
    return
  }

  const okCases = manifest.filter(
    (e): e is PairwiseManifestEntry & Required<Pick<PairwiseManifestEntry, 'htmlFile' | 'clientJsFile'>> => e.status === 'ok',
  )

  function loadCaseFixture(entry: (typeof okCases)[number]): JSXFixture {
    const html = readFileSync(resolve(PAIRWISE_DIR, entry.htmlFile), 'utf8')
    const clientJs = readFileSync(resolve(PAIRWISE_DIR, entry.clientJsFile), 'utf8')
    return createFixture({
      // The manifest's own id is already the full axis-tuple string
      // (`scripts/pairwise-generate.ts`'s `idFor`) and unique across the
      // whole covering array by construction — also `fixture-host.ts`'s
      // route key.
      id: entry.id,
      description: `pairwise: ${entry.id}`,
      // No JSX source to carry — `composeCase`'s output (html/clientJs
      // below) is all `fixture-host.ts` ever reads; `source` only exists
      // on `JSXFixture` for the adapter-conformance compile path, which
      // this suite doesn't use.
      source: '',
      componentName: entry.componentName,
      props: entry.props,
      expectedHtml: html,
      expectedClientJs: clientJs,
      interactions: entry.interactions,
    })
  }

  let server: Server
  let baseUrl: string

  test.beforeAll(async () => {
    const fixtures = okCases.map(loadCaseFixture)
    ;({ server, baseUrl } = await startFixtureServer(fixtures))
  })

  test.afterAll(async () => {
    await new Promise<void>(resolveClose => server.close(() => resolveClose()))
  })

  /**
   * Mirrors `mutation.playwright.ts`'s `runQuarantined`, keyed on the
   * (caseId, oracle) pair against `pairwise-quarantine.ts` instead of the
   * (fixtureId, mutationId, oracle) triple against `mutation-quarantine.ts`.
   */
  async function runQuarantined(caseId: string, oracle: OracleKind, assertion: () => Promise<void>): Promise<void> {
    const entry = pairwiseQuarantineEntry(caseId, oracle)
    if (!entry) {
      await assertion()
      return
    }
    let failure: unknown
    try {
      await assertion()
    } catch (err) {
      failure = err
    }
    if (failure === undefined) {
      throw new Error(
        `pairwise-quarantine.ts entry for [${caseId}]/'${oracle}' is stale — the case now passes this oracle; ` +
          `delete the entry (and close/update its tracking issue: ${entry.issue ?? '<none filed yet>'}).`,
      )
    }
  }

  for (const entry of okCases) {
    const fixture = loadCaseFixture(entry)

    test(`[snap] ${entry.id}: hydration is a no-op on SSR state`, async ({ page }) => {
      await runQuarantined(entry.id, 'snap', () => runSnapOracle(page, fixture, baseUrl))
    })

    test(`[three-point] ${entry.id}: SSR ≡ hydrated ≡ csr-mount`, async ({ page }) => {
      await runQuarantined(entry.id, 'three-point', () => runThreePointOracle(page, fixture, baseUrl))
    })

    if (actionStepsOf(fixture.interactions).length === 0) continue
    test(`[idempotence] ${entry.id}: replayed actions agree between hydrated and csr-mount`, async ({ page }) => {
      test.setTimeout(30_000)
      await runQuarantined(entry.id, 'idempotence', () => runIdempotenceOracle(page, fixture, baseUrl))
    })
  }
})
