/**
 * Pairwise sweep suite (#2481 step 5, browser-oracle leg).
 *
 * `oracle.playwright.ts` runs three independent oracles (`oracle-core.ts`)
 * against the FROZEN fixture corpus; `mutation.playwright.ts` runs them
 * against single meaning-preserving mutations of that corpus. This suite
 * runs the same three oracles against every `status: 'ok'` case
 * `scripts/pairwise-generate.ts` produced from the t=2 (plus fragile-axis
 * t=3) covering array over #2481's feature grammar — combinations no
 * single-feature fixture and no one-mutation-at-a-time sweep reaches.
 *
 * Requires `.pairwise/manifest.json` (gitignored, regenerated by
 * `test:pairwise`'s `bun run scripts/pairwise-generate.ts` step) — when
 * absent, every test in this file is skipped with a pointer to that
 * command rather than erroring, so running `bunx playwright test` directly
 * against a checkout that never ran the sweep doesn't look like a crash.
 *
 * ONE deliberate difference from `mutation.playwright.ts`: that suite has
 * `baseAlreadyQuarantined`, which skips a mutant's oracle when the SAME
 * oracle is already known-broken on the unmutated BASE fixture the mutant
 * derives from. A pairwise case has no base fixture to inherit a known
 * failure from — every case is synthesized directly from the axis tuple —
 * so there is no analogous skip here. Every failure this suite finds is a
 * genuine new one; `pairwise-quarantine.ts` is the only noise control.
 */

import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { Server } from 'node:http'
import { expect, test } from '@playwright/test'
import { createFixture, type JSXFixture } from '../src/types'
import { startFixtureServer, fixtureUrl } from './fixture-host'
import type { OracleKind } from './oracle-quarantine'
import { pairwiseQuarantineEntry } from './pairwise-quarantine'
import { runIdempotenceOracle, runSnapOracle, runThreePointOracle, waitOneFrame } from './oracle-core'
import { actionStepsOf } from './interaction-runner'
import type { PairwiseManifestEntry } from '../scripts/pairwise-generate'
import { isLegitimatelyRowLess } from '../pairwise/axes'

const HERE = dirname(fileURLToPath(import.meta.url))
const PAIRWISE_DIR = resolve(HERE, '../.pairwise')
const MANIFEST_PATH = resolve(PAIRWISE_DIR, 'manifest.json')

function loadManifest(): PairwiseManifestEntry[] | undefined {
  if (!existsSync(MANIFEST_PATH)) return undefined
  return JSON.parse(readFileSync(MANIFEST_PATH, 'utf8')) as PairwiseManifestEntry[]
}

const manifest = loadManifest()

test.describe('pairwise sweep', () => {
  test.skip(
    manifest === undefined,
    `${MANIFEST_PATH} not found — run \`bun run scripts/pairwise-generate.ts\` (or \`bun run test:pairwise\`) first.`,
  )

  if (manifest === undefined) {
    test('pairwise sweep skipped — manifest not generated', () => {})
    return
  }

  const okCases = manifest.filter(
    (e): e is PairwiseManifestEntry & Required<Pick<PairwiseManifestEntry, 'htmlFile' | 'clientJsFile'>> => e.status === 'ok',
  )

  function loadCaseFixture(entry: (typeof okCases)[number]): JSXFixture {
    const html = readFileSync(resolve(PAIRWISE_DIR, entry.htmlFile), 'utf8')
    const clientJs = readFileSync(resolve(PAIRWISE_DIR, entry.clientJsFile), 'utf8')
    return createFixture({
      // The manifest's own id is already the full axis-tuple string
      // (`scripts/pairwise-generate.ts`'s `idFor`) and unique across the
      // whole covering array by construction — also `fixture-host.ts`'s
      // route key.
      id: entry.id,
      description: `pairwise: ${entry.id}`,
      // No JSX source to carry — `composeCase`'s output (html/clientJs
      // below) is all `fixture-host.ts` ever reads; `source` only exists
      // on `JSXFixture` for the adapter-conformance compile path, which
      // this suite doesn't use.
      source: '',
      componentName: entry.componentName,
      props: entry.props,
      expectedHtml: html,
      expectedClientJs: clientJs,
      interactions: entry.interactions,
      // Why paint the target instead of clicking around its geometry (e.g.
      // `force: true`, or dispatching a synthetic event at an arbitrary
      // point): Playwright's actionability checks — visible, stable,
      // receives pointer events at the click point — exist to catch a REAL
      // hydration bug (an element covered by an overlay, detached mid-click,
      // etc). Bypassing them here would silently swallow that class of bug
      // for every pairwise case, not just the ones this hostStyles rule
      // targets. The actual defect is narrower than "the click can't land"
      // — it's that several `binding` values (`attr`/`class`/`style`) render
      // an event target whose only content is an attribute with no text, so
      // the browser gives it no line box at all (a `<span>`) or a
      // content-driven zero height (a `<div>` wrapping that empty `<span>`).
      // That's a layout artefact of the harness's plain corpus, not
      // something a passing case is supposed to exercise — so giving the
      // target a floor size is the narrow fix, not a workaround for the
      // click itself.
      //
      // Why CSS is safe here (and wouldn't be for a fixture whose oracle
      // cared about layout): every oracle in `oracle-core.ts` compares
      // `document.body`'s serialized HTML and a live DOM-state property
      // table (`dom-state.ts`) — never computed style, geometry, or
      // anything this stylesheet could perturb. It also applies IDENTICALLY
      // to all three host modes (`fixture-host.ts`'s shared `hostStyles`
      // gate), so it can't introduce an asymmetry between the legs being
      // compared.
      //
      // `min-width`/`min-height` alone doesn't reach a `<span>`: CSS
      // exempts non-replaced INLINE elements from min/max sizing, so the
      // `<span>` rule also switches it to `inline-block` first. `1em` (not
      // `1px`) is load-bearing for the `fragment-row-loop` structure, whose
      // rows sit adjacent with no gap — at `1px` two adjacent 1x1 boxes
      // measure fine but Playwright's hit-test resolves the shared edge to
      // the WRONG sibling (`<span data-key="1">` intercepts the click meant
      // for `data-key="0"`), a real regression caught empirically before
      // landing this rule. The `<div>` rule carries the same `1em` for the
      // same reason, and that is load-bearing rather than symmetry for its
      // own sake: at `min-height: 1px` the three stacked row roots of
      // `component-row-root-loop` sit edge-to-edge at 1px tall each, and
      // `document.elementFromPoint` at row 0's click point returns row 1 —
      // the span bug above, rotated onto the vertical axis. Found by review
      // asking whether the div case had been verified or merely not yet
      // triggered; measurement said the latter, on two cases. `<div>` targets
      // never need the display change — block is already sized by
      // `min-height` — and `<li>`/`<button>`/
      // `<input>`/`<select>`/`<textarea>` targets already have a UA-given
      // line box or intrinsic size and are deliberately left untouched: an
      // earlier, broader `[data-pw-event]{display:inline-block}` rule (no
      // tag qualifier) flipped `<li>` out of `list-item` flow, collapsing
      // sibling list rows onto the same line so one covered another's click
      // point — a real regression this file's own history caught (see the
      // floor test below, which now guards the whole class from without).
      hostStyles: 'span[data-pw-event]{display:inline-block;min-width:1em;min-height:1em;}div[data-pw-event]{min-height:1em;}',
    })
  }

  let server: Server
  let baseUrl: string

  test.beforeAll(async () => {
    const fixtures = okCases.map(loadCaseFixture)
    ;({ server, baseUrl } = await startFixtureServer(fixtures))
  })

  test.afterAll(async () => {
    await new Promise<void>(resolveClose => server.close(() => resolveClose()))
  })

  /**
   * Mirrors `mutation.playwright.ts`'s `runQuarantined`, keyed on the
   * (caseId, oracle) pair against `pairwise-quarantine.ts` instead of the
   * (fixtureId, mutationId, oracle) triple against `mutation-quarantine.ts`.
   */
  async function runQuarantined(caseId: string, oracle: OracleKind, assertion: () => Promise<void>): Promise<void> {
    const entry = pairwiseQuarantineEntry(caseId, oracle)
    if (!entry) {
      await assertion()
      return
    }
    let failure: unknown
    try {
      await assertion()
    } catch (err) {
      failure = err
    }
    if (failure === undefined) {
      throw new Error(
        `pairwise-quarantine.ts entry for [${caseId}]/'${oracle}' is stale — the case now passes this oracle; ` +
          `delete the entry (and close/update its tracking issue: ${entry.issue ?? '<none filed yet>'}).`,
      )
    }
  }

  for (const entry of okCases) {
    const fixture = loadCaseFixture(entry)

    test(`[snap] ${entry.id}: hydration is a no-op on SSR state`, async ({ page }) => {
      await runQuarantined(entry.id, 'snap', () => runSnapOracle(page, fixture, baseUrl))
    })

    test(`[three-point] ${entry.id}: SSR ≡ hydrated ≡ csr-mount`, async ({ page }) => {
      await runQuarantined(entry.id, 'three-point', () => runThreePointOracle(page, fixture, baseUrl))
    })

    if (actionStepsOf(fixture.interactions).length === 0) continue

    // `conditional-ternary`/`early-return` combos in `LEGITIMATELY_ROW_LESS`
    // (`pairwise/axes.ts` — shared with `pairwise-covering-array.test.ts` so
    // the two consumers can't drift apart) render the row-LESS branch on
    // first SSR: no `[data-pw-event]` element exists AT ALL, by design, so
    // `runIdempotenceOracle`'s click can never find a target. Without this
    // skip that's not a fast, obvious "no target" signal — it's a genuine
    // `TimeoutError: locator.click` indistinguishable in the failure list
    // from a real geometry or hydration bug, burning 5s per case to
    // rediscover a fact the covering-array test already proved structurally.
    // This is deliberately NOT "skip idempotence when the selector count is
    // 0" — that blanket form would also silently swallow a row that SHOULD
    // have rendered but didn't (a real hydration bug). It only fires for
    // the specific structure/state combos the table documents, and the
    // assertion below keeps the table honest: if a future compose.ts change
    // ever makes one of these combos render the row after all, the skip
    // itself fails loudly instead of quietly continuing to skip a case that
    // now has something real to click.
    if (isLegitimatelyRowLess(entry.axes.structure, entry.axes.state)) {
      test(`[idempotence] ${entry.id}: skipped — documented row-less combo renders no click target (LEGITIMATELY_ROW_LESS)`, () => {
        expect(
          fixture.expectedHtml,
          `${entry.id}: LEGITIMATELY_ROW_LESS says this structure/state combo never renders '[data-pw-event]', ` +
            `but the SSR HTML has one — remove this entry from LEGITIMATELY_ROW_LESS (pairwise/axes.ts) and let the ` +
            `real [idempotence] test run instead.`,
        ).not.toContain('data-pw-event')
      })
      continue
    }

    test(`[idempotence] ${entry.id}: replayed actions agree between hydrated and csr-mount`, async ({ page }) => {
      test.setTimeout(30_000)
      await runQuarantined(entry.id, 'idempotence', () => runIdempotenceOracle(page, fixture, baseUrl))
    })
  }

  /**
   * Mechanical floor for the `hostStyles` rule above (#2481 step 5,
   * browser-oracle leg — the geometry hole this whole file's history is
   * about). Without this, a future change to `compose.ts`'s structure/
   * binding templates could reintroduce a `[data-pw-event]` target with no
   * line box — exactly the defect the CSS rule fixes today — and nothing
   * would notice until it silently widened `idempotence`'s click-timeout
   * failure list again. This test measures the SAME leg (`'hydrate'`) the
   * real `[idempotence]` tests click first, for every case this suite
   * expects to have a target (excluding `LEGITIMATELY_ROW_LESS`, which by
   * design has none) — so it fails LOUDLY, by name, the moment the hole
   * reopens, instead of being rediscovered as an unexplained pile of
   * `TimeoutError: locator.click` failures.
   *
   * Why only the `'hydrate'` leg, when `runIdempotenceOracle` replays the
   * same click against `'csr-mount'` too: measured across all 85 `ok`
   * cases, the `'csr-mount'` leg is missing `[data-pw-event]` entirely for
   * a set of cases — not because the target has no box, but because the
   * component either drops the caller-supplied prop or throws during
   * construction (#2750, #2751). Those are product defects with their own
   * issues and quarantine rows. Asserting geometry over that leg would
   * fold them into THIS test, which exists to answer one narrow question
   * — "does the harness's own corpus still produce clickable targets?" —
   * and would leave it permanently red for reasons no `compose.ts` change
   * can fix. A geometry floor that can only be satisfied by fixing the
   * compiler is not a geometry floor.
   */
  test('every click target actually receives the click at its own click point', async ({ page }) => {
    test.setTimeout(60_000)
    const targets = okCases.filter(
      e => actionStepsOf(e.interactions).length > 0 && !isLegitimatelyRowLess(e.axes.structure, e.axes.state),
    )
    // Guards the guard: if the covering array ever stopped generating
    // cases with a real click target, the loop below would vacuously pass.
    expect(targets.length).toBeGreaterThan(0)

    const unreachable: string[] = []
    for (const entry of targets) {
      await page.goto(fixtureUrl(baseUrl, entry.id, 'hydrate'))
      await waitOneFrame(page)
      // Playwright's own actionability criterion, asserted directly: take the
      // point it would click (the target's centre) and ask the browser what
      // is actually there. Non-zero area is NOT sufficient and asserting it
      // was the earlier, weaker form of this test: a 1px-tall row root has
      // area 1264, passes an area check, and still hit-tests to its SIBLING
      // (measured on two `component-row-root-loop` cases before the `<div>`
      // rule's `1em` floor). Area was a proxy; this is the property.
      const verdict = await page.evaluate(() => {
        const els = [...document.querySelectorAll('[data-pw-event]')]
        const first = els[0] as HTMLElement | undefined
        if (!first) return 'no-target'
        const box = first.getBoundingClientRect()
        if (box.width <= 0 || box.height <= 0) return `zero-area box=${box.width}x${box.height}`
        const at = document.elementFromPoint(box.left + box.width / 2, box.top + box.height / 2)
        if (at === null) return `nothing at click point (box=${box.width}x${box.height})`
        if (at === first || first.contains(at)) return 'ok'
        const sibling = els.findIndex(e => e === at || e.contains(at))
        return `click point resolves to ${sibling >= 0 ? `sibling #${sibling}` : `<${at.tagName.toLowerCase()}>`} (box=${box.width}x${box.height})`
      })
      if (verdict !== 'ok') unreachable.push(`${entry.id}: ${verdict}`)
    }
    expect(
      unreachable,
      `${unreachable.length} case(s) have a [data-pw-event] target the click cannot reach:\n${unreachable.join('\n')}`,
    ).toEqual([])
  })
})
