package dev.barefootjs.integrations.spring;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * The blog corpus, generated by `scripts/gen-blog-data.ts` from the single
 * TS source of truth (`../shared/blog/posts.ts`) into `dist/blog-data.json`
 * at build time — mirrors {@code integrations/axum/src/blog.rs}'s
 * {@code BlogData}/{@code load_blog_data}.
 */
public final class BlogData {
  public List<Post> posts = new ArrayList<>();
  @SerializedName("listItems")
  public List<ListItem> listItems = new ArrayList<>();
  @SerializedName("allTags")
  public List<String> allTags = new ArrayList<>();

  public static final class Post {
    public String slug;
    public String title;
    public String date;
    public List<String> tags = new ArrayList<>();
    public String excerpt;
    public List<String> body = new ArrayList<>();
  }

  public static final class ListItem {
    public String slug;
    public String title;
    public String date;
    public List<String> tags = new ArrayList<>();
    public String meta;
  }

  public static BlogData load(Path path) {
    if (!Files.exists(path)) {
      System.err.println("barefoot: blog data not found at " + path + " (run `bun run build`)");
      return new BlogData();
    }
    try {
      Gson gson = new GsonBuilder().create();
      String text = Files.readString(path);
      BlogData data = gson.fromJson(text, BlogData.class);
      return data != null ? data : new BlogData();
    } catch (IOException | com.google.gson.JsonSyntaxException e) {
      System.err.println("barefoot: blog data parse error: " + e);
      return new BlogData();
    }
  }
}
