import { arc as d3Arc, pie as d3Pie } from 'd3-shape'
import type { PieArcDatum } from 'd3-shape'
import { scaleLinear } from 'd3-scale'
import { max } from 'd3-array'

export interface PieSliceSpec {
  /** Slice path generated by `d3-shape`'s `arc()`. */
  d: string
  /** Resolved fill — datum override, then ChartConfig color, then fallback. */
  fill: string
  /** Datum's name used for tooltip lookup and as the stable map key. */
  name: string
  /** Numeric value used to size the slice. */
  value: number
}

export interface RadialBarArcSpec {
  /** Background-track path (full sweep, dim). */
  trackD: string | null
  /** Foreground value path (proportional to data value). */
  arcD: string | null
  /** Numeric value used to size the arc. */
  value: number
  /** Optional per-datum fill override (when datum.fill is set). */
  itemFill?: string
  /** Index in the input data, used as a stable identifier for SVG. */
  index: number
}

/**
 * Build the arc geometry for a single radial-bar series. Each input datum
 * becomes a concentric ring within `[innerR, outerR]`, with the value arc
 * sweeping from `startDeg` (top) to a fraction of the dataset max.
 *
 * Pure data — caller renders one `<path d={track.trackD}>` plus one
 * `<path d={track.arcD}>` per spec, keeping the d3-shape dependency inside
 * `@barefootjs/chart` and out of consumer bundles.
 */
export function buildRadialBarArcs(
  data: Record<string, unknown>[],
  dataKey: string,
  innerR: number,
  outerR: number,
  startDeg: number,
  endDeg: number,
): RadialBarArcSpec[] {
  if (data.length === 0) return []

  // SVG arc convention: 0° = top, clockwise. d3-shape uses 0 = right, ccw,
  // so subtract 90° before converting to radians.
  const startRad = (startDeg - 90) * (Math.PI / 180)
  const endRad = (endDeg - 90) * (Math.PI / 180)

  const maxValue =
    max(data, (d) => {
      const v = d[dataKey]
      return typeof v === 'number' ? v : 0
    }) ?? 1

  const angleScale = scaleLinear().domain([0, maxValue]).range([startRad, endRad])

  const ringCount = data.length
  const ringThickness = (outerR - innerR) / ringCount
  const ringPadding = Math.max(1, ringThickness * 0.1)

  const arcGenerator = d3Arc<{
    innerR: number
    outerR: number
    startAngle: number
    endAngle: number
  }>()
    .innerRadius((d) => d.innerR)
    .outerRadius((d) => d.outerR)
    .startAngle((d) => d.startAngle)
    .endAngle((d) => d.endAngle)
    .cornerRadius(4)

  return data.map((datum, i) => {
    const value = Number(datum[dataKey]) || 0
    const rInner = innerR + i * ringThickness + ringPadding / 2
    const rOuter = innerR + (i + 1) * ringThickness - ringPadding / 2
    const itemFill = datum.fill as string | undefined

    return {
      trackD: arcGenerator({
        innerR: rInner,
        outerR: rOuter,
        startAngle: startRad,
        endAngle: endRad,
      }),
      arcD: arcGenerator({
        innerR: rInner,
        outerR: rOuter,
        startAngle: startRad,
        endAngle: angleScale(value),
      }),
      value,
      itemFill,
      index: i,
    }
  })
}

/**
 * Build the slice geometry for a single pie/donut series. Each input datum
 * becomes one path with its `d` string generated from `d3-shape`'s `arc()`.
 *
 * Pure data — caller renders one `<path d={slice.d}>` per spec, keeping the
 * d3-shape dependency inside `@barefootjs/chart` and out of consumer bundles.
 */
export function buildPieSlices(
  data: Record<string, unknown>[],
  dataKey: string,
  nameKey: string,
  config: Record<string, { label: string; color: string }>,
  width: number,
  height: number,
  innerRadiusRatio: number,
  outerRadiusRatio: number,
  paddingAngleDeg: number,
): PieSliceSpec[] {
  if (data.length === 0) return []

  const radius = Math.min(width, height) / 2

  const pieData = data.map((d) => {
    const name = String(d[nameKey] ?? '')
    const value = Number(d[dataKey]) || 0
    const configEntry = config[name]
    const fill = configEntry?.color ?? 'currentColor'
    return { name, value, fill }
  })

  const pieLayout = d3Pie<{ name: string; value: number; fill: string }>()
    .value((d) => d.value)
    .padAngle((paddingAngleDeg * Math.PI) / 180)
    .sort(null)

  const arcGenerator = d3Arc<PieArcDatum<{ name: string; value: number; fill: string }>>()
    .innerRadius(radius * innerRadiusRatio)
    .outerRadius(radius * outerRadiusRatio)

  return pieLayout(pieData).map((arcDatum) => ({
    d: arcGenerator(arcDatum) ?? '',
    fill: arcDatum.data.fill,
    name: arcDatum.data.name,
    value: arcDatum.data.value,
  }))
}
