/**
 * Type-derived adversarial value catalogue
 * (`spec/subset-conformance.md`, roadmap stage 3).
 *
 * Stage-2 hand-written data points proved which values bite; this module
 * scales that judgement: each prop's `TypeInfo` (from the compiled IR's
 * `propsParams`) maps to a small value set, and points are generated by
 * varying ONE prop at a time over the fixture's primary `props` (axis
 * sampling — the cross-product would explode and mostly re-test the
 * same lowering). Generated points flow through the same oracle
 * conformance as declared ones: gate-ordered behind `expectedHtml`,
 * compared live against the JS reference render, opt-out via
 * `skipDataPoints` (`gen:`-prefixed names keep them distinguishable and
 * collision-free).
 *
 * Points are materialized into a COMMITTED artifact
 * (`generated-data-points.json`, regen:
 * `bun packages/adapter-tests/scripts/generate-data-points.ts`) rather
 * than computed at suite registration — same shape as the coverage
 * ledger: zero registration cost per adapter run, reviewable diffs when
 * the catalogue widens, and stable names for the skip discipline, all
 * held by a freshness meta-test.
 *
 * Deliberate v1 exclusions (each is a catalogue extension, not a
 * redesign):
 * - non-integer numbers — a bare `number` prop lowers to Go `int`
 *   absent other evidence (#2168), so fractional values would fail at
 *   the harness, not as a semantic divergence;
 * - astral-plane strings — pinned per-adapter by hand (#2255); the
 *   catalogue stays BMP so a new string prop doesn't mint eight skips;
 * - union / object / interface / function-typed props — value synthesis
 *   needs member enumeration (unions) or required-field construction
 *   (objects);
 * - `Date` — joins the data domain in roadmap stage 4.
 */

import { compileJSX } from '@barefootjs/jsx'
import { HonoAdapter } from '@barefootjs/hono/adapter'
import { jsxFixtures } from '../fixtures'
import type { JSXFixture, JSXDataPoint } from './types'

/** Sentinel meaning "omit the key" (an absent optional prop). */
const ABSENT = Symbol('absent')

interface CatalogValue {
  tag: string
  value: unknown | typeof ABSENT
}

/** Matches the IR's `ParamInfo`/`TypeInfo` shapes (structurally). */
interface PropParam {
  name: string
  optional: boolean
  isRest?: boolean
  defaultValue?: string
  type: {
    kind: string
    primitive?: string
  }
}

function catalogValuesFor(param: PropParam): CatalogValue[] {
  const values: CatalogValue[] = []
  if (param.optional) values.push({ tag: 'absent', value: ABSENT })
  if (param.type.kind === 'primitive') {
    switch (param.type.primitive) {
      case 'string':
        values.push(
          { tag: 'empty', value: '' },
          { tag: 'markup', value: '<b>&"\'</b>' },
          { tag: 'multibyte', value: '日本語' },
        )
        break
      case 'number':
        values.push(
          { tag: 'zero', value: 0 },
          { tag: 'negative', value: -7 },
          { tag: 'large', value: 1234567890 },
        )
        break
      case 'boolean':
        values.push({ tag: 'true', value: true }, { tag: 'false', value: false })
        break
    }
  } else if (param.type.kind === 'array') {
    values.push({ tag: 'empty', value: [] })
  }
  return values
}

function stableStringify(value: unknown): string {
  return JSON.stringify(value, (_key, v) =>
    v && typeof v === 'object' && !Array.isArray(v)
      ? Object.fromEntries(Object.entries(v).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)))
      : v,
  )
}

/**
 * Generate points for one fixture from its compiled `propsParams`.
 * Candidates that reproduce the primary props or any declared point's
 * props verbatim are dropped — a duplicate would double render cost and
 * mint a second skippable name for the same behaviour.
 */
export function generateDataPointsForFixture(fixture: JSXFixture): JSXDataPoint[] {
  if (!fixture.expectedHtml) return []
  const result = compileJSX(fixture.source, 'component.tsx', {
    adapter: new HonoAdapter(),
    outputIR: true,
    siblingTemplatesRegistered: Boolean(fixture.components),
  })
  // The props must belong to the component the suite RENDERS: a
  // multi-export source emits one IR per component, and taking the
  // first one injected another component's props into the rendered
  // one's input (Go: "unknown field X in struct literal"). Match by
  // `componentName`; a multi-IR source without one is ambiguous the
  // same way the render path's alphabetical fallback is — generate
  // nothing rather than guess.
  const irs = result.files
    .filter(f => f.type === 'ir')
    .map(f => JSON.parse(f.content))
  const ir = fixture.componentName
    ? irs.find(i => i.metadata?.componentName === fixture.componentName)
    : irs.length === 1
      ? irs[0]
      : undefined
  if (!ir) return []
  const propsParams: PropParam[] = ir.metadata?.propsParams ?? []

  const base = fixture.props ?? {}
  const seen = new Set<string>([
    stableStringify(base),
    ...(fixture.dataPoints ?? []).map(p => stableStringify(p.props)),
  ])

  const points: JSXDataPoint[] = []
  for (const param of propsParams) {
    if (param.isRest) continue
    if (param.name.startsWith('__')) continue
    for (const { tag, value } of catalogValuesFor(param)) {
      const props: Record<string, unknown> = structuredClone(base)
      if (value === ABSENT) {
        delete props[param.name]
      } else {
        props[param.name] = structuredClone(value)
      }
      const key = stableStringify(props)
      if (seen.has(key)) continue
      seen.add(key)
      points.push({ name: `gen:${param.name}:${tag}`, props })
    }
  }
  return points
}

/** Generate the whole corpus's points, keyed by fixture id (sorted). */
export function generateAllDataPoints(): Record<string, JSXDataPoint[]> {
  const out: Record<string, JSXDataPoint[]> = {}
  for (const fixture of [...jsxFixtures].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0))) {
    const points = generateDataPointsForFixture(fixture)
    if (points.length > 0) out[fixture.id] = points
  }
  return out
}
