/**
 * Type-derived adversarial value catalogue
 * (`spec/subset-conformance.md`, roadmap stage 3).
 *
 * Stage-2 hand-written data points proved which values bite; this module
 * scales that judgement: each prop's `TypeInfo` (from the compiled IR's
 * `propsParams`) maps to a small value set, and points are generated by
 * varying ONE prop at a time over the fixture's primary `props` (axis
 * sampling — the cross-product would explode and mostly re-test the
 * same lowering). Generated points flow through the same oracle
 * conformance as declared ones: gate-ordered behind `expectedHtml`,
 * compared live against the JS reference render, opt-out via
 * `skipDataPoints` (`gen:`-prefixed names keep them distinguishable and
 * collision-free).
 *
 * Points are materialized into a COMMITTED artifact
 * (`generated-data-points.json`, regen:
 * `bun packages/adapter-tests/scripts/generate-data-points.ts`) rather
 * than computed at suite registration — same shape as the coverage
 * ledger: zero registration cost per adapter run, reviewable diffs when
 * the catalogue widens, and stable names for the skip discipline, all
 * held by a freshness meta-test.
 *
 * Deliberate v1 exclusions (each is a catalogue extension, not a
 * redesign):
 * - non-integer numbers — a bare `number` prop lowers to Go `int`
 *   absent other evidence (#2168), so fractional values would fail at
 *   the harness, not as a semantic divergence;
 * - astral-plane strings — pinned per-adapter by hand (#2255); the
 *   catalogue stays BMP so a new string prop doesn't mint eight skips;
 * - union / object / interface / function-typed props — value synthesis
 *   needs member enumeration (unions) or required-field construction
 *   (objects).
 *
 * The catalogued rich type `Date` (#2274) IS synthesized: a `Date`-typed
 * param yields the same adversarial instants as the golden-vector grid,
 * carried as `{ $date: ISO }` envelopes (a `Date` cannot survive the
 * committed JSON artifact) that `data-point-conformance.ts` materializes
 * back into a `Date` before each render leg.
 */

import { compileJSX } from '@barefootjs/jsx'
import { HonoAdapter } from '@barefootjs/hono/adapter'
import { jsxFixtures } from '../fixtures'
import type { JSXFixture, JSXDataPoint } from './types'

/** Sentinel meaning "omit the key" (an absent optional prop). */
const ABSENT = Symbol('absent')

interface CatalogValue {
  tag: string
  value: unknown | typeof ABSENT
}

/** Matches the IR's `ParamInfo`/`TypeInfo` shapes (structurally). */
interface PropParam {
  name: string
  optional: boolean
  isRest?: boolean
  defaultValue?: string
  type: {
    kind: string
    primitive?: string
    /** Original TS type string; for a `Date` prop this is `'Date'`. */
    raw?: string
  }
}

/** Strip any generic arguments from a raw type string (`Foo<Bar>` → `Foo`). */
function baseTypeName(raw: string): string {
  const idx = raw.indexOf('<')
  return (idx === -1 ? raw : raw.slice(0, idx)).trim()
}

/**
 * Replace every real `Date` with a `{ $date: ISO }` envelope, recursing
 * through arrays and plain objects. Generated points are serialized into the
 * committed `generated-data-points.json`, which cannot hold a `Date`; the
 * envelope round-trips as a plain object and is materialized back into a
 * `Date` at render time (`data-point-conformance.ts`). Normalizing the base
 * props here also keeps a `Date` carried from `fixture.props` into a point
 * that varies some OTHER prop envelope-shaped, so the freshness deepEquals
 * (a real `Date` in memory vs a string in the JSON) can never diverge.
 */
function toDateEnvelopes(value: unknown): unknown {
  if (value instanceof Date) return { $date: value.toISOString() }
  if (Array.isArray(value)) return value.map(toDateEnvelopes)
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>).map(([k, v]) => [k, toDateEnvelopes(v)]),
    )
  }
  return value
}

function catalogValuesFor(param: PropParam): CatalogValue[] {
  const values: CatalogValue[] = []
  if (param.optional) values.push({ tag: 'absent', value: ABSENT })
  if (param.type.kind === 'primitive') {
    switch (param.type.primitive) {
      case 'string':
        values.push(
          { tag: 'empty', value: '' },
          { tag: 'markup', value: '<b>&"\'</b>' },
          { tag: 'multibyte', value: '日本語' },
        )
        break
      case 'number':
        values.push(
          { tag: 'zero', value: 0 },
          { tag: 'negative', value: -7 },
          { tag: 'large', value: 1234567890 },
        )
        break
      case 'boolean':
        values.push({ tag: 'true', value: true }, { tag: 'false', value: false })
        break
    }
  } else if (param.type.kind === 'array') {
    values.push({ tag: 'empty', value: [] })
  } else if (param.type.kind === 'interface' && param.type.raw && baseTypeName(param.type.raw) === 'Date') {
    // Catalogued rich type (#2274). Envelopes — not real Dates — so the
    // point survives the committed JSON artifact; the conformance runner
    // materializes them back. The instants mirror the golden-vector
    // adversarial grid (vectors/cases.ts): the epoch, a pre-1970 instant
    // with nonzero ms (the negative-epoch floor-division trap), a leap day,
    // and the four-digit-year boundary.
    values.push(
      { tag: 'epoch', value: { $date: '1970-01-01T00:00:00.000Z' } },
      { tag: 'pre-1970', value: { $date: '1969-07-20T20:17:40.123Z' } },
      { tag: 'leap-day', value: { $date: '2024-02-29T12:00:00.000Z' } },
      { tag: 'year-9999', value: { $date: '9999-12-31T23:59:59.999Z' } },
    )
  }
  return values
}

function stableStringify(value: unknown): string {
  return JSON.stringify(value, (_key, v) =>
    v && typeof v === 'object' && !Array.isArray(v)
      ? Object.fromEntries(Object.entries(v).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)))
      : v,
  )
}

/**
 * Generate points for one fixture from its compiled `propsParams`.
 * Candidates that reproduce the primary props or any declared point's
 * props verbatim are dropped — a duplicate would double render cost and
 * mint a second skippable name for the same behaviour.
 */
export function generateDataPointsForFixture(fixture: JSXFixture): JSXDataPoint[] {
  if (!fixture.expectedHtml) return []
  const result = compileJSX(fixture.source, 'component.tsx', {
    adapter: new HonoAdapter(),
    outputIR: true,
    siblingTemplatesRegistered: Boolean(fixture.components),
  })
  // The props must belong to the component the suite RENDERS: a
  // multi-export source emits one IR per component, and taking the
  // first one injected another component's props into the rendered
  // one's input (Go: "unknown field X in struct literal"). Match by
  // `componentName`; a multi-IR source without one is ambiguous the
  // same way the render path's alphabetical fallback is — generate
  // nothing rather than guess.
  const irs = result.files
    .filter(f => f.type === 'ir')
    .map(f => JSON.parse(f.content))
  const ir = fixture.componentName
    ? irs.find(i => i.metadata?.componentName === fixture.componentName)
    : irs.length === 1
      ? irs[0]
      : undefined
  if (!ir) return []
  const propsParams: PropParam[] = ir.metadata?.propsParams ?? []

  // Envelope-normalize up front: a `Date` in the primary props (or a
  // declared point) becomes a `{ $date: ISO }` envelope so every generated
  // point is JSON-clean and the dedup keys compare like-for-like against a
  // Date-typed catalogue value (also an envelope).
  const base = toDateEnvelopes(fixture.props ?? {}) as Record<string, unknown>
  const seen = new Set<string>([
    stableStringify(base),
    ...(fixture.dataPoints ?? []).map(p => stableStringify(toDateEnvelopes(p.props))),
  ])

  const points: JSXDataPoint[] = []
  for (const param of propsParams) {
    if (param.isRest) continue
    if (param.name.startsWith('__')) continue
    for (const { tag, value } of catalogValuesFor(param)) {
      const props: Record<string, unknown> = structuredClone(base)
      if (value === ABSENT) {
        delete props[param.name]
      } else {
        props[param.name] = structuredClone(value)
      }
      const key = stableStringify(props)
      if (seen.has(key)) continue
      seen.add(key)
      points.push({ name: `gen:${param.name}:${tag}`, props })
    }
  }
  return points
}

/** Generate the whole corpus's points, keyed by fixture id (sorted). */
export function generateAllDataPoints(): Record<string, JSXDataPoint[]> {
  const out: Record<string, JSXDataPoint[]> = {}
  for (const fixture of [...jsxFixtures].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0))) {
    const points = generateDataPointsForFixture(fixture)
    if (points.length > 0) out[fixture.id] = points
  }
  return out
}
