/**
 * Accordion fixture lifted from `site/ui/components/accordion-demo.tsx`
 * (#1467 Phase 2c — disclosure).
 *
 * `AccordionSingleOpenDemo` drives three composed `AccordionItem`s off a
 * single `openItem` signal. Two distinct runtime paths cooperate per
 * item, and the interactions assert both at every step:
 *
 *   - the item `<div>`'s `data-state` is a *reactive prop → attribute
 *     binding* (`open={openItem() === 'item-1'}` rendered by
 *     `AccordionItem`'s template), updated by the compiled binding when
 *     the parent signal changes;
 *   - the trigger's `aria-expanded` and the content's `data-state` are
 *     *effect-driven* (`useContext` + `createEffect` inside each child's
 *     `ref` mount callback) — the SSR HTML ships the trigger
 *     `aria-expanded="false"` even for the initially-open item, so the
 *     first assertion below only passes if hydration ran the mount
 *     effects with working context.
 *
 * This is also the first demo-root fixture whose sibling graph nests:
 * `accordion` itself imports `../icon` (ChevronDownIcon), so the
 * committed accordion SSR module carries a `../icon` import that the
 * Hono test renderer re-anchors to icon's own committed module.
 *
 * The host page serves no CSS, so open/closed visibility (a
 * `grid-rows-[0fr]`/`invisible` class swap) cannot be asserted via
 * `expectVisible`/`expectHidden`; the `data-state` attributes are the
 * observable contract.
 *
 * Snapshots in `__snapshots__/accordion.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * accordion`.
 */

import { defineDemoFixture, type SharedFixtureSpec } from './_helpers'

const item = (v: string) => `[data-slot="accordion-item"][data-value="${v}"]`
const trigger = (v: string) => `${item(v)} [data-slot="accordion-trigger"]`
const content = (v: string) => `${item(v)} [data-slot="accordion-content"]`

export const spec: SharedFixtureSpec = {
  id: 'accordion',
  componentName: 'AccordionSingleOpenDemo',
  sourceFile: 'accordion-demo',
  description:
    'site/ui Accordion demo — single-open disclosure across composed items (reactive-prop data-state + context/effect-driven trigger and content)',
  interactions: [
    // Post-hydration initial state: openItem starts as 'item-1'. The
    // trigger's aria-expanded flipping to "true" (SSR ships "false")
    // proves the mount effect + context wiring ran.
    { type: 'expectAttribute', selector: item('item-1'), attribute: 'data-state', value: 'open' },
    { type: 'expectAttribute', selector: trigger('item-1'), attribute: 'aria-expanded', value: 'true' },
    { type: 'expectAttribute', selector: content('item-1'), attribute: 'data-state', value: 'open' },
    { type: 'expectAttribute', selector: item('item-2'), attribute: 'data-state', value: 'closed' },
    { type: 'expectAttribute', selector: trigger('item-2'), attribute: 'aria-expanded', value: 'false' },
    // Open item 2 — single-open invariant closes item 1.
    { type: 'click', selector: trigger('item-2') },
    { type: 'expectAttribute', selector: item('item-2'), attribute: 'data-state', value: 'open' },
    { type: 'expectAttribute', selector: trigger('item-2'), attribute: 'aria-expanded', value: 'true' },
    { type: 'expectAttribute', selector: content('item-2'), attribute: 'data-state', value: 'open' },
    { type: 'expectAttribute', selector: item('item-1'), attribute: 'data-state', value: 'closed' },
    { type: 'expectAttribute', selector: trigger('item-1'), attribute: 'aria-expanded', value: 'false' },
    { type: 'expectAttribute', selector: content('item-1'), attribute: 'data-state', value: 'closed' },
    // Click item 2 again — toggling the open item closes everything
    // (openItem → null).
    { type: 'click', selector: trigger('item-2') },
    { type: 'expectAttribute', selector: item('item-2'), attribute: 'data-state', value: 'closed' },
    { type: 'expectAttribute', selector: trigger('item-2'), attribute: 'aria-expanded', value: 'false' },
    { type: 'expectAttribute', selector: item('item-1'), attribute: 'data-state', value: 'closed' },
  ],
}

export const fixture = defineDemoFixture(spec)
