/**
 * BodyDestructuredPropsLive fixture — lifted from
 * `integrations/shared/components/BodyDestructuredPropsLive.tsx`.
 *
 * Body-destructure twin of `destructured-props-live` (#2934). Pins that a
 * PURE body-destructured prop alias (`const { value } = props`, including a
 * default and a rename) stays live across plain text, a `createMemo`
 * computation, a `createEffect` body, an event handler argument, and a
 * reactive attribute (`data-label`, which also exercises the destructure
 * DEFAULT). `raw`/`memo`/`effect` moving together after ONE parent click is
 * the assertion a captured-once compiler cannot pass — only `raw`, a plain
 * reactive-text position, would track.
 *
 * `effect` starts at `0`, not `1`, for the same hydration-parity reason as
 * `destructured-props-live` — see the component.
 *
 * Snapshots in `__snapshots__/body-destructured-props-live.{html,client.js}`
 * are regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * body-destructured-props-live`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const child = '.body-live-child'

export const spec: SharedFixtureSpec = {
  id: 'body-destructured-props-live',
  componentName: 'BodyDestructuredPropsLive',
  sourceFile: 'BodyDestructuredPropsLive',
  description:
    'A body-destructured-props child stays fully reactive across text/memo/effect/handler/attribute positions',
  props: {},
  interactions: [
    // Initial: parent count = 1, label omitted → default 'none'.
    { type: 'expectContains', selector: '.parent-count', text: 'Count: 1' },
    { type: 'expectContains', selector: '.picked', text: 'Picked: 0' },
    { type: 'expectText', selector: `${child} .raw`, text: '1' },
    { type: 'expectText', selector: `${child} .memo`, text: '2' },
    { type: 'expectText', selector: `${child} .effect`, text: '0' },
    { type: 'expectAttribute', selector: child, attribute: 'data-label', value: 'none' },

    // Parent +1 → EVERY body-destructured-prop-alias read updates together:
    // raw, memo (createMemo body reads `value`), and effect (createEffect
    // body reads `value` then calls `setSeen`). A captured-once compiler
    // fails exactly here — `raw` alone would update.
    { type: 'click', selector: '.btn-increment' },
    { type: 'expectContains', selector: '.parent-count', text: 'Count: 2' },
    { type: 'expectText', selector: `${child} .raw`, text: '2' },
    { type: 'expectText', selector: `${child} .memo`, text: '4' },
    { type: 'expectText', selector: `${child} .effect`, text: '2' },

    // Handler reads the LIVE body-destructured (and RENAMED — `onPick: pick`)
    // `value`, not the value at mount: `onClick={() => pick(value)}` must
    // see 2, not 1.
    { type: 'click', selector: `${child} .btn-pick` },
    { type: 'expectContains', selector: '.picked', text: 'Picked: 2' },

    // Toggling the `named` signal flips the `label` prop between
    // `undefined` (destructure default `'none'` applies — live per
    // read, not just at mount) and `'named'`, live in the `data-label`
    // reactive-attribute binding.
    { type: 'click', selector: '.btn-name' },
    { type: 'expectAttribute', selector: child, attribute: 'data-label', value: 'named' },
    { type: 'click', selector: '.btn-name' },
    { type: 'expectAttribute', selector: child, attribute: 'data-label', value: 'none' },
  ],
}

export const fixture = defineSharedFixture(spec)
