/**
 * Regression pin (#2472) for a reactive attribute on an early-return
 * branch's OWN ROOT ELEMENT that is driven by a PROP (not a signal).
 *
 * `signal-early-return` covers a component-level `if`/`else` early return
 * whose branches are a static `<button>` and `<p>` — no reactive attribute
 * on either root. `if-statement-child-swap` covers a branch that mounts a
 * CHILD component — but its own attribute coverage is nil. Neither pins
 * the shape `ui/components/ui/badge` and `ui/components/ui/button` actually
 * ship: a branch whose own root element (no synthetic `bf-c` wrapper —
 * `insertRoot()`'s root-swap path, `ConditionalElement.rootSwap`) carries a
 * `className` computed from a destructured prop with a default
 * (`variantClasses[variant]`).
 *
 * PR #2472 lowered that attribute through a different expression
 * transformer than the top-level (non-branch) reactive-attribute path
 * (`emitReactiveAttributeUpdates`'s `rewriteDestructuredPropsInExpr` call in
 * `emit-reactive.ts`), so the branch effect read the once-captured
 * destructured local (`variant`, snapshotted at the top of `init`) instead
 * of re-reading the live props object (`_p.variant`) on every effect run —
 * freezing the class after the first render even as the forwarded prop kept
 * changing. Observed for real as the Badge/Button playground E2E failures
 * (`site/ui/e2e/badge.spec.ts`, `button.spec.ts`): changing `variant`/`size`
 * left the rendered class unchanged.
 *
 * `VariantTag` (the branch-bearing component) is forwarded a live getter
 * prop from `BranchRootPropAttr` (the signal owner) — exactly how a real
 * page forwards a playground signal into `<Badge variant={variant()}/>` —
 * so a snapshot-vs-live regression is only observable through this
 * two-component shape, not by inlining everything into one component.
 *
 * Snapshots in `__snapshots__/branch-root-prop-attr.{html,client.js}` are
 * regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts branch-root-prop-attr`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const tag = 'span[data-slot="tag"]'
const button = 'button'

export const spec: SharedFixtureSpec = {
  id: 'branch-root-prop-attr',
  componentName: 'BranchRootPropAttr',
  sourceRoot: 'fixture',
  additionalComponents: ['VariantTag'],
  description:
    'Prop-driven reactive class on an if/else early-return branch\'s own root element updates live (#2472)',
  interactions: [
    // Initial SSR/hydration state: variant defaults to 'a'.
    { type: 'expectAttribute', selector: tag, attribute: 'class', value: 'cls-a' },
    // Click cycles the parent's signal, forwarded to the child as a live
    // prop — the branch-root class effect must re-read it, not a snapshot.
    { type: 'click', selector: button },
    { type: 'expectAttribute', selector: tag, attribute: 'class', value: 'cls-b' },
    { type: 'click', selector: button },
    { type: 'expectAttribute', selector: tag, attribute: 'class', value: 'cls-a' },
  ],
}

export const fixture = defineSharedFixture(spec)
