/**
 * Coverage for #2477: a `Record[key]` class lookup keyed by a prop
 * forwarded from a parent SIGNAL, sitting on an if/else early-return
 * branch's own root element — the exact shape `ui/components/ui/badge`
 * ships (`if (asChild) return <Slot className={variantClasses[variant]}…`).
 *
 * Two things this pins, both found the hard way:
 *
 * 1. SSR (#2477): `const cls = variantClasses[variant]` followed by
 *    `className={cls}` must lower through the shared `lookup` template
 *    part. Before the fix, the one-hop const fell through to a
 *    bare-expression attr — Hono evaluated the const fine, every template
 *    backend emitted a reference to a variable the template never defines
 *    and rendered `class=""` silently. The inline form (#2300) and the
 *    template-literal hop already lowered correctly; only this hop leaked.
 *    The shared `Icon` component (`const path = iconPaths[name]`) had the
 *    same shape, so SVG icons server-rendered blank on every non-Hono
 *    backend until hydration.
 *
 * 2. CSR (the `interactions` below): the class must track the LIVE
 *    forwarded prop (`_p.variant`), not an init-time snapshot of the
 *    destructured local. A snapshot-vs-live bug is only observable through
 *    this two-component shape (signal owner forwarding `variant={variant()}`
 *    into the branch-bearing child), never by inlining everything into one
 *    component — which is why no earlier fixture caught either half.
 *
 * The child also uses an explicit literal-union type argument
 * (`createSignal<'a' | 'b'>` / `variant?: 'a' | 'b'`), pinning the Go
 * adapter's literal-union collapse (#2477's second leg: union types
 * previously fell to `interface{}` + a `nil` seed and failed `go run`).
 *
 * Snapshots in `__snapshots__/branch-root-prop-attr.{html,client.js}` are
 * regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts branch-root-prop-attr`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const tag = 'span[data-slot="tag"]'
const button = 'button'

export const spec: SharedFixtureSpec = {
  id: 'branch-root-prop-attr',
  componentName: 'BranchRootPropAttr',
  sourceRoot: 'fixture',
  additionalComponents: ['VariantTag'],
  description:
    'Record[key] class lookup keyed by a forwarded prop, on an early-return branch root, SSRs resolved and updates live (#2477)',
  interactions: [
    // Initial SSR/hydration state: variant defaults to 'a'.
    { type: 'expectAttribute', selector: tag, attribute: 'class', value: 'cls-a' },
    // Click cycles the parent's signal, forwarded to the child as a live
    // prop — the branch-root class effect must re-read it, not a snapshot.
    { type: 'click', selector: button },
    { type: 'expectAttribute', selector: tag, attribute: 'class', value: 'cls-b' },
    { type: 'click', selector: button },
    { type: 'expectAttribute', selector: tag, attribute: 'class', value: 'cls-a' },
  ],
}

export const fixture = defineSharedFixture(spec)
