/**
 * Native `<input type="checkbox" checked={...}>` fixture lifted from
 * `integrations/shared/components/CheckboxNative.tsx` (#2481).
 *
 * Fills a DOM-state-carrier gap: every existing checkbox-shaped fixture
 * (`checkbox` site/ui, `form`'s terms checkbox) is an ARIA
 * `role="checkbox"` `<button>`, never a native `<input type="checkbox">`
 * — so the live `checked` IDL property (as opposed to the `checked`
 * ATTRIBUTE, which only reflects the initial value) had no fixture
 * exercising it. A runtime that patches the attribute but not the
 * property after the user has already toggled the control would pass
 * every existing attribute-based assertion while this oracle catches it.
 *
 * Snapshots in `__snapshots__/checkbox-native-shared.{html,client.js}`
 * are regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * checkbox-native-shared`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'checkbox-native-shared',
  componentName: 'CheckboxNative',
  description: 'Native <input type="checkbox" checked={signal}> with a text readout',
  interactions: [
    { type: 'expectText', selector: '.subscribe-label', text: 'Not subscribed' },
    { type: 'click', selector: '.subscribe-checkbox' },
    { type: 'expectText', selector: '.subscribe-label', text: 'Subscribed' },
    { type: 'click', selector: '.subscribe-checkbox' },
    { type: 'expectText', selector: '.subscribe-label', text: 'Not subscribed' },
  ],
}

export const fixture = defineSharedFixture(spec)
