/**
 * Checkbox fixture lifted from `ui/components/ui/checkbox/index.tsx`
 * (#1467 Phase 2b).
 *
 * Unlike `toggle` / `switch`, the click handler here only mutates the
 * signal — `data-state`, `aria-checked`, and the conditionally-rendered
 * `CheckIcon` are all driven by the compiler's reactivity (`insert()` for
 * the `{isChecked() && <CheckIcon/>}` branch). That makes it a good probe
 * for the conditional-insert runtime path: the indicator SVG must appear on
 * check and disappear on uncheck.
 *
 * `CheckIcon` is imported from `../icon`, so the sibling is auto-inferred
 * and its client bundle combined via the `@bf-child` placeholder — the
 * first Phase 2b fixture to exercise sibling-component composition for an
 * interactive `site/ui` root.
 *
 * The indicator presence is asserted via `expectAttribute` (DOM presence)
 * for the checked state and `expectHidden` (absent from the DOM) for the
 * unchecked state, rather than `expectVisible`: the fixture-hydrate host
 * page serves no CSS, so the inserted `size-3.5` SVG has a zero bounding
 * box and would read as "hidden" even when present. Presence/absence still
 * fully exercises the conditional-`insert()` runtime path.
 *
 * Snapshots in `__snapshots__/checkbox.{html,client.js}` are regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts checkbox`.
 */

import { defineUiFixture, type SharedFixtureSpec } from './_helpers'

const box = 'button[role="checkbox"]'
const indicator = '[data-slot="checkbox-indicator"]'

export const spec: SharedFixtureSpec = {
  id: 'checkbox',
  componentName: 'Checkbox',
  sourceFile: 'checkbox',
  description:
    'site/ui Checkbox — signal-driven data-state/aria-checked + conditional CheckIcon insert',
  props: { className: '' },
  interactions: [
    // Initial unchecked: no indicator in the DOM.
    { type: 'expectAttribute', selector: box, attribute: 'aria-checked', value: 'false' },
    { type: 'expectAttribute', selector: box, attribute: 'data-state', value: 'unchecked' },
    { type: 'expectHidden', selector: indicator },
    // Check — reactivity flips attributes and inserts the indicator SVG.
    { type: 'click', selector: box },
    { type: 'expectAttribute', selector: box, attribute: 'aria-checked', value: 'true' },
    { type: 'expectAttribute', selector: box, attribute: 'data-state', value: 'checked' },
    { type: 'expectAttribute', selector: indicator, attribute: 'data-slot', value: 'checkbox-indicator' },
    // Uncheck — attributes revert and the indicator is removed again.
    { type: 'click', selector: box },
    { type: 'expectAttribute', selector: box, attribute: 'aria-checked', value: 'false' },
    { type: 'expectAttribute', selector: box, attribute: 'data-state', value: 'unchecked' },
    { type: 'expectHidden', selector: indicator },
  ],
}

export const fixture = defineUiFixture(spec)
