/**
 * Coverage for #3055 (`child-prop-mirror-attr-ssr`): the compiler's
 * child-root prop mirror (`collectReactiveChildProps` /
 * `emitReactiveChildProps`) must write an attribute onto a child
 * component's root ONLY where the child's own render actually puts it
 * there — never a prop the child merely consumes internally.
 *
 * `RestForwardTag` gives the two cases in one fixture:
 *
 * 1. `variant` is destructured and used only to compute a class — it is
 *    never forwarded to the root, so `variant` must NEVER appear as an
 *    attribute on `[data-slot="rest-tag"]`, on the server render OR
 *    after any number of clicks. This is `branch-root-prop-attr`'s twin
 *    shape, pinned again here to keep the fix from regressing the case
 *    a future refactor might reintroduce.
 * 2. `tag` is NOT destructured by the child, so it falls into `{...rest}`
 *    and reaches the root — the shape the mirror mechanism exists for.
 *    It must keep updating reactively across clicks, so the #3055 fix
 *    (gating the mirror's write on the child's rendered attribute) cannot
 *    regress the case the mirror was legitimately built to serve. The
 *    value cycles THROUGH `undefined` (`one` → absent → `two`): the
 *    mirror removes the attribute and must re-apply it afterwards, which
 *    a live `hasAttribute` gate cannot do once its own removal has run
 *    (the seeded-once gate can).
 *
 * Snapshots in `__snapshots__/child-prop-rest-forward.{html,client.js}`
 * are regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts child-prop-rest-forward`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const rootTag = 'span[data-slot="rest-tag"]'
const button = 'button'

export const spec: SharedFixtureSpec = {
  id: 'child-prop-rest-forward',
  componentName: 'ChildPropRestForward',
  sourceRoot: 'fixture',
  additionalComponents: ['RestForwardTag'],
  description:
    'a child-component prop the child forwards via {...rest} onto its root keeps updating reactively, while a prop the child only consumes internally never appears there (#3055)',
  interactions: [
    // Initial SSR/hydration state: the forwarded prop is on the root;
    // the internally-consumed one never is — see `expectedHtml` for that
    // half (no `expectAttribute` step can assert absence).
    { type: 'expectAttribute', selector: rootTag, attribute: 'tag', value: 'one' },
    // Click 1 sets `tag` to `undefined` — the mirror removes the attribute
    // (no step can assert absence; the next step is the one that matters).
    { type: 'click', selector: button },
    // Click 2 sets `tag` to `two`: the attribute must come BACK after the
    // removal — the ratchet a live `hasAttribute` gate would fall into.
    { type: 'click', selector: button },
    { type: 'expectAttribute', selector: rootTag, attribute: 'tag', value: 'two' },
    // Click 3 wraps to `one` again — a plain non-null → non-null update.
    { type: 'click', selector: button },
    { type: 'expectAttribute', selector: rootTag, attribute: 'tag', value: 'one' },
  ],
}

export const fixture = defineSharedFixture(spec)
