/**
 * #3057 regression pin: sibling of `child-prop-rest-forward`
 * (`child-prop-mirror-attr-ssr`, #3055/#3056). That fixture cycles the
 * forwarded `tag` prop THROUGH `undefined` after it has already rendered
 * once — this one starts `undefined` from the very first render, so SSR
 * never puts a `tag` attribute on `RestForwardTag`'s root at all.
 *
 * Before #3057's fix, nothing ever applied a `tag` set after that: the
 * parent-side mirror's `hasAttribute('tag')` gate seeds `false` forever
 * (SSR never rendered the attribute) and the child's statically-expanded
 * `{...rest}` binding had no `createEffect` of its own. The fix gives the
 * child (`RestForwardTag`, via its closed-type rest expansion) a reactive
 * attribute binding of its own, independent of the parent-side mirror.
 *
 * Snapshots in `__snapshots__/child-prop-rest-forward-undefined-start.{html,client.js}`
 * are regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts child-prop-rest-forward-undefined-start`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const rootTag = 'span[data-slot="rest-tag"]'
const button = 'button'

export const spec: SharedFixtureSpec = {
  id: 'child-prop-rest-forward-undefined-start',
  componentName: 'ChildPropRestForwardUndefinedStart',
  sourceRoot: 'fixture',
  additionalComponents: ['RestForwardTag'],
  description:
    'a child-component prop that starts undefined (never rendered by SSR) still reaches the child root reactively once set, for a prop the child forwards via {...rest} (#3057)',
  interactions: [
    // Initial SSR/hydration state: no `tag` attribute at all — see
    // `expectedHtml` for that half (no `expectAttribute` step can assert
    // absence).
    { type: 'click', selector: button },
    { type: 'expectAttribute', selector: rootTag, attribute: 'tag', value: 'x' },
    // Back to undefined, then set again — the same re-apply-after-removal
    // ratchet `child-prop-rest-forward` pins, now exercised from a colder
    // start.
    { type: 'click', selector: button },
    { type: 'click', selector: button },
    { type: 'expectAttribute', selector: rootTag, attribute: 'tag', value: 'x' },
  ],
}

export const fixture = defineSharedFixture(spec)
