/**
 * Combobox fixture lifted from `site/ui/components/combobox-demo.tsx`
 * (#1467 Phase 2d).
 *
 * `ComboboxBasicDemo` layers *typed filtering* on top of the `select`
 * loop: the portaled content carries a real `<input>`, and each item's
 * visibility is an effect that toggles the `hidden` attribute against
 * the search signal. `hidden` matters: it is the one visibility
 * mechanism the CSS-less host page still honours (the UA stylesheet
 * maps it to `display: none`), so `expectHidden`/`expectVisible`
 * exercise Playwright's real visibility computation rather than a
 * data-attribute proxy.
 *
 * The selection leg mirrors `select` (item click → signal →
 * close + trigger value rewrite); the empty-state leg types a
 * no-match string and expects every item hidden with the
 * `ComboboxEmpty` row unhidden — that row's visibility is itself an
 * effect counting visible siblings, i.e. DOM-derived reactivity.
 *
 * Snapshots in `__snapshots__/combobox.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * combobox`.
 */

import { defineDemoFixture, type SharedFixtureSpec } from './_helpers'

const trigger = '[data-slot="combobox-trigger"]'
const value = '[data-slot="combobox-value"]'
// `body >` pins the post-portal location (see dialog fixture).
const content = 'body > [data-slot="combobox-content"]'
const input = `${content} [data-slot="combobox-input"]`
const item = (v: string) => `${content} [data-slot="combobox-item"][data-value="${v}"]`
const empty = `${content} [data-slot="combobox-empty"]`
const readout = '.selected-value'

export const spec: SharedFixtureSpec = {
  id: 'combobox',
  componentName: 'ComboboxBasicDemo',
  sourceFile: 'combobox-demo',
  description:
    'site/ui Combobox demo — typed filtering hides items via the hidden attribute; selection closes and rewrites the trigger',
  interactions: [
    // Closed after hydration.
    { type: 'expectAttribute', selector: trigger, attribute: 'aria-expanded', value: 'false' },
    { type: 'expectAttribute', selector: content, attribute: 'data-state', value: 'closed' },
    { type: 'expectContains', selector: readout, text: 'None' },
    // Open and filter: "sv" keeps SvelteKit, drops Next.js.
    { type: 'click', selector: trigger },
    { type: 'expectAttribute', selector: content, attribute: 'data-state', value: 'open' },
    { type: 'fill', selector: input, value: 'sv' },
    { type: 'expectVisible', selector: item('svelte') },
    { type: 'expectHidden', selector: item('next') },
    { type: 'expectHidden', selector: empty },
    // Select the surviving item — closes, checks, rewrites trigger.
    { type: 'click', selector: item('svelte') },
    { type: 'expectAttribute', selector: content, attribute: 'data-state', value: 'closed' },
    { type: 'expectText', selector: value, text: 'SvelteKit' },
    { type: 'expectContains', selector: readout, text: 'svelte' },
    // Reopen and type a no-match: every item hides, the empty row
    // unhides (its visibility is an effect counting visible siblings).
    { type: 'click', selector: trigger },
    { type: 'expectAttribute', selector: content, attribute: 'data-state', value: 'open' },
    { type: 'fill', selector: input, value: 'zzz' },
    { type: 'expectHidden', selector: item('svelte') },
    { type: 'expectHidden', selector: item('next') },
    { type: 'expectVisible', selector: empty },
    // ESC closes; selection from the first leg survives.
    { type: 'press', selector: 'body', key: 'Escape' },
    { type: 'expectAttribute', selector: content, attribute: 'data-state', value: 'closed' },
    { type: 'expectText', selector: value, text: 'SvelteKit' },
  ],
}

export const fixture = defineDemoFixture(spec)
