/**
 * Command fixture lifted from `site/ui/components/command-demo.tsx`
 * (#1467 Phase 2d).
 *
 * `CommandPreviewDemo` is the always-open palette — no portal, no
 * trigger, just an input whose search signal fans out to a per-item
 * visibility effect (`hidden` attribute, honoured by the UA stylesheet
 * on the CSS-less host page), a per-group effect that hides a group
 * when all of its items hide, and a CommandEmpty row that unhides when
 * nothing matches. The default filter is a case-insensitive substring
 * match, so "cal" keeps both Calendar and Calculator across *different*
 * groups while dropping everything else — one input event, four
 * independent effect updates.
 *
 * Items resolve their `data-value` during the mount callback (not in
 * the SSR HTML), so the very first assertion addressing
 * `[data-value="Calendar"]` doubles as a hydration probe.
 *
 * The clear-filter leg (`fill ''`) drives the input back to the
 * everything-visible state — asserting the effects run symmetrically,
 * not just on the narrowing direction.
 *
 * Snapshots in `__snapshots__/command.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * command`.
 */

import { defineDemoFixture, type SharedFixtureSpec } from './_helpers'

const input = '[data-slot="command-input"]'
const item = (v: string) => `[data-slot="command-item"][data-value="${v}"]`
const empty = '[data-slot="command-empty"]'

export const spec: SharedFixtureSpec = {
  id: 'command',
  componentName: 'CommandPreviewDemo',
  sourceFile: 'command-demo',
  description:
    'site/ui Command demo — search signal fans out to item/group/empty visibility effects via the hidden attribute',
  interactions: [
    // Post-hydration: items got their data-value from the mount
    // callback, everything visible, empty row hidden.
    { type: 'expectVisible', selector: item('Calendar') },
    { type: 'expectVisible', selector: item('Billing') },
    { type: 'expectHidden', selector: empty },
    // "cal" — substring match keeps Calendar + Calculator (different
    // groups), hides the rest.
    { type: 'fill', selector: input, value: 'cal' },
    { type: 'expectVisible', selector: item('Calendar') },
    { type: 'expectVisible', selector: item('Calculator') },
    { type: 'expectHidden', selector: item('Search Emoji') },
    { type: 'expectHidden', selector: item('Billing') },
    { type: 'expectHidden', selector: empty },
    // No match — every item hides, the empty row unhides.
    { type: 'fill', selector: input, value: 'zzzz' },
    { type: 'expectHidden', selector: item('Calendar') },
    { type: 'expectHidden', selector: item('Calculator') },
    { type: 'expectVisible', selector: empty },
    // Clearing restores the everything-visible state symmetrically.
    { type: 'fill', selector: input, value: '' },
    { type: 'expectVisible', selector: item('Calendar') },
    { type: 'expectVisible', selector: item('Search Emoji') },
    { type: 'expectVisible', selector: item('Billing') },
    { type: 'expectHidden', selector: empty },
  ],
}

export const fixture = defineDemoFixture(spec)
