/**
 * CondForwardedChildAttr fixture (#3324) — source lives in the fixture-only
 * root (`fixtures/components/CondForwardedChildAttr.tsx`).
 *
 * A reactive attribute on an element forwarded as a conditional child
 * component's `children` used to stay at its initial value: the branch's
 * `qsa(__branchScope, '[bf="^sN"]')` lookup rejected the parent-owned
 * element because it renders inside the child's own scope. Covers the
 * hydrated branch, a client-recreated branch (toggle twice), and the
 * nested child's own same-numbered slot staying untouched.
 *
 * Snapshots in `__snapshots__/cond-forwarded-child-attr.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * cond-forwarded-child-attr`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'cond-forwarded-child-attr',
  componentName: 'CondForwardedChildAttr',
  sourceRoot: 'fixture',
  description:
    'a reactive attribute on an element forwarded into a conditional child component\'s children must update (#3324)',
  interactions: [
    { type: 'expectAttribute', selector: '.forwarded', attribute: 'data-label', value: 'alpha' },
    // Hydrated branch: the effect bound at hydration updates the attribute.
    { type: 'click', selector: '.update' },
    { type: 'expectAttribute', selector: '.forwarded', attribute: 'data-label', value: 'beta' },
    { type: 'expectAttribute', selector: '.badge', attribute: 'data-label', value: 'badge' },
    // Client-recreated branch: remove, re-create, then update again.
    { type: 'click', selector: '.toggle' },
    { type: 'expectHidden', selector: '.forwarded' },
    { type: 'click', selector: '.toggle' },
    { type: 'expectAttribute', selector: '.forwarded', attribute: 'data-label', value: 'beta' },
    { type: 'click', selector: '.update' },
    { type: 'expectAttribute', selector: '.forwarded', attribute: 'data-label', value: 'alpha' },
    { type: 'expectAttribute', selector: '.badge', attribute: 'data-label', value: 'badge' },
  ],
}

export const fixture = defineSharedFixture(spec)
