/**
 * CondArmTagCollision fixture (#2868) — source lives in the fixture-only
 * root (`fixtures/components/CondArmTagCollision.tsx`).
 *
 * The real-browser regression pin for #2868: a reactive conditional branch
 * whose FALSE-arm root tag (`<b>`, `<i>`) collides with the enclosing
 * `.map()`'s item param name (`b`) or a sibling branch's own root tag.
 * Before the fix, the branch's own re-render `template()` builder corrupted
 * that tag name into `<b()>`/`<i()>` — broken markup no CSS selector can
 * match — because the loop-param accessor rewrite ran as a regex over the
 * already-assembled HTML string instead of over parsed JS expression
 * positions. Clicking "Toggle" flips both rows' conditional to the branch
 * whose selector would fail to resolve if the corruption were still present.
 *
 * Snapshots in `__snapshots__/cond-arm-tag-collision.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * cond-arm-tag-collision`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'cond-arm-tag-collision',
  componentName: 'CondArmTagCollision',
  sourceRoot: 'fixture',
  description:
    'a reactive conditional branch whose root tag collides with the loop\'s item param name must not corrupt that tag on re-render (#2868)',
  interactions: [
    // Initial: on() === true.
    { type: 'expectText', selector: 'ul.eager li:nth-child(1) b.on', text: 'even 0' },
    { type: 'expectText', selector: 'ul.eager li:nth-child(2) b.on', text: 'even 1' },
    { type: 'expectText', selector: 'ul.lazy li:nth-child(1) .t', text: 'x' },
    { type: 'expectText', selector: 'ul.lazy li:nth-child(2) .t', text: 'y' },

    // Toggle: swaps to the FALSE branch — `<i class="off">` in the eager
    // row. If the branch's own re-render template were still corrupted to
    // `<i()>`, this selector would never resolve.
    { type: 'click', selector: '.toggle' },
    { type: 'expectText', selector: 'ul.eager li:nth-child(1) i.off', text: 'odd 0' },
    { type: 'expectText', selector: 'ul.eager li:nth-child(2) i.off', text: 'odd 1' },
    { type: 'expectText', selector: 'ul.lazy li:nth-child(1) .t', text: 'none' },
    { type: 'expectText', selector: 'ul.lazy li:nth-child(2) .t', text: 'none' },

    // Toggle back: swaps to the TRUE branch (`<b class="on">`) again.
    { type: 'click', selector: '.toggle' },
    { type: 'expectText', selector: 'ul.eager li:nth-child(1) b.on', text: 'even 0' },
    { type: 'expectText', selector: 'ul.lazy li:nth-child(1) .t', text: 'x' },
  ],
}

export const fixture = defineSharedFixture(spec)
