/**
 * A conditional-return component whose default branch is fragment-wrapped
 * while the other branch is a bare element — the shape the mutation sweep's
 * `fragment-wrap` mutant produces from `conditional-return-button` /
 * `button` / `kbd`, written out as real source so the divergence has a
 * fixture of its own instead of living only in `mutation-quarantine.ts`.
 *
 * Measured in a real browser (the `'three-point'` oracle and the
 * fixture-hydrate runner): SSR wraps the fragment-wrapped branch in a
 * `<!--bf-scope:…-->` comment pair, but `ComponentDef`'s `comment` /
 * `fragmentRoot` flags are decided once per component from
 * `ir.root.type === 'if-statement'` and cannot say "branch A is
 * fragment-rooted, branch B is not" — so hydration never claims that root
 * (no `bf-s`, the click does nothing), while a pure client mount
 * (`createComponent`, the `'csr-mount'` leg) renders it correctly. Registry
 * limitation `fragment-wrapped-conditional-return-branch-scope`; quarantined
 * against `'three-point'` in `oracle-quarantine.ts`. The interactions stop
 * at the initial state on purpose: a click step would fail the
 * fixture-hydrate runner (which has no quarantine) for exactly this reason.
 *
 * Snapshots in `__snapshots__/conditional-return-fragment-branch.{html,client.js}`
 * are regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts conditional-return-fragment-branch`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'conditional-return-fragment-branch',
  componentName: 'ConditionalReturnFragmentBranch',
  sourceRoot: 'fixture',
  description:
    'Conditional return whose default branch is fragment-wrapped — hydration never claims the branch root',
  props: {},
  interactions: [{ type: 'expectContains', selector: '.cr-button', text: 'button: 0' }],
}

export const fixture = defineSharedFixture(spec)
