/**
 * Real-browser regression test. Source lives in the fixture-only root
 * (`fixtures/components/ConditionalChildListenerCleanup.tsx`).
 *
 * A child component sits directly inside a reactive conditional branch
 * that is active at hydration, and registers a window listener in
 * `onMount` (removed in `onCleanup`). The child must be initialized once,
 * by its branch: one ping counts once, and the listener goes away with
 * the branch. It used to be initialized a second time by the component's
 * static child-init pass (against the SSR node the branch had just
 * re-rendered away), so each ping counted twice and one listener outlived
 * the branch.
 *
 * Snapshots in
 * `__snapshots__/conditional-child-listener-cleanup.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * conditional-child-listener-cleanup`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'conditional-child-listener-cleanup',
  componentName: 'ConditionalChildListenerCleanup',
  sourceRoot: 'fixture',
  description:
    'A child inside a reactive conditional branch that is active at hydration initializes once: its onMount listener counts each ping once and is removed with the branch',
  interactions: [
    { type: 'expectText', selector: '.count', text: '0 pings' },
    // One ping while mounted counts once (not twice: the child's onMount
    // must run once).
    { type: 'click', selector: '.ping' },
    { type: 'expectText', selector: '.count', text: '1 pings' },
    // Removing the branch must remove its listener: a ping afterwards
    // changes nothing.
    { type: 'click', selector: '.unmount' },
    { type: 'expectHidden', selector: '.listener' },
    { type: 'click', selector: '.ping' },
    { type: 'expectText', selector: '.count', text: '1 pings' },
  ],
}

export const fixture = defineSharedFixture(spec)
