/**
 * `createQuery` mode B (#3165): `initial` from an optional prop that is
 * absent. The value is `undefined` at SSR on every adapter, so the skeleton
 * branch renders, and in the browser the query sends its first request on
 * mount.
 *
 * Snapshots in `__snapshots__/create-query-optional-initial.{html,client.js}`
 * are regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts create-query-optional-initial`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'create-query-optional-initial',
  componentName: 'CreateQueryOptionalInitial',
  sourceRoot: 'fixture',
  description: 'createQuery with `initial` from an absent optional prop SSR-renders the skeleton and sends on mount',
  interactions: [
    { type: 'expectVisible', selector: '[data-slot="skeleton"]' },
    { type: 'expectFetchCount', urlIncludes: '/api/posts', count: 1 },
  ],
}

export const fixture = defineSharedFixture(spec)
