/**
 * `createQuery` mode A (#3165): `initial` from a required prop seeds the
 * value at SSR on every adapter, so the list is server-rendered. In the
 * browser the query sends nothing on mount; the action sends one request.
 *
 * Snapshots in `__snapshots__/create-query-initial.{html,client.js}` are
 * regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts create-query-initial`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'create-query-initial',
  componentName: 'CreateQueryInitial',
  sourceRoot: 'fixture',
  description: 'createQuery with `initial` from a required prop SSR-renders the list and sends no request on mount',
  props: {
    posts: [
      { id: 1, title: 'Alpha' },
      { id: 2, title: 'Beta' },
    ],
  },
  interactions: [
    { type: 'expectText', selector: 'li', text: 'Alpha' },
    { type: 'expectFetchCount', urlIncludes: '/api/posts', count: 0 },
    { type: 'click', selector: 'button' },
    { type: 'expectFetchCount', urlIncludes: '/api/posts', count: 1 },
  ],
}

export const fixture = defineSharedFixture(spec)
