/**
 * A `createMutation` form (#3210): `disabled={save.isPending()}` and an error
 * branch on `save.error()` render the enabled, no-error state at SSR on every
 * adapter. In the browser the mutation sends nothing on mount; clicking sends
 * one request, and the fixture server's 404 lands in the error branch.
 *
 * Snapshots in `__snapshots__/create-mutation-form.{html,client.js}` are
 * regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts create-mutation-form`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'create-mutation-form',
  componentName: 'CreateMutationForm',
  sourceRoot: 'fixture',
  description:
    'A createMutation form renders the enabled, no-error state at SSR (disabled={save.isPending()}, an error branch on save.error()) and sends only when the action is called',
  props: { postId: 1 },
  interactions: [
    { type: 'expectFetchCount', urlIncludes: '/api/posts/1/comments', count: 0 },
    { type: 'click', selector: 'button' },
    { type: 'expectFetchCount', urlIncludes: '/api/posts/1/comments', count: 1 },
    { type: 'expectText', selector: '[role="alert"]', text: 'Failed to save' },
  ],
}

export const fixture = defineSharedFixture(spec)
