/**
 * DataTable fixture lifted from `site/ui/components/data-table-demo.tsx`
 * (#1467 Phase 2e).
 *
 * `DataTablePreviewDemo` is the corpus's first **keyed-loop
 * reconciliation** probe: the table body is `sortedData().map(payment
 * => <TableRow key={payment.id}>…)`, where `sortedData` is a
 * `/* @client *​/`-sorted memo. Clicking a column header re-sorts the
 * memo and the runtime must *reorder* the five keyed rows in place —
 * the exact path where a broken keyed diff duplicates, drops, or
 * re-creates rows. Row-order assertions before AND after each sort
 * (first row + the amount cell of the would-be-last row) pin the
 * reorder; the row count is implied by asserting different rows into
 * the same positions across steps.
 *
 * The demo's sort cycle also has a deliberate quirk worth pinning:
 * clicking a *different* column while one is sorted RESETS to unsorted
 * (`handleSort` sets the key to null), so the Status leg first
 * observes the reset, then the actual status sort on the second click.
 *
 * This is also the first fixture whose demo source imports siblings
 * through the `@/components/ui/<name>` alias (`@/*` → `site/ui/dist/*`,
 * the built copies of the same ui sources) — exercising the
 * second-alias branch of the sibling inference.
 *
 * Snapshots in `__snapshots__/data-table.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * data-table`.
 */

import { defineDemoFixture, type SharedFixtureSpec } from './_helpers'

const cell = (row: number, col: number) =>
  `tbody tr:nth-child(${row}) td:nth-child(${col})`
// Header buttons: column 2 = Status, column 4 = Amount.
const statusHeader = 'thead th:nth-child(2) [data-slot="data-table-column-header"]'
const amountHeader = 'thead th:nth-child(4) [data-slot="data-table-column-header"]'

export const spec: SharedFixtureSpec = {
  id: 'data-table',
  componentName: 'DataTablePreviewDemo',
  sourceFile: 'data-table-demo',
  description:
    'site/ui DataTable demo — keyed-loop reorder on sort: column-header clicks resort the memo and the runtime reorders rows in place',
  interactions: [
    // Source order after hydration.
    { type: 'expectText', selector: cell(1, 1), text: 'PAY001' },
    { type: 'expectText', selector: cell(5, 1), text: 'PAY005' },
    // Amount ascending: 242, 316, 721, 837, 874.
    { type: 'click', selector: amountHeader },
    { type: 'expectText', selector: cell(1, 1), text: 'PAY002' },
    { type: 'expectText', selector: cell(1, 4), text: '$242.00' },
    { type: 'expectText', selector: cell(5, 1), text: 'PAY004' },
    { type: 'expectText', selector: cell(5, 4), text: '$874.00' },
    // Same column again: descending.
    { type: 'click', selector: amountHeader },
    { type: 'expectText', selector: cell(1, 1), text: 'PAY004' },
    { type: 'expectText', selector: cell(5, 1), text: 'PAY002' },
    // Different column while sorted: the demo's cycle RESETS to
    // unsorted first…
    { type: 'click', selector: statusHeader },
    { type: 'expectText', selector: cell(1, 1), text: 'PAY001' },
    { type: 'expectText', selector: cell(5, 1), text: 'PAY005' },
    // …and the second click applies the status sort (failed <
    // processing < success; stable within ties).
    { type: 'click', selector: statusHeader },
    { type: 'expectText', selector: cell(1, 1), text: 'PAY005' },
    { type: 'expectText', selector: cell(1, 2), text: 'failed' },
    { type: 'expectText', selector: cell(2, 1), text: 'PAY003' },
    { type: 'expectText', selector: cell(5, 1), text: 'PAY004' },
  ],
}

export const fixture = defineDemoFixture(spec)
