/**
 * DestructuredPropsLive fixture — lifted from
 * `integrations/shared/components/DestructuredPropsLive.tsx`.
 *
 * Move B's (#2760's follow-up) positive counterpart to
 * `props-reactivity-comparison`: a destructured-props child
 * (`function LiveChild({ value, label = 'none', onPick })`) whose every
 * downstream read of a destructured prop — plain text, a `createMemo`
 * computation, a `createEffect` body, an event handler argument, and a
 * reactive attribute (`data-label`, which also exercises the destructure
 * DEFAULT staying live) — tracks the parent's CURRENT value across
 * updates. Before Move B every one of those positions but the attribute
 * captured its value once at mount; `props-reactivity-comparison` still
 * pins that OLD behavior for `props.xxx` vs (pre-Move-B) destructured
 * access on a different component, so this fixture is deliberately
 * separate rather than a rewrite of that one.
 *
 * The `raw`/`memo`/`effect` updating together after ONE parent click is
 * the assertion a captured-once compiler cannot pass — before Move B,
 * `memo`/`effect` would stay frozen at their mount-time values while only
 * `raw` (a plain reactive-text position) tracked.
 *
 * Snapshots in `__snapshots__/destructured-props-live.{html,client.js}`
 * are regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * destructured-props-live`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const child = '.live-child'

export const spec: SharedFixtureSpec = {
  id: 'destructured-props-live',
  componentName: 'DestructuredPropsLive',
  sourceFile: 'DestructuredPropsLive',
  description:
    'A destructured-props child stays fully reactive across text/memo/effect/handler/attribute positions (Move B)',
  props: {},
  interactions: [
    // Initial: parent count = 1, label omitted → default 'none'.
    { type: 'expectContains', selector: '.parent-count', text: 'Count: 1' },
    { type: 'expectContains', selector: '.picked', text: 'Picked: 0' },
    { type: 'expectText', selector: `${child} .raw`, text: '1' },
    { type: 'expectText', selector: `${child} .memo`, text: '2' },
    { type: 'expectText', selector: `${child} .effect`, text: '1' },
    { type: 'expectAttribute', selector: child, attribute: 'data-label', value: 'none' },

    // Parent +1 → EVERY destructured-prop read updates together: raw,
    // memo (createMemo body reads `value`), and effect (createEffect
    // body reads `value` then calls `setSeen`). A captured-once compiler
    // fails exactly here — `raw` alone would update.
    { type: 'click', selector: '.btn-increment' },
    { type: 'expectContains', selector: '.parent-count', text: 'Count: 2' },
    { type: 'expectText', selector: `${child} .raw`, text: '2' },
    { type: 'expectText', selector: `${child} .memo`, text: '4' },
    { type: 'expectText', selector: `${child} .effect`, text: '2' },

    // Handler reads the LIVE destructured `value`, not the value at
    // mount: `onClick={() => onPick(value)}` must see 2, not 1.
    { type: 'click', selector: `${child} .btn-pick` },
    { type: 'expectContains', selector: '.picked', text: 'Picked: 2' },

    // Toggling the `named` signal flips the `label` prop between
    // `undefined` (destructure default `'none'` applies — live per
    // read, not just at mount) and `'named'`, live in the `data-label`
    // reactive-attribute binding.
    { type: 'click', selector: '.btn-name' },
    { type: 'expectAttribute', selector: child, attribute: 'data-label', value: 'named' },
    { type: 'click', selector: '.btn-name' },
    { type: 'expectAttribute', selector: child, attribute: 'data-label', value: 'none' },
  ],
}

export const fixture = defineSharedFixture(spec)
