/**
 * DestructuredPropsLive fixture — lifted from
 * `integrations/shared/components/DestructuredPropsLive.tsx`.
 *
 * Pins that every downstream read of a destructured prop stays live: plain
 * text, a `createMemo` computation, a `createEffect` body, an event handler
 * argument, and a reactive attribute (`data-label`, which also exercises the
 * destructure DEFAULT). `raw`/`memo`/`effect` moving together after ONE
 * parent click is the assertion a captured-once compiler cannot pass —
 * only `raw`, a plain reactive-text position, would track.
 *
 * Covers BOTH destructuring styles: `LiveChild` destructures in its
 * PARAMETER (`function LiveChild({ value })`); `BodyLiveChild` takes the
 * whole `props` object and destructures in its BODY
 * (`const { value } = props`) — the form #2934 fixed to read live the
 * same way. Both children are wired to the same `value`/`label`/`onPick`
 * source, so a click on either is independently observable against the
 * shared `picked` signal (clicking `.live-child`'s pick button, then
 * `.body-live-child`'s, must show two DIFFERENT `Picked:` values).
 *
 * `effect` starts at `0`, not `1`, for both children, because their effect
 * skips its own first run's write to keep hydration a no-op — see the
 * component.
 *
 * Snapshots in `__snapshots__/destructured-props-live.{html,client.js}`
 * are regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * destructured-props-live`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const paramChild = '.live-child'
const bodyChild = '.body-live-child'

export const spec: SharedFixtureSpec = {
  id: 'destructured-props-live',
  componentName: 'DestructuredPropsLive',
  sourceFile: 'DestructuredPropsLive',
  description:
    'Parameter- and body-destructured-props children both stay fully reactive across text/memo/effect/handler/attribute positions (#2934)',
  props: {},
  interactions: [
    // Initial: parent count = 1, label omitted → default 'none'. Both
    // children start identically.
    { type: 'expectContains', selector: '.parent-count', text: 'Count: 1' },
    { type: 'expectContains', selector: '.picked', text: 'Picked: 0' },
    { type: 'expectText', selector: `${paramChild} .raw`, text: '1' },
    { type: 'expectText', selector: `${paramChild} .memo`, text: '2' },
    { type: 'expectText', selector: `${paramChild} .effect`, text: '0' },
    { type: 'expectAttribute', selector: paramChild, attribute: 'data-label', value: 'none' },
    { type: 'expectText', selector: `${bodyChild} .raw`, text: '1' },
    { type: 'expectText', selector: `${bodyChild} .memo`, text: '2' },
    { type: 'expectText', selector: `${bodyChild} .effect`, text: '0' },
    { type: 'expectAttribute', selector: bodyChild, attribute: 'data-label', value: 'none' },

    // Parent +1 → EVERY destructured-prop read updates together, in BOTH
    // children: raw, memo (createMemo body reads `value`), and effect
    // (createEffect body reads `value` then calls `setSeen`). A
    // captured-once compiler fails exactly here — `raw` alone would update.
    { type: 'click', selector: '.btn-increment' },
    { type: 'expectContains', selector: '.parent-count', text: 'Count: 2' },
    { type: 'expectText', selector: `${paramChild} .raw`, text: '2' },
    { type: 'expectText', selector: `${paramChild} .memo`, text: '4' },
    { type: 'expectText', selector: `${paramChild} .effect`, text: '2' },
    { type: 'expectText', selector: `${bodyChild} .raw`, text: '2' },
    { type: 'expectText', selector: `${bodyChild} .memo`, text: '4' },
    { type: 'expectText', selector: `${bodyChild} .effect`, text: '2' },

    // Handler reads the LIVE destructured `value`, not the value at
    // mount: the parameter child's pick button must see 2, not 1.
    { type: 'click', selector: `${paramChild} .btn-pick` },
    { type: 'expectContains', selector: '.picked', text: 'Picked: 2' },

    // Parent +1 again → count is now 3, both children track it live.
    { type: 'click', selector: '.btn-increment' },
    { type: 'expectContains', selector: '.parent-count', text: 'Count: 3' },
    { type: 'expectText', selector: `${paramChild} .raw`, text: '3' },
    { type: 'expectText', selector: `${bodyChild} .raw`, text: '3' },

    // The BODY-destructured child's pick button reads the SAME live
    // `value` its parameter-form sibling does — a discriminating check
    // against the shared `picked` signal: it must now show 3, not the
    // stale 1 a captured-once body destructure would freeze at, and not
    // the 2 the OTHER child already wrote.
    { type: 'click', selector: `${bodyChild} .btn-pick` },
    { type: 'expectContains', selector: '.picked', text: 'Picked: 3' },

    // Toggling the `named` signal flips the `label` prop between
    // `undefined` (destructure default `'none'` applies — live per
    // read, not just at mount) and `'named'`, live in the `data-label`
    // reactive-attribute binding, for BOTH children.
    { type: 'click', selector: '.btn-name' },
    { type: 'expectAttribute', selector: paramChild, attribute: 'data-label', value: 'named' },
    { type: 'expectAttribute', selector: bodyChild, attribute: 'data-label', value: 'named' },
    { type: 'click', selector: '.btn-name' },
    { type: 'expectAttribute', selector: paramChild, attribute: 'data-label', value: 'none' },
    { type: 'expectAttribute', selector: bodyChild, attribute: 'data-label', value: 'none' },
  ],
}

export const fixture = defineSharedFixture(spec)
