/**
 * Native `<details open={...}>` fixture lifted from
 * `integrations/shared/components/DetailsFaq.tsx` (#2481).
 *
 * Fills a DOM-state-carrier gap: no shared fixture exercised a native
 * `<details>` before this — the only prior coverage was the static,
 * non-hydrating `details-open` conformance fixture (no `expectedClientJs`
 * / `interactions`). This one hydrates for real, so the oracle harness's
 * `dom-state.ts` vocabulary can capture and compare the live `open` IDL
 * property across SSR/hydrated/csr-mount renders.
 *
 * `expectHidden`/`expectVisible` on `.faq-body` lean on the browser's own
 * UA stylesheet (`details:not([open]) > :not(summary) { display: none }`,
 * always in effect regardless of the fixture-hydrate host page's
 * deliberately CSS-less body) rather than on any host-provided styling.
 *
 * Snapshots in `__snapshots__/details-shared.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * details-shared`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'details-shared',
  componentName: 'DetailsFaq',
  description: 'Native <details open={signal}> toggled by a click handler',
  interactions: [
    { type: 'expectHidden', selector: '.faq-body' },
    { type: 'click', selector: '.faq-summary' },
    { type: 'expectVisible', selector: '.faq-body' },
    { type: 'expectAttribute', selector: '.faq-details', attribute: 'open', value: '' },
    { type: 'click', selector: '.faq-summary' },
    { type: 'expectHidden', selector: '.faq-body' },
  ],
}

export const fixture = defineSharedFixture(spec)
