/**
 * Real-browser regression pin for the reactive runtime's diamond
 * propagation gap — landed as a fixture per CLAUDE.md's "a reproducible
 * defect lands as a fixture, not a prose report" rule, NOT a fix. Source
 * lives in the fixture-only root
 * (`fixtures/components/DiamondPropagation.tsx`).
 *
 * One signal (`a`) is read through two memos (`b`, `c`) by a single
 * effect. The runtime dispatches a write synchronously in subscription
 * order with no topological stage, so after one `setA` the effect runs
 * three times (once per memo recompute, once for its own subscription)
 * and its first re-run observes `b` updated while `c` is still stale. The
 * initial SSR render is correct (`expectedHtml`), and so is the DOM once
 * the handler returns — the gap is only visible to side-effecting
 * effects, which the component's `runs` / `glitches` counters surface.
 * The `interactions` below describe the CONTRACT (one run per write, no
 * half-updated snapshot) and currently FAIL; they are quarantined in
 * `packages/adapter-tests/e2e/fixture-hydrate-quarantine.ts` under the
 * `diamond-propagation-glitch` registry limitation
 * (`packages/adapter-tests/limitations/diamond-propagation-glitch.ts`).
 *
 * Snapshots in `__snapshots__/diamond-propagation.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * diamond-propagation`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'diamond-propagation',
  componentName: 'DiamondPropagation',
  sourceRoot: 'fixture',
  description:
    'An effect behind a diamond (one signal → two memos) runs once per write and never observes a half-updated memo pair (currently broken — quarantined)',
  interactions: [
    // Initial SSR/hydration state: a = 1, memos derived, no post-mount
    // effect run has been counted yet.
    { type: 'expectText', selector: '.a', text: '1' },
    { type: 'expectText', selector: '.b', text: '10' },
    { type: 'expectText', selector: '.c', text: '100' },
    { type: 'expectText', selector: '.runs', text: '0' },
    { type: 'expectText', selector: '.glitches', text: '0' },
    // One write. The settled DOM is correct on every runtime — `a`, `b`,
    // `c` all reflect the new value once the handler returns.
    { type: 'click', selector: '.btn-inc' },
    { type: 'expectText', selector: '.a', text: '2' },
    { type: 'expectText', selector: '.b', text: '20' },
    { type: 'expectText', selector: '.c', text: '200' },
    // The CONTRACT: one write → one effect run, and that run saw both
    // memos already recomputed. These two are the assertions that fail
    // today — `.runs` reads 3 and `.glitches` reads 1.
    { type: 'expectText', selector: '.runs', text: '1' },
    { type: 'expectText', selector: '.glitches', text: '0' },
  ],
}

export const fixture = defineSharedFixture(spec)
