/**
 * Real-browser regression test for glitch-free propagation through memos.
 * Source lives in the fixture-only root
 * (`fixtures/components/DiamondPropagation.tsx`).
 *
 * One signal (`a`) is read through two memos (`b`, `c`) by a single
 * effect. The runtime propagates a write in two phases — mark every
 * affected node, then bring each one up to date, pulling the memos it
 * reads first (`packages/client/src/reactive.ts`, "Propagation") — so
 * after one `setA` the effect runs exactly once and sees both memos
 * already recomputed. Before that, it ran three times per write (once per
 * memo recompute, once for its own subscription) and its first re-run
 * observed `b` updated while `c` was still stale. The settled DOM was
 * right either way; only side-effecting effects saw the difference, which
 * the component's `runs` / `glitches` counters surface.
 *
 * Snapshots in `__snapshots__/diamond-propagation.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * diamond-propagation`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'diamond-propagation',
  componentName: 'DiamondPropagation',
  sourceRoot: 'fixture',
  description:
    'An effect behind a diamond (one signal → two memos) runs once per write and never observes a half-updated memo pair',
  interactions: [
    // Initial SSR/hydration state: a = 1, memos derived, no post-mount
    // effect run has been counted yet.
    { type: 'expectText', selector: '.a', text: '1' },
    { type: 'expectText', selector: '.b', text: '10' },
    { type: 'expectText', selector: '.c', text: '100' },
    { type: 'expectText', selector: '.runs', text: '0' },
    { type: 'expectText', selector: '.glitches', text: '0' },
    // One write: `a`, `b`, `c` all reflect the new value once the handler
    // returns.
    { type: 'click', selector: '.btn-inc' },
    { type: 'expectText', selector: '.a', text: '2' },
    { type: 'expectText', selector: '.b', text: '20' },
    { type: 'expectText', selector: '.c', text: '200' },
    // The contract: one write → one effect run, and that run saw both
    // memos already recomputed (before the fix: `.runs` 3, `.glitches` 1).
    { type: 'expectText', selector: '.runs', text: '1' },
    { type: 'expectText', selector: '.glitches', text: '0' },
  ],
}

export const fixture = defineSharedFixture(spec)
