/**
 * DropdownMenu fixture lifted from
 * `site/ui/components/dropdown-menu-demo.tsx` (#1467 Phase 2d).
 *
 * `DropdownMenuCheckboxDemo` is picked over the basic demo because its
 * checkbox items carry observable state: each `aria-checked` is a
 * reactive prop binding fed by the demo's signals
 * (`checked={showStatus()}`), toggled by `onCheckedChange` — and
 * toggling must NOT close the menu (the demo's whole point), so the
 * steps interleave item toggles with content `data-state` assertions to
 * pin the stays-open behaviour. Closing happens via ESC at the end,
 * reusing the document-level-listener path `dialog`/`popover` probe.
 *
 * The two checkbox items have no distinguishing static attribute, so
 * they're addressed positionally among the portaled content's children
 * (label, separator, then the two items).
 *
 * Snapshots in `__snapshots__/dropdown-menu.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * dropdown-menu`.
 */

import { defineDemoFixture, type SharedFixtureSpec } from './_helpers'

const trigger = '[data-slot="dropdown-menu-trigger"]'
// `body >` pins the post-portal location (see dialog fixture).
const content = 'body > [data-slot="dropdown-menu-content"]'
// Content children: 1 = label, 2 = separator, 3 = Status Bar item,
// 4 = Activity Panel item.
const statusItem = `${content} > :nth-child(3)`
const activityItem = `${content} > :nth-child(4)`

export const spec: SharedFixtureSpec = {
  id: 'dropdown-menu',
  componentName: 'DropdownMenuCheckboxDemo',
  sourceFile: 'dropdown-menu-demo',
  description:
    'site/ui DropdownMenu demo — checkbox items toggle reactive aria-checked without closing the portaled menu',
  interactions: [
    // Closed after hydration, already portaled.
    { type: 'expectAttribute', selector: trigger, attribute: 'aria-expanded', value: 'false' },
    { type: 'expectAttribute', selector: content, attribute: 'data-state', value: 'closed' },
    // Open — initial signal values surface on the items.
    { type: 'click', selector: trigger },
    { type: 'expectAttribute', selector: content, attribute: 'data-state', value: 'open' },
    { type: 'expectAttribute', selector: statusItem, attribute: 'aria-checked', value: 'true' },
    { type: 'expectAttribute', selector: activityItem, attribute: 'aria-checked', value: 'false' },
    // Toggle Activity Panel on — menu must stay open.
    { type: 'click', selector: activityItem },
    { type: 'expectAttribute', selector: content, attribute: 'data-state', value: 'open' },
    { type: 'expectAttribute', selector: activityItem, attribute: 'aria-checked', value: 'true' },
    { type: 'expectAttribute', selector: statusItem, attribute: 'aria-checked', value: 'true' },
    // Toggle Status Bar off — independent signals, still open.
    { type: 'click', selector: statusItem },
    { type: 'expectAttribute', selector: content, attribute: 'data-state', value: 'open' },
    { type: 'expectAttribute', selector: statusItem, attribute: 'aria-checked', value: 'false' },
    { type: 'expectAttribute', selector: activityItem, attribute: 'aria-checked', value: 'true' },
    // ESC closes; the toggled state survives the close.
    { type: 'press', selector: 'body', key: 'Escape' },
    { type: 'expectAttribute', selector: content, attribute: 'data-state', value: 'closed' },
    { type: 'expectAttribute', selector: trigger, attribute: 'aria-expanded', value: 'false' },
  ],
}

export const fixture = defineDemoFixture(spec)
