/**
 * Form fixture lifted from `integrations/shared/components/Form.tsx`.
 *
 * Exercises **reactive boolean & enumerated attribute bindings** in a
 * single-signal component:
 *   - `data-state={accepted() ? 'checked' : 'unchecked'}` — string value
 *     swap on the checkbox button
 *   - `aria-checked={accepted()}` — boolean attribute stringified
 *   - `disabled={!accepted()}` — boolean attribute on the submit button
 *
 * Beyond conditional-return (which covered a single reactive
 * `data-active` attribute), this fixture verifies multiple reactive
 * attributes update coherently from the same signal across two different
 * elements (the checkbox and the submit button).
 *
 * Snapshots in `__snapshots__/form.{html,client.js}` are regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts form`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'form',
  componentName: 'Form',
  description:
    'Terms-acceptance form — reactive data-state / aria-checked / disabled from one signal',
  props: {},
  interactions: [
    // Initial state: accepted = false → checkbox unchecked, submit disabled.
    {
      type: 'expectAttribute',
      selector: '.checkbox',
      attribute: 'data-state',
      value: 'unchecked',
    },
    {
      type: 'expectAttribute',
      selector: '.checkbox',
      attribute: 'aria-checked',
      value: 'false',
    },

    // Click checkbox → all three reactive attrs flip together.
    { type: 'click', selector: '.checkbox' },
    {
      type: 'expectAttribute',
      selector: '.checkbox',
      attribute: 'data-state',
      value: 'checked',
    },
    {
      type: 'expectAttribute',
      selector: '.checkbox',
      attribute: 'aria-checked',
      value: 'true',
    },

    // Click again → back to unchecked, attributes revert.
    { type: 'click', selector: '.checkbox' },
    {
      type: 'expectAttribute',
      selector: '.checkbox',
      attribute: 'data-state',
      value: 'unchecked',
    },
    {
      type: 'expectAttribute',
      selector: '.checkbox',
      attribute: 'aria-checked',
      value: 'false',
    },
  ],
}

export const fixture = defineSharedFixture(spec)
