/**
 * Real-browser regression test for #3355. Source lives in the fixture-only
 * root (`fixtures/components/FragmentChildInConditional.tsx`).
 *
 * A conditional branch renders a stateless transparent-fragment child
 * (`<>{children}</>`). SSR gives the passed-through element no scope marker,
 * and hydration used to stamp `bf-s` / `bf-h` / `bf-m` onto it, so the
 * oracle's SSR-vs-hydrated check failed. The `snap` and `three-point` oracles
 * pin SSR ≡ hydrated ≡ csr-mount. The interactions toggle the branch off
 * and on again.
 *
 * Snapshots in `__snapshots__/fragment-child-in-conditional.{html,client.js}`
 * are regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * fragment-child-in-conditional`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'fragment-child-in-conditional',
  componentName: 'FragmentChildInConditional',
  sourceRoot: 'fixture',
  description:
    'A stateless transparent-fragment child inside a conditional branch hydrates without gaining scope markers and toggles off and on',
  interactions: [
    { type: 'expectText', selector: 'mark.m', text: 'value' },
    { type: 'click', selector: 'button.toggle' },
    { type: 'expectHidden', selector: 'mark.m' },
    { type: 'click', selector: 'button.toggle' },
    { type: 'expectText', selector: 'mark.m', text: 'value' },
  ],
}

export const fixture = defineSharedFixture(spec)
