/**
 * Input fixture lifted from `ui/components/ui/input/index.tsx` (#1467
 * Phase 2b).
 *
 * `Input` is a thin pass-through wrapper (`{...props}` spread, no internal
 * signal), so this fixture's value is confirming the runtime hydrates a
 * native form control without tearing down its DOM or stealing user input:
 * after hydration, typing into the field updates and retains the value.
 *
 * Snapshots in `__snapshots__/input.{html,client.js}` are regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts input`.
 */

import { defineUiFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'input',
  componentName: 'Input',
  sourceFile: 'input',
  description: 'site/ui Input — native text field survives hydration + accepts typing',
  // `className: ''` is passed explicitly for the same reason as `button`:
  // the CSR template emits raw `_p.className` and does not apply the
  // component's destructured `className = ''` default, so without it the
  // CSR render diverges from SSR with a literal `undefined` in the class.
  props: { type: 'text', placeholder: 'Enter your name', className: '' },
  interactions: [
    { type: 'expectValue', selector: 'input', value: '' },
    { type: 'fill', selector: 'input', value: 'Barefoot' },
    { type: 'expectValue', selector: 'input', value: 'Barefoot' },
  ],
}

export const fixture = defineUiFixture(spec)
