/**
 * Kbd fixture lifted from `ui/components/ui/kbd/index.tsx` (#1467
 * Phase 2b).
 *
 * Like `label`, a static helper that ships **no** `interactions` to cover
 * the runner's `interactions: undefined` skip path. It additionally
 * imports `Slot` from `../slot` (used only on the `asChild` branch), so the
 * sibling is auto-inferred — keeping the static-helper corpus honest about
 * sibling resolution even when the component itself is inert.
 *
 * Snapshots in `__snapshots__/kbd.{html,client.js}` are regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts kbd`.
 */

import { defineUiFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'kbd',
  componentName: 'Kbd',
  sourceFile: 'kbd',
  description: 'site/ui Kbd — static helper with Slot sibling, no interactions (skip-path coverage)',
  props: { className: '', children: 'K' },
  // No `interactions`: verifies the runner's undefined-interactions skip path.
}

export const fixture = defineUiFixture(spec)
