/**
 * KeyedLoopPureIndexReorder fixture (#2861) — source lives in the
 * fixture-only root (`fixtures/components/KeyedLoopPureIndexReorder.tsx`),
 * alongside the other `.map()`-index regression pins.
 *
 * The real-browser regression pin for #2861: a keyed `.map()` row whose
 * badge text (`{i}`) and `class` (`i % 2 === 0 ? … : …`) are derived
 * PURELY from the row's own index — no signal read, no function call
 * anywhere in either expression. Clicking "Rotate" reorders the SAME THREE
 * keyed rows (moves the first to the back) without creating or destroying
 * any of them — exactly the path where a never-wired index effect goes
 * stale.
 *
 * Snapshots in
 * `__snapshots__/keyed-loop-pure-index-reorder.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * keyed-loop-pure-index-reorder`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const li = (n: number) => `ul li:nth-child(${n})` as const
const badge = (n: number) => `ul li:nth-child(${n}) .badge` as const
const label = (n: number) => `ul li:nth-child(${n}) .label` as const

export const spec: SharedFixtureSpec = {
  id: 'keyed-loop-pure-index-reorder',
  componentName: 'KeyedLoopPureIndexReorder',
  sourceRoot: 'fixture',
  description:
    'keyed .map() row with a badge text and class derived purely from the row\'s own index (no signal, no function call) — a same-key reorder must still update both (#2861)',
  interactions: [
    { type: 'expectText', selector: label(1), text: 'Alpha' },
    { type: 'expectText', selector: badge(1), text: '0' },
    { type: 'expectAttribute', selector: li(1), attribute: 'class', value: 'even' },
    { type: 'expectText', selector: label(2), text: 'Bravo' },
    { type: 'expectText', selector: badge(2), text: '1' },
    { type: 'expectAttribute', selector: li(2), attribute: 'class', value: 'odd' },
    { type: 'expectText', selector: label(3), text: 'Charlie' },
    { type: 'expectText', selector: badge(3), text: '2' },
    { type: 'expectAttribute', selector: li(3), attribute: 'class', value: 'even' },

    // Rotate: Alpha (same key, same DOM node) moves to the back. A frozen
    // (non-reactive) index would leave every badge/class exactly as above.
    { type: 'click', selector: '.rotate' },
    { type: 'expectText', selector: label(1), text: 'Bravo' },
    { type: 'expectText', selector: badge(1), text: '0' },
    { type: 'expectAttribute', selector: li(1), attribute: 'class', value: 'even' },
    { type: 'expectText', selector: label(2), text: 'Charlie' },
    { type: 'expectText', selector: badge(2), text: '1' },
    { type: 'expectAttribute', selector: li(2), attribute: 'class', value: 'odd' },
    { type: 'expectText', selector: label(3), text: 'Alpha' },
    { type: 'expectText', selector: badge(3), text: '2' },
    { type: 'expectAttribute', selector: li(3), attribute: 'class', value: 'even' },

    // Rotate again: full cycle.
    { type: 'click', selector: '.rotate' },
    { type: 'expectText', selector: label(1), text: 'Charlie' },
    { type: 'expectText', selector: badge(1), text: '0' },
    { type: 'expectAttribute', selector: li(1), attribute: 'class', value: 'even' },
    { type: 'expectText', selector: label(2), text: 'Alpha' },
    { type: 'expectText', selector: badge(2), text: '1' },
    { type: 'expectAttribute', selector: li(2), attribute: 'class', value: 'odd' },
    { type: 'expectText', selector: label(3), text: 'Bravo' },
    { type: 'expectText', selector: badge(3), text: '2' },
    { type: 'expectAttribute', selector: li(3), attribute: 'class', value: 'even' },
  ],
}

export const fixture = defineSharedFixture(spec)
