/**
 * KeyedLoopIndexReorder fixture (#2859) — source lives in the fixture-only
 * root (`fixtures/components/KeyedLoopIndexReorder.tsx`), joining
 * `preamble-cells` / `multi-root-fragment` there (no particular reason to
 * keep it out of `integrations/shared/components`, but this keeps every
 * `.map()`-index regression pin together with its siblings).
 *
 * The real-browser regression pin for #2859: a keyed `.map()` row whose
 * badge text (`{String(i + 1)}`) and `class` (`selected() === i`) both
 * depend on the row's OWN INDEX, while the row's `key` tracks the
 * underlying item. Clicking "Rotate" reorders the SAME THREE keyed rows
 * (moves the first to the back) without creating or destroying any of
 * them — exactly the path where a frozen (non-reactive) index goes stale.
 *
 * `selected` never changes here; what moves is which row now SITS at
 * index 0. Before the fix, the "selected" class stayed glued to whichever
 * row was originally created at position 0 (Alpha) forever, and every
 * row's badge kept its original number — both wrong after a reorder.
 *
 * Snapshots in `__snapshots__/keyed-loop-index-reorder.{html,client.js}`
 * are regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * keyed-loop-index-reorder`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const li = (n: number) => `ul li:nth-child(${n})` as const
const badge = (n: number) => `ul li:nth-child(${n}) .badge` as const
const label = (n: number) => `ul li:nth-child(${n}) .label` as const

export const spec: SharedFixtureSpec = {
  id: 'keyed-loop-index-reorder',
  componentName: 'KeyedLoopIndexReorder',
  sourceRoot: 'fixture',
  description:
    'keyed .map() row with index-derived badge text and class — a same-key reorder must update both to the row\'s CURRENT position (#2859)',
  interactions: [
    // Initial order: Alpha=1 (selected, index 0), Bravo=2, Charlie=3.
    { type: 'expectText', selector: label(1), text: 'Alpha' },
    { type: 'expectText', selector: badge(1), text: '1' },
    { type: 'expectAttribute', selector: li(1), attribute: 'class', value: 'row selected' },
    { type: 'expectText', selector: label(2), text: 'Bravo' },
    { type: 'expectText', selector: badge(2), text: '2' },
    { type: 'expectAttribute', selector: li(2), attribute: 'class', value: 'row' },
    { type: 'expectText', selector: label(3), text: 'Charlie' },
    { type: 'expectText', selector: badge(3), text: '3' },
    { type: 'expectAttribute', selector: li(3), attribute: 'class', value: 'row' },

    // Rotate: Alpha (same key, same DOM node) moves to the back. `selected`
    // itself never changes — but the row now AT index 0 is Bravo, so Bravo
    // must pick up both the "1" badge and the selected class; Alpha must
    // lose the class and show "3". A frozen (non-reactive) index would
    // leave the badges unchanged and the class stuck on Alpha.
    { type: 'click', selector: '.rotate' },
    { type: 'expectText', selector: label(1), text: 'Bravo' },
    { type: 'expectText', selector: badge(1), text: '1' },
    { type: 'expectAttribute', selector: li(1), attribute: 'class', value: 'row selected' },
    { type: 'expectText', selector: label(2), text: 'Charlie' },
    { type: 'expectText', selector: badge(2), text: '2' },
    { type: 'expectAttribute', selector: li(2), attribute: 'class', value: 'row' },
    { type: 'expectText', selector: label(3), text: 'Alpha' },
    { type: 'expectText', selector: badge(3), text: '3' },
    { type: 'expectAttribute', selector: li(3), attribute: 'class', value: 'row' },

    // Rotate again: full cycle. Charlie now sits at index 0.
    { type: 'click', selector: '.rotate' },
    { type: 'expectText', selector: label(1), text: 'Charlie' },
    { type: 'expectText', selector: badge(1), text: '1' },
    { type: 'expectAttribute', selector: li(1), attribute: 'class', value: 'row selected' },
    { type: 'expectText', selector: label(2), text: 'Alpha' },
    { type: 'expectText', selector: badge(2), text: '2' },
    { type: 'expectAttribute', selector: li(2), attribute: 'class', value: 'row' },
    { type: 'expectText', selector: label(3), text: 'Bravo' },
    { type: 'expectText', selector: badge(3), text: '3' },
    { type: 'expectAttribute', selector: li(3), attribute: 'class', value: 'row' },
  ],
}

export const fixture = defineSharedFixture(spec)
