/**
 * Label fixture lifted from `ui/components/ui/label/index.tsx` (#1467
 * Phase 2b).
 *
 * A static helper with no reactive state. It deliberately ships **no**
 * `interactions`, so the fixture-hydrate runner's guard
 * (`if (!fixture.interactions || ...) continue`) skips it — exercising the
 * `interactions: undefined` skip path the phase calls out. Its real
 * coverage is at the adapter-conformance + CSR layers (template HTML +
 * client-JS DOM), where it still participates via the corpus.
 *
 * Snapshots in `__snapshots__/label.{html,client.js}` are regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts label`.
 */

import { defineUiFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'label',
  componentName: 'Label',
  sourceFile: 'label',
  description: 'site/ui Label — static helper, no interactions (skip-path coverage)',
  props: { className: '', children: 'Email' },
  // No `interactions`: verifies the runner's undefined-interactions skip path.
}

export const fixture = defineUiFixture(spec)
