/**
 * LazyRowIndexReorder fixture (#2859 follow-on) — source lives in the
 * fixture-only root (`fixtures/components/LazyRowIndexReorder.tsx`), joining
 * `keyed-loop-index-reorder` there.
 *
 * The real-browser regression pin for the lazy-row-graph widening: a keyed
 * `.map()` row with no per-row imperative content (no ref, no child
 * component, no inner loop) whose text depends on its OWN INDEX stays on the
 * lazy `mapArrayLazy` path (`lazy-row-eligibility.ts` no longer refuses it
 * for referencing the index) AND still updates correctly across a same-key
 * reorder — the runtime tracks each row's current position on `entry.index`
 * and calls `applyItem` on a pure reorder (`LazyRowPlan.indexDriven`).
 *
 * Snapshots in `__snapshots__/lazy-row-index-reorder.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * lazy-row-index-reorder`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const badge = (n: number) => `ul li:nth-child(${n}) .badge` as const
const label = (n: number) => `ul li:nth-child(${n}) .label` as const

export const spec: SharedFixtureSpec = {
  id: 'lazy-row-index-reorder',
  componentName: 'LazyRowIndexReorder',
  sourceRoot: 'fixture',
  description:
    'keyed .map() row with index-derived text and no per-row imperative content — stays on the lazy row graph and still updates across a same-key reorder (#2859 follow-on)',
  interactions: [
    // Initial order: Alpha=1, Bravo=2, Charlie=3.
    { type: 'expectText', selector: label(1), text: 'Alpha' },
    { type: 'expectText', selector: badge(1), text: '1' },
    { type: 'expectText', selector: label(2), text: 'Bravo' },
    { type: 'expectText', selector: badge(2), text: '2' },
    { type: 'expectText', selector: label(3), text: 'Charlie' },
    { type: 'expectText', selector: badge(3), text: '3' },

    // Rotate: Alpha (same key, same DOM node) moves to the back. A frozen
    // (non-reactive) index would leave every badge unchanged.
    { type: 'click', selector: '.rotate' },
    { type: 'expectText', selector: label(1), text: 'Bravo' },
    { type: 'expectText', selector: badge(1), text: '1' },
    { type: 'expectText', selector: label(2), text: 'Charlie' },
    { type: 'expectText', selector: badge(2), text: '2' },
    { type: 'expectText', selector: label(3), text: 'Alpha' },
    { type: 'expectText', selector: badge(3), text: '3' },

    // Rotate again: full cycle. Charlie now sits at index 0.
    { type: 'click', selector: '.rotate' },
    { type: 'expectText', selector: label(1), text: 'Charlie' },
    { type: 'expectText', selector: badge(1), text: '1' },
    { type: 'expectText', selector: label(2), text: 'Alpha' },
    { type: 'expectText', selector: badge(2), text: '2' },
    { type: 'expectText', selector: label(3), text: 'Bravo' },
    { type: 'expectText', selector: badge(3), text: '3' },
  ],
}

export const fixture = defineSharedFixture(spec)
