/**
 * Real-browser regression pin for #3107 — landed as a fixture per
 * CLAUDE.md's "a reproducible defect lands as a fixture, not a prose
 * report" rule, NOT a fix. Source lives in the fixture-only root
 * (`fixtures/components/LoopRowChildChildrenAttrs.tsx`).
 *
 * A `.map()` loop row calls a child component (`Chip`) passing a JSX
 * element as `children`; that element has its own reactive `href` /
 * `data-current` attributes keyed off the row's item against an outer
 * signal. The initial SSR render is correct (`expectedHtml` below), but
 * after a signal update the `<a>`'s attributes never patch — no compiler
 * diagnostic, no runtime error, the DOM just goes stale. The `interactions`
 * below describe the CORRECT post-click state and currently FAIL; they
 * are quarantined in
 * `packages/adapter-tests/e2e/fixture-hydrate-quarantine.ts` under the
 * `loop-row-child-children-attrs-frozen` registry limitation
 * (`packages/adapter-tests/limitations/loop-row-child-children-attrs-frozen.ts`).
 *
 * Snapshots in
 * `__snapshots__/loop-row-child-children-attrs.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * loop-row-child-children-attrs`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const anchor = (n: number) => `div > span:nth-child(${n}) > a` as const
const toggle = '.toggle'

export const spec: SharedFixtureSpec = {
  id: 'loop-row-child-children-attrs',
  componentName: 'LoopRowChildChildrenAttrs',
  sourceRoot: 'fixture',
  description:
    'A loop-row child component\'s JSX `children` element keeps its own reactive attrs patched after a signal update (#3107, currently broken — quarantined)',
  interactions: [
    // Initial SSR/hydration state: `active` defaults to 'a', so the first
    // chip's anchor is "current" and the second is not.
    { type: 'expectAttribute', selector: anchor(1), attribute: 'href', value: '/current' },
    { type: 'expectAttribute', selector: anchor(1), attribute: 'data-current', value: 'true' },
    { type: 'expectAttribute', selector: anchor(2), attribute: 'href', value: '/other/b' },
    { type: 'expectAttribute', selector: anchor(2), attribute: 'data-current', value: 'false' },
    // Click flips the signal to 'b' — the CORRECT behavior swaps which
    // row's anchor is "current". This is the assertion that currently
    // fails: the compiler never emits an effect for these attributes at
    // all, so both anchors stay frozen at their SSR values.
    { type: 'click', selector: toggle },
    { type: 'expectAttribute', selector: anchor(1), attribute: 'href', value: '/other/a' },
    { type: 'expectAttribute', selector: anchor(1), attribute: 'data-current', value: 'false' },
    { type: 'expectAttribute', selector: anchor(2), attribute: 'href', value: '/current' },
    { type: 'expectAttribute', selector: anchor(2), attribute: 'data-current', value: 'true' },
  ],
}

export const fixture = defineSharedFixture(spec)
