/**
 * A `.map()` row calling a stateless, fragment-rooted child component (the
 * template-only registration path). Source lives in the fixture-only root
 * (`fixtures/components/LoopRowFragmentRootChild.tsx`).
 *
 * SSR scopes each row's child with a `<!--bf-scope:-->` comment pair and no
 * `bf-s` on its `<span>`; hydration keeps that. The CSR-mount leg of the
 * real-browser `three-point` / `idempotence` oracles must render the same,
 * which needs the child's template-only `hydrate()` def to declare
 * `comment` / `fragmentRoot` like an init-bearing component's does.
 *
 * Snapshots in `__snapshots__/loop-row-fragment-root-child.{html,client.js}`
 * are regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts loop-row-fragment-root-child`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'loop-row-fragment-root-child',
  componentName: 'LoopRowFragmentRootChild',
  sourceRoot: 'fixture',
  description:
    'a .map() row calls a stateless fragment-rooted child; CSR mount scopes it with a comment pair like SSR (no bf-s on the child element)',
  interactions: [
    { type: 'expectAttribute', selector: 'span:nth-of-type(1) > b', attribute: 'data-current', value: 'true' },
    { type: 'expectAttribute', selector: 'span:nth-of-type(2) > b', attribute: 'data-current', value: 'false' },
    { type: 'click', selector: '.toggle' },
    { type: 'expectAttribute', selector: 'span:nth-of-type(1) > b', attribute: 'data-current', value: 'false' },
    { type: 'expectAttribute', selector: 'span:nth-of-type(2) > b', attribute: 'data-current', value: 'true' },
  ],
}

export const fixture = defineSharedFixture(spec)
