/**
 * MultiRootFragment fixture (#2735) — source lives in the fixture-only
 * root (`fixtures/components/MultiRootFragment.tsx`), joining
 * `branch-root-prop-attr` / `preamble-cells` / `tag-cloud` there.
 *
 * The real-browser regression pin for a genuine multi-root fragment
 * component mounted through the real `createComponent()` CSR path (the
 * `'three-point'` / `'idempotence'` oracles in `oracle.playwright.ts`,
 * which boot `fixture-host.ts`'s `'csr-mount'` host mode) rather than the
 * Bun-side template-string mock `csr-render.ts` uses. `fragment.ts`
 * already proves the SAME shape server-renders and cross-adapter
 * conforms correctly (`fixture.ts`'s `FragmentDemo`) — this fixture picks
 * up exactly where that one stops, at the runtime DOM-materialization
 * step `parseHTML(...).firstChild` (`@barefootjs/client/runtime/
 * component.ts`) used to silently truncate to.
 *
 * `snap` (deferred SSR vs hydrated) passes regardless: hydration never
 * goes through `materializeComponent`'s bare-`createComponent()` path —
 * only a from-scratch client mount with no SSR input does. `three-point`
 * and `idempotence` are this fixture's real coverage of that path, fixed
 * in the same change that added this fixture (component.ts's step 6).
 *
 * Snapshots in `__snapshots__/multi-root-fragment.{html,client.js}` are
 * regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts multi-root-fragment`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'multi-root-fragment',
  componentName: 'MultiRootFragment',
  sourceRoot: 'fixture',
  description:
    'genuine multi-root fragment component (two top-level roots, no loop) — CSR mount must materialize every root, not just the first (#2735)',
  interactions: [
    { type: 'expectText', selector: 'h1', text: 'title' },
    { type: 'expectText', selector: 'p', text: '0' },
    { type: 'click', selector: 'p' },
    { type: 'expectText', selector: 'p', text: '1' },
  ],
}

export const fixture = defineSharedFixture(spec)
