/**
 * NestedLoopOuterIndexReorder fixture (#2861) — source lives in the
 * fixture-only root
 * (`fixtures/components/NestedLoopOuterIndexReorder.tsx`).
 *
 * The real-browser regression pin for the nested half of #2861: a `.map()`
 * nested inside another `.map()`'s JSX body, whose row reads the OUTER
 * loop's own index parameter (not its own index, and not the outer item).
 * Rotating the OUTER array (same keys, reordered) must update every
 * group's inner index display to its CURRENT position.
 *
 * Snapshots in
 * `__snapshots__/nested-loop-outer-index-reorder.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * nested-loop-outer-index-reorder`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const groupIndex = (n: number) => `.groups > li:nth-child(${n}) .group-index` as const
const label = (n: number) => `.groups > li:nth-child(${n}) .label` as const

export const spec: SharedFixtureSpec = {
  id: 'nested-loop-outer-index-reorder',
  componentName: 'NestedLoopOuterIndexReorder',
  sourceRoot: 'fixture',
  description:
    'a nested .map() row reading the OUTER loop\'s own index must follow the outer group\'s current position after a same-key reorder (#2861)',
  interactions: [
    { type: 'expectText', selector: groupIndex(1), text: '0' },
    { type: 'expectText', selector: label(1), text: 'one' },
    { type: 'expectText', selector: groupIndex(2), text: '1' },
    { type: 'expectText', selector: label(2), text: 'two' },
    { type: 'expectText', selector: groupIndex(3), text: '2' },
    { type: 'expectText', selector: label(3), text: 'three' },

    // Rotate: group 1 (same key, same DOM node) moves to the back. Its
    // inner "group-index" display must follow, not stay frozen at 0.
    { type: 'click', selector: '.rotate' },
    { type: 'expectText', selector: groupIndex(1), text: '0' },
    { type: 'expectText', selector: label(1), text: 'two' },
    { type: 'expectText', selector: groupIndex(2), text: '1' },
    { type: 'expectText', selector: label(2), text: 'three' },
    { type: 'expectText', selector: groupIndex(3), text: '2' },
    { type: 'expectText', selector: label(3), text: 'one' },

    { type: 'click', selector: '.rotate' },
    { type: 'expectText', selector: groupIndex(1), text: '0' },
    { type: 'expectText', selector: label(1), text: 'three' },
    { type: 'expectText', selector: groupIndex(2), text: '1' },
    { type: 'expectText', selector: label(2), text: 'one' },
    { type: 'expectText', selector: groupIndex(3), text: '2' },
    { type: 'expectText', selector: label(3), text: 'two' },
  ],
}

export const fixture = defineSharedFixture(spec)
