/**
 * NestedCondToggleList fixture lifted from
 * `integrations/shared/components/NestedCondToggleList.tsx` (#2347).
 *
 * Regression coverage for a compiler bug where an element sitting inside a
 * per-item conditional (`item.hidden ? null : <button/>`) AND carrying its
 * own dynamic attribute + event handler got bound twice: once directly
 * against the loop item's own initial template clone, once again inside
 * the conditional's `insert()` bindEvents against whatever node it mounts.
 * At runtime this meant a single click fired its handler twice (toggling
 * state on then immediately back off) and the `className` effect was left
 * pointed at a detached node (stopped updating after the first branch swap).
 *
 * The interaction sequence below fails on either regression:
 *   - a double-bound click handler would toggle 'Off' -> 'Off' (fires twice)
 *     instead of 'Off' -> 'On' on the first click
 *   - an orphaned class effect would leave `class="toggle-btn"` after the
 *     click even though the text correctly updated to 'On'
 *
 * Snapshots in `__snapshots__/nested-cond-toggle-list.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * nested-cond-toggle-list`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'nested-cond-toggle-list',
  componentName: 'NestedCondToggleList',
  description:
    'Per-item conditional wrapping an element with dynamic className + onClick binds exactly once (#2347)',
  props: {
    items: [
      { id: 'a', hidden: false, active: false },
      { id: 'b', hidden: true, active: false },
    ],
  },
  interactions: [
    { type: 'expectText', selector: '[data-testid="toggle-a"]', text: 'Off' },
    {
      type: 'expectAttribute',
      selector: '[data-testid="toggle-a"]',
      attribute: 'class',
      value: 'toggle-btn',
    },
    { type: 'expectHidden', selector: '[data-testid="toggle-b"]' },
    { type: 'click', selector: '[data-testid="toggle-a"]' },
    { type: 'expectText', selector: '[data-testid="toggle-a"]', text: 'On' },
    {
      type: 'expectAttribute',
      selector: '[data-testid="toggle-a"]',
      attribute: 'class',
      value: 'toggle-btn on',
    },
    { type: 'click', selector: '[data-testid="toggle-a"]' },
    { type: 'expectText', selector: '[data-testid="toggle-a"]', text: 'Off' },
    {
      type: 'expectAttribute',
      selector: '[data-testid="toggle-a"]',
      attribute: 'class',
      value: 'toggle-btn',
    },
  ],
}

export const fixture = defineSharedFixture(spec)
