/**
 * NestedLoopIndependentSignal fixture (#2865) — source lives in the
 * fixture-only root (`fixtures/components/NestedLoopIndependentSignal.tsx`),
 * alongside the other `.map()`-reactivity regression pins.
 *
 * The real-browser regression pin for #2865: a nested `.map()` whose array
 * (`tags()`) does not reference the outer loop's item (`row`) at all. Before
 * the fix, the compiler classified such a loop "static" and emitted a
 * hydration-only `forEach` with no `mapArray`/`createEffect` — clicking
 * "Add tag" updated the `tags` signal but neither row's tag list ever grew.
 *
 * Snapshots in `__snapshots__/nested-loop-independent-signal.{html,client.js}`
 * are regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * nested-loop-independent-signal`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const rowTag = (row: number, tag: number) => `.rows > li:nth-child(${row}) .tags li:nth-child(${tag})` as const

export const spec: SharedFixtureSpec = {
  id: 'nested-loop-independent-signal',
  componentName: 'NestedLoopIndependentSignal',
  sourceRoot: 'fixture',
  description:
    'a nested .map() whose array does not reference the outer loop\'s item must still reconcile reactively (#2865)',
  interactions: [
    // Both rows start with the same two tags, shared from one independent signal.
    { type: 'expectText', selector: rowTag(1, 1), text: 'a' },
    { type: 'expectText', selector: rowTag(1, 2), text: 'b' },
    { type: 'expectText', selector: rowTag(2, 1), text: 'a' },
    { type: 'expectText', selector: rowTag(2, 2), text: 'b' },

    // Adding a tag must grow the list in BOTH rows — the old bug baked the
    // tag list once per row at creation and never revisited it.
    { type: 'click', selector: '.add-tag' },
    { type: 'expectText', selector: rowTag(1, 3), text: 'c' },
    { type: 'expectText', selector: rowTag(2, 3), text: 'c' },

    { type: 'click', selector: '.add-tag' },
    { type: 'expectText', selector: rowTag(1, 4), text: 'd' },
    { type: 'expectText', selector: rowTag(2, 4), text: 'd' },
  ],
}

export const fixture = defineSharedFixture(spec)
