/**
 * An attribute bound to an `undefined`-valued signal is omitted in SSR, the
 * CSR template and the hydrated page, for both the zero-arg
 * `createSignal<T>()` (#3215) and an explicit `undefined` initial value. A
 * click then sets both attributes.
 *
 * Snapshots in `__snapshots__/nullish-signal-attr.{html,client.js}` are
 * regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts nullish-signal-attr`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'nullish-signal-attr',
  componentName: 'NullishSignalAttr',
  sourceRoot: 'fixture',
  description: 'an attribute bound to an undefined-valued signal is omitted, for a zero-arg createSignal<T>() and an explicit undefined (#3215)',
  interactions: [
    { type: 'expectText', selector: 'button', text: 'none' },
    { type: 'click', selector: 'button' },
    { type: 'expectText', selector: 'button', text: '1' },
    { type: 'expectAttribute', selector: 'button', attribute: 'data-n', value: '1' },
    { type: 'expectAttribute', selector: 'button', attribute: 'title', value: 'x' },
  ],
}

export const fixture = defineSharedFixture(spec)
