/**
 * Real-browser pin for a child-component prop named like an event handler
 * but not one (`once`: `on` + a lowercase letter). Source lives in the
 * fixture-only root (`fixtures/components/OnPrefixedDataProp.tsx`).
 *
 * The prop is fed from an outer signal at three call sites — top level, a
 * component nested in an element loop row, and the loop-row component
 * itself — and after a click flips the signal, each child must show the new
 * value. Only `on[A-Z]` names are event handlers (`isEventHandlerName`); a
 * site that classified any `on`-prefixed name as a handler would pass
 * `once` as a one-shot value (or skip it), and the child would stay at its
 * first render.
 *
 * Snapshots in `__snapshots__/on-prefixed-data-prop.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * on-prefixed-data-prop`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const top = '.top .badge'
const row = (n: number) => `.rows li:nth-child(${n}) .badge` as const
const direct = (n: number) => `.direct .badge:nth-child(${n})` as const

export const spec: SharedFixtureSpec = {
  id: 'on-prefixed-data-prop',
  componentName: 'OnPrefixedDataProp',
  sourceRoot: 'fixture',
  description:
    'A child-component prop named `once` (`on` + lowercase) is reactive data, not an event handler, at top level and in loop rows',
  interactions: [
    // Initial SSR/hydration state: `flag` is true.
    { type: 'expectAttribute', selector: row(2), attribute: 'data-label', value: 'B' },
    { type: 'expectAttribute', selector: direct(2), attribute: 'data-label', value: 'B' },
    { type: 'expectAttribute', selector: top, attribute: 'data-once', value: 'yes' },
    { type: 'expectText', selector: top, text: 'on' },
    { type: 'expectAttribute', selector: row(1), attribute: 'data-once', value: 'yes' },
    { type: 'expectText', selector: row(2), text: 'on' },
    { type: 'expectAttribute', selector: direct(1), attribute: 'data-once', value: 'yes' },
    { type: 'expectText', selector: direct(2), text: 'on' },
    // The click flips `flag` to false; every child re-renders from it.
    { type: 'click', selector: '.toggle' },
    { type: 'expectAttribute', selector: top, attribute: 'data-once', value: 'no' },
    { type: 'expectText', selector: top, text: 'off' },
    { type: 'expectAttribute', selector: row(1), attribute: 'data-once', value: 'no' },
    { type: 'expectText', selector: row(1), text: 'off' },
    { type: 'expectAttribute', selector: row(2), attribute: 'data-once', value: 'no' },
    { type: 'expectText', selector: row(2), text: 'off' },
    { type: 'expectAttribute', selector: direct(1), attribute: 'data-once', value: 'no' },
    { type: 'expectText', selector: direct(1), text: 'off' },
    { type: 'expectAttribute', selector: direct(2), attribute: 'data-once', value: 'no' },
    { type: 'expectText', selector: direct(2), text: 'off' },
    // And back.
    { type: 'click', selector: '.toggle' },
    { type: 'expectAttribute', selector: top, attribute: 'data-once', value: 'yes' },
    { type: 'expectText', selector: row(1), text: 'on' },
    { type: 'expectText', selector: direct(2), text: 'on' },
  ],
}

export const fixture = defineSharedFixture(spec)
