/**
 * Pagination fixture lifted from `site/ui/components/pagination-demo.tsx`
 * (#1467 Phase 2e).
 *
 * `PaginationDynamicDemo` drives seven anchor controls off one
 * `currentPage` signal: each numbered link's `data-active` /
 * `aria-current` is a reactive prop binding (`isActive={currentPage()
 * === N}`), and every control's `onClick` must run
 * `e.preventDefault()` — the links carry `href="#"`, so a handler that
 * failed to wire through hydration would *navigate* instead of
 * updating state, which the post-click assertions would catch as a
 * page reload losing the signal.
 *
 * The closing leg pins the demo's range guard: `goToPage` ignores
 * page 0, so Previous on page 1 must leave every binding untouched —
 * the no-op path through a wired handler, distinct from a dead one.
 *
 * Snapshots in `__snapshots__/pagination.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * pagination`.
 */

import { defineDemoFixture, type SharedFixtureSpec } from './_helpers'

// Content children: 1 = Previous, 2..6 = pages 1..5, 7 = Next.
const link = (item: number) =>
  `[data-slot="pagination-item"]:nth-child(${item}) [data-slot="pagination-link"]`
const page = (n: number) => link(n + 1)
const previous = link(1)
const next = link(7)
const readout = 'p.text-center'

export const spec: SharedFixtureSpec = {
  id: 'pagination',
  componentName: 'PaginationDynamicDemo',
  sourceFile: 'pagination-demo',
  description:
    'site/ui Pagination demo — one signal drives data-active across seven links; href="#" handlers must preventDefault',
  interactions: [
    // Page 1 after hydration.
    { type: 'expectAttribute', selector: page(1), attribute: 'data-active', value: 'true' },
    { type: 'expectAttribute', selector: page(2), attribute: 'data-active', value: 'false' },
    { type: 'expectContains', selector: readout, text: 'Page 1 of 5' },
    // Next → page 2.
    { type: 'click', selector: next },
    { type: 'expectAttribute', selector: page(2), attribute: 'data-active', value: 'true' },
    { type: 'expectAttribute', selector: page(1), attribute: 'data-active', value: 'false' },
    { type: 'expectContains', selector: readout, text: 'Page 2 of 5' },
    // Direct jump → page 4.
    { type: 'click', selector: page(4) },
    { type: 'expectAttribute', selector: page(4), attribute: 'data-active', value: 'true' },
    { type: 'expectAttribute', selector: page(2), attribute: 'data-active', value: 'false' },
    { type: 'expectContains', selector: readout, text: 'Page 4 of 5' },
    // Previous → page 3.
    { type: 'click', selector: previous },
    { type: 'expectAttribute', selector: page(3), attribute: 'data-active', value: 'true' },
    { type: 'expectContains', selector: readout, text: 'Page 3 of 5' },
    // Back to page 1, then Previous again — the range guard makes it a
    // no-op through a live handler (page 0 is rejected).
    { type: 'click', selector: page(1) },
    { type: 'expectContains', selector: readout, text: 'Page 1 of 5' },
    { type: 'click', selector: previous },
    { type: 'expectAttribute', selector: page(1), attribute: 'data-active', value: 'true' },
    { type: 'expectContains', selector: readout, text: 'Page 1 of 5' },
  ],
}

export const fixture = defineDemoFixture(spec)
