/**
 * The `ref`-callback SSR-portal pattern (`ssrPortalOwnerScope`) inside a
 * fragment-rooted component. Source lives in the fixture-only root
 * (`fixtures/components/PortalFragmentRoot.tsx`).
 *
 * SSR renders the panel at the portal outlet with `bf-po` naming the
 * component's own scope, and hydration keeps it. The CSR-mount leg of the
 * real-browser `three-point` / `idempotence` oracles must render the same
 * owner marker even though the ref callback's `el.closest('[bf-s]')` finds
 * no owner there (a fragment root's scope id lives on a comment).
 *
 * Snapshots in `__snapshots__/portal-fragment-root.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts portal-fragment-root`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'portal-fragment-root',
  componentName: 'PortalFragmentRoot',
  sourceRoot: 'fixture',
  description:
    'a ref-callback portal (SSR-placed at the outlet with bf-po) inside a fragment-rooted component; CSR mount carries the same owner marker',
  interactions: [
    { type: 'expectHidden', selector: '.panel' },
    { type: 'click', selector: '.open' },
    { type: 'expectVisible', selector: '.panel' },
    { type: 'click', selector: '.close' },
    { type: 'expectHidden', selector: '.panel' },
  ],
}

export const fixture = defineSharedFixture(spec)
