/**
 * PreambleCells fixture — source lives in the fixture-only root
 * (`fixtures/components/PreambleCells.tsx`), NOT `integrations/shared/components`:
 * every integration app's `bf build` compiles that directory wholesale, and
 * this component's preamble+JSX loop body is intentionally DSL-refused
 * (BF021, jsRuntime-only per spec/callback-fidelity.md), which would break
 * every DSL integration build.
 *
 * The real-browser regression pin for #2389 (patch-on-update): a keyed,
 * signal-backed `.map()` row whose preamble builds a JSX leaf from item
 * state and embeds it as a bare interpolation (`{cells}`) — a same-key
 * `toggle()` update must patch that region in place via a claimed 'markup'
 * slot writer (slot unification A3, `@barefootjs/client/runtime/
 * claim-slots.ts`), not freeze it at its mount-time content while the
 * sibling `{t.name}` text slot updates normally.
 *
 * Data carries `&` and `"` so escaping parity rides the same pin. Snapshots
 * in `__snapshots__/preamble-cells.{html,client.js}` are regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts preamble-cells`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const stateCell = (n: number) => `tbody tr:nth-child(${n}) td.state` as const
const toggleBtn = (n: number) => `tbody tr:nth-child(${n}) button.toggle` as const

export const spec: SharedFixtureSpec = {
  id: 'preamble-cells',
  componentName: 'PreambleCells',
  sourceRoot: 'fixture',
  description:
    'keyed .map() row with a preamble-built leaf child — patched in place on same-key update, not frozen',
  interactions: [
    // Initial SSR/hydration state.
    { type: 'expectText', selector: stateCell(1), text: 'open' },
    { type: 'expectText', selector: stateCell(2), text: 'open' },

    // Toggle row 1 — the region patches to the new preamble-computed value;
    // row 2 (same key, untouched) must stay exactly as it was.
    { type: 'click', selector: toggleBtn(1) },
    { type: 'expectText', selector: stateCell(1), text: 'done & dusted' },
    { type: 'expectText', selector: stateCell(2), text: 'open' },

    // Toggle again — back to the original value (proves it's a live patch,
    // not a one-shot "first change only" fluke).
    { type: 'click', selector: toggleBtn(1) },
    { type: 'expectText', selector: stateCell(1), text: 'open' },
  ],
}

export const fixture = defineSharedFixture(spec)
