/**
 * PreambleCells fixture — source lives in the fixture-only root
 * (`fixtures/components/PreambleCells.tsx`), NOT `integrations/shared/components`:
 * every integration app's `bf build` compiles that directory wholesale, and
 * this component's preamble+JSX loop body is intentionally DSL-refused
 * (BF021, jsRuntime-only per spec/callback-fidelity.md), which would break
 * every DSL integration build.
 *
 * The real-browser regression pin for #2389 (patch-on-update): a keyed,
 * signal-backed `.map()` row whose preamble builds a JSX leaf from item
 * state and embeds it as a bare interpolation (`{cells}`) — a same-key
 * `toggle()` update must patch that region in place via a claimed 'markup'
 * slot writer (slot unification A3, `@barefootjs/client/runtime/
 * claim-slots.ts`), not freeze it at its mount-time content while the
 * sibling `{t.name}` text slot updates normally.
 *
 * Data carries `&` and `"` so escaping parity rides the same pin. Snapshots
 * in `__snapshots__/preamble-cells.{html,client.js}` are regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts preamble-cells`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const stateCell = (n: number) => `tbody tr:nth-child(${n}) td.state` as const
const toggleBtn = (n: number) => `tbody tr:nth-child(${n}) button.toggle` as const

export const spec: SharedFixtureSpec = {
  id: 'preamble-cells',
  componentName: 'PreambleCells',
  sourceRoot: 'fixture',
  description:
    'keyed .map() row with a preamble-built leaf child — patched in place on same-key update, not frozen',
  // #2613 escapeNotOwed: this fixture is the real-browser regression pin
  // for #2389 (patch-on-update) — its interactions assert that a same-key
  // `toggle()` PATCHES an already-SSR-adopted preamble region in place. A
  // `/* @client */` twin would SSR nothing for that region, so there would
  // be no adopted DOM node left to patch: the test would degrade into
  // "does client-only mounting work", which `client-only-loop` already
  // covers, contributing zero new coverage. Separately, per this
  // component's own file-placement docstring, the component lives outside
  // `integrations/shared/components/` specifically because every
  // integration app's `bf build` compiles that directory wholesale, and an
  // un-escaped copy there would break every DSL integration build — so an
  // escaped copy would also need to live there to be reachable by a DSL
  // build at all, defeating the reason it's kept fixture-only.
  escapeNotOwed: {
    reason:
      "By design: this fixture is the SSR-adopting-hydration + patch-on-update regression pin for #2389. A '/* @client */' escape twin would SSR an empty region, eliminating the adopted DOM node the fixture exists to test patching — collapsing it to the already-covered client-only-loop case with zero new coverage. It is also deliberately kept out of integrations/shared/components (per this file's own docstring) because every DSL integration app's bf build compiles that directory wholesale, so no DSL escape variant is wanted there either.",
  },
  interactions: [
    // Initial SSR/hydration state.
    { type: 'expectText', selector: stateCell(1), text: 'open' },
    { type: 'expectText', selector: stateCell(2), text: 'open' },

    // Toggle row 1 — the region patches to the new preamble-computed value;
    // row 2 (same key, untouched) must stay exactly as it was.
    { type: 'click', selector: toggleBtn(1) },
    { type: 'expectText', selector: stateCell(1), text: 'done & dusted' },
    { type: 'expectText', selector: stateCell(2), text: 'open' },

    // Toggle again — back to the original value (proves it's a live patch,
    // not a one-shot "first change only" fluke).
    { type: 'click', selector: toggleBtn(1) },
    { type: 'expectText', selector: stateCell(1), text: 'open' },
  ],
}

export const fixture = defineSharedFixture(spec)
