/**
 * PropsReactivityComparison fixture — second export of
 * `integrations/shared/components/ReactiveProps.tsx`.
 *
 * Sibling of `reactive-props`. Pins PARITY between the two ways to read a
 * prop: `props.xxx` access and destructured `{ value, label }` must behave
 * identically, so a change that makes one of them capture-once shows up
 * here as a divergence between the two children rather than as a
 * plausible-looking value. `destructured-props-live` is the fuller
 * positive-behavior fixture (text/memo/effect/handler/attribute positions).
 *
 * Locked behavior from spec/compiler.md:
 *   - PropsStyleChild's raw + computed values track parent's signal
 *   - DestructuredStyleChild's raw + computed values track it identically
 *
 * Snapshots in `__snapshots__/props-reactivity-comparison.{html,client.js}`
 * are regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * props-reactivity-comparison`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const propsStyle = '.props-style-child'
const destructured = '.destructured-style-child'

export const spec: SharedFixtureSpec = {
  id: 'props-reactivity-comparison',
  componentName: 'PropsReactivityComparison',
  // Second export of ReactiveProps.tsx — sourceFile pins the file basename
  // since it differs from the component name.
  sourceFile: 'ReactiveProps',
  description:
    'props.xxx vs destructured prop access — both fully reactive, and behaviourally identical',
  // PropsReactivityComparison seeds its internal signal at 1 (not 0); both
  // children render with that initial value.
  props: {},
  interactions: [
    // Initial: parent count = 1 → both children show raw=1, computed=10.
    { type: 'expectContains', selector: '.parent-count', text: 'Count: 1' },
    { type: 'expectText', selector: `${propsStyle} .child-raw-value`, text: '1' },
    { type: 'expectText', selector: `${propsStyle} .child-computed-value`, text: '10' },
    { type: 'expectText', selector: `${destructured} .child-raw-value`, text: '1' },
    { type: 'expectText', selector: `${destructured} .child-computed-value`, text: '10' },

    // Parent +1 → BOTH children track identically: raw=2, memo=20.
    { type: 'click', selector: '.btn-increment' },
    { type: 'expectContains', selector: '.parent-count', text: 'Count: 2' },
    { type: 'expectText', selector: `${propsStyle} .child-raw-value`, text: '2' },
    { type: 'expectText', selector: `${propsStyle} .child-computed-value`, text: '20' },
    { type: 'expectText', selector: `${destructured} .child-raw-value`, text: '2' },
    { type: 'expectText', selector: `${destructured} .child-computed-value`, text: '20' },

    // One more click — parity holds.
    { type: 'click', selector: '.btn-increment' },
    { type: 'expectText', selector: `${propsStyle} .child-raw-value`, text: '3' },
    { type: 'expectText', selector: `${propsStyle} .child-computed-value`, text: '30' },
    { type: 'expectText', selector: `${destructured} .child-raw-value`, text: '3' },
    { type: 'expectText', selector: `${destructured} .child-computed-value`, text: '30' },
  ],
}

export const fixture = defineSharedFixture(spec)
