/**
 * PropsReactivityComparison fixture — second export of
 * `integrations/shared/components/ReactiveProps.tsx`.
 *
 * Sibling of `reactive-props`. Historically (pre-Move-B, #2760's
 * follow-up) this fixture's point was what did NOT update: `props.xxx`
 * access (reactive — `createMemo` picks up the proxy read as a
 * dependency) against destructured `{ value, label } = props` (captured
 * once at component invocation, so later parent updates never
 * propagated).
 *
 * Move B made destructured-prop reads live too (every value-position
 * read of a destructured prop compiles to a live `_p.x` read, same as
 * `props.x` already was — see `props-binding.ts`'s `livePropReadExpr`),
 * so this fixture's point is now the OPPOSITE: `props.xxx` access and
 * destructured access are BYTE-FOR-BYTE EQUIVALENT in behavior. Both
 * children's raw + computed values track the parent's signal identically.
 * `destructured-props-live` is the fuller positive-behavior fixture
 * (text/memo/effect/handler/attribute positions); this one stays focused
 * on the props-object-vs-destructured PARITY question its name promises.
 *
 * Locked behavior from spec/compiler.md:
 *   - PropsStyleChild's raw + computed values track parent's signal
 *   - DestructuredStyleChild's raw + computed values track it identically
 *
 * Snapshots in `__snapshots__/props-reactivity-comparison.{html,client.js}`
 * are regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * props-reactivity-comparison`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const propsStyle = '.props-style-child'
const destructured = '.destructured-style-child'

export const spec: SharedFixtureSpec = {
  id: 'props-reactivity-comparison',
  componentName: 'PropsReactivityComparison',
  // Second export of ReactiveProps.tsx — sourceFile pins the file basename
  // since it differs from the component name.
  sourceFile: 'ReactiveProps',
  description:
    'props.xxx vs destructured prop access — both fully reactive and byte-for-byte equivalent since Move B',
  // PropsReactivityComparison seeds its internal signal at 1 (not 0); both
  // children render with that initial value.
  props: {},
  interactions: [
    // Initial: parent count = 1 → both children show raw=1, computed=10.
    { type: 'expectContains', selector: '.parent-count', text: 'Count: 1' },
    { type: 'expectText', selector: `${propsStyle} .child-raw-value`, text: '1' },
    { type: 'expectText', selector: `${propsStyle} .child-computed-value`, text: '10' },
    { type: 'expectText', selector: `${destructured} .child-raw-value`, text: '1' },
    { type: 'expectText', selector: `${destructured} .child-computed-value`, text: '10' },

    // Parent +1 → BOTH children track identically: raw=2, memo=20.
    { type: 'click', selector: '.btn-increment' },
    { type: 'expectContains', selector: '.parent-count', text: 'Count: 2' },
    { type: 'expectText', selector: `${propsStyle} .child-raw-value`, text: '2' },
    { type: 'expectText', selector: `${propsStyle} .child-computed-value`, text: '20' },
    { type: 'expectText', selector: `${destructured} .child-raw-value`, text: '2' },
    { type: 'expectText', selector: `${destructured} .child-computed-value`, text: '20' },

    // One more click — parity holds.
    { type: 'click', selector: '.btn-increment' },
    { type: 'expectText', selector: `${propsStyle} .child-raw-value`, text: '3' },
    { type: 'expectText', selector: `${propsStyle} .child-computed-value`, text: '30' },
    { type: 'expectText', selector: `${destructured} .child-raw-value`, text: '3' },
    { type: 'expectText', selector: `${destructured} .child-computed-value`, text: '30' },
  ],
}

export const fixture = defineSharedFixture(spec)
