/**
 * RadioGroup fixture lifted from `site/ui/components/radio-group-demo.tsx`
 * (#1467 Phase 2b deferral, landed with the demo source root).
 *
 * `radio-group` was the one Phase 2b primitive that doesn't fit the
 * single-root `ui` fixture model: its interactive surface only exists
 * composed — `<RadioGroup>` provides context, `<RadioGroupItem>` children
 * consume it (`useContext` inside a `ref` mount callback), and selection
 * state lives in the parent demo's signal. This is the first fixture on
 * the `demo` source root (`defineDemoFixture`): the root is the composed
 * demo component, and the `RadioGroup` / `RadioGroupItem` primitives are
 * auto-inferred siblings via the `@ui/components/ui/radio-group` alias
 * import.
 *
 * What the interactions probe, runtime-wise:
 *   - context propagation across component scopes after hydration
 *     (`createContext` in the sibling module, `useContext` in each item's
 *     mount callback);
 *   - `createEffect`-driven attribute writes (`aria-checked`,
 *     `data-state`) — the SSR HTML carries every item `unchecked`, so the
 *     `defaultValue="default"` selection appearing on item 1 is itself
 *     proof the effect ran post-hydration;
 *   - single-selection invariant: checking one item unchecks the other.
 *
 * The items carry no distinguishing static attribute (the `value` prop is
 * not reflected to the DOM), so selectors address them positionally via
 * their wrapper rows inside the `radiogroup` container.
 *
 * Snapshots in `__snapshots__/radio-group.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * radio-group`.
 */

import { defineDemoFixture, type SharedFixtureSpec } from './_helpers'

const item = (n: number) =>
  `[data-slot="radio-group"] > div:nth-child(${n}) button[role="radio"]`
// The demo's `Selected: {density()}` readout row.
const readout = 'div.border-t'

export const spec: SharedFixtureSpec = {
  id: 'radio-group',
  componentName: 'RadioGroupBasicDemo',
  sourceFile: 'radio-group-demo',
  description:
    'site/ui RadioGroup demo — context-driven single selection across composed RadioGroupItem children',
  interactions: [
    // Post-hydration initial state: defaultValue="default" selects item 1
    // (the SSR HTML ships all items unchecked — this assertion alone
    // proves the mount effect ran and the context wiring resolved).
    { type: 'expectAttribute', selector: item(1), attribute: 'aria-checked', value: 'true' },
    { type: 'expectAttribute', selector: item(1), attribute: 'data-state', value: 'checked' },
    { type: 'expectAttribute', selector: item(2), attribute: 'data-state', value: 'unchecked' },
    { type: 'expectContains', selector: readout, text: 'Selected: default' },
    // Select item 2 — moves the check, unchecks item 1, updates the
    // parent demo's signal-driven readout.
    { type: 'click', selector: item(2) },
    { type: 'expectAttribute', selector: item(2), attribute: 'aria-checked', value: 'true' },
    { type: 'expectAttribute', selector: item(2), attribute: 'data-state', value: 'checked' },
    { type: 'expectAttribute', selector: item(1), attribute: 'aria-checked', value: 'false' },
    { type: 'expectAttribute', selector: item(1), attribute: 'data-state', value: 'unchecked' },
    { type: 'expectContains', selector: readout, text: 'Selected: comfortable' },
    // And item 3 — same invariant from a non-default starting state.
    { type: 'click', selector: item(3) },
    { type: 'expectAttribute', selector: item(3), attribute: 'data-state', value: 'checked' },
    { type: 'expectAttribute', selector: item(2), attribute: 'data-state', value: 'unchecked' },
    { type: 'expectContains', selector: readout, text: 'Selected: compact' },
  ],
}

export const fixture = defineDemoFixture(spec)
