/**
 * ReactiveProps fixture lifted from
 * `integrations/shared/components/ReactiveProps.tsx`.
 *
 * Exercises the **getter-wrapped prop propagation** path:
 *   - parent declares `createSignal` + `createMemo`
 *   - children receive `value={count()}` and `value={doubled()}`
 *   - callbacks `onIncrement={() => setCount(n => n + 1)}` flow back up
 *
 * Beyond conditional-return (single scope, reactive attribute), this is
 * the first multi-instance composition fixture with a **reactive
 * data-flow loop**: parent button increments → both children's `value`
 * props update; child button → parent's signal updates → both children's
 * props update again.
 *
 * Snapshots in `__snapshots__/reactive-props.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * reactive-props`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

// Two ReactiveChild instances follow the .parent-section div in document
// order. Within `.reactive-props-container` all children are `<div>` so
// `.reactive-child:nth-of-type(2)` / `:nth-of-type(3)` resolve to Child A
// / Child B respectively (parent-section is :nth-of-type(1) of div).
const childA = '.reactive-child:nth-of-type(2)'
const childB = '.reactive-child:nth-of-type(3)'

export const spec: SharedFixtureSpec = {
  id: 'reactive-props',
  componentName: 'ReactiveProps',
  description:
    'Parent signal/memo propagating to multiple children via dynamic props; child callbacks updating parent',
  props: {},
  interactions: [
    // Initial reactive-props snapshot derived from createSignal(0).
    { type: 'expectContains', selector: '.parent-count', text: 'Parent count: 0' },
    { type: 'expectContains', selector: '.parent-doubled', text: 'Doubled: 0' },
    { type: 'expectText', selector: `${childA} .child-value`, text: '0' },
    { type: 'expectText', selector: `${childB} .child-value`, text: '0' },

    // Parent button → signal update → both children's `value` props update
    // (getter-wrapped propagation), parent memo recomputes.
    { type: 'click', selector: '.btn-parent-increment' },
    { type: 'expectContains', selector: '.parent-count', text: 'Parent count: 1' },
    { type: 'expectContains', selector: '.parent-doubled', text: 'Doubled: 2' },
    { type: 'expectText', selector: `${childA} .child-value`, text: '1' },
    { type: 'expectText', selector: `${childB} .child-value`, text: '2' },

    // Child callback → parent signal → full chain re-propagates.
    { type: 'click', selector: `${childA} .btn-child-increment` },
    { type: 'expectContains', selector: '.parent-count', text: 'Parent count: 2' },
    { type: 'expectText', selector: `${childA} .child-value`, text: '2' },
    { type: 'expectText', selector: `${childB} .child-value`, text: '4' },
  ],
}

export const fixture = defineSharedFixture(spec)
