/**
 * `escapes` twin of `ref-mount-attr` (BF063, `rewrite`): the same `ref`
 * mount callback writing `data-mounted`, with the attribute ALSO rendered
 * in the element's JSX. SSR now emits the value the callback writes on
 * mount, so the server HTML and the hydrated DOM agree and the real-browser
 * oracle suite (`snap` / `three-point`) passes with no quarantine row.
 *
 * No `interactions` — nothing here changes after mount.
 *
 * Snapshots in `__snapshots__/ref-mount-attr-rendered.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts ref-mount-attr-rendered`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'ref-mount-attr-rendered',
  componentName: 'RefMountAttrRendered',
  sourceRoot: 'fixture',
  description: 'a ref mount callback writes an attribute the JSX also renders, so SSR already carries it',
  interactions: [],
}

export const fixture = defineSharedFixture(spec)
