/**
 * RefMountAttr fixture — a minimal, component-agnostic repro of the
 * `ref-effect-attr-state-ssr` registry entry's mechanism: a `ref` mount
 * callback that writes an attribute via `setAttribute` never runs at SSR,
 * so the server HTML omits the attribute while the hydrated DOM carries
 * it. The named UI components the entry used to cite (accordion,
 * radio-group, command, combobox, select) have all since threaded the
 * value through an explicit prop instead of a `ref` effect, which is why
 * this fixture exists: without it the entry would have no fixture left in
 * the corpus even though the general mechanism is still real (the
 * pairwise sweep's `…event-ref-callback…` rows reproduce the same
 * `data-mounted` shape independently).
 *
 * No `interactions` — nothing here is meant to change after mount; the
 * oracle suite (`snap`/`three-point`) is what exercises this fixture, the
 * same way `kbd`/`label` ship none.
 *
 * Snapshots in `__snapshots__/ref-mount-attr.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts ref-mount-attr`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'ref-mount-attr',
  componentName: 'RefMountAttr',
  sourceRoot: 'fixture',
  description: 'a ref mount callback writes an attribute via setAttribute, which never reaches SSR',
  interactions: [],
}

export const fixture = defineSharedFixture(spec)
