/**
 * Real-browser pin for a `ref`-callback portal on an element inside a keyed
 * `.map()` row. Source lives in the fixture-only root
 * (`fixtures/components/RowPortalRef.tsx`).
 *
 * SSR renders each row's `<button>` at the portal outlet, carrying its row
 * key, and hydration pairs it with its row (#3318): the hydrated page
 * matches that server HTML, and clicking a row button runs its `onClick`,
 * so the counter outside the loop shows `1`.
 *
 * Snapshots in `__snapshots__/row-portal-ref.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * row-portal-ref`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'row-portal-ref',
  componentName: 'RowPortalRef',
  sourceRoot: 'fixture',
  description: 'A ref-callback createPortal on a keyed loop-row element keeps the row click handler working after hydration',
  props: { rows: ['a', 'b'] },
  interactions: [
    { type: 'expectText', selector: '.count', text: '0' },
    { type: 'click', selector: 'button.row' },
    { type: 'expectText', selector: '.count', text: '1' },
  ],
}

export const fixture = defineSharedFixture(spec)
