/**
 * Native `<select>` fixture lifted from
 * `integrations/shared/components/SelectNative.tsx` (#2481).
 *
 * Fills a DOM-state-carrier gap in the fixture-hydrate corpus: no shared
 * fixture exercised a native `<select>` before this — `select` (site/ui)
 * is a custom Radix-style `div`/`role="listbox"` composite, and the only
 * native-`<select>` conformance fixtures (`select-loop-selected`,
 * `select-option-selected`, `select-value-ssr`) are static, non-hydrating
 * inline-source fixtures with no `expectedClientJs`/`interactions`. This
 * one hydrates for real, so the oracle harness's `dom-state.ts` vocabulary
 * (`e2e/dom-state.ts`) can capture and compare the live `selectedIndex`
 * IDL property across SSR/hydrated/csr-mount renders — a property that
 * never round-trips through `innerHTML`.
 *
 * The `press('ArrowUp'/'ArrowDown')` interactions move the selection via
 * the keyboard rather than `selectOption()`: Chromium renders a
 * `<select>`'s dropdown as a native OS popup that Playwright's
 * `click()`-based automation can't reach, and `selectOption()` bypasses
 * the DOM entirely (it doesn't exercise the compiled `onChange` handler
 * the same way a real user interaction would) — arrow-key navigation
 * changes the selection AND fires a real `change` event without opening
 * the popup.
 *
 * Snapshots in `__snapshots__/select-native-shared.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * select-native-shared`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'select-native-shared',
  componentName: 'SelectNative',
  description: 'Native <select> populated by .map() with a signal-controlled value',
  interactions: [
    { type: 'expectValue', selector: '.fruit-select', value: 'banana' },
    { type: 'expectContains', selector: '.picked-value', text: 'banana' },
    { type: 'press', selector: '.fruit-select', key: 'ArrowUp' },
    { type: 'expectValue', selector: '.fruit-select', value: 'apple' },
    { type: 'expectContains', selector: '.picked-value', text: 'apple' },
    { type: 'press', selector: '.fruit-select', key: 'ArrowDown' },
    { type: 'expectValue', selector: '.fruit-select', value: 'banana' },
  ],
}

export const fixture = defineSharedFixture(spec)
