/**
 * SelectOutOfRange fixture — source lives in the fixture-only root
 * (`fixtures/components/SelectOutOfRange.tsx`), so it joins the frozen
 * corpus `oracle.playwright.ts` runs in a real browser.
 *
 * The plain corpus fixture `select-value-no-match-ssr` pins the #2852 SSR
 * output (the hidden placeholder option) for every adapter; this one pins
 * what only a browser can see — that after hydration the select's live
 * `selectedIndex` is -1 where the server-rendered one was 0. Quarantined
 * in `e2e/oracle-quarantine.ts` under `select-out-of-range-selected-index`,
 * the same entry the pairwise sweep's `controlled-select` rows cite.
 *
 * Snapshots in `__snapshots__/select-out-of-range-hydration.{html,client.js}`
 * are regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * select-out-of-range-hydration`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'select-out-of-range-hydration',
  componentName: 'SelectOutOfRange',
  sourceRoot: 'fixture',
  description:
    'controlled <select> bound to a value outside its option set — SSR selects the #2852 placeholder, hydration selects nothing',
  interactions: [
    // The text binding proves hydration ran; the select state is what the
    // oracles measure.
    { type: 'expectText', selector: '.current', text: '7' },
  ],
}

export const fixture = defineSharedFixture(spec)
