/**
 * Signal-conditioned early return:
 * `if (loading()) return <button/>; return <p/>`.
 *
 * Source lives in the fixture-only root (`fixtures/components/LoadGate.tsx`)
 * rather than inline, so the fixture can participate in the fixture-hydrate
 * real-browser layer (#1467) — that requires `expectedHtml` +
 * `expectedClientJs` + `interactions` together (`defineSharedFixture`
 * reads the frozen `__snapshots__/signal-early-return.{html,client.js}`
 * pair), which a plain inline-source `createFixture` can't supply without
 * a committed client-JS snapshot to load.
 *
 * The SSR side renders the initial branch correctly — that is what
 * `expectedHtml` pins. The gap was the client side (#2463): no
 * branch-switch effect was emitted (clicking called `setLoading(false)`
 * and nothing subscribed, so the UI could never leave the SSR branch),
 * and the CSR template lambda referenced `loading()` out of scope — a
 * `ReferenceError` on CSR mount, fixed by routing the condition through
 * the same static-template gate `IRConditional` already used
 * (`canGenerateStaticTemplate`'s `if-statement` arm), and by giving
 * `if-statement` its own client-js collector arm (`collect-elements.ts`)
 * that lowers to the runtime's `insertRoot()` — the root-swap counterpart
 * of `insert()` for a conditional with no synthetic wrapper to search
 * within (see `ConditionalElement.rootSwap`).
 *
 * The semantically identical root ternary
 * (`return loading() ? <button/> : <p/>`) compiles to an `insert()` with a
 * branch-switch effect — see the `top-level-ternary` fixture — so this
 * pins the statement-form/expression-form asymmetry #2463 tracked.
 *
 * Snapshots in `__snapshots__/signal-early-return.{html,client.js}` are
 * regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts signal-early-return`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const button = 'button'

export const spec: SharedFixtureSpec = {
  id: 'signal-early-return',
  componentName: 'LoadGate',
  sourceRoot: 'fixture',
  description: 'Signal-conditioned early return renders the initial branch and reacts to the signal (#2463)',
  interactions: [
    // Initial SSR/hydration state: the loading branch is live.
    { type: 'expectText', selector: button, text: 'Loading...' },
    // Click flips `loading` to false — the branch-switch effect must swap
    // the button out for the `<p>Ready</p>` branch.
    { type: 'click', selector: button },
    { type: 'expectHidden', selector: button },
    { type: 'expectText', selector: 'p', text: 'Ready' },
  ],
}

export const fixture = defineSharedFixture(spec)
