/**
 * SignalOptionalInit fixture — a signal declared as
 * `createSignal<string | undefined>('one')` and rendered as both an
 * attribute (`title={label()}`) and a text expression.
 *
 * The contract is the reference's: the literal initial value is what SSR
 * renders (`title="one"`, text `one`), whatever the declared type argument
 * is. A template adapter that derives the field's type from the union and
 * seeds it with its zero value instead of the literal renders `title=""`
 * and empty text — go-template did until it learned to unwrap the
 * `T | undefined` union for the literal seed (`unwrapNullableUnion`), so
 * this fixture is that fix's regression test on every adapter.
 *
 * Interactions cycle the value `one` → `undefined` → `one`, so hydration
 * is checked both ways: the attribute and text come back after the
 * `undefined` step.
 *
 * Snapshots in `__snapshots__/signal-optional-init.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts signal-optional-init`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const target = 'span[data-slot="target"]'
const button = 'button'

export const spec: SharedFixtureSpec = {
  id: 'signal-optional-init',
  componentName: 'SignalOptionalInit',
  sourceRoot: 'fixture',
  description:
    'a signal declared as `T | undefined` with a literal initial value renders that value at SSR as an attribute and as text',
  interactions: [
    { type: 'expectAttribute', selector: target, attribute: 'title', value: 'one' },
    { type: 'expectText', selector: target, text: 'one' },
    // undefined: the attribute is removed and the text emptied (no step
    // asserts absence); the next click must bring both back.
    { type: 'click', selector: button },
    { type: 'click', selector: button },
    { type: 'expectAttribute', selector: target, attribute: 'title', value: 'one' },
    { type: 'expectText', selector: target, text: 'one' },
  ],
}

export const fixture = defineSharedFixture(spec)
