/**
 * StaticNestedLoopConditional fixture (#2897) — source lives in the
 * fixture-only root (`fixtures/components/StaticNestedLoopConditional.tsx`).
 *
 * A STATIC (non-signal) outer array whose row contains a depth-1 nested
 * `.map()` over plain elements, and the INNER loop's row has a reactive
 * conditional. #2798's `inner-loop-nested` clone-and-wire architecture wires
 * ref/reactive-text/reactive-attr bindings but has no conditional-handling
 * machinery at all — the branch froze at its SSR-time value. Clicking
 * "Toggle" now verifies the branch swaps live.
 *
 * Sibling to `static-nested-loop-ref.ts` (#2798, ref/text/attr wiring) —
 * this fixture is the conditional counterpart #2798 explicitly left as a
 * known limitation.
 *
 * Snapshots in
 * `__snapshots__/static-nested-loop-conditional.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * static-nested-loop-conditional`.
 */

import type { JSXFixture } from '../src/types'
import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'static-nested-loop-conditional',
  componentName: 'StaticNestedLoopConditional',
  sourceRoot: 'fixture',
  description:
    'a static outer array + depth-1 inner loop row conditional swaps live, not frozen at its SSR-time value (#2897)',
  interactions: [
    { type: 'expectText', selector: 'ul li span.child:nth-of-type(1) b.on', text: 'on' },
    { type: 'expectText', selector: 'ul li span.child:nth-of-type(2) b.on', text: 'on' },

    { type: 'click', selector: '.toggle' },
    { type: 'expectText', selector: 'ul li span.child:nth-of-type(1) i.off', text: 'off' },
    { type: 'expectText', selector: 'ul li span.child:nth-of-type(2) i.off', text: 'off' },

    { type: 'click', selector: '.toggle' },
    { type: 'expectText', selector: 'ul li span.child:nth-of-type(1) b.on', text: 'on' },
    { type: 'expectText', selector: 'ul li span.child:nth-of-type(2) b.on', text: 'on' },
  ],
}

export const fixture: JSXFixture = defineSharedFixture(spec)
