/**
 * StaticLoopConditional fixture (#2897) — source lives in the fixture-only
 * root (`fixtures/components/StaticLoopConditional.tsx`).
 *
 * A STATIC (non-signal) array's `.map()` row contains a reactive conditional
 * alongside a static sibling, both arms rendering an element. The static
 * forEach bake this row used to take had no conditional-handling machinery
 * at all — the branch froze at its SSR-time value. Clicking "Toggle" now
 * verifies the branch swaps live, matching the same shape on a signal-backed
 * array (`loop-row-static-conditional.ts`'s dynamic control).
 *
 * Snapshots in `__snapshots__/static-loop-conditional.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * static-loop-conditional`.
 */

import type { JSXFixture } from '../src/types'
import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'static-loop-conditional',
  componentName: 'StaticLoopConditional',
  sourceRoot: 'fixture',
  description:
    'a static array\'s .map() row conditional swaps live, not frozen at its SSR-time value (#2897)',
  interactions: [
    { type: 'expectText', selector: 'ul li:nth-child(1) b.on', text: 'on' },
    { type: 'expectText', selector: 'ul li:nth-child(2) b.on', text: 'on' },

    { type: 'click', selector: '.toggle' },
    { type: 'expectText', selector: 'ul li:nth-child(1) i.off', text: 'off' },
    { type: 'expectText', selector: 'ul li:nth-child(2) i.off', text: 'off' },

    { type: 'click', selector: '.toggle' },
    { type: 'expectText', selector: 'ul li:nth-child(1) b.on', text: 'on' },
    { type: 'expectText', selector: 'ul li:nth-child(2) b.on', text: 'on' },
  ],
}

export const fixture: JSXFixture = defineSharedFixture(spec)
