/**
 * Switch fixture lifted from `ui/components/ui/switch/index.tsx` (#1467
 * Phase 2b).
 *
 * Like `toggle`, an uncontrolled boolean two-state button, but the click
 * also drives a second element: the thumb `<span>`'s `data-state` is
 * updated alongside the track's `aria-checked` / `data-state`. The
 * assertions cover both so a regression that only re-renders the root
 * (and skips the nested thumb) is caught.
 *
 * Snapshots in `__snapshots__/switch.{html,client.js}` are regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts switch`.
 */

import { defineUiFixture, type SharedFixtureSpec } from './_helpers'

const track = 'button[role="switch"]'
const thumb = '[data-slot="switch-thumb"]'

export const spec: SharedFixtureSpec = {
  id: 'switch',
  componentName: 'Switch',
  sourceFile: 'switch',
  description:
    'site/ui Switch — uncontrolled toggle updates track + thumb data-state',
  props: { className: '' },
  interactions: [
    // Initial unchecked state.
    { type: 'expectAttribute', selector: track, attribute: 'aria-checked', value: 'false' },
    { type: 'expectAttribute', selector: track, attribute: 'data-state', value: 'unchecked' },
    { type: 'expectAttribute', selector: thumb, attribute: 'data-state', value: 'unchecked' },
    // Toggle on — both track and thumb flip.
    { type: 'click', selector: track },
    { type: 'expectAttribute', selector: track, attribute: 'aria-checked', value: 'true' },
    { type: 'expectAttribute', selector: track, attribute: 'data-state', value: 'checked' },
    { type: 'expectAttribute', selector: thumb, attribute: 'data-state', value: 'checked' },
    // Toggle off again.
    { type: 'click', selector: track },
    { type: 'expectAttribute', selector: track, attribute: 'aria-checked', value: 'false' },
    { type: 'expectAttribute', selector: thumb, attribute: 'data-state', value: 'unchecked' },
  ],
}

export const fixture = defineUiFixture(spec)
