/**
 * Tabs fixture lifted from `site/ui/components/tabs-demo.tsx`
 * (#1467 Phase 2c — disclosure).
 *
 * Deliberate contrast with `accordion`: the tabs primitives hold **no
 * internal state and no context** — `TabsBasicDemo`'s `activeTab` signal
 * feeds two memos whose values flow as reactive props into every
 * trigger and panel (`aria-selected`, `data-state`, `tabindex`). Each
 * assertion is therefore a probe of the compiled
 * parent-memo → child-prop → attribute-binding chain after hydration —
 * there is no mount-effect fallback that could mask a broken binding.
 *
 * Panel visibility is a `hidden` utility-class swap and the host page
 * serves no CSS, so the panels' `data-state` attribute is the
 * observable contract (same reasoning as `accordion`).
 *
 * Snapshots in `__snapshots__/tabs.{html,client.js}` are regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts tabs`.
 */

import { defineDemoFixture, type SharedFixtureSpec } from './_helpers'

const trigger = (v: string) => `[data-slot="tabs-trigger"][data-value="${v}"]`
const panel = (v: string) => `[data-slot="tabs-content"][data-value="${v}"]`

export const spec: SharedFixtureSpec = {
  id: 'tabs',
  componentName: 'TabsBasicDemo',
  sourceFile: 'tabs-demo',
  description:
    'site/ui Tabs demo — prop-driven selection: parent memos flow into trigger/panel attribute bindings',
  interactions: [
    // SSR initial state survives hydration: account selected.
    { type: 'expectAttribute', selector: trigger('account'), attribute: 'data-state', value: 'active' },
    { type: 'expectAttribute', selector: trigger('account'), attribute: 'aria-selected', value: 'true' },
    { type: 'expectAttribute', selector: trigger('account'), attribute: 'tabindex', value: '0' },
    { type: 'expectAttribute', selector: panel('account'), attribute: 'data-state', value: 'active' },
    { type: 'expectAttribute', selector: trigger('password'), attribute: 'data-state', value: 'inactive' },
    { type: 'expectAttribute', selector: trigger('password'), attribute: 'tabindex', value: '-1' },
    { type: 'expectAttribute', selector: panel('password'), attribute: 'data-state', value: 'inactive' },
    // Switch to password — every binding on both sides flips.
    { type: 'click', selector: trigger('password') },
    { type: 'expectAttribute', selector: trigger('password'), attribute: 'data-state', value: 'active' },
    { type: 'expectAttribute', selector: trigger('password'), attribute: 'aria-selected', value: 'true' },
    { type: 'expectAttribute', selector: trigger('password'), attribute: 'tabindex', value: '0' },
    { type: 'expectAttribute', selector: panel('password'), attribute: 'data-state', value: 'active' },
    { type: 'expectAttribute', selector: trigger('account'), attribute: 'data-state', value: 'inactive' },
    { type: 'expectAttribute', selector: trigger('account'), attribute: 'aria-selected', value: 'false' },
    { type: 'expectAttribute', selector: trigger('account'), attribute: 'tabindex', value: '-1' },
    { type: 'expectAttribute', selector: panel('account'), attribute: 'data-state', value: 'inactive' },
    // And back — the round trip rules out one-way binding updates.
    { type: 'click', selector: trigger('account') },
    { type: 'expectAttribute', selector: trigger('account'), attribute: 'data-state', value: 'active' },
    { type: 'expectAttribute', selector: panel('account'), attribute: 'data-state', value: 'active' },
    { type: 'expectAttribute', selector: trigger('password'), attribute: 'data-state', value: 'inactive' },
    { type: 'expectAttribute', selector: panel('password'), attribute: 'data-state', value: 'inactive' },
  ],
}

export const fixture = defineDemoFixture(spec)
