/**
 * TagCloud fixture — source lives in the fixture-only root
 * (`fixtures/components/TagCloud.tsx`), NOT `integrations/shared/components`:
 * every integration app's `bf build` compiles that directory wholesale, and
 * this component's segment-carried flatMap is intentionally DSL-refused
 * (BF021), which would break every DSL integration build.
 *
 * The real-browser regression pin for the flatMap client-loop rewiring: a
 * signal-driven `.flatMap()` BLOCK body (early return + `const` preamble +
 * keyed leaf per tag) driven through the descriptor-based `mapArray` path.
 *
 * Interactions cover the four behaviours the pre-fix wiring broke:
 *   1. hydration adopts every SSR leaf (pre-fix: leaves vanished on load —
 *      reconciled against the UN-flattened source with index keys),
 *   2. content change under stable keys patches leaves in place (`shout`),
 *   3. adding an item creates its leaves (pre-fix: `cloneNode(null)` crash
 *      against an empty item template),
 *   4. removing an item drops exactly its leaves.
 *
 * Leaf data carries `<`, `&`, `"` so escaping parity rides the same pin.
 * Snapshots in `__snapshots__/tag-cloud.{html,client.js}` are regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts tag-cloud`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const leaf = (n: number) => `.tags li:nth-child(${n})` as const

export const spec: SharedFixtureSpec = {
  id: 'tag-cloud',
  componentName: 'TagCloud',
  sourceRoot: 'fixture',
  description:
    'flatMap block-body tag list — hydration adoption, in-place leaf patch, add, and remove',
  props: {
    items: [
      { id: 1, label: 'write <b>docs</b>', tags: ['a & b', 'q "c"'] },
      // Empty tag set — exercises the early-return segment at every step.
      { id: 2, label: 'no tags', tags: [] },
      { id: 3, label: "ship it's", tags: ['<script>'] },
    ],
  },
  interactions: [
    // 1. Hydration adopts all three SSR leaves (2 from id=1, 1 from id=3).
    { type: 'expectText', selector: leaf(1), text: 'write <b>docs</b> — a & b' },
    { type: 'expectText', selector: leaf(2), text: 'write <b>docs</b> — q "c"' },
    { type: 'expectText', selector: leaf(3), text: "ship it's — <script>" },
    { type: 'expectHidden', selector: leaf(4) },

    // 2. Content change under stable keys — every leaf patches in place.
    { type: 'click', selector: '.shout' },
    { type: 'expectText', selector: leaf(1), text: 'WRITE <B>DOCS</B> — a & b' },
    { type: 'expectText', selector: leaf(3), text: "SHIP IT'S — <script>" },

    // 3. Add — the new item's leaf is CREATED client-side.
    { type: 'click', selector: '.add' },
    { type: 'expectText', selector: leaf(4), text: 'new & <fresh> #100 — x "100"' },

    // 4. Remove the first item — exactly its two leaves drop.
    { type: 'click', selector: '.drop' },
    { type: 'expectText', selector: leaf(1), text: "SHIP IT'S — <script>" },
    { type: 'expectText', selector: leaf(2), text: 'new & <fresh> #100 — x "100"' },
    { type: 'expectHidden', selector: leaf(3) },
  ],
}

export const fixture = defineSharedFixture(spec)
