/**
 * Native controlled `<textarea value={...}>` fixture lifted from
 * `integrations/shared/components/NoteBoxNative.tsx` (#2481).
 *
 * Widens `value`-property coverage with an unwrapped native element (the
 * existing `textarea` fixture wraps `ui/components/ui/textarea`); paired
 * with a live text preview so the same signal drives both a form-control
 * IDL property and ordinary reactive text, the way `checkbox-native-shared`
 * pairs `checked` with a text readout.
 *
 * Snapshots in `__snapshots__/textarea-native-shared.{html,client.js}`
 * are regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * textarea-native-shared`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'textarea-native-shared',
  componentName: 'NoteBoxNative',
  description: 'Native controlled <textarea value={signal}> with a live preview',
  interactions: [
    { type: 'expectValue', selector: '.note-textarea', value: 'initial note' },
    { type: 'expectContains', selector: '.note-preview', text: 'initial note' },
    { type: 'fill', selector: '.note-textarea', value: 'Hello\nworld' },
    { type: 'expectValue', selector: '.note-textarea', value: 'Hello\nworld' },
    { type: 'expectContains', selector: '.note-preview', text: 'world' },
  ],
}

export const fixture = defineSharedFixture(spec)
