/**
 * Textarea fixture lifted from `ui/components/ui/textarea/index.tsx`
 * (#1467 Phase 2b).
 *
 * Multi-line sibling of `input`: a pass-through native control whose value
 * the runtime must preserve across hydration. `<textarea>` is also one of
 * the elements whose inter-element whitespace matters, so this fixture
 * doubles as coverage that the fixture-hydrate runner serves
 * `rawExpectedHtml` (byte-exact) rather than the whitespace-collapsed
 * `expectedHtml`.
 *
 * Snapshots in `__snapshots__/textarea.{html,client.js}` are regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts textarea`.
 */

import { defineUiFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'textarea',
  componentName: 'Textarea',
  sourceFile: 'textarea',
  description: 'site/ui Textarea — native multi-line control survives hydration + accepts typing',
  // `className: ''` and `value: ''` are passed explicitly: the CSR template
  // emits raw `_p.className` / `_p.value` and does not apply the component's
  // destructured `= ''` defaults, so without them the CSR render diverges
  // from SSR (a literal `undefined` class, and a missing `value=""`).
  props: { placeholder: 'Type your message here.', className: '', value: '' },
  interactions: [
    { type: 'expectValue', selector: 'textarea', value: '' },
    { type: 'fill', selector: 'textarea', value: 'Hello\nworld' },
    { type: 'expectValue', selector: 'textarea', value: 'Hello\nworld' },
  ],
}

export const fixture = defineUiFixture(spec)
