// TodoAppSSR fixture lifted from
// `integrations/shared/components/TodoAppSSR.tsx`.
//
// Twin of TodoApp.tsx with **no `/* @client */` markers** — the loop
// and conditionals all server-render at the initial pass instead of
// deferring to the client. This sibling exists so the corpus pins both
// pre-rendered and client-only loop materialization paths through the
// runtime; if the runtime drops support for hydrating an already-
// server-rendered keyed loop, todo-app would still pass (its SSR pass
// emits empty markers) but todo-app-ssr would break.
//
// Mutation paths share TodoApp's fetch dependence and are deferred for
// the same reason. The interaction set mirrors todo-app's.
//
// Snapshots in `__snapshots__/todo-app-ssr.{html,client.js}` are
// regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
// todo-app-ssr`.

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const item = (id: number) => `.todo-list [data-key="${id}"]` as const

export const spec: SharedFixtureSpec = {
  id: 'todo-app-ssr',
  componentName: 'TodoAppSSR',
  additionalComponents: ['TodoItem'],
  description:
    'TodoMVC parent with server-rendered loop (no /* @client */ markers); hydration must adopt the pre-rendered child scopes',
  props: {
    initialTodos: [
      { id: 1, text: 'Eat breakfast', done: true },
      { id: 2, text: 'Write tests', done: false },
      { id: 3, text: 'Ship code', done: false },
    ],
  },
  interactions: [
    // After hydration, the server-rendered list of TodoItems is adopted
    // by the loop reconciliation — the children should remain present.
    { type: 'expectVisible', selector: item(1) },
    { type: 'expectVisible', selector: item(2) },
    { type: 'expectVisible', selector: item(3) },
    { type: 'expectContains', selector: '.todo-count', text: '2 items left' },

    // Active filter — completed (id=1) removed from DOM.
    { type: 'click', selector: '.filters a[href="#/active"]' },
    { type: 'expectHidden', selector: item(1) },
    { type: 'expectVisible', selector: item(2) },
    { type: 'expectVisible', selector: item(3) },

    // Completed — only the done todo remains.
    { type: 'click', selector: '.filters a[href="#/completed"]' },
    { type: 'expectVisible', selector: item(1) },
    { type: 'expectHidden', selector: item(2) },
    { type: 'expectHidden', selector: item(3) },

    // Back to All.
    { type: 'click', selector: '.filters a[href="#/"]' },
    { type: 'expectVisible', selector: item(1) },
    { type: 'expectVisible', selector: item(2) },
    { type: 'expectVisible', selector: item(3) },
  ],
}

export const fixture = defineSharedFixture(spec)
