/**
 * Toggle fixture lifted from `ui/components/ui/toggle/index.tsx`.
 *
 * First interactive `site/ui` fixture (#1467 Phase 2b). Where the Phase 2a
 * `button` fixture only proved hydration preserved a stateless DOM, this
 * one exercises a real reactive transition: clicking the toggle flips the
 * internal `createSignal`, and the `isPressed` memo drives both the
 * `data-state` (`on`/`off`) and `aria-pressed` attribute bindings. The
 * label (`children`) is unaffected, so the assertions target the attributes
 * rather than text.
 *
 * Uncontrolled mode (no `pressed` prop) so the click path lands on the
 * internal signal — the controlled branch needs a parent owner to bind the
 * `pressed` prop, which a single-component fixture can't express.
 *
 * Snapshots in `__snapshots__/toggle.{html,client.js}` are regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts toggle`.
 */

import { defineUiFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'toggle',
  componentName: 'Toggle',
  sourceFile: 'toggle',
  description:
    'site/ui Toggle — uncontrolled press toggles data-state + aria-pressed',
  // `className: ''` for the same CSR-template default-prop reason as button.
  props: { className: '', children: 'Bold' },
  interactions: [
    // Initial uncontrolled state (defaultPressed unset → false).
    { type: 'expectAttribute', selector: 'button', attribute: 'aria-pressed', value: 'false' },
    { type: 'expectAttribute', selector: 'button', attribute: 'data-state', value: 'off' },
    { type: 'expectText', selector: 'button', text: 'Bold' },
    // Press → reactive flip to on.
    { type: 'click', selector: 'button' },
    { type: 'expectAttribute', selector: 'button', attribute: 'aria-pressed', value: 'true' },
    { type: 'expectAttribute', selector: 'button', attribute: 'data-state', value: 'on' },
    { type: 'expectText', selector: 'button', text: 'Bold' },
    // Press again → back to off.
    { type: 'click', selector: 'button' },
    { type: 'expectAttribute', selector: 'button', attribute: 'aria-pressed', value: 'false' },
    { type: 'expectAttribute', selector: 'button', attribute: 'data-state', value: 'off' },
  ],
}

export const fixture = defineUiFixture(spec)
