/**
 * #3215 regression pin: a `createSignal()` with no argument renders its
 * `undefined` initial value on every path. SSR, the CSR template and the
 * hydrated page all show the `?? 'none'` fallback; a click then sets it.
 *
 * Snapshots in `__snapshots__/zero-arg-signal.{html,client.js}` are
 * regenerated by
 * `bun run packages/adapter-tests/scripts/snapshot.ts zero-arg-signal`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'zero-arg-signal',
  componentName: 'ZeroArgSignal',
  sourceRoot: 'fixture',
  description: 'a createSignal() with no argument starts as undefined in SSR, CSR and hydration (#3215)',
  interactions: [
    { type: 'expectText', selector: 'button', text: 'none' },
    { type: 'click', selector: 'button' },
    { type: 'expectText', selector: 'button', text: 'x' },
  ],
}

export const fixture = defineSharedFixture(spec)
