/**
 * Compatibility Matrix page.
 *
 * Renders the committed `ui/compat.lock.json` (component × adapter
 * compile-compatibility, generated by the repo-internal `packages/compat`
 * tool) as a docs page. The lock file is imported at build time so it is
 * bundled into the Worker — never read from disk at request time.
 *
 * Content is generated as a Markdown string and run through the site's
 * standard `renderMarkdown` pipeline so it gets the same heading IDs,
 * TOC extraction, and table styling as every other docs page, instead of
 * hand-rolling HTML/JSX.
 */

import type { Hono } from 'hono'
import { renderMarkdown } from '../lib/markdown'
import { getDocsNavLinks } from '../lib/navigation'
import lock from '../../../ui/compat.lock.json' with { type: 'json' }
import supportMatrixLock from '../../../ui/support-matrix.lock.json' with { type: 'json' }

const SLUG = 'advanced/compatibility-matrix'
const TITLE = 'Compatibility Matrix'
const DESCRIPTION = 'Compile-compatibility of every ui/ component across template adapters.'

interface CompatDiagnostic {
  code: string
  severity: 'error' | 'warning'
  issues?: string[]
}

interface CompatCell {
  ok: boolean
  diagnostics?: CompatDiagnostic[]
}

interface FixtureDivergenceCell {
  kind: 'refusal' | 'render'
  codes?: string[]
  issues?: string[]
  reason?: string
}

interface FixtureDoc {
  description: string
  url: string
}

interface FixtureDivergences {
  note: string
  totalFixtures: number
  fixtures: Record<string, Record<string, FixtureDivergenceCell>>
  /** Optional: fixture id → description + source link (older locks lack it). */
  docs?: Record<string, FixtureDoc>
}

interface ComponentDoc {
  title: string
  description: string
  url: string
  /** Optional: public component page on ui.barefootjs.dev (absent for components with no routed page). */
  uiUrl?: string
}

interface CompatLock {
  note: string
  knownLimitationLabel: string
  adapters: string[]
  components: Record<string, Record<string, CompatCell>>
  /** Optional: component name → title + description + source link (older locks lack it). */
  componentDocs?: Record<string, ComponentDoc>
  /** Optional: locks generated before #2168's render-honesty section lack it. */
  fixtureDivergences?: FixtureDivergences
}

const compat = lock as CompatLock

/** One `kind` or `axis` construct's covering-fixture total and its per-adapter cells (`ui/support-matrix.lock.json`). */
interface SupportMatrixGap {
  fixture: string
  issues: string[]
}

interface SupportMatrixCell {
  pass: number
  total: number
  gaps?: SupportMatrixGap[]
}

interface SupportMatrixSourceLink {
  file: string
  line: number
  url: string
}

interface SupportMatrixExample {
  fixture: string
  description: string
  url: string
  code?: string
}

interface SupportMatrixConstruct {
  total: number
  cells: Record<string, SupportMatrixCell>
  source?: SupportMatrixSourceLink
  example?: SupportMatrixExample
}

interface SupportMatrixLock {
  note: string
  knownLimitationLabel: string
  adapters: string[]
  kinds: Record<string, SupportMatrixConstruct>
  axes: Record<string, SupportMatrixConstruct>
}

const supportMatrix = supportMatrixLock as SupportMatrixLock

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|')
}

/**
 * Deduped, sorted issue URLs as `#NNNN` links, falling back to the repo-
 * wide known-limitation label when none exist. Shared by `buildLegend`
 * (compat matrix, per diagnostic code) and the construct-support section
 * below (per gapped cell) so both link formats stay identical.
 */
function formatIssueLinks(issues: string[], fallbackLabel: string): string {
  // Dedupe + code-unit sort HERE (matching the lockfiles' issue ordering) so
  // both callers are deterministic from one place: `collectLegend` feeds
  // Set-insertion-ordered URLs, and the construct-support cells feed already-
  // flattened gap URLs — neither is pre-sorted at the call site.
  const unique = [...new Set(issues)].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))
  if (unique.length === 0) return `[known limitation](${fallbackLabel})`
  return unique.map((url) => `[#${url.split('/').pop()}](${url})`).join(', ')
}

/** Render one matrix cell as a Markdown fragment. */
function cellMarkdown(cell: CompatCell | undefined): string {
  if (!cell) return '?'
  const diagnostics = cell.diagnostics ?? []
  if (cell.ok && diagnostics.length === 0) return '✓'
  if (diagnostics.length === 0) return cell.ok ? '✓' : '?'

  return diagnostics
    .map((d) => {
      const label = d.severity === 'warning' ? `⚠ ${d.code}` : d.code
      const firstIssue = d.issues?.[0]
      return firstIssue ? `[${label}](${firstIssue})` : label
    })
    .join('<br>')
}

/** Build the "N components × M adapters — X / Y cells compile clean" summary line. */
function buildSummary(componentNames: string[]): string {
  const adapters = compat.adapters
  const totalCells = componentNames.length * adapters.length
  let okCells = 0
  for (const name of componentNames) {
    for (const adapter of adapters) {
      if (compat.components[name]?.[adapter]?.ok) okCells++
    }
  }
  return `**${componentNames.length} components × ${adapters.length} adapters — ${okCells} / ${totalCells} cells compile clean**`
}

/**
 * The "Component" cell: the name linked to its public component page on
 * ui.barefootjs.dev when it has one, else to its source (`componentDocs`
 * is generated alongside the lock), else a plain code span.
 */
function componentLabelMarkdown(name: string, doc: ComponentDoc | undefined): string {
  const code = `\`${escapeCell(name)}\``
  const url = doc?.uiUrl ?? doc?.url
  return url ? `[${code}](${url})` : code
}

/** Build the Markdown table: one row per component, a description, then one column per adapter. */
function buildTable(componentNames: string[]): string {
  const adapters = compat.adapters
  const header = `| Component | Description | ${adapters.join(' | ')} |`
  const divider = `| --- | --- | ${adapters.map(() => '---').join(' | ')} |`
  const rows = componentNames.map((name) => {
    const doc = compat.componentDocs?.[name]
    const description = doc?.description ? escapeCell(doc.description) : '—'
    const cells = adapters.map((adapter) => cellMarkdown(compat.components[name]?.[adapter]))
    return `| ${componentLabelMarkdown(name, doc)} | ${description} | ${cells.join(' | ')} |`
  })
  return [header, divider, ...rows].join('\n')
}

/** Collect every distinct diagnostic code across all cells, with its deduped issue URLs. */
function collectLegend(): { code: string; severity: CompatDiagnostic['severity']; issues: string[] }[] {
  const byCode = new Map<string, { severity: CompatDiagnostic['severity']; issues: Set<string> }>()

  for (const adapterMap of Object.values(compat.components)) {
    for (const cell of Object.values(adapterMap)) {
      for (const d of cell.diagnostics ?? []) {
        const entry = byCode.get(d.code) ?? { severity: d.severity, issues: new Set<string>() }
        for (const issue of d.issues ?? []) entry.issues.add(issue)
        byCode.set(d.code, entry)
      }
    }
  }

  return [...byCode.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([code, { severity, issues }]) => ({ code, severity, issues: [...issues] }))
}

function buildLegend(): string {
  const entries = collectLegend()
  if (entries.length === 0) {
    return `No diagnostics were reported — every component compiles cleanly on every adapter.`
  }

  return entries
    .map(({ code, severity, issues }) => {
      const label = severity === 'warning' ? `⚠ \`${code}\`` : `\`${code}\``
      return `- ${label} — ${formatIssueLinks(issues, compat.knownLimitationLabel)}`
    })
    .join('\n')
}

/**
 * Render one fixture-divergence cell: refusal cells show their diagnostic
 * codes (linked to the tracking issue when one exists), render-divergence
 * cells show a `≠` marker (detail lives in the per-fixture list below the
 * table — 9 columns of prose would be unreadable).
 */
function fixtureCellMarkdown(cell: FixtureDivergenceCell | undefined): string {
  if (!cell) return '✓'
  if (cell.kind === 'refusal') {
    const codes = cell.codes ?? []
    const firstIssue = cell.issues?.[0]
    const label = codes.join(', ') || 'refused'
    return firstIssue ? `[${label}](${firstIssue})` : label
  }
  return '≠'
}

/**
 * Per-fixture detail list: adapters sharing an identical reason string are
 * grouped onto one line, so the common "same divergence everywhere" case
 * reads as a single sentence instead of nine copies.
 */
function buildFixtureDetails(fd: FixtureDivergences): string {
  const blocks: string[] = []
  for (const fixtureId of Object.keys(fd.fixtures).sort()) {
    const row = fd.fixtures[fixtureId]
    const byText = new Map<string, string[]>()
    for (const adapterId of Object.keys(row).sort()) {
      const cell = row[adapterId]
      const text =
        cell.kind === 'refusal'
          ? `refused at build time with ${(cell.codes ?? []).map((c) => `\`${c}\``).join(', ')}`
          : (cell.reason ?? 'rendered output diverges from the Hono reference')
      const adapters = byText.get(text) ?? []
      adapters.push(adapterId)
      byText.set(text, adapters)
    }
    const lines = [...byText.entries()].map(
      ([text, adapters]) => `  - ${adapters.map((a) => `\`${a}\``).join(', ')} — ${escapeCell(text)}`,
    )
    const doc = fd.docs?.[fixtureId]
    const heading = doc?.url ? `**[\`${fixtureId}\`](${doc.url})**` : `**\`${fixtureId}\`**`
    const summary = doc?.description ? ` — ${escapeCell(doc.description)}` : ''
    blocks.push(`- ${heading}${summary}\n${lines.join('\n')}`)
  }
  return blocks.join('\n')
}

/** The render-honesty section: fixture × adapter divergence table + detail list. */
function buildFixtureSection(): string {
  const fd = compat.fixtureDivergences
  if (!fd || Object.keys(fd.fixtures).length === 0) return ''

  const fixtureIds = Object.keys(fd.fixtures).sort()
  const adapters = compat.adapters
  const cleanCount = fd.totalFixtures - fixtureIds.length

  const header = `| Fixture | ${adapters.join(' | ')} |`
  const divider = `| --- | ${adapters.map(() => '---').join(' | ')} |`
  const rows = fixtureIds.map((id) => {
    const doc = fd.docs?.[id]
    const label = doc?.url ? `[\`${escapeCell(id)}\`](${doc.url})` : `\`${escapeCell(id)}\``
    const cells = adapters.map((adapter) => fixtureCellMarkdown(fd.fixtures[id]?.[adapter]))
    return `| ${label} | ${cells.join(' | ')} |`
  })

  return `
## Render Conformance (fixture corpus)

The component matrix above is **compile-time only**. This section reports the **render-level** state honestly: the shared conformance corpus (\`packages/adapter-tests\`) is rendered through every adapter's real backend (Go, Ruby, Perl, PHP, Python, Rust) and byte-compared against the Hono reference. Fixtures listed here diverge on at least one adapter — either refused loudly at build time (\`conformancePins\`) or rendering differently from the reference (\`renderDivergences\`, skipped in that adapter's conformance suite until fixed). Fixtures absent from this table render to reference parity on every adapter.

**${cleanCount} / ${fd.totalFixtures} fixtures render to reference parity on every adapter.** The ${fixtureIds.length} below diverge on at least one:

${[header, divider, ...rows].join('\n')}

\`✓\` renders to reference parity · \`≠\` compiles clean but the rendered output diverges (skipped in that adapter's conformance suite until fixed) · a diagnostic code means the adapter refuses the shape loudly at build time.

### Divergence details

${buildFixtureDetails(fd)}
`
}

/**
 * Render one construct-support cell as `pass/total`, plus linked tracking
 * issues when the construct has gaps on this adapter. Deduped across every
 * gapped fixture in the cell — a common case is several fixtures gapped by
 * the same pinned diagnostic, which would otherwise repeat its issue link.
 */
function supportCellMarkdown(cell: SupportMatrixCell | undefined): string {
  if (!cell) return '?'
  const ratio = `${cell.pass}/${cell.total}`
  const gaps = cell.gaps ?? []
  if (gaps.length === 0) return ratio
  // `formatIssueLinks` dedupes + sorts, so just flatten every gapped
  // fixture's issues here (several fixtures gapped by the same diagnostic
  // repeat its URL — the helper collapses them).
  const issues = gaps.flatMap((gap) => gap.issues)
  return `${ratio} (${formatIssueLinks(issues, supportMatrix.knownLimitationLabel)})`
}

/**
 * The "Construct" cell: the label linked to the construct's exemplar
 * conformance fixture — a small self-contained component showing the
 * case in real code — falling back to the definition-site permalink
 * (where the construct is registered in the compiler) for constructs
 * with no covering fixture yet (`total: 0` rows). See the "Data Source"
 * section below for how these stay in sync as the source moves.
 */
function constructLabelMarkdown(construct: SupportMatrixConstruct | undefined, name: string): string {
  const code = `\`${escapeCell(name)}\``
  const url = construct?.example?.url ?? construct?.source?.url
  return url ? `[${code}](${url})` : code
}

/**
 * The "Example" cell: the extracted code snippet (when one exists) with
 * the exemplar fixture's description under it. A snippet containing a
 * backtick (template literals) uses a double-backtick code span, per
 * CommonMark.
 */
function exampleCellMarkdown(construct: SupportMatrixConstruct | undefined): string {
  const example = construct?.example
  if (!example) return '—'
  const description = escapeCell(example.description)
  if (!example.code) return description
  const code = escapeCell(example.code)
  const span = code.includes('`') ? `\`\` ${code} \`\`` : `\`${code}\``
  return `${span}<br>${description}`
}

/** One `construct × adapter` table — shared by the "By kind" and "By axis" tables. */
function buildSupportTable(records: Record<string, SupportMatrixConstruct>): string {
  const adapters = supportMatrix.adapters
  const names = Object.keys(records).sort()
  const header = `| Construct | Example | ${adapters.join(' | ')} |`
  const divider = `| --- | --- | ${adapters.map(() => '---').join(' | ')} |`
  const rows = names.map((name) => {
    const cells = adapters.map((adapter) => supportCellMarkdown(records[name]?.cells[adapter]))
    return `| ${constructLabelMarkdown(records[name], name)} | ${exampleCellMarkdown(records[name])} | ${cells.join(' | ')} |`
  })
  return [header, divider, ...rows].join('\n')
}

/**
 * Construct-level drill-down: every `ParsedExpr` kind (`identifier`,
 * `call`, `literal`, ...) and every finer-grained axis within a kind
 * (`binary:===`, `literal:string`, `array-method:includes`, ...) against
 * the shared conformance corpus. Complements the component matrix above —
 * that one answers "does this whole component compile clean", this one
 * answers "of the fixtures that exercise construct X, how many are clean".
 */
function buildSupportMatrixSection(): string {
  return `
## Construct Support (kind × axis)

${supportMatrix.note}

**Read this as a ratio, not a binary.** \`conformancePins\` and \`renderDivergences\` are attributed to a whole **fixture** (a component), not to the individual construct — a gapped fixture is usually a complex component that happens to exercise many common kinds and axes alongside the one shape it exists to pin down. A construct showing \`137/138\` has exactly one gapped fixture contributing to it, not 137 broken cases. A construct with \`total: 0\` (currently just \`regex\`) has no fixture exercising it yet.

Each construct name links to a conformance fixture exercising it — a small self-contained component showing the case in real code — and the **Example** column is that fixture's description. Constructs with no covering fixture yet link to where they're registered in the compiler instead.

### By kind

${buildSupportTable(supportMatrix.kinds)}

### By axis

${buildSupportTable(supportMatrix.axes)}
`
}

function buildMarkdown(): string {
  const componentNames = Object.keys(compat.components).sort()
  const summary = buildSummary(componentNames)
  const table = buildTable(componentNames)
  const legend = buildLegend()
  const fixtureSection = buildFixtureSection()
  const supportMatrixSection = buildSupportMatrixSection()

  return `# ${TITLE}

This matrix reports **compile-time** compatibility: for every component under \`ui/\`, whether \`compileJSX\` plus each adapter's \`generate()\` step produces diagnostics-free output. ${compat.note}

${summary}

## Matrix

Each component name links to its [component page](https://ui.barefootjs.dev/components) (or its source, for components without one); the **Description** column says what it is.

${table}

## Legend

Each diagnostic code below links to the known-limitation issue(s) tracking it. Codes with no linked issue fall back to the repo-wide [\`known-limitation\`](${compat.knownLimitationLabel}) label.

${legend}
${fixtureSection}
${supportMatrixSection}
## Data Source

This table is generated from the committed [\`ui/compat.lock.json\`](https://github.com/piconic-ai/barefootjs/blob/main/ui/compat.lock.json), regenerated with \`bun run compat:lock\` and drift-checked in CI. Render-level divergences are declared per adapter in \`packages/adapter-*/src/render-divergences.ts\` (each adapter's conformance suite derives its skip list from the same declaration, so this page and the tests cannot drift apart). Tracked limitations carry the [\`known-limitation\`](${compat.knownLimitationLabel}) label.

Component and fixture descriptions are computed into the same lock at regen time ([\`component-docs.ts\`](https://github.com/piconic-ai/barefootjs/blob/main/packages/compat/src/component-docs.ts)) — component copy is taken from the public component page's own \`description\` (falling back to the \`ui/registry.json\` catalogue one-liner, then the component's JSDoc tagline), and the component name links to that page when one exists; fixture descriptions come from the corpus itself. All of it is drift-checked with everything else and can't go stale independently.

The construct-support section above is generated from the committed [\`ui/support-matrix.lock.json\`](https://github.com/piconic-ai/barefootjs/blob/main/ui/support-matrix.lock.json), regenerated with \`bun run support-matrix:lock\` and drift-checked in CI alongside the component matrix. Each construct's fixture link and example description are computed the same way — the exemplar is mechanically chosen as the most narrowly targeted covering fixture ([\`construct-examples.ts\`](https://github.com/piconic-ai/barefootjs/blob/main/packages/compat/src/construct-examples.ts)), and definition-site fallback links come from a TS AST walk over the compiler's construct catalogues ([\`construct-source-links.ts\`](https://github.com/piconic-ai/barefootjs/blob/main/packages/compat/src/construct-source-links.ts)) — so they are regenerated and drift-checked on the same schedule: a link can't silently go stale, because moving the code it points at changes what the next regen commits, and CI fails if that regen was forgotten.

Every issue link on this page is freshness-checked on a schedule (\`bun run compat:issues\`, the [\`compat-issue-freshness\`](https://github.com/piconic-ai/barefootjs/blob/main/.github/workflows/compat-issue-freshness.yml) workflow): if a referenced issue is closed while its pin still points at it, an alert issue is opened automatically so the link is re-pointed or removed — the matrix cannot silently link a live limitation to a completed ticket.
`
}

export function registerCompatMatrixRoutes(app: Hono): void {
  const markdown = buildMarkdown()

  app.get(`/${SLUG}`, async (c) => {
    const parsed = await renderMarkdown(markdown)
    const navLinks = getDocsNavLinks(SLUG)

    return c.render(
      <div dangerouslySetInnerHTML={{ __html: parsed.html }} />,
      {
        title: TITLE,
        description: DESCRIPTION,
        slug: SLUG,
        toc: parsed.toc,
        prev: navLinks.prev,
        next: navLinks.next,
      },
    )
  })

  app.get(`/${SLUG}.md`, (c) => {
    c.header('Content-Type', 'text/markdown; charset=utf-8')
    return c.body(markdown)
  })
}
